### ISSUE TITLE
Ability to send DTMF tones using GTK window

### ISSUE THREAD

**Issue by robert-scheck** [baresip/baresip#1003]
As of writing, the GTK window of baresip during a call looks like this:

![image](https://user-images.githubusercontent.com/10982488/83691554-ac52d600-a5f2-11ea-99c8-afdb4ad29f95.png)

It would be very helpful if there is a chance for either a very simple ITU E 1.161 compliant telephone keypad, e.g.

```
1 2 3
4 5 6
7 8 9
* 0 #
```

as buttons, or to simply allow pressing the corresponding keys like on the command line to gain the same effect. According to my tests, pressing e.g. `1` on the GTK window doesn't lead to a DTMF tone.

**Comment by alfredh** [comment]
https://github.com/baresip/baresip/wiki/Guidelines-for-reporting-Issues

**Comment by robert-scheck** [comment]
Actually #1010 seems to lead to the expected behaviour.
