### ISSUE TITLE
Problems building baresip webrtc_aec module.

### ISSUE THREAD

**Issue by jr-selphius** [baresip/baresip#1005]
Baresip version: v0.6.6
Re version:         v0.6.0
Rem version:      v0.6.0
Prebuilt binaries for Linux x86 -> https://github.com/sourcey/webrtc-precompiled-builds/raw/master/webrtc-18252-6294a7e-linux-x86.tar.gz

As the webrtc structure folder changes a bit, I changed the webrtc_aec/module.mk properly. Specifically:

WEBRTC_PATH     :=~/webrtc
CPPFLAGS        += -isystem $(WEBRTC_PATH)/include/webrtc

LIBS    += \
        -L$(WEBRTC_PATH)/lib/x86/Debug \
        -lwebrtc_full \
        -lstdc++

When I try to build baresip
***make STATIC=yes EXTRA_MODULES=webrtc_aec***

It outputs the next error
**CXX [m] build-arm6/modules/webrtc_aec/aec.o
In file included from modules/webrtc_aec/aec.cpp:13:
/home/pi/webrtc/include/modules/audio_processing/aec/echo_cancellation.h:19:10: fatal error: webrtc/common_audio/ring_buffer.h: No such file or directory
 #include "webrtc/common_audio/ring_buffer.h"
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make: *** [mk/mod.mk:97: build-arm6/modules/webrtc_aec/aec.o] Error 1**

Could you provide any guidance on this problem?

Thank you so much for your time,
Javier.

**Comment by juha-h** [comment]
Try with
```
CPPFLAGS += -isystem $(WEBRTC_PATH)/include
```

**Comment by alfredh** [comment]
can you please show the content of the webrtc_sdk ?

is the file `ring_buffer.h` present ?

**Comment by alfredh** [comment]
it compiles for me:

```
$ make EXTRA_MODULES=webrtc_aec STATIC=yes
  SH      src/static.c
  CC      build-x86_64/src/static.o
  CXX [m] build-x86_64/modules/webrtc_aec/aec.o
  CXX [m] build-x86_64/modules/webrtc_aec/encode.o
  CXX [m] build-x86_64/modules/webrtc_aec/decode.o
  LD      baresip
```

```
find ../webrtc_sdk/include/ -name ring_buffer.h
../webrtc_sdk/include//base/containers/ring_buffer.h
../webrtc_sdk/include//common_audio/ring_buffer.h
../webrtc_sdk/include//modules/audio_processing/agc2/rnn_vad/ring_buffer.h
```

NOTE: please try to use the absolute path of the sdk, avoid tilde (`~`).

**Comment by alfredh** [comment]
please re-open if you can provide the required info...
