### ISSUE TITLE
Secondary SIP server with sipnat outbound

### ISSUE THREAD

**Issue by 129solutions** [baresip/baresip#1008]
From https://github.com/baresip/baresip/issues/916(url)

I have two client with baresip 0.6.3

My baresip configs as following:

Client-01:
`<sip:20001@sip.megasip.org>;sipnat=outbound;outbound="sip:192.168.1.222:5060;transport=udp";outbound2="sip:192.168.1.223:5060;transport=udp";auth_pass=12345678;video_codecs=vp8;regint=10`

and 

Client-02:
`<sip:20002@sip.megasip.org>;sipnat=outbound;outbound="sip:192.168.1.222:5060;transport=udp";outbound2="sip:192.168.1.223:5060;transport=udp";auth_pass=12345678;video_codecs=vp8;regint=10`

When SIP server-01 (192.168.1.222) alive and server-02 (192.168.1.223) died, I can call from Client-01 to Client-02 and vice versa.
But when server-01 (192.168.1.222) died, two clients could not register/connect so could not call from them, although server-02 (192.168.1.223) is still alive.

I want to use one sip account with many servers (different separate IPs, SIP server are chosen in order of priority: primary, secondary,...) with the goal of ensuring availability. Is there any solution to this problem on the client side?

I think it was possible to solve this problem on the server side by using HA or domain SRV, but I could not control on the server side, so I tried to find a client-side solution.

Thanks in advance.

**Comment by alfredh** [comment]
please use the mailing list for asking questions:

https://github.com/baresip/baresip/wiki/Guidelines-for-reporting-Issues

the `outbound` parameter is for outgoing SIP requests. If you have 2 outbound parameters,
it will register to 2 SIP servers. This is useful in case one of the SIP servers dies, the incoming call
can still be routed via the 2nd SIP server. How this SIP network is setup, is outside the scope
of baresip client.

In addition to multiple "outbound" you should use SIP SRV records to support HA.
