### ISSUE TITLE
Discrepancy in the module amr

### ISSUE THREAD

**Issue by janakj** [baresip/baresip#1011]
Function `encode_wb` makes sure that the target array is at least NB_SERIAL_MAX:
```c
...
if (*len < NB_SERIAL_MAX)
  return ENOMEM;
...
```
but the resiprocal `decode_wb` actually checks that the input is no more than NB_SERIAL_MAX+1:
```c
...
if (len > (1+NB_SERIAL_MAX))
  return EINVAL;
```
I am not sure if this is an actual error, but the discrepancy looks suspicious.

**Comment by juha-h** [comment]
Tests go the same way also in nb encode/decode.  Surely looks suspicious, but can't tell for sure.

**Comment by alfredh** [comment]
hi @janakj how are you doing, are you still working on VoIP projects ?

The packet has 1 byte in the beginning:

```c
        /* CMR value 15 indicates that no mode request is present */
        buf[0] = 15 << 4;
```

so the correct answer should be 1+ NB_SERIAL_MAX

is anyone willing to make a tested fix for this ? 


Alfred

**Comment by janakj** [comment]
Hi Alfred,

> hi @janakj how are you doing, are you still working on VoIP projects ?

Yeah, occasionally, but mostly on special-purpose VoIP setups, for example:
https://irtlab.gitlab.io/lmr-emulator/

-Jan
