### ISSUE TITLE
gzrtp module needs updating

### ISSUE THREAD

**Issue by ndilieto** [baresip/baresip#1022]
media_alloc function is missing last parameter (const struct stream *strm) and no longer compiles

**Comment by juha-h** [comment]
ndilieto writes:

> media_alloc function is missing last parameter (const struct stream
> *strm) and no longer compiles

I don't know if gzrtp module currently has a maintainer.  I use zrtp
module because it is written in C and was easier to build on Android.
gzrtp module also lacks session event handlers.

**Comment by ndilieto** [comment]
The interface changed; srtp/dtls_srtp/zrtp got updated but not gzrtp.

https://github.com/baresip/baresip/commit/939740c1a9a37c99c7c94d1a5d0a109861a8a3d9#diff-627eca715e874805b85fea1320c0da0b

**Comment by alfredh** [comment]
do you want to create a patch to fix the issue ?

if nobody wants to maintain gzrtp.so I think it is better to delete the module.

**Comment by ndilieto** [comment]
I'll try a patch. Give me some time.

**Comment by ndilieto** [comment]
Here it is, works ok now: https://github.com/baresip/baresip/pull/1034
