### ISSUE TITLE
Impossible to compile on Debian 8 amd64

### ISSUE THREAD

**Issue by kYroL01** [baresip/baresip#1032]
Hello here,

I have a Debian 8 system where I need to install **baresip** but I'm struggling to compile it.
My system is `Linux 3.16.0-4-amd64 #1 SMP Debian 3.16.51-3 x86_64 GNU/Linux`

When I run `make` I have:

> LD [M]  avcodec.so
> /usr/bin/ld: /usr/local/lib/libavcodec.a(allcodecs.o): relocation R_X86_64_32 against `ff_a64multi_encoder' can not be used when making a shared object; recompile with -fPIC
> /usr/local/lib/libavcodec.a: error adding symbols: Bad value
> collect2: error: ld returned 1 exit status
> mk/mod.mk:35: recipe for target 'avcodec.so' failed
> make: *** [avcodec.so] Error 1

So I tried to put the `-fPIC` flag in Makefile and also in `baresip/modules/avcodec/module.mk` but still the same result.
Is there a way to fix this problem ? 

Thank you

**Comment by alfredh** [comment]
please include the full build log.

the problem is your ffmpeg installation.

please try to use ffmpeg packages from Debian.

or enable shared libs in your local ffmpeg installation.
(`./configure --enable-shared`)

**Comment by alfredh** [comment]
it compiles without problems in Debian 9:

```
$ make
  CC [M]  build-x86_64/modules/avcodec/avcodec.o
  CC [M]  build-x86_64/modules/avcodec/decode.o
  CC [M]  build-x86_64/modules/avcodec/encode.o
  CC [M]  build-x86_64/modules/avcodec/h263.o
  CC [M]  build-x86_64/modules/avcodec/h265.o
  CC [M]  build-x86_64/modules/avcodec/sdp.o
  LD [M]  avcodec.so
alfredh@debian:~/git/baresip$ dpkg -l | grep libavcodec
ii  libavcodec-dev:amd64                  7:3.2.14-1~deb9u1                 amd64        FFmpeg library with de/encoders for audio/video codecs - development files
ii  libavcodec57:amd64                    7:3.2.14-1~deb9u1                 amd64        FFmpeg library with de/encoders for audio/video codecs - runtime files
```

NOTE: Please upgrade from Debian 8 to either 9 or 10.

NOTE: Please use system wide ffmpeg installation
