### ISSUE TITLE
baresip 'accounts' attempting to set mediaenc before mediaenc modules are loaded

### ISSUE THREAD

**Issue by ampledata** [baresip/baresip#1035]
Using a hard-coded 'accounts' file with the following line:

`sip:user@example.com;regint=0;transport=tls;mediaenc=srtp-mand`

I get the following error:

`account: mediaenc not found: 'srtp-mand'`

However, if I forego the hard-coded 'accounts' file and instead use `/uanew sip:user@example.com;regint=0;transport=tls;mediaenc=srtp-mand`, I get no error.

Configuration & Full logs follow.

Configuration:

```
module_path /usr/local/lib/baresip/modules

module account.so
module stdio.so
module contact.so
module debug_cmd.so
module g711.so
module menu.so
module srtp.so

sip_certificate /dev_volume/example.pem
```

Log with hard-coded 'accounts' file:

```
$ baresip -f /dev_volume/
baresip v1.0.0 Copyright (C) 2010 - 2020 Alfred E. Heggestad et al.
Local network address:  IPv4=eth0|192.168.1.1
SIP Certificate: /dev_volume/example.pem
account: mediaenc not found: 'srtp-mand'
Populated 1 account
Populated 0 contacts
aucodec: PCMU/8000/1
aucodec: PCMA/8000/1
mediaenc: srtp
mediaenc: srtp-mand
mediaenc: srtp-mandf
Populated 2 audio codecs
Populated 0 audio filters
Populated 0 video codecs
Populated 0 video filters
baresip is ready.
```

Log without hard-coded 'accounts' file, using the `/uanew` command:

```
$ baresip -f /dev_volume/
baresip v1.0.0 Copyright (C) 2010 - 2020 Alfred E. Heggestad et al.
Local network address:  IPv4=eth0|192.168.1.1
SIP Certificate: /dev_volume/example.pem
Populated 0 accounts
account: No SIP accounts found
 -- check your config or add an account using 'uanew' command
Populated 0 contacts
aucodec: PCMU/8000/1
aucodec: PCMA/8000/1
mediaenc: srtp
mediaenc: srtp-mand
mediaenc: srtp-mandf
Populated 2 audio codecs
Populated 0 audio filters
Populated 0 video codecs
Populated 0 video filters
baresip is ready.
/uanew sip:user@example.com;regint=0;transport=tls;mediaenc=srtp-mand
Creating UA for sip:user@example.com;regint=0;transport=tls;mediaenc=srtp-mand ...
user@example.com: Using media encryption 'srtp-mand'

--- User Agents (1) ---
> sip:user@example.com
```

**Comment by sreimers** [comment]
You need to load account with module_tmp in config:
```
module_tmp              account.so
```
And after `module srtp.so`

https://github.com/baresip/baresip/blob/master/docs/examples/config#L133

**Comment by ampledata** [comment]
@sreimers Thanks, works. To put a finer point on this, should this be cited in the documentation somewhere?

**Comment by juha-h** [comment]
How about allowing any order, i.e., baresip would first load modules with 'module' key, then with 'module_tmp' key, and finally with 'module_app' key?

**Comment by alfredh** [comment]
the directive `module_tmp` is the same as `module`, except that the module is just loaded and then unloaded.
it was added a long time ago to save RAM.

today I think the `module_tmp` command is not so useful, and can be removed.

**Comment by juha-h** [comment]
If `module_tmp` key is replaced by `module` key, one could still get the same effect in

https://github.com/baresip/baresip/wiki/Using-baresip-as-a-library

by calling module_unload() API function for the used tmp modules between Load modules and Main Loop, right?
```
        /* Load modules */
	err = conf_modules();
	if (err)
		goto out;

        /* Unload tmp modules here */

	/* Main loop */
	err = re_main(signal_handler);
```
