### ISSUE TITLE
Looking for baresip programmer

### ISSUE THREAD

**Issue by jbittner1002** [baresip/baresip#1040]
Hello sorry to post this on this list but I have been looking for someone that knows baresip for months to work on a programming project. Anyone that is interested please email me off list john@xaccel.net or skype me. 

Thanks
John Bittner
Xaccel Networks

**Comment by alfredh** [comment]
you can contact me off list on: alfred.heggestad@gmail.com

please use the mailing-list for these kind of questions:

https://groups.google.com/forum/#!forum/baresip
