### ISSUE TITLE
REGISTER attempts more than two attempts

### ISSUE THREAD

**Issue by sergey-safarov** [baresip/baresip#1042]
We use `kamailio` load-balancing hashing method using `authorization-username`([link](https://kamailio.org/docs/modules/5.4.x/modules/dispatcher.html#dispatcher.f.ds_select_dst)).

So `nonce` for first REGISTER message from one kamailio backend server. And second REGISTER message send to other kamailio backend server.
So registration will fail.

Could you add options that defined how many REGISTRATION attempts need to send?
Could you set a default REGISTRATION attempt to 3. One without `Authorization` header and next two with "Authorization" header.

**Comment by juha-h** [comment]
sergey-safarov writes:

> We use `kamailio` load-balancing hashing method using `authorization-username`([link](https://kamailio.org/docs/modules/5.4.x/modules/dispatcher.html#dispatcher.f.ds_select_dst)).
> 
> So `nonce` for first REGISTER message from one kamailio backend server. And second REGISTER message send to other kamailio backend server.
> So registration will fail.
> 
> Could you add options that defined how many REGISTRATION attempts need to send?
> Could you set a default REGISTRATION attempt to 3. One without `Authorization` header and next two with "Authorization" header.

It is not a good idea to complicate the app to cope with some
non-standard practices.  It should work if you change your hashing
method to callid, since it is the same both in the first and the second
REGISTER message.

**Comment by alfredh** [comment]
the backend cluster should use the same authentication settings on all servers.
sending first REGISTER to server one and the second REGISTER to server two
is a valid usecase and should work.
