### ISSUE TITLE
'BACKUP SYSTEM' on the road | general request for sharing ideas & advice

### ISSUE THREAD

**Issue by 004930** [baresip/baresip#1046]
So, how are members of the baresip community handling there 'backup system' strategy for having access to important business tools like baresip, especially on the road? 

When my laptop would die or get lost by (for example) theft, I need to have a 'backup system' for getting access to email, voip, pass [passwordstore.org], pgp keys, ssh keys (including '~/.ssh/config'), yubikey, vpn's, etc. withing <24h. In case of international travelling this is an issue, since a second laptop on the road is not convenient.

Right now I use a rpi4 with 8GB RAM and alpinelinux installed on a SD card. Alpine runs completely in RAM, the alpine config is encrypted on the SD card (very easy to do, just enable encryption in '/etc/lbu/lbu.conf') and all is fine. So on the road, I can take my rpi4 with me, or in theory I only take my SD card and in case of disaster I can buy a rpi4 locally, hook up a keyboard and monitor and have access to all my important software, keys and data.

The only thing is that Alpine uses musl-libc instead of glibc and baresip doesn't support musl-libc (or at least, I did not succeed compiling baresip so far on Alpine).
 
My question to other members:
- How do you handle your 'backup system' strategy on the road?
- Any advice for getting baresip running; putting it in a docker container with a different small (glibc based) linux OS?
- Other things I didn't think about and should consider?

Hope to get feedback from other baresip members and may this topic be helpful for others to shape a good 'Plan for the worse, hope for the best' strategy.
Thanks.

**Comment by GGGO** [comment]
Please use [https://groups.google.com/forum/#!forum/baresip](url) to get community feedback.
