### ISSUE TITLE
Error compiling Master || /src/call.o: in function `update_video':  || undefined reference to `sdp_media_disabled'

### ISSUE THREAD

**Issue by 004930** [baresip/baresip#1047]
=== cut ===

  CC      build-x86_64/src/call.o
src/call.c: In function ‘update_video’:
src/call.c:358:7: warning: implicit declaration of function ‘sdp_media_disabled’; did you mean ‘sdp_media_set_disabled’? [-Wimplicit-function-declaration]
  358 |  if (!sdp_media_disabled(m))
      |       ^~~~~~~~~~~~~~~~~~
      |       sdp_media_set_disabled
src/call.c:358:7: warning: nested extern declaration of ‘sdp_media_disabled’ [-Wnested-externs]

=== cut ===

  LD      baresip
/usr/bin/ld: build-x86_64/src/call.o: in function `update_video':
xxxx/baresip/src/call.c:358: undefined reference to `sdp_media_disabled'
collect2: error: ld returned 1 exit status
make: *** [Makefile:220: baresip] Error 1

Tying building on a flavor of Ubuntu 20.04.

**Comment by sreimers** [comment]
You need to build with https://github.com/baresip/re as dependency.

**Comment by 004930** [comment]
It was build with re and rem.

**Comment by sreimers** [comment]
https://github.com/baresip/re is a fork from https://github.com/creytiv/re. Try a fresh clone.

**Comment by 004930** [comment]
I changed my build script to baresip/re and everything did build now.
Sorry for overlooking creytiv/re vs baresip/re; thank you for the quick pointer Sebastian.
