### ISSUE TITLE
Error on compile:  /src/call.c:358: undefined reference to `sdp_media_disabled'

### ISSUE THREAD

**Issue by webstean** [baresip/baresip#1050]
Clone of latest version fails

  CC      build-x86_64/src/auframe.o
  CC      build-x86_64/src/aulevel.o
  CC      build-x86_64/src/auplay.o
  CC      build-x86_64/src/ausrc.o
  CC      build-x86_64/src/baresip.o
  CC      build-x86_64/src/call.o
src/call.c: In function ‘update_video’:
src/call.c:358:7: warning: implicit declaration of function ‘sdp_media_disabled’; did you mean ‘sdp_media_set_disabled’? [-Wimplicit-function-declaration]
  358 |  if (!sdp_media_disabled(m))
      |       ^~~~~~~~~~~~~~~~~~
      |       sdp_media_set_disabled
src/call.c:358:7: warning: nested extern declaration of ‘sdp_media_disabled’ [-Wnested-externs]
  CC      build-x86_64/src/cmd.o
  CC      build-x86_64/src/conf.o
  CC      build-x86_64/src/config.o
  CC      build-x86_64/src/contact.o
  CC      build-x86_64/src/custom_hdrs.o
  CC      build-x86_64/src/event.o
  CC      build-x86_64/src/h264.o
  CC      build-x86_64/src/log.o
  CC      build-x86_64/src/mctrl.o
  CC      build-x86_64/src/mediadev.o
  CC      build-x86_64/src/menc.o
  CC      build-x86_64/src/message.o
  CC      build-x86_64/src/metric.o
  CC      build-x86_64/src/mnat.o
  CC      build-x86_64/src/module.o
  CC      build-x86_64/src/net.o
  CC      build-x86_64/src/play.o
  CC      build-x86_64/src/reg.o
  CC      build-x86_64/src/rtpext.o
  CC      build-x86_64/src/rtpstat.o
  CC      build-x86_64/src/sdp.o
  CC      build-x86_64/src/sipreq.o
  CC      build-x86_64/src/stream.o
  CC      build-x86_64/src/stunuri.o
  CC      build-x86_64/src/timer.o
  CC      build-x86_64/src/timestamp.o
  CC      build-x86_64/src/ua.o
  CC      build-x86_64/src/ui.o
  CC      build-x86_64/src/vidcodec.o
  CC      build-x86_64/src/video.o
  CC      build-x86_64/src/vidfilt.o
  CC      build-x86_64/src/vidisp.o
  CC      build-x86_64/src/vidsrc.o
  CC      build-x86_64/src/vidutil.o
  CC      build-x86_64/src/main.o
  LD      baresip
/usr/bin/ld: build-x86_64/src/call.o: in function `update_video':
/home/webstean/git/baresip/src/call.c:358: undefined reference to `sdp_media_disabled'
collect2: error: ld returned 1 exit status
make: *** [Makefile:220: baresip] Error 1

**Comment by sreimers** [comment]
See: https://github.com/baresip/baresip/issues/1047

**Comment by juha-h** [comment]
webstean writes:

> Clone of latest version fails

You need to use https://github.com/baresip/re.
