### ISSUE TITLE
Baresip as a library

### ISSUE THREAD

**Issue by jaimelaborda** [baresip/baresip#1052]
Hi, 

I'm just trying to integrate baresip as a library with my application but I cannot compilate the example in the Wiki: https://github.com/baresip/baresip/wiki/Using-baresip-as-a-library

It seems that this piece of code is not compatible with recent version of baresip (actually I am using v0.6.5 commit 4c892e2406) 

This is the error I'm getting:

```
main.c: In function ‘main’:
main.c:59:8: error: too many arguments to function ‘baresip_init’
  err = baresip_init(conf_config(), false);
        ^
In file included from main.c:4:0:
/usr/local/include/baresip.h:1462:6: note: declared here
 int  baresip_init(struct config *cfg);
      ^
main.c:66:8: error: too many arguments to function ‘ua_init’
  err = ua_init("baresip v" BARESIP_VERSION " (" ARCH "/" OS ")",
        ^
In file included from main.c:4:0:
/usr/local/include/baresip.h:766:6: note: declared here
 int  ua_init(const char *software, bool udp, bool tcp, bool tls);

```
Best regards,
Jaime.

**Comment by GGGO** [comment]
Yes, you are right, this example needs some refresh.

int  baresip_init(struct config *cfg);
int ua_init(const char *software, bool udp, bool tcp, bool tls)

**Comment by GGGO** [comment]
This is now fixed.

**Comment by alfredh** [comment]
thanks for fixing @GGGO
