### ISSUE TITLE
Weird echo

### ISSUE THREAD

**Issue by egothor** [baresip/baresip#1054]
I am running Fedora32 with baresip v1.0.0 package. Baresip is configured with sip/tls and srtp.

When Bob is running baresip and Alice calls him, Bob has perfect sound, but Alice can hear her own voice with a delay. I guess, it is sent back from Bob - mixed with his own voice. The point is, that Bob uses headphones, so that the echo should be caused by some software mixer. When Bob runs Linphone, everything is OK.

Should I enable something in baresip configuration to eliminate the issue?

Account definition:

`<sip:XXXX@YYYY:PPPP;transport=tls>;auth_user=XXXX;auth_pass=*****;mediaenc=srtp;audio_codecs=""`

Configuration:

```
poll_method		epoll		# poll, select, epoll ..
call_local_timeout	120
call_max_calls		4
audio_player		pulse
audio_source		pulse
audio_alert		pulse
audio_level		no
ausrc_format		s16		# s16, float, ..
auplay_format		s16		# s16, float, ..
auenc_format		s16		# s16, float, ..
audec_format		s16		# s16, float, ..
audio_buffer		20-160		# ms
video_size		352x288
video_bitrate		500000
video_fps		25.00
video_fullscreen	no
videnc_format		yuv420p
rtp_tos			184
rtcp_mux		no
jitter_buffer_delay	5-10		# frames
rtp_stats		no
module_path		/usr/lib64/baresip/modules
module			stdio.so
module			opus.so
module			g722.so
module			g726.so
module			g711.so
module			gsm.so
module			l16.so
module			mpa.so
module			pulse.so
module			stun.so
module			turn.so
module			ice.so
module			srtp.so
module			dtls_srtp.so
module			zrtp.so
module_tmp		uuid.so
module_tmp		account.so
module_app		auloop.so
module_app		contact.so
module_app		debug_cmd.so
module_app		gtk.so
module_app		menu.so
module_app		vidloop.so
cons_listen		0.0.0.0:5555 # cons
http_listen		0.0.0.0:8000 # httpd - server
ctrl_tcp_listen		0.0.0.0:4444 # ctrl_tcp
evdev_device		/dev/input/event0
opus_bitrate		28000 # 6000-510000
vumeter_stderr		yes
video_selfview		window # {window,pip}
ice_debug		no
```

Runtime messages:

```
sip:XXXX@YYYY:PPPP: Incoming call from: **** sip:**** - (press 'a' to accept)
call: answering call on line 1 from sip:**** with 200
stream: update 'audio'
stream: audio: starting mediaenc 'srtp' (wait_secure=0)
srtp: audio: SRTP is Enabled (cryptosuite=AES_CM_128_HMAC_SHA1_80)
audio: Set audio encoder: PCMA 8000Hz 1ch
audio: source started with sample format S16LE
audio: Set audio decoder: PCMA 8000Hz 1ch
audio: player started with sample format S16LE
audio tx pipeline:       pulse ---> gtk_vumeter ---> PCMA
audio rx pipeline:       pulse <--- gtk_vumeter <--- PCMA
XXXX@YYYY: Call established: sip:****
stream: incoming rtp for 'audio' established, receiving from A.B.C.D:E

```

**Comment by sreimers** [comment]
Can you test ALSA instead of PulseAudio. It may help to narrow down where the echo comes from.

https://github.com/baresip/baresip/wiki/Using-Baresip:-Module-alsa

**Comment by alfredh** [comment]
you can use the sndfile module to dump WAV files with the transmitted/received audio stream.

can you please record a file and upload it here so we can listen to it ?

**Comment by alfredh** [comment]
hi @egothor are you able to provide the required information ?

**Comment by egothor** [comment]
Hello, I have this task in my queue. Unfortunately, I gotta solve other high priority activities first.

**Comment by alfredh** [comment]
okay, then I will close it for now.

feel free to re-open it when you have the additional info.
