### ISSUE TITLE
RTP Stats from HTTP API

### ISSUE THREAD

**Issue by lmangani** [baresip/baresip#1055]
Hi @alfredh et all

Raising an observation for discussion. I noticed there's currently no way to print out the good old RTP/RTCP stats when using the HTTP API as those provide console output only, ie:
```
audio           Transmit:     Receive:
packets:           1319         1296
avg. bitrate:      63.7         63.2  (kbit/s)
errors:               0            0
pkt.report:        1147         1134
lost:                 0            0
jitter:             0.0          0.0  (ms)
```

Is there any chance those could be dumped with their own command `/rtpstat` or perhaps just included in the `/callstat` command output when available? This would allow dumping them on demand and/or collecting them before terminating a call? I didn't find an immediate way to patch the code yet but I'm happy to try do it, but first I'm wondering if I'm missing some other way to achieve the same via HTTP API.

Thanks in advance!

**Comment by alfredh** [comment]
the HTTP API is using the same command system as other UI modules.
so for example stdio, cons, ctrl_tcp, httpd all expose the same set of commands.

it should be possible to add such a command yes.

**Comment by alfredh** [comment]
please use the mailing list for discussions ...

**Comment by lmangani** [comment]
Why so? This is related to code and producing a PR so it belongs where the code is?
