### ISSUE TITLE
Can we get a git tag updated every time VERSION changes in the makefile

### ISSUE THREAD

**Issue by webstean** [baresip/baresip#1058]
Currently:-
git describe --abbrev=0 --tags --always
returns
v0.6.6

It would be nice if a tag was created each time the version was changed.

which is out of date. I'm not sure how to do this, this link much offer a solution.
[](https://gist.github.com/andrewgross/be3229cf99d5f517f8dd)

This would allow specific versions to be used in regulated environments such as Healthcare, Emergency Services

**Comment by sreimers** [comment]
v0.6.6 is the latest stable released version. 1.0.0 is not released at the moment.

**Comment by webstean** [comment]
Ok I thought was 1.0 was released, (excuse my ignorance) but how is the tag updated each time the release is updated. Is that done manually?

**Comment by alfredh** [comment]
We are planning to make a 1.0.0 release soon ..

**Comment by alfredh** [comment]
we are using the github release tool to make new releases/tags.
