### ISSUE TITLE
Segfault because of mem_deref(call) in module menu ua_event_handler

### ISSUE THREAD

**Issue by cspiel1** [baresip/baresip#1059]
In case of UA_EVENT_CALL_TRANSFER_FAILED, UA_EVENT_AUDIO_ERROR the pointer call given as function parameter is de-referenced.

Other ua_event_handler that use information from call will crash with a segfault if there are called after menus ua_event_handler.

It depends on the order of modules initialization. If a module with an ua_event_handler is loaded after menu, the segfault occurs.

Commits that cause the issue:
commit 7b6b8a05ebf44d566810b3a60b8799b6f8da5ddd
Author: Alfred E. Heggestad <alfred.heggestad@gmail.com>
Date:   Wed Oct 10 17:57:26 2018 +0200

    add UA_EVENT_AUDIO_ERROR (ref #539) (#555)

commit 4dd9bc9783ecb591eebdb421d6fdef548ecb2026
Author: juha-h <jh@tutpro.com>
Date:   Tue Oct 30 11:42:29 2018 +0200

    pass CALL_EVENT_TRANSFER_FAILED event to handler and handle it in menu module (#567)

**Comment by alfredh** [comment]
fixed in commit f42021893713bba85f5730c95545485f436f51a6
