### ISSUE TITLE
make fails with error: 'AAC_PCM_MIN_OUTPUT_CHANNELS' undeclared

### ISSUE THREAD

**Issue by sampleref** [baresip/baresip#1063]
Trying to build with https://github.com/baresip/baresip#build-with-debug-enabled

```
  CC [M]  build-x86_64/modules/aac/decode.o
modules/aac/decode.c: In function 'aac_decode_update':
modules/aac/decode.c:135:40: error: 'AAC_PCM_MIN_OUTPUT_CHANNELS' undeclared (first use in this function)
  error  = aacDecoder_SetParam(ads->dec, AAC_PCM_MIN_OUTPUT_CHANNELS,
                                        ^
modules/aac/decode.c:135:40: note: each undeclared identifier is reported only once for each function it appears in
modules/aac/decode.c:137:41: error: 'AAC_PCM_MAX_OUTPUT_CHANNELS' undeclared (first use in this function)
  error |= aacDecoder_SetParam(ads->dec, AAC_PCM_MAX_OUTPUT_CHANNELS,
                                         ^
mk/mod.mk:42: recipe for target 'build-x86_64/modules/aac/decode.o' failed
make: *** [build-x86_64/modules/aac/decode.o] Error 1
```

Any suggestions would help

**Comment by GGGO** [comment]
If you need aac module, make sure you have fdk-aac package installed.

**Comment by sampleref** [comment]
I am using opus for audio, but in my machine aac(_libfdk-aac-dev_) was already installed, so the header file at /usr/include/fdk-aac/aacdecoder_lib.h does not contain AAC_PCM_MIN_OUTPUT_CHANNELS and AAC_PCM_MAX_OUTPUT_CHANNELS definition

For now I modified in _baresip- modules/aac/decode.c AAC_PCM_MIN_OUTPUT_CHANNELS_ and _AAC_PCM_MAX_OUTPUT_CHANNELS_ with available _AAC_PCM_OUTPUT_CHANNELS_ from _/usr/include/fdk-aac/aacdecoder_lib.h_  for make build to succeed and its fine
