### ISSUE TITLE
Baresip over OpenVPN

### ISSUE THREAD

**Issue by AndyW999** [baresip/baresip#1066]
Hi

I have a Debian 10 board which runs baresip OK over a Wifi interface to a FreeSwitch server which is on the same Windows machine as OpenVPN.

I now am routing it over OpenVPN - 10.8.0.9.

In config I have net_interface		10.8.0.9

If I look at Wireshark on the Windows machine - 10.0.0.14 - hosting the server I see -

No.     Time                          Source                Destination           Protocol Length Info
      3 2020-08-19 15:33:16.019202    10.8.0.9              10.0.0.14             SIP      550    Request: REGISTER sip:10.0.0.14  (1 binding) | 
      4 2020-08-19 15:33:16.019346    10.0.0.14             10.8.0.9              SIP      618    Status: 401 Unauthorized | 

The reply packet is apparently not getting back to baresip. 

Do you have any suggestions where to look and is there a way of dumping the SIP packets to see if they have been received as tcpdump does not even show the outgoing packets.

Thanks

Andy.

**Comment by alfredh** [comment]
are you using UDP or TCP ? can you please include full config/accounts files ?

there is a patch for adding SIP trace:

https://github.com/alfredh/re/commit/81a998c1d810282f470e440a689aa85c5b69a3bb

this patch could be copied over to baresip/re repo.

**Comment by AndyW999** [comment]
I have now put the LTE dongle on and do not get any SIP traffic.
It does not matter if I put tun0 or 10.8.0.9 in net_interface, it always shows
Local network address:  IPv4=tun0|10.8.0.9

--- Network debug ---
 Local IPv4:  [E] tun0|10.8.0.9
 Local IPv6:  [E] (not set)
 Domain:
net interfaces:
         lo:  127.0.0.1
       usb0:  192.168.0.109
       tun0:  10.8.0.9
         lo:  ::1
       usb0:  fe80::dded:75c8:7c91:47b4
       tun0:  fe80::38bb:c15c:4022:309e
 DNS Servers from System: (2)
   0: 8.8.4.4:53
   1: 8.8.8.8:53

UDP 10.8.0.9:36652 -> 10.0.0.14:5060
REGISTER sip:10.0.0.14 SIP/2.0
Via: SIP/2.0/UDP 10.8.0.9:36652;branch=z9hG4bK7083da045c5d80ff;rport
Contact: <sip:100101-0x64a3788@10.8.0.9:36652>;expires=3670;+sip.instance="<urn:uuid:d902be87-e6a3-49b4-d88c-e9f4ae570416>"
Max-Forwards: 70
To: <sip:100101@10.0.0.14>
From: <sip:100101@10.0.0.14>;tag=1b0b9e531ae0e279
Call-ID: 61735a647ebb4d1d
CSeq: 16415 REGISTER
User-Agent: baresip v1.0.0 (arm/linux)
Allow: INVITE,ACK,BYE,CANCEL,OPTIONS,NOTIFY,SUBSCRIBE,INFO,MESSAGE,REFER
Content-Length: 0


reg: sip:100101@10.0.0.14: Register: Connection timed out
I suspect the tun0 traffic is being sent to the usb0 by mistake

Enclosed is a pcap using tcpdump -i usb0 from the client.
It seems the 10.8.0.9 traffic is sent to usb0 - is there a configuration item I have missed?
[cap_usb0.zip](https://github.com/baresip/baresip/files/5116735/cap_usb0.zip)


I will sort out any acl problems when I manage to get some SIP traffic!

**Comment by 004930** [comment]
Andy, you can try to setup you baresip account like:

"YOURNAME" <sip:USER@domain.tld:5060>;auth_pass=YOURPASS;outbound="sip:vpn-ipaddress-freeswitch-server"

or (depending on you sofia profile)

"YOURNAME" <sip:USER@ipaddressfreeswitch:5060>;auth_pass=YOURPASS;outbound="sip:vpn-ipaddress-freeswitch-server"


I have many years experience with a baresip over different sort 
of vpn's solutions towards different sort of sip servers. So 
there is not an issue with baresip.

Instead of trying to get baresip + vpn working over LTE, try it 
first over a normal internet connection and see if that works.  
Then you know it's related to the LTE connection.

Also try to get to understand/know the basics about your 
network/vpn. ip route, ping, tracepath, mtu set right? Etc.

-

**Comment by AndyW999** [comment]
I already know baresip works over wifi without openvpn

Have you looked at the pcap I attached?

**Comment by AndyW999** [comment]
If I then put baresip over the vpn using wifi I get the results shown in the pcap in the third message in this thread in baresip zip where FreeSwitch sees the registration and does a 401 with the digest authentication information.

I am no stranger to SIP myself ;)

**Comment by 004930** [comment]
Adapt your baresip config & account as I pointed out since then.

Login to freeswitch server (fs_cli).

Start baresip + vpn over wifi.

What is the ouput of the log on the freeswitch server (fs_cli) 
when you register?

**Comment by AndyW999** [comment]
sofia global siptrace on
sofia loglevel all 9

FreeSwitch looks like it is sending it to the right place.
But if I do a tcpdump and ping 10.8.0.9 I see packets, also when I use motion I see packets but when FS is sending stuff I don't

c:\freeswitch\libs\sofia-sip\libsofia-sip-ua\tport\tport.c:2753 tport_wakeup_pri() tport_wakeup_pri(00000287DE363830): events IN
c:\freeswitch\libs\sofia-sip\libsofia-sip-ua\tport\tport.c:2868 tport_recv_event() tport_recv_event(00000287DE363830)
c:\freeswitch\libs\sofia-sip\libsofia-sip-ua\tport\tport.c:3209 tport_recv_iovec() tport(00000287DE363830) msg 00000287DF38AFE0 from (udp/10.0.0.14:5060) has 507 bytes, veclen = 1
recv 507 bytes from udp/[10.8.0.9]:59844 at 10:25:54.168253:
   ------------------------------------------------------------------------
   REGISTER sip:10.0.0.14 SIP/2.0
   Via: SIP/2.0/UDP 10.8.0.9:59844;branch=z9hG4bK65dc63786901a3cb;rport
   Contact: <sip:100101-0xc8c1720@10.8.0.9:59844>;expires=3609;+sip.instance="<urn:uuid:d902be87-e6a3-49b4-d88c-e9f4ae570416>"
   Max-Forwards: 70
   To: <sip:100101@10.0.0.14>
   From: <sip:100101@10.0.0.14>;tag=79bf3e42176649f2
   Call-ID: 5316ccc44dbe674b
   CSeq: 4948 REGISTER
   User-Agent: baresip v1.0.0 (arm/linux)
   Allow: INVITE,ACK,BYE,CANCEL,OPTIONS,NOTIFY,SUBSCRIBE,INFO,MESSAGE,REFER
   Content-Length: 0

   ------------------------------------------------------------------------
c:\freeswitch\libs\sofia-sip\libsofia-sip-ua\tport\tport.c:3027 tport_deliver() tport(00000287DE363830): msg 00000287DF38AFE0 (507 bytes) from udp/10.8.0.9:5060/sip next=0000000000000000
c:\freeswitch\libs\sofia-sip\libsofia-sip-ua\nta\nta.c:2880 agent_recv_request() nta: received REGISTER sip:10.0.0.14 SIP/2.0 (CSeq 4948)
c:\freeswitch\libs\sofia-sip\libsofia-sip-ua\nta\nta.c:3012 agent_recv_request() nta: REGISTER (4948) going to existing REGISTER transaction
c:\freeswitch\libs\sofia-sip\libsofia-sip-ua\nta\nta.c:6178 incoming_recv() nta: re-received REGISTER request, retransmitting 401 reply
c:\freeswitch\libs\sofia-sip\libsofia-sip-ua\tport\tport.c:3261 tport_tsend() tport_tsend(00000287DE363830) tpn = UDP/10.8.0.9:59844
c:\freeswitch\libs\sofia-sip\libsofia-sip-ua\tport\tport.c:4050 tport_resolve() tport_resolve addrinfo = 10.8.0.9:59844
c:\freeswitch\libs\sofia-sip\libsofia-sip-ua\tport\tport.c:4684 tport_by_addrinfo() tport(00000287DE363830): not found by name UDP/10.8.0.9:59844
c:\freeswitch\libs\sofia-sip\libsofia-sip-ua\tport\tport.c:3598 tport_vsend() tport_vsend(00000287DE363830): 575 bytes of 575 to udp/10.8.0.9:59844
c:\freeswitch\libs\sofia-sip\libsofia-sip-ua\tport\tport.c:3496 tport_send_msg() tport_vsend returned 575
send 575 bytes to udp/[10.8.0.9]:59844 at 10:25:54.169217:
   ------------------------------------------------------------------------
   SIP/2.0 401 Unauthorized
   Via: SIP/2.0/UDP 10.8.0.9:59844;branch=z9hG4bK65dc63786901a3cb;rport=59844
   From: <sip:100101@10.0.0.14>;tag=79bf3e42176649f2
   To: <sip:100101@10.0.0.14>;tag=SmaD75aNpQcmD
   Call-ID: 5316ccc44dbe674b
   CSeq: 4948 REGISTER
   User-Agent: FreeSWITCH-mod_sofia/1.9.0~64bit
   Allow: INVITE, ACK, BYE, CANCEL, OPTIONS, MESSAGE, INFO, UPDATE, REGISTER, REFER, NOTIFY, PUBLISH, SUBSCRIBE
   Supported: timer, path, replaces
   WWW-Authenticate: Digest realm="10.0.0.14", nonce="08b39e2c-30b7-4b6a-9f1f-b81d283e4082", algorithm=MD5, qop="auth"
   Content-Length: 0

**Comment by 004930** [comment]
Well, the siptrace and loglevel 9 was not what I asked for; also 
I believe you provided me with a cut of the log since FS would 
actually give a lot more feedback when you register.

But at least now now it is clear baresip is actually reaching and 
registering at FS (as I expected). As I pointed out earlier you 
need to configure and adapt you FS configuration (sofia profile) 
to your vpn network ip so it sends the SIP traffic correctly 
back.

You are getting:
>    SIP/2.0 401 Unauthorized

The issue here is configuring FS correctly. 
This has nothing to do with baresip.

**Comment by alfredh** [comment]
this is not a bug in baresip.

please report the issue to freeswitch or use the mailing-list:

https://github.com/baresip/baresip/wiki/Guidelines-for-reporting-Issues
