### ISSUE TITLE
implicit subscription created by REFER is not terminated

### ISSUE THREAD

**Issue by juha-h** [baresip/baresip#1075]
baresip receiving REFER request fails to terminate the implicit subscription created by the REFER request when baresip (= referee) cancels the INVITE it sent based on the REFER request before the INVITE was answered or rejected.

A test showing the issue is described in https://groups.google.com/forum/#!topic/baresip/-ZyWJT25LWE.

**Comment by alfredh** [comment]
how is the REFER cancelled ?

can you check if any of the event close handlers are called in call.c
(for example sipsub_close_handler)

**Comment by juha-h** [comment]
Implicit REFER subscription is terminated  by sending NOTIFY that has header:
```
Subscription-State: terminated;reason=noresource
```
If referee cancel the call, it should send same kind of NOTIFY as when referred to rejects the call, for example:
```
T 2020/08/30 18:02:54.261042 192.168.43.82:57586 -> 192.168.43.82:5060 [AP] #39
NOTIFY sip:foo@test.tutpro.com;gr=urn:uuid:7a8e5a06-4620-72d2-8498-bf8c1614a440 SIP/2.0.
Via: SIP/2.0/TCP 192.168.43.82:45939;branch=z9hG4bK5ed65eae363de51d;rport.
Contact: <sip:test@test.tutpro.com;gr=urn:uuid:9b21c1a8-dc58-a3d6-83d5-7be67cbe70ce>.
Max-Forwards: 70.
Route: <sip:192.168.43.82;transport=tcp;lr;n1;pm=0>.
To: "Foo" <sip:foo@test.tutpro.com>;tag=76b76656d5a58493.
From: <sip:test@test.tutpro.com>;tag=eef248055ce90bc0.
Call-ID: 25157acb34a056f7.
CSeq: 12609 NOTIFY.
User-Agent: baresip v1.0.0 (x86_64/linux).
Event: refer;id=8591.
Subscription-State: terminated;reason=noresource.
Allow: INVITE,ACK,BYE,CANCEL,OPTIONS,NOTIFY,SUBSCRIBE,INFO,MESSAGE,REFER.
Content-Type: message/sipfrag.
Content-Length: 21.
.
SIP/2.0 486 Rejected

```
I can try to add some debug to call.c to see if any event is generated when referee cancels the call.

**Comment by juha-h** [comment]
When referee cancels the call to refer-to, presence module of referee gets CALL_CLOSED event, but that does not cause sending of NOTIFY to referrer that would terminate the subscription:
```
test@test.tutpro.com: Call established: sip:foo@test.tutpro.com
presence: ua=0x556cc8e2fdf0 got event 10 (CALL_ESTABLISHED)
stream: incoming rtp for 'audio' established, receiving from 192.168.43.82:50114
presence: ua=0x556cc8e2fdf0 got event 16 (CALL_RTPESTAB)
presence: ua=0x556cc8e2fdf0 got event 17 (CALL_RTCP)  
menu: transferring call 20e2d4fabee0f92b to '<sip:jh@test.tutpro.com>'
ua: using best effort AF: af=AF_INET
call: alloc with params laddr=192.168.43.82, af=AF_INET, use_rtp=1
call: use_video=1
call: connecting to '<sip:jh@test.tutpro.com>'..
presence: ua=0x556cc8e2fdf0 got event 22 (CALL_LOCAL_SDP)
presence: ua=0x556cc8e2fdf0 got event 12 (TRANSFER)
call: SIP Progress: 100 Trying (/)
call: SIP Progress: 100 Trying (/)
call: SIP Progress: 180 Ringing (/)
video: stopping video source ..
alsa: reset: srate=8000, ch=1, num_frames=320, pcmfmt=S16_LE
alsa: playback started (default)
presence: ua=0x556cc8e2fdf0 got event 8 (CALL_RINGING)
presence: ua=0x556cc8e2fdf0 got event 17 (CALL_RTCP)
presence: ua=0x556cc8e2fdf0 got event 17 (CALL_RTCP)
alsa: stopping playback thread (default)
call: terminate call '4c26d34d8cbff25c' with sip:jh@test.tutpro.com
video: stopping video source ..
presence: ua=0x556cc8e2fdf0 got event 11 (CALL_CLOSED)
video: stopping video source ..
audio: destroyed (started=0)
presence: ua=0x556cc8e2fdf0 got event 17 (CALL_RTCP).0/0.0    
presence: ua=0x556cc8e2fdf0 got event 17 (CALL_RTCP).0/0.0    
presence: ua=0x556cc8e2fdf0 got event 17 (CALL_RTCP).0/0.0    
...
```

**Comment by alfredh** [comment]
the presence module is not related to call transfer. please try to unload presence.so and
repeat the test.

call transfer is fully handled in call.c:

```c
/**
 * Transfer the call to a target SIP uri
 *
 * @param call  Call object
 * @param uri   Target SIP uri
 *
 * @return 0 if success, otherwise errorcode
 */
int call_transfer(struct call *call, const char *uri)
{
	char *nuri;
	int err;

	if (!call || !uri)
		return EINVAL;

	err = normalize_uri(&nuri, uri, &call->acc->luri);
	if (err)
		return err;

	info("transferring call to %s\n", nuri);

	call->sub = mem_deref(call->sub);
	err = sipevent_drefer(&call->sub, uag_sipevent_sock(),
			      sipsess_dialog(call->sess), ua_cuser(call->ua),
			      auth_handler, call->acc, true,
			      sipsub_notify_handler, sipsub_close_handler,
			      call,
			      "Refer-To: %s\r\n", nuri);
	if (err) {
		warning("call: sipevent_drefer: %m\n", err);
	}

	mem_deref(nuri);

	return err;
}
```

if there is a bug in call transfer, it must be located in call.c

**Comment by juha-h** [comment]
After commenting out presence module in config and starting baresip with -v option, I don't see any call related events on terminal when referee (test@test.tutpro.com) cancels transferred call (to jh@test.tutpro.com):
```
test@test.tutpro.com: Call established: sip:foo@test.tutpro.com
stream: incoming rtp for 'audio' established, receiving from 192.168.43.82:50184
menu: transferring call ed81ed152855f9b6 to '<sip:jh@test.tutpro.com>'
ua: using best effort AF: af=AF_INET
call: alloc with params laddr=192.168.43.82, af=AF_INET, use_rtp=1
call: use_video=1
call: connecting to '<sip:jh@test.tutpro.com>'..
call: SIP Progress: 100 Trying (/)
call: SIP Progress: 100 Trying (/)
call: SIP Progress: 180 Ringing (/)
video: stopping video source ..
alsa: reset: srate=8000, ch=1, num_frames=320, pcmfmt=S16_LE
alsa: playback started (default)
alsa: stopping playback thread (default)
call: terminate call 'aea32075ffe10f2a' with sip:jh@test.tutpro.com
video: stopping video source ..
video: stopping video source ..
audio: destroyed (started=0)
```

**Comment by juha-h** [comment]
When referee CANCELs the refer-to call, perhaps instead of
```
SIP/2.0 486 Rejected
```
NOTIFY body terminating the subscription could be
```
487 Request Terminated
```
which means

>Request has terminated by bye or cancel.

**Comment by alfredh** [comment]
when there is an incoming call transfer event, this function is called:

`sipsess_refer_handler`

which creates the subscription in `call->not` and generates this event: `CALL_EVENT_TRANSFER`

in case of errors, this one is called:

```
			(void)call_notify_sipfrag(call, 500, "%m", err);
```

perhaps it can be used also in your case ?

**Comment by juha-h** [comment]
Yes, looks like it.  Just need to find the place where the outgoing call leg is closed due to CANCEL.

**Comment by juha-h** [comment]
If I read the source correctly. Refer-To call gets its call->not from the parent call.  So when Refer-To call is hung up, call_hangup() could check if call->not exists and if so, call call_notify_sipfrag() on the parent call.  But does Refer-To call have access to its parent call?

**Comment by alfredh** [comment]
initially there is one instance of `struct call`.

when the transfer happens, it creates a second instance of `struct call`.
the `call->not` object is inherited from the original call.

while the transfer is in progress, you have to deal with 2 instances of `struct call`
which can make debugging tricky.

**Comment by juha-h** [comment]
The problem that I'm facing is that the second call (to Refer-To) only inherits call->not objects (not the whole call object)  from the original call:
```
int call_alloc(...struct call *xcall,...)
{
...
	/* inherit certain properties from original call */
	if (xcall) {
		call->not = mem_ref(xcall->not);
	}
...
}
```
When the second call is closed by the caller,  its CALL_EVENT_CLOSED  handler should be able to make call
```
call_notify_sipfrag(xcall, 487, "Request Terminated");
```
where xcall param is the original call object.

**Comment by alfredh** [comment]
take a look at this function:

```c
int call_notify_sipfrag(struct call *call, uint16_t scode,
			const char *reason, ...)
{
	struct mbuf *mb;
	va_list ap;
	int err;

	if (!call)
		return EINVAL;

	mb = mbuf_alloc(512);
	if (!mb)
		return ENOMEM;

	va_start(ap, reason);
	(void)mbuf_printf(mb, "SIP/2.0 %u %v\n", scode, reason, &ap);
	va_end(ap);

	mb->pos = 0;

	if (scode >= 200) {
		err = sipevent_notify(call->not, mb, SIPEVENT_TERMINATED,
				      SIPEVENT_NORESOURCE, 0);

		call->not = mem_deref(call->not);
	}
	else {
		err = sipevent_notify(call->not, mb, SIPEVENT_ACTIVE,
				      SIPEVENT_NORESOURCE, 0);
	}

	mem_deref(mb);

	return err;
}
```

only `call->not` is used.

the `not` object is shared between parent call and 2nd call, so it does not matter which one you use.

your suggested code should work if you use "call", i.e. 2nd call object.

**Comment by juha-h** [comment]
How about this:
```
diff --git a/src/call.c b/src/call.c
index 914327d..1fd36d4 100644
--- a/src/call.c
+++ b/src/call.c
@@ -1015,6 +1017,9 @@ void call_hangup(struct call *call, uint16_t scode, const char *reason)
             sip_dialog_callid(sipsess_dialog(call->sess)),
             call->peer_uri);
 
+       if (call->not)
+           call_notify_sipfrag(call, 487, "Request Terminated");
+
        call->sess = mem_deref(call->sess);
        break;
    }
```
According to my tests, it causes NOTIFY to be sent to referrer when referee cancels the Refer-To call.

**Comment by alfredh** [comment]
without looking into the details, this patch looks fine to me.

**Comment by juha-h** [comment]
OK, I created pull request https://github.com/baresip/baresip/pull/1082 that includes the patch.

**Comment by juha-h** [comment]
Closed by https://github.com/baresip/baresip/commit/356d7f9d8bdc410e7a4e88147a722eee444a3931.
