### ISSUE TITLE
about RPI 4b video coding with omx

### ISSUE THREAD

**Issue by jobo-zt** [baresip/baresip#1077]
remote display right when OMX is not used
![image](https://user-images.githubusercontent.com/38849089/91836794-dbbec080-ec7d-11ea-93a0-9dfb98f03033.png)

I enabled video hardware acceleration whith omx after remote display error
![image](https://user-images.githubusercontent.com/38849089/91836834-e7aa8280-ec7d-11ea-852f-d121a584316f.png)

log
pi@raspberrypi:~/code/baresip/baresip $ ./baresip -v -e "/answermode auto" 
baresip v1.0.0 Copyright (C) 2010 - 2020 Alfred E. Heggestad et al.
Binding to interface or IP address 'tun0'
net: tun0: could not get IPv6 address (No such device)
Local network address:  IPv4=tun0|10.8.0.13 
ui: stdio
opus: fmtp="stereo=1;sprop-stereo=1;maxaveragebitrate=28000"
aucodec: opus/48000/2
aucodec: PCMU/8000/1
aucodec: PCMA/8000/1
aufilt: speex_pp
ausrc: alsa
auplay: alsa
omx: created video_render component
vidisp: omx
vidcodec: H264
vidcodec: H264
vidcodec: H263
vidcodec: MP4V-ES
vidcodec: H265
avcodec: using H.264 encoder 'h264_omx' -- OpenMAX IL H.264 video encoder
avcodec: using H.264 decoder 'h264' -- H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10
avcodec: using H.265 encoder 'libx265' -- libx265 H.265 / HEVC
avcodec: using H.265 decoder 'hevc' -- HEVC (High Efficiency Video Coding)
vidsrc: v4l2
medianat: stun
medianat: turn
medianat: ice
uuid: loaded UUID 478a0f68-3fce-11e5-2156-7b5121da1ebc from file /home/pi/.baresip/uuid
Populated 2 accounts
module: loading app auloop.so
module: loading app contact.so
Populated 3 contacts
module: loading app debug_cmd.so
module: loading app menu.so
module: loading app vidloop.so
Populated 3 audio codecs
Populated 1 audio filter
Populated 5 video codecs
Populated 0 video filters
baresip is ready.
/answermode auto
Answer mode changed to: auto
unhandeled request from 10.8.0.13:5060: REGISTER sip:10.8.0.13
reg: sip:0755000013@10.8.0.13: 501 Not Implemented (baresip v1.0.0 (arm6/linux))
ua: sipsess connect via UDP 10.8.0.3:5060 --> 10.8.0.13:5060
ua: using AF from sdp offer: af=AF_INET
call: alloc with params laddr=10.8.0.13, af=AF_INET, use_rtp=1
call: use_video=1
call: answering call on line 1 from sip:0755000003@10.8.0.3 with 200
call: update media
stream: update 'audio'
stream: audio: starting RTCP with remote 10.8.0.3:10185
stream: update 'video'
stream: video: starting RTCP with remote 10.8.0.3:8375
audio: Set audio decoder: opus 48000Hz 2ch
audio: start
audio: create recv buffer [20 - 160 ms] [3840 - 30720 bytes]
alsa: reset: srate=48000, ch=2, num_frames=960, pcmfmt=S16_LE
alsa: playback started (plughw:0,0)
audio: player started with sample format S16LE
audio: Set audio encoder: opus 48000Hz 2ch
opus: encoder fmtp (stereo=1;sprop-stereo=1;maxaveragebitrate=28000)
audio: start
speex_pp: Speex preprocessor loaded: srate = 48000Hz
alsa: reset: srate=48000, ch=2, num_frames=960, pcmfmt=S16_LE
alsa: recording started (plughw:1,0) format=S16LE
audio: source started with sample format S16LE
audio tx pipeline:        alsa ---> speex_pp ---> opus
audio rx pipeline:        alsa <--- opus
Set video encoder: H264 packetization-mode=0 (2500000 bit/s, 25.00 fps)
avcodec: h264 encoder activated
avcodec: video encoder H264: 25.00 fps, 2500000 bit/s, pktsize=1024
omx: vidisp_alloc
v4l2: /dev/video0: found valid V4L2 device (1920 x 1080) pixfmt=YUYV
v4l2: Current input: "Camera 1"
v4l2: current framerate is 5.00 fps
warning: The VAD has been replaced by a hack pending a complete rewrite
speex_pp: state inited (frame_size=1920)
main: long async blocking: 513>100 ms (h=0xb6f0b904 arg=0x1ad6c00)
stream: incoming rtp for 'audio' established, receiving from 10.8.0.3:10184
[h264_omx @ 0xab5005d0] Using OMX.broadcom.video_encode
call: stream start (active=1)
opus: encoder fmtp (stereo=1;sprop-stereo=1;maxaveragebitrate=28000)
audio: start
Set video decoder: H264 packetization-mode=0
avcodec: h264 decoder activated
avcodec: decode: hardware accel disabled
avcodec: video decoder H264 ()
0755000013@10.8.0.13: Call established: sip:0755000003@10.8.0.3
avcodec: encoder picture updatebit/s) efps=0.0/0.0    
stream: incoming rtp for 'video' established, receiving from 10.8.0.3:8374
video: receiving with resolution 1280 x 720 and format 'yuv420p'
omx: new frame size: w=1280 h=720
omx: linesize[0]=1280   linesize[1]=640 linesize[2]=640
omx_update_size 1280 720
omx port definition: h=160 w=64 s=160 sh=64
omx.EventHandler: Previous command completed
d1=0    d2=2    eventData=(nil) appdata=(nil)
omx_update_size: send to execute stateomx.EventHandler: Previous command completed
d1=0    d2=3    eventData=(nil) appdata=(nil)
reg: sip:0755000013@172.16.8.254: Register: Connection timed out/9.1    
unhandeled request from 10.8.0.13:5060: REGISTER sip:10.8.0.130/9.0      
reg: sip:0755000013@10.8.0.13: 501 Not Implemented (baresip v1.0.0 (arm6/linux))
reg: sip:0755000013@172.16.8.254: Register: Connection timed out/8.4     
unhandeled request from 10.8.0.13:5060: REGISTER sip:10.8.0.130/9.8     
reg: sip:0755000013@10.8.0.13: 501 Not Implemented (baresip v1.0.0 (arm6/linux))
avcodec: encoder picture updateeo=509723/662179 (bit/s) efps=5.0/9.5     
avcodec: encoder picture updateeo=509723/662179 (bit/s) efps=5.0/9.5    
avcodec: encoder picture updateeo=495685/644552 (bit/s) efps=5.0/9.5

**Comment by alfredh** [comment]
from your picture, is look like the Y component is correct, but the U+V components are
slightly too far to the right.

the video picture is stored in this struct:

```c
/** Video frame */
struct vidframe {
	uint8_t *data[4];      /**< Video planes        */
	uint16_t linesize[4];  /**< Array of line-sizes */
	struct vidsz size;     /**< Frame resolution    */
	enum vidfmt fmt;       /**< Video pixel format  */
};
```

sometimes linesize can be larger than the width, so that linesize is aligned to 16,32 etc.

can you check the linesizes of your image?

also can you try to pinpoint which module is causing the issue?
i.e. if you only use v4l2+omx is the issue there or not ?

**Comment by alfredh** [comment]
no response from reporter .. closing ticket.

**Comment by jobo-zt** [comment]
The camera uses Logitech C920 PRO HD.
v4l2+omx There is a problem
used v4l2_codec is OK. but  blurred screen

**Comment by jobo-zt** [comment]
When used v4l2+omx, input yum422

**Comment by jobo-zt** [comment]
v4l2_codec: Driver Caps:
  Driver:        "uvcvideo"
  Card:          "HD Pro Webcam C920"
  Bus:           "usb-0000:01:00.0-1.4"
  Version:       4.0
  Capabilities:  0x84a00001
  Formats:
     YUYV:    'YUYV 4:2:2'   Maybe that's the problemMaybe that's the problem. 'YUYV 4:2:2'  format conver 'yuv420'
