### ISSUE TITLE
Using baresip as a library ==> undefined reference to `libre_init'

### ISSUE THREAD

**Issue by jacob9fanchiang** [baresip/baresip#1080]
I follow the wiki to build Baresip as a lib but I got very basic error.

My O.S: Linux demo-Lenovo-G50-70 4.15.0-112-generic #113~16.04.1-Ubuntu SMP Fri Jul 10 04:37:08 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
$ gcc --version
gcc (Ubuntu 5.4.0-6ubuntu1~16.04.12) 5.4.0 20160609

demo@demo-Lenovo:~/tt$ gcc -I/usr/local/include/re -I/usr/local/include/baresip -lbaresip -lrem -lre custom.c
/tmp/cc7X01xP.o: In function `signal_handler':
custom.c:(.text+0x17): undefined reference to `mod_close'
custom.c:(.text+0x3c): undefined reference to `info'
custom.c:(.text+0x46): undefined reference to `ua_stop_all'
/tmp/cc7X01xP.o: In function `ua_exit_handler':
custom.c:(.text+0x64): undefined reference to `debug'
custom.c:(.text+0x69): undefined reference to `re_cancel'
/tmp/cc7X01xP.o: In function `ua_event_handler':
custom.c:(.text+0x91): undefined reference to `uag_event_str'
custom.c:(.text+0xa3): undefined reference to `re_printf'
/tmp/cc7X01xP.o: In function `main':
custom.c:(.text+0xba): undefined reference to `libre_init'
custom.c:(.text+0xcc): undefined reference to `conf_configure'
custom.c:(.text+0xe9): undefined reference to `warning'
custom.c:(.text+0xf3): undefined reference to `conf_config'
custom.c:(.text+0xfb): undefined reference to `baresip_init'
custom.c:(.text+0x118): undefined reference to `warning'
custom.c:(.text+0x133): undefined reference to `ua_init'
custom.c:(.text+0x14b): undefined reference to `uag_set_exit_handler'
custom.c:(.text+0x15a): undefined reference to `uag_event_register'
custom.c:(.text+0x15f): undefined reference to `conf_modules'
custom.c:(.text+0x172): undefined reference to `re_main'
custom.c:(.text+0x18e): undefined reference to `ua_stop_all'
custom.c:(.text+0x193): undefined reference to `ua_close'
custom.c:(.text+0x198): undefined reference to `module_app_unload'
custom.c:(.text+0x19d): undefined reference to `conf_close'
custom.c:(.text+0x1a2): undefined reference to `baresip_close'
custom.c:(.text+0x1b1): undefined reference to `debug'
custom.c:(.text+0x1b6): undefined reference to `mod_close'
custom.c:(.text+0x1bb): undefined reference to `libre_close'
custom.c:(.text+0x1c0): undefined reference to `tmr_debug'
custom.c:(.text+0x1c5): undefined reference to `mem_debug'
collect2: error: ld returned 1 exit status

Then I clean up to find the reason but still got fail.

//========custom.c=====
#include <stdint.h>
#include <stdlib.h>
#include <re.h>
#include <baresip.h>
int main(int argc, char *argv[]) {
	int err;
	err = libre_init();
	return err;
}
//========end custom.c=====

Below is the console build log.
demo@demo-Lenovo:~/tt$ gcc -I/usr/local/include/re -I/usr/local/include/baresip -lbaresip -lrem -lre custom.c
/tmp/cclXDXng.o: In function `main':
custom.c:(.text+0x10): undefined reference to `libre_init'
custom.c:(.text+0x1c): undefined reference to `libre_close'
collect2: error: ld returned 1 exit status

I have git clone and make 3 libs and follow the instruction to make and install.
git clone https://github.com/baresip/re.git
git clone https://github.com/creytiv/rem.git
git clone https://github.com/alfredh/baresip.git

The /usr/local/lib contains all the libs.

demo@demo-Lenovo:/usr/local/lib$ ls -al
total 6104
drwxr-xr-x  6 root root     4096  9   6 11:38 .
drwxr-xr-x 10 root root     4096  3   1  2018 ..
drwxr-xr-x  3 root root     4096  6  23 10:56 baresip
-rw-r--r--  1 root root  1013814  9   6 11:19 libbaresip.a
-rw-r--r--  1 root root   562840  9   6 11:19 libbaresip.so
-rwxr-xr-x  1 root root  2661182  9   6 11:16 libre.a
-rwxr-xr-x  1 root root   437458  9   6 00:31 librem.a
-rwxr-xr-x  1 root root   261648  9   6 00:31 librem.so
-rwxr-xr-x  1 root root  1280176  9   6 11:16 libre.so
drwxr-xr-x  2 root root     4096  9   6 11:19 pkgconfig

Sorry for my new to Baresip and maybe a dumb question.

Thanks.

Jacob

**Comment by alfredh** [comment]
try to put the linker flags after the input .c file, i.e.:

```
$ gcc -I/usr/local/include/re -I/usr/local/include/baresip custom.c -lbaresip -lrem -lre 
```

**Comment by alfredh** [comment]
note: for this kind of questions, it is probably better to ask on the mailing list:

https://github.com/baresip/baresip/wiki/Guidelines-for-reporting-Issues

**Comment by jacob9fanchiang** [comment]
Sorry for late reply.
It works. Thanks. And I see guideline now. Will ask in right category next time.

Jacob
