### ISSUE TITLE
Main website down

### ISSUE THREAD

**Issue by martim01** [baresip/baresip#1088]
Hi,
I wanted to look at the documentation linked to in the ReadMe but it seems the whole creytive.com website is not working,

**Comment by alfredh** [comment]
The creytiv.com server has been closed down.

We are now only using Github and Google groups for project hosting.

You can generate local doxygen with:

`$ make dox`

**Comment by juha-h** [comment]
Alfred E. Heggestad writes:

> The creytiv.com server has been closed down.

There was lots of useful info on that site plus the mailing list
archives.  It is pity if all that is lost.
