### ISSUE TITLE
avfilter module is missing explicit license

### ISSUE THREAD

**Issue by jonassmedegaard** [baresip/baresip#1089]
Hi,

Newly added avfilter module has copyright Mikhail Kurkov but no license statement.

I assume it has same license as the project in general (BSD-3-Clause) but would be better if explicitly stated in each copyright-protected file.

**Comment by alfredh** [comment]
adding @mkurkov 

the license is defined in docs/COPYING (BSD license).

all files and the whole project has the same license.

should we add the BSD license text to all .c files ?

**Comment by jonassmedegaard** [comment]
Well, not all code is BSD-3-Clause licensed: test/ccheck.py is GPL-2.

I think it is best if both copyright and license is stated in each file: That way the information is less likely to be lost if code is borrowed by other projects (like apparently you did with modules/ctrl_tcp/netstring).

As I understand it (I am not a lawyer), *nothing* is required for legal purposes - it is (nowadays, since [the US signed the Berne Convention in 1989](https://en.wikipedia.org/wiki/Copyright#International_copyright_treaties)) all done purely as a curtesy for your users, to clearly inform them of the freedoms that you have granted them.

**Comment by alfredh** [comment]
we could change the license for ccheck.py to BSD also, it is just a small test tool.

adding the BSD license text to all .c file is IMHO not really needed.
it will be a lot of redundant text in all .c files.

**Comment by jonassmedegaard** [comment]
Quoting Alfred E. Heggestad (2020-09-28 14:51:33)
> we could change the license for ccheck.py to BSD also, it is just a small test tool.
> 
> adding the BSD license text to all .c file is IMHO not really needed.
> it will be a lot of redundant text in all .c files.

there is _already_ a license notice in all code files _except_ the few I filed as an issue here.

I am not talking about expanding to write _more_ everywhere.

**Comment by jonassmedegaard** [comment]
Quoting Jonas Smedegaard (2020-09-28 15:58:27)
> Quoting Alfred E. Heggestad (2020-09-28 14:51:33)
> > we could change the license for ccheck.py to BSD also, it is just a small test tool.
> > 
> > adding the BSD license text to all .c file is IMHO not really needed.
> > it will be a lot of redundant text in all .c files.
> 
> there is _already_ a license notice in all code files _except_ the few I filed as an issue here.
> 
> I am not talking about expanding to write _more_ everywhere.

oh, my mistake: Indeed most files lack license.

I recommend to add just a minimum license hint.

...and I am not alone - see e.g. here: https://reuse.software/

**Comment by jonassmedegaard** [comment]
Concretely, I recommend to add this below copyright line(s) in every 
code file:

  SPDX-License-Identifier: BSD-3-Clause

**Comment by alfredh** [comment]
all the code in this project is now BSD.

I suggest to keep the file headers as is. I dont see any value of adding more text, that is
already present in docs/COPYING.

The individual contributors are welcome to put what ever they want in the file header.

If you want to keep discussions about this topic, I suggest that you move it
to the baresip mailing list.

suggest closing this issue.

**Comment by jonassmedegaard** [comment]
Thanks for clarifying the licensing of the project.

It seems I succeeded in expressing my suggestions for clarifying even further, and that you in turn made it clear that you disagree with that.  That's fine - I see no need to discuss further.
