### ISSUE TITLE
dl: mod: /usr/local/lib/baresip/modules/alsa.so (/usr/local/lib/baresip/modules/alsa.so: cannot open shared object file: No such file or directory)

### ISSUE THREAD

**Issue by mreading2020** [baresip/baresip#1093]
Getting this when staring the service. 

dl: mod: /usr/local/lib/baresip/modules/alsa.so (/usr/local/lib/baresip/modules/alsa.so: cannot open shared object file: No such file or directory)
module alsa.so: No such file or directory

################

after compiling (I can not seeing it being added, from the latest repo "master" 

install -m 0755 baresip /usr/local/bin
install -m 0644 account.so auloop.so b2bua.so contact.so ctrl_tcp.so debug_cmd.so ebuacip.so echo.so fakevideo.so httpd.so ice.so menu.so mwi.so natpmp.so presence.so selfview.so srtp.so stun.so turn.so uuid.so vidbridge.so vidinfo.so vidloop.so vumeter.so aubridge.so aufile.so ausine.so cons.so evdev.so g711.so l16.so oss.so stdio.so syslog.so v4l2.so v4l2_codec.so /usr/local/lib/baresip/modules
install -m 0644 share/* /usr/local/share/baresip

**Comment by mreading2020** [comment]
fixed with : https://github.com/baresip/baresip/wiki/Using-Baresip:-Module-alsa

**Comment by alfredh** [comment]
you need to install ALSA dev headers and re-compile.
