### ISSUE TITLE
remote control

### ISSUE THREAD

**Issue by amoonrah** [baresip/baresip#1094]
Hi,

is there any documentation on how to control baresip.

I want to launch baresip, (accounts configured of course)

then tell it to dial a numer and then tell it to play a DTMF sequence.

is there documentation anywhere how to do that with the different CTRL modules ?

**Comment by alfredh** [comment]
please take a look at the ctrl_tcp module:

https://github.com/baresip/baresip/blob/master/modules/ctrl_tcp/ctrl_tcp.c#L13


please use the mailing-list to ask questions, as stated here:

https://github.com/baresip/baresip/wiki/Guidelines-for-reporting-Issues
