### ISSUE TITLE
Buildroot 2020 support

### ISSUE THREAD

**Issue by MAhlborg** [baresip/baresip#1108]
I am trying to compile baresip for ARM via buildroot 2020.08.1. I am using the mk files from issue #260 , which I did adapt to version 1.0.0 of baresip (changed version numbers and download sources). libre and librem are building fine, however baresip produces error messages:

...
 CC [M]  build-arm/modules/account/account.o
  CC [M]  build-arm/modules/auloop/auloop.o
  CC [M]  build-arm/modules/b2bua/b2bua.o
  CC [M]  build-arm/modules/contact/contact.o
  CC [M]  build-arm/modules/ctrl_tcp/ctrl_tcp.o
arm-buildroot-linux-gnueabihf-gcc: ERROR: unsafe header/library path used in cross-compilation: '-I/usr/local/include/rem'
arm-buildroot-linux-gnueabihf-gcc: ERROR: unsafe header/library path used in cross-compilation: '-I/usr/local/include/rem'
arm-buildroot-linux-gnueabihf-gcc: ERROR: unsafe header/library path used in cross-compilation: '-I/usr/local/include/rem'
mk/mod.mk:42: recipe for target 'build-arm/modules/account/account.o' failed
make[2]: *** [build-arm/modules/account/account.o] Error 1
make[2]: *** Waiting for unfinished jobs....
mk/mod.mk:42: recipe for target 'build-arm/modules/auloop/auloop.o' failed
make[2]: *** [build-arm/modules/auloop/auloop.o] Error 1
mk/mod.mk:42: recipe for target 'build-arm/modules/b2bua/b2bua.o' failed
make[2]: *** [build-arm/modules/b2bua/b2bua.o] Error 1
  CC [M]  build-arm/modules/ctrl_tcp/tcp_netstring.o
arm-buildroot-linux-gnueabihf-gcc: ERROR: unsafe header/library path used in cross-compilation: '-I/usr/local/include/rem'
mk/mod.mk:42: recipe for target 'build-arm/modules/contact/contact.o' failed
make[2]: *** [build-arm/modules/contact/contact.o] Error 1
arm-buildroot-linux-gnueabihf-gcc: ERROR: unsafe header/library path used in cross-compilation: '-I/usr/local/include/rem'
mk/mod.mk:42: recipe for target 'build-arm/modules/ctrl_tcp/ctrl_tcp.o' failed
make[2]: *** [build-arm/modules/ctrl_tcp/ctrl_tcp.o] Error 1
arm-buildroot-linux-gnueabihf-gcc: ERROR: unsafe header/library path used in cross-compilation: '-I/usr/local/include/rem'
mk/mod.mk:42: recipe for target 'build-arm/modules/ctrl_tcp/tcp_netstring.o' failed
make[2]: *** [build-arm/modules/ctrl_tcp/tcp_netstring.o] Error 1
package/pkg-generic.mk:247: recipe for target '/home/martin/buildroot/buildroot-2020.08.1/output/build/baresip-1.0.0/.stamp_built' failed
make[1]: *** [/home/martin/buildroot/buildroot-2020.08.1/output/build/baresip-1.0.0/.stamp_built] Error 2
Makefile:84: recipe for target '_all' failed
make: *** [_all] Error 2

**Comment by alfredh** [comment]
hi,

can you please share the full set of makefiles and the exact command for how the makefile is invoked ?


you can try to disable the mentioned rem path here in Makefile:

```
CFLAGS    += -I$(SYSROOT)/local/include/rem -I$(SYSROOT)/include/rem
ifneq ($(SYSROOT_LOCAL),)
CFLAGS    += -I$(SYSROOT_LOCAL)/include/rem
endif
```

**Comment by MAhlborg** [comment]
Hi,

just this afternoon I solved the problem. When SYSROOT_LOCAL is not defined, it is set to /usr/local in the baresip Makefile (line 39 to 41). Defining this variable in the buildroot .mk file leads to a successful compile. If wanted, I can post my .mk files on monday when I am back at work.

Best regards,
Martin Ahlborg

**Comment by MAhlborg** [comment]
Here as promised, the .mk files for libre, librem and baresip, that will work with baresip 1.0 and buildroot 2020.

libre.mk
`############################################################################
#
# libre
#
###########################################################################

LIBRE_VERSION = 1.1.0
LIBRE_SOURCE = v$(LIBRE_VERSION).tar.gz
LIBRE_SITE = https://github.com/baresip/re/archive
LIBRE_INSTALL_STAGING = YES

ifeq ($(BR2_PACKAGE_OPENSSL),y)
LIBRE_DEPENDENCIES += openssl
endif
ifeq ($(BR2_PACKAGE_ZLIB),y)
LIBRE_DEPENDENCIES += zlib
endif

define LIBRE_BUILD_CMDS
	$(TARGET_MAKE_ENV) \
		$(MAKE) -C $(@D) \
			LIBRE_MK=$(STAGING_DIR)/usr/share/re/re.mk \
			LIBRE_INC=$(STAGING_DIR)/usr/include/re \
			LIBRE_SO=$(STAGING_DIR)/usr/lib \
			CC="$(TARGET_CC)" \
			EXTRA_CFLAGS="$(TARGET_CFLAGS)" \
			EXTRA_LFLAGS="-lm" \
			DESTDIR="$(STAGING_DIR)" \
			SYSROOT="$(STAGING_DIR)/usr" \
			SYSROOT_ALT="$(STAGING_DIR)/usr" \
			RELEASE=1 \
			CROSS_COMPILE="$(TARGET_CROSS)" \
			OS=linux \
			all install
endef


define LIBRE_INSTALL_TARGET_CMDS
        $(INSTALL) -m 644 -D $(@D)/libre.so $(TARGET_DIR)/usr/lib/libre.so
endef

define LIBRE_UNINSTALL_STAGING_CMDS
        $(RM) -r $(STAGING_DIR)/usr/include/re
        $(RM) $(STAGING_DIR)/usr/lib/libre.a
        $(RM) $(STAGING_DIR)/usr/lib/libre.so
endef

define LIBRE_UNINSTALL_TARGET_CMDS
        $(RM) $(TARGET_DIR)/usr/lib/libre.so
endef

$(eval $(generic-package))
$(eval $(host-generic-package))
`

librem.mk
`#############################################################
#
# librem
#
#############################################################

LIBREM_VERSION = 0.6.0
LIBREM_SOURCE = v$(LIBREM_VERSION).tar.gz
LIBREM_SITE = https://github.com/creytiv/rem/archive
LIBREM_INSTALL_STAGING = YES

ifeq ($(BR2_PACKAGE_LIBRE),y)
LIBREM_DEPENDENCIES += libre
endif

define LIBREM_BUILD_CMDS
	$(TARGET_MAKE_ENV) \
		$(MAKE) -C $(@D) \
			LIBRE_MK=$(STAGING_DIR)/usr/share/re/re.mk \
			LIBRE_INC=$(STAGING_DIR)/usr/include/re \
			LIBRE_SO=$(STAGING_DIR)/usr/lib \
			HAVE_LIBRESOLV= \
			CC="$(TARGET_CC)" \
			EXTRA_CFLAGS="$(TARGET_CFLAGS)" \
			EXTRA_LFLAGS="-lm" \
			DESTDIR="$(STAGING_DIR)" \
			SYSROOT="$(STAGING_DIR)/usr" \
			SYSROOT_ALT="$(STAGING_DIR)/usr" \
			RELEASE=1 \
			CROSS_COMPILE="$(TARGET_CROSS)" \
			OS=linux \
			all install
endef

define LIBREM_INSTALL_TARGET_CMDS
        $(INSTALL) -m 644 -D $(@D)/librem.so $(TARGET_DIR)/usr/lib/librem.so
endef

define LIBREM_UNINSTALL_STAGING_CMDS
        $(RM) -r $(STAGING_DIR)/usr/include/rem
        $(RM) $(STAGING_DIR)/usr/lib/librem.a
        $(RM) $(STAGING_DIR)/usr/lib/librem.so
endef

define LIBREM_UNINSTALL_TARGET_CMDS
        $(RM) $(TARGET_DIR)/usr/lib/librem.so
endef

$(eval $(generic-package))
#$(eval $(host-generic-package))
`

baresip.mk
`#############################################################
#
# BARESIP
#
#############################################################

BARESIP_VERSION = 1.0.0
BARESIP_SOURCE = v$(BARESIP_VERSION).tar.gz
BARESIP_SITE = https://github.com/baresip/baresip/archive
BARESIP_DEPENDENCIES = libre librem zlib

BARESIP_MAKE_ENV = \
        $(TARGET_CONFIGURE_OPTS) \
        SYSROOT=$(STAGING_DIR)/usr \
        SYSROOT_LOCAL=$(STAGING_DIR)/usr \
        LD="$(TARGET_CC)" \
        LFLAGS="$(TARGET_LDFLAGS)"

BARESIP_MAKE_ARGS = \
        LIBRE_MK="$(STAGING_DIR)/usr/share/re/re.mk" \
        LIBRE_INC="$(STAGING_DIR)/usr/include/re" \
        LIBRE_SO="$(STAGING_DIR)/usr/lib" \
        LIBREM_MK="$(STAGING_DIR)/usr/share/rem/rem.mk" \
        LIBREM_INC="$(STAGING_DIR)/usr/include/rem" \
        LIBREM_SO="$(STAGING_DIR)/usr/lib"

ifeq ($(BR2_PACKAGE_ALSA_LIB),y)
BARESIP_DEPENDENCIES += alsa-lib
endif

ifeq ($(BR2_PACKAGE_FFMPEG_SWSCALE),y)
BARESIP_DEPENDENCIES += ffmpeg
BARESIP_MAKE_ENV += \
        CFLAGS+=-DCODEC_TYPE_VIDEO=AVMEDIA_TYPE_VIDEO
endif

ifeq ($(BR2_PACKAGE_LIBSNDFILE),y)
BARESIP_DEPENDENCIES += libsndfile
endif

ifeq ($(BR2_PACKAGE_SPEEX),y)
BARESIP_DEPENDENCIES += speex
endif

ifeq ($(BR2_PACKAGE_UTIL_LINUX_LIBUUID),y)
BARESIP_DEPENDENCIES += util-linux
endif

ifeq ($(BR2_PACKAGE_XORG7),y)
BARESIP_DEPENDENCIES += xlib_libXext
endif

define BARESIP_BUILD_CMDS
        $(BARESIP_MAKE_ENV) $(MAKE) $(BARESIP_MAKE_ARGS) -C $(@D) all
endef

define BARESIP_CLEAN_CMDS
        $(BARESIP_MAKE_ENV) $(MAKE) $(BARESIP_MAKE_ARGS) -C $(@D) clean
endef

define BARESIP_INSTALL_TARGET_CMDS       
        $(BARESIP_MAKE_ENV) DESTDIR=$(TARGET_DIR) $(MAKE) $(BARESIP_MAKE_ARGS) -C $(@D) install
endef

define BARESIP_UNINSTALL_TARGET_CMDS
        $(RM) $(TARGET_DIR)/usr/bin/baresip
        $(RM) -r $(TARGET_DIR)/usr/lib/baresip
        $(RM) -r $(TARGET_DIR)/usr/share/baresip
endef

$(eval $(generic-package))
$(eval $(host-generic-package))
`

**Comment by alfredh** [comment]
many thanks.

is this a project that is publicly available ?
i.e. can we link to it ?

**Comment by MAhlborg** [comment]
At the moment, this is just an internal prototype (which looks promising nonetheless). So unfortunately there is nothing to link to yet. If we ever reach a stage where we have something to show, I will send you a message.

Thanks for the help,
Best regards

**Comment by alfredh** [comment]
okay, thanks

is there then anything else that is open in this ticket ?

the link to your project can also be added here:
https://github.com/baresip/baresip/wiki/3rd-party-projects-using-Baresip

**Comment by MAhlborg** [comment]
Will do! Otherwise everything is fine. I will close the ticket.

**Comment by n00b42** [comment]
Using BR 2020.11 and using your Makefiles I still cant get past a very similar error.
>   CC [M]  build-arm/modules/avcodec/avcodec.o
arm-buildroot-linux-gnueabihf-gcc: ERROR: unsafe header/library path used in cross-compilation: '-isystem' '/usr/local/include'

However, the "-isystem" is added in the "modules/avcodec/module.mk", removing it will allow to compile, but might yield other problems.
