### ISSUE TITLE
S16 44100 Sample Rate

### ISSUE THREAD

**Issue by bpm1992** [baresip/baresip#1109]
Hi,
I'm trying to connect to an asterisk server using the L16 codec so that I can bridge between a local environment where Jackd needs to run at 44.1 KHz and use the Asterisk server to transcode and resample Opus 48 KHz. 

It looks like Baresip is only showing capabilities for 48 KHz based codecs, versus the 44.1 KHz (slin44) codec.

In the configuration, I've set the following to 44.1 KHz.
```
ausrc_srate             44100
auplay_srate            44100
```

The sample rate shows up here:
```
aucodec: L16/48000/2
aucodec: L16/44100/2
aucodec: L16/32000/2
aucodec: L16/16000/2
aucodec: L16/8000/2
aucodec: L16/48000/1
aucodec: L16/44100/1
aucodec: L16/32000/1
aucodec: L16/16000/1
aucodec: L16/8000/1
```

Here is the error from Asterisk where the capabilities incompatibility is shown. Asterisk is offering slin44 whereas Baresip is not despite it showing up as an available codec.  

```
res_pjsip_sdp_rtp.c: No joint capabilities for 'audio' media stream between 
our configuration((opus|speex32|silk24|g722|g726|slin44|ilbc|gsm|speex16|speex|silk16|silk12|silk8|ulaw)) 
and incoming SDP((slin|slin48|slin32|slin16))
```

Are there settings I'm missing to force baresip to run at 44.1 KHz?  I am running the latest code compiled from Git. I'm also happy to do a custom build if I can be pointed to the relevant areas of the code.

Thanks.

**Comment by alfredh** [comment]
hi,

can you try to enable SIP trace in baresip to see which codecs are sent in the SDP Offer:

```
$ baresip -s
```

You can force a specific codec by using the `audio_codecs` option in accounts:

```
<sip:user@example.net>;audio_codecs=L16/44100
```

**Comment by alfredh** [comment]
hi @bpm1992 

I tried to force that codec, and it is listed in the outgoing SDP:

```
v=0
o=- 2424690746 2019574143 IN IP4 192.168.88.29
s=-
c=IN IP4 192.168.88.29
t=0 0
a=tool:baresip 1.0.0
m=audio 14358 RTP/AVP 11 101
a=rtpmap:11 L16/44100
a=rtpmap:101 telephone-event/8000
a=fmtp:101 0-15
a=sendrecv
a=label:1
a=rtcp-rsize
a=ssrc:288142074 cname:sip:aeh@iptel.org
a=minptime:10
a=ptime:20
```

so it should be working as expected.

Can you please check the outgoing SDP on your side ?

**Comment by bpm1992** [comment]
Thanks for the help.  I made the changes to the account configuration, and am now able to get the call to connect with asterisk. 

```
stream: update 'audio'
audio: Set audio decoder: L16 44100Hz 1ch
jack: play 44100Hz,1ch
jack: source unique name `baresip' assigned
jack: engine sample rate: 44100 max_frames=1024
jack: connecting default input ports
jack: sampc=1024
audio: player started with sample format FLOAT
audio: Set audio encoder: L16 44100Hz 1ch
jack: destination unique name `baresip-01' assigned
jack: engine sample rate: 44100 max_frames=1024
jack: connecting default output ports
jack: source sampc=1024
audio: source started with sample format FLOAT
audio tx pipeline:        jack ---> L16
audio rx pipeline:        jack <--- L16
```

The issue I now see seems to be related to encoding, or somewhere in the call.  The L16 Encode errors keep flowing through and I cannot hear audio on either side of the call.

```
940@pbx.test.net: Call established: sip:920@pbx.test.net;transport=udp;answermode=auto
main: long async blocking: 105>100 ms (h=0x7f9f54b25bdf arg=0x56080ead3af0)
audio: L16 encode error: 441 samples (Operation not supported)
audio: L16 encode error: 441 samples (Operation not supported)
audio: L16 encode error: 441 samples (Operation not supported)
```

**Comment by alfredh** [comment]
please have a look at the config:

```
ausrc_format            s16             # s16, float, ..
auplay_format           s16             # s16, float, ..
auenc_format            s16             # s16, float, ..
audec_format            s16             # s16, float, ..
```

the ausrc format should match the sample format of the audio driver,
which in your case is Jack and Float.

The auenc format should match the sample format of the encoder,
which in your case is L16 and S16

and similar with auplay and audec format.

you can try this:

```
ausrc_format            float
auplay_format           float
auenc_format            s16
audec_format            s16
```

it is not intuitive for an end-user to understand this. one suggestion might be to
remove auenc/audec format and let the core convert automatically.

we should also consider updating the aucodec API to use this type
for audio frames:

```c
/**
 * Defines a frame of audio samples
 */
struct auframe {
	int fmt;             /**< Sample format (enum aufmt)        */
	void *sampv;         /**< Audio samples (must be mem_ref'd) */
	size_t sampc;        /**< Total number of audio samples     */
	uint64_t timestamp;  /**< Timestamp in AUDIO_TIMEBASE units */
};
```

**Comment by alfredh** [comment]
I did not hear back from you, so I assume that it is working.

please also use the mailing-list to ask questions:

https://github.com/baresip/baresip/wiki/Guidelines-for-reporting-Issues
