### ISSUE TITLE
TLS SNI shows IP address rather than domain name

### ISSUE THREAD

**Issue by robdyck** [baresip/baresip#1111]
Edit: sorry about the double post. I thought the first one didn't go through because when I hit submit, I went to a 404 unknown.

If the server is configured to do domain matching against the received SNI the TLS connection will be dropped if the SNI has an address rather than a configured domain name. The point of SNI is to have an IP address serve multiple SIP domains.

**Comment by alfredh** [comment]
can you please provide a Wireshark trace of the TLS traffic ?

please also include a full config and full log.

**Comment by robdyck** [comment]
Unfortunately I didn't keep the original wireshark trace and in the meantime I updated baresip and re. Now I am unable to reproduce the result. When i capture the TLS HELLO the servername extension is missing. I am attaching it anyways.
Regardless whether the SNI has incorrect information or it missing entirely, the result is the same.
If servername matching is configured then TLS setup fails. I had a quick look into the re code and I see a function for setting servername but it doesn't seem to be called.
```
Populated 1 account
Populated 3 contacts
Populated 4 audio codecs
Populated 0 audio filters
Populated 2 video codecs
Populated 2 video filters
baresip is ready.
tls: connect: error (r=-1, ssl_err=1)
```
From opensips I see the following -
```Nov 12 15:17:26 [737482] INFO:tls_mgm:ssl_servername_cb: No domain found matching host: (null) in servername extension
Nov 12 15:17:26 [737482] ERROR:proto_tls:tls_accept: New TLS connection from 2001:DEAD:BEEF:9B5D:41748 failed to accept
Nov 12 15:17:26 [737482] ERROR:proto_tls:tls_print_errstack: TLS errstack: error:1422E0EA:SSL routines:final_server_name:callback failed
Nov 12 15:17:26 [737482] ERROR:proto_tls:tls_read_req: failed to do pre-tls reading
[tls-hello.txt](https://github.com/baresip/baresip/files/5533932/tls-hello.txt)

```

**Comment by robdyck** [comment]
I forgot the configuration and logs.
[config.txt](https://github.com/baresip/baresip/files/5533968/config.txt)
[accounts.txt](https://github.com/baresip/baresip/files/5533979/accounts.txt)
[baresip.log.txt](https://github.com/baresip/baresip/files/5533989/baresip.log.txt)

**Comment by alfredh** [comment]
are you sure that it is the missing SNI that is causing the TLS error on the server side ?

I did not know that SNI was required for SIP over TLS to work.
what about SIP over TCP, the TCP protocol has no SNI field and SIP/TCP is still used
to server multiple SIP domains on one server.

are you sure that your SIP server is configured properly ?

did you test with other SIP clients, if so did it work/not-work? did they have TLS SNI?

**Comment by robdyck** [comment]
I run my own SIP proxy. Most recently I was trying out WEBRTC and websocket. Both SIPS and websocket require TLS intially. Websocket has been working fine and domain matching was enabled in the proxy. I had tree domains configured and the corresponding certificates. I hadn't tried baresip on TLS but thought it should just work. When it didn't work my investigation led me to SNI. If I disabled domain matching or used a wildcard baresip could connect using TLS.
SNI is not required for TLS. The proxy, opensips, also has IP matching. With IPV6 it would easy to configure multiple addresses to achieve the same thing as domain matching. IPV4 would not be so easy.
It was apparent that baresip was providing SNI but wireshark showed the IP rather than a domain name. As I said I updated baresip and re ( ICE issue ) and the SNI disappeared.
See attached file of TLS HELLO from WEBRTC client.
[TLS-with-SNI.txt](https://github.com/baresip/baresip/files/5540181/TLS-with-SNI.txt)

**Comment by alfredh** [comment]
do you have any other SIP clients that supports SNI on the SIP/TLS transport ?


you can try to add it using this function:

```c
int tls_set_servername(struct tls_conn *tc, const char *servername)
```

you can try to call it from re/src/sip/transp.c:

after this code:

```c
              err = tls_start_tcp(&conn->sc, transp->tls, conn->tc, 0);
                if (err)
                        goto out;
```

**Comment by robdyck** [comment]
Linphone sends SNI in its Hello.  Saraphone sends SNI. Clients built with AudioCodes demo kit send SNI. These are WebRTC clients. Saraphone is built with sip.js library and AudioCodes is built with the JSSip library.

A tool I have used for testing TLS is openssl s_client. It always sends SNI unless
 given the -noservername option. It takes the servername from the URL but the -servername option can be set to send an arbitrary name.

I tried WSS again. It didn't work well in the previous re version that I used but with my latest I get a bit farther. It actually fails the same way as my initial report, that is to say it is sending the IP instead of the domain name. Here is the opensips log ( servername matching enabled ) --
```
Nov 18 10:23:20 [1568344] INFO:tls_mgm:ssl_servername_cb: No domain found matching host: 2001::d2b4 in servername extension
Nov 18 10:23:20 [1568344] ERROR:proto_wss:tls_accept: New TLS connection from 2001::9B5D:41510 failed to accept
```
Also the http request is attached as a file.

Sorry, I don't know what you are getting at with that code. Are you suggesting I modify re?

[wss-hello-with-SNI.txt](https://github.com/baresip/baresip/files/5561906/wss-hello-with-SNI.txt)

**Comment by alfredh** [comment]
in the HTTP client, the SNI is set here:

https://github.com/baresip/re/blob/master/src/http/client.c#L515


the TLS code is here:

```c
/**
 * Set SSL verification of hostname
 *
 * @param tc       TLS Connection
 * @param hostname Certificate hostname
 *
 * @return int     0 if success, errorcode otherwise
 */
int tls_peer_set_verify_host(struct tls_conn *tc, const char *hostname)
{
	int err = 0;

	if (!tc)
		return EINVAL;

#if OPENSSL_VERSION_NUMBER >= 0x10100000L
	err = SSL_set1_host(tc->ssl, hostname);
#else
	DEBUG_WARNING("verify hostname needs openssl version 1.1.0\n");
	return ENOSYS;
#endif

	return err == 1 ? 0 : EINVAL;
}
```

could you add some debugging to that function, and print the hostname ?

**Comment by robdyck** [comment]
```
baresip is ready.
websock: connecting to 'wss://[2001:569:7db6:9100:223:7dff:feb8:d2b4]:8000/'
tls: Host name is 2001:569:7db6:9100:223:7dff:feb8:d2b4
```

**Comment by alfredh** [comment]
can you please share your config+accounts file ?

please also share the full log.

**Comment by robdyck** [comment]
See attached files.
[baresip-log.txt](https://github.com/baresip/baresip/files/5576846/baresip-log.txt)
[baresip-config.txt](https://github.com/baresip/baresip/files/5576847/baresip-config.txt)
[baresip-accounts.txt](https://github.com/baresip/baresip/files/5576848/baresip-accounts.txt)

I did some digging. What we are seeing ( IP rather than domain ) is ws_conn_send derives ws_uri
from dst. It is defined as struct sa dst. so of course we see an IP.

I followed some of the function calls. Request > sip_ctrans_request > sip_transp_send > ws_conn_send. The file src/sip/request.c defines a structure sip_request which contains among other things the uri. The pointer to this structure gets passed along as a pointer to void. The structure definition is out of scope so not really accessible in ws_conn_send.

**Comment by juha-h** [comment]
I hit the same problem when trying to add path to wss URI, like
```
;outbound="sip:webserver.example.com:443/wss;transport=wss"
```
There was no way to get the path `/wss` to the point in code where the request was sent out.

**Comment by alfredh** [comment]
The SNI in SIP/TLS is not implemented, if you want to implemented it a patch is welcome.
or we can add it as a feature request on the Roadmap.

The SNI in http client was added in this commit:

```
4b1b8424 (Franz Auernigg        2019-10-18 11:15:08 +0200  511) 
4b1b8424 (Franz Auernigg        2019-10-18 11:15:08 +0200  512)                 if (err)
4b1b8424 (Franz Auernigg        2019-10-18 11:15:08 +0200  513)                         goto out;
4b1b8424 (Franz Auernigg        2019-10-18 11:15:08 +0200  514) 
4b1b8424 (Franz Auernigg        2019-10-18 11:15:08 +0200  515)                 err = tls_set_servername(conn->sc, req->host);
4b1b8424 (Franz Auernigg        2019-10-18 11:15:08 +0200  516)                 if (err)
4b1b8424 (Franz Auernigg        2019-10-18 11:15:08 +0200  517)                         goto out;
```

@cspiel1 @cHuberCoffee is Franz in your team ?

perhaps a good logic for setting SNI is to check if the host is a hostname or IP-address:

1. if host is hostname, add SNI
2. if host is IP-address, dont add SNI

Relevant commit:
https://github.com/baresip/re/pull/10/files

**Comment by cspiel1** [comment]
Yes, he is. But currently on another project. @cHuberCoffee  is working currently on similar things. I will discuss with him.

**Comment by cspiel1** [comment]
We think in http/client.c it should be:
```
		if (req->cli->tlshn) {
			err  = tls_peer_set_verify_host(conn->sc,
				req->cli->tlshn);
			err |= tls_set_servername(conn->sc, req->cli->tlshn);
		} else if (sa_set_str(&sa, req->host, 0)) {
			err  = tls_peer_set_verify_host(conn->sc, req->host);
			err |= tls_set_servername(conn->sc, req->host);
		}
```
But I have to test first. So first have to setup a HTTP(S) server. Then make a PR.

Should we do it similar in SIP/TLS?

**Comment by alfredh** [comment]
I have added SIP/TLS SNI to the roadmap:

https://github.com/baresip/baresip/wiki/Roadmap

this is a new feature, which is tracked in the Roadmap or elsewhere.
This issues tracker is only for bugs and defects.

The SIP/WSS should not add SNI with IP-address, which is a bug.
Christian and his team have made a fix for this, in baresip/re

**Comment by alfredh** [comment]
should be fixed in baresip/re commit c6ba3a97250a23b8f9e685b0bedffc771ca329f9

please verify.

**Comment by robdyck** [comment]
By the comments it appears I should be using re master. Is this correct? Also the change only affects WSS. Is this correct?
When compiling and testing re master with wss, SNI is missing from TLS hello. To double check I reinstalled my previous version of re and verified that SNI was included but showed IP rather than DN.

**Comment by cspiel1** [comment]
Yes, re master. The fix was done for HTTP(S) client. We plan a PR for SIP/TLS SNI.
