### ISSUE TITLE
ICE interprets IPV4 candidate as IPV6

### ISSUE THREAD

**Issue by robdyck** [baresip/baresip#1120]
The test scenario is two ICE aware UAs on the same LAN. An incoming call to baresip works fine. An outgoing call from baresip results in one way media. Baresip receives media but does not send any.
Statistics confirm this. I used verbose debug and wireshark to investigate. I am not sure that it is the root of the problem but I noticed the baresip was interpreting an IPV4 candidate as IPV6.
```
{      audio.1} added PeerReflexive remote candidate with priority 1853759231 ([::ffff:192.168.1.87]:33382)
stunsrv: {audio.1} candidate pair not found: source=[::ffff:192.168.1.87]:33382
{      video.1} added PeerReflexive remote candidate with priority 1853759231 ([::ffff:192.168.1.87]:49789)
stunsrv: {video.1} candidate pair not found: source=[::ffff:192.168.1.87]:49789
```
Attached are lengthy files of baresip debug logs and pcap from wireshark. Renaming pcap to txt.
[baresip-ice.txt](https://github.com/baresip/baresip/files/5540213/baresip-ice.txt)
[baresip.txt](https://github.com/baresip/baresip/files/5540217/baresip.txt)

**Comment by juha-h** [comment]
robdyck writes:

> Statistics confirm this. I used verbose debug and wireshark to
> investigate. I am not sure that it is the root of the problem but I
> noticed the baresip was interpreting an IPV4 candidate as IPV6.

Maybe it is because your baresip is choosing to use IPv6:
```
ua: using best effort AF: af=AF_INET6
call: alloc with params laddr=fd00::6631:50ff:fe3c:9b5d, af=AF_INET6, use_rtp=1
```

I you want to use IPv4, try if it helps if you configure IPv4 sip_listen
address.

**Comment by robdyck** [comment]
Changing the listener shouldn't have any bearing on an origination in my opinion. A modern app should prefer IPV6 anyway when there is a choice.

One of the fundamentals of SIP is the logical separation of signalling and media. Coupled with that we have ICE the purpose of which is the find a media path regardless if it IPV4, IPV6, local, or global. The devil of course is in the details such as priority.

**Comment by alfredh** [comment]
hi,

I made a small test program:

```c
#include <re.h>


int main(int argc, char *argv[])
{
	const char *addr = argv[1];
	struct sa sa;
	int err;

	err = sa_set_str(&sa, addr, 0);
	if (err) {
		re_printf("failed to parse '%s'\n", addr);
		return err;
	}

	re_printf("%s -> %j (af=%s)\n", addr, &sa, net_af2name(sa_af(&sa)));
}
```

and run it:

```
$ ./test ::ffff:192.168.1.87
::ffff:192.168.1.87 -> 192.168.1.87 (af=AF_INET)
```

This address is a so-called v4-mapped IPv6 address (IN6_IS_ADDR_V4MAPPED)

could you try to run the same program on your host and see if you get the same results ?

I am wondering if the UDP-socket is listening on v6 and the incoming packet is v4,
and in this case the address is not translated.

**Comment by robdyck** [comment]
Looks the same.
```
[root@blacky test]# ./test ::ffff:192.168.1.87
::ffff:192.168.1.87 -> 192.168.1.87 (af=AF_INET)
```
As I stated earlier, I don't know that this is the root of the one-way media problem.
Does "peer reflexive" mean that baresip got the address from the peer's SDP?

**Comment by alfredh** [comment]
the 2 agents exchange a set of candidates via SDP, normally host+srflx+relay.
if you are on a LAN, normally host-host will be selected.

a peer reflexive candidate is a new candidate discovered during the connectivity check phase.

in your case, even if Peer Reflexive fails, the host-host should still work.

I am wondering if the root of this problem is re-using a UDP socket for both
IPv4 and IPv6 traffic. Originally it was designed to handle it, perhaps it is not working properly.

BTW: which OS are you on ?

for completeness, could you please re-run the test with forcing IPv4 ?
this can be achieved with `baresip -4`.

**Comment by robdyck** [comment]
I am using Fedora 33. I tested with IPV4 only and it works.  Because my router will not hairpin I needed to register using a local IP address rather than rely on DNS. The proxy is behind NAT.
```
{      audio.1} Rx Binding Request from 192.168.1.87:44942 via Socket (candpair=Succeeded) 
{      video.1} Rx Binding Request from 192.168.1.87:51820 via Socket (candpair=Succeeded) 
{      audio.1} Rx Binding Request from 192.168.1.87:44942 via Socket (candpair=Succeeded) 
{      video.1} Rx Binding Request from 192.168.1.87:51820 via Socket (candpair=Succeeded) 
call: terminate call '3cb04c7af76ebf17' with sip:4@192.168.1.2;transport=tcp
alsa: stopping recording thread (plughw:0,0)
alsa: stopping playback thread (plug:dmix0)
video: stopping video source ..
v4l2: stopping video source..
sip:2@192.168.1.2: Call with sip:4@192.168.1.2;transport=tcp terminated (duration: 2 mins 2 secs)
video: stopping video source ..
audio: destroyed (started=1)

audio           Transmit:     Receive:
packets:           6068         6067
avg. bitrate:      21.4        128.0  (kbit/s)
errors:               0            0
pkt.report:        6021         6020
lost:                 0            0
jitter:            17.7          6.1  (ms)

video           Transmit:     Receive:
packets:          16536        21975
avg. bitrate:    1063.4       1574.9  (kbit/s)
errors:               0            0
pkt.report:       16528        21962
lost:                 0            0
jitter:            46.5          4.5  (ms)
```

**Comment by alfredh** [comment]
hi,

the IP-address in question is a so called IPv4 mapped IPv6 address:

https://en.wikipedia.org/wiki/IPv6#IPv4-mapped_IPv6_addresses

some platforms support IPv4 traffic on the IPv6 socket, which is controlled by
the socket option IPV6_V6ONLY.

```
.-------------------------.
|listen:  | IPv4  | IPv6  |
+---------+-------+-------+
|0.0.0.0  | yes   |  no   |
|::       | maybe |  yes  |
'-------------------------'
```

If the UDP socket is listening on `::` then it can be used to send/recv IPv6 packets.
But it also might be able to send/recv IPv4 packets, this depends if the OS supports it.

I have been thinking about this type of address, and I am wondering if we should classify
it as an IPv4 address or IPv6 address. It should not matter for the network stack, since it should
be able to send to 1.2.3.4 or ::ffff:1.2.3.4

but it may matter for the ICE stack, where candidate pairs are formed only with the same
address family, e.g. v4-v4 and v6-v6.

it would also be interesting to check if the socket option IPV6_V6ONLY is on/off on your platform,
this can be enabled in:

https://github.com/baresip/re/blob/master/src/udp/udp.c#L340

**Comment by robdyck** [comment]
On Fedora 33 -
```
cat /proc/sys/net/ipv6/bindv6only
0
```

**Comment by alfredh** [comment]
I have made a test-program to reproduce the problem:

```c

#define HAVE_INTTYPES_H 1
#define HAVE_INET6 1
#include <re/re.h>


static struct udp_sock *us;


static void udp_recv(const struct sa *src, struct mbuf *mb, void *arg)
{
	size_t pos = mb->pos;
	bool v4mapped = IN6_IS_ADDR_V4MAPPED(&src->u.in6.sin6_addr);
	int err;

	re_printf("receive %zu bytes from %J\n", mbuf_get_left(mb), src);
	
	re_printf("sending to %J ..\n", src);
	err = udp_send(us, src, mb);
	if (err)
		re_printf("udp send error (%m)\n", err);

	if (v4mapped) {
		char buf[64];
		struct sa addr4;

		re_snprintf(buf, sizeof(buf), "%j", src);

		sa_set_str(&addr4, buf, sa_port(src));

		re_printf("sending to %J ..\n", &addr4);

		mb->pos = pos;
		err = udp_send(us, &addr4, mb);
		if (err)
			re_printf("udp send to %J failed (%m)\n", &addr4, err);
	}
}


int main()
{
	struct sa laddr;
	int err;

	sa_set_str(&laddr, "::", 2000);

	re_printf("listening on UDP %J\n", &laddr);

	err = udp_listen(&us, &laddr, udp_recv, NULL);
	if (err) {
		re_printf("udp listen error (%m)\n", err);
		return 2;
	}

	re_main(NULL);
}
```


it can be compiled with:

```
$ gcc udpecho.c -lre
```

send a UDP packet from another host:

```
$ echo hei | nc -u 10.0.1.2 2000
hei
```

the program will run:

```
$ ./a.out 
listening on UDP [::]:2000
udp: v6only workaround for unspec addr
udp: socket 3: IPV6_V6ONLY is 1

receive 4 bytes from [::ffff:10.0.1.11]:65217
sending to [::ffff:10.0.1.11]:65217 ..
sending to 10.0.1.11:65217 ..
udp send to 10.0.1.11:65217 failed (Bad file descriptor)
```

so the conclusion is that:

1. sending to an IPv4 mapped IPv6 address works
2. sending to a normal IPv4 address fails

the error (Bad file descriptor) is the same as in your ICE logs.

**Comment by alfredh** [comment]
hi @robdyck 

can you please test the above program on your machine, and report the status ?

to summarize the problem:

1. RTP socket is listening on UDP socket on any address, either 0.0.0.0 or ::

2. The ICE stack is re-using the same UDP socket to send/recv packets

3. in a dualstack setup, it will send both IPv4 and IPv6 packets on that socket.

The UDP socket actually has 2 file descriptors, so in theory it should be possible to listen
to both IPv4 and IPv6 at the same time. But it is a long time ago since I wrote that code,
and forgot how it is supposed to work ..

**Comment by robdyck** [comment]
```
[rdyck@blacky re]$ ./a.out
listening on UDP [::]:2000
receive 4 bytes from [::ffff:192.168.1.87]:40194
sending to [::ffff:192.168.1.87]:40194 ..
sending to 192.168.1.87:40194 ..
udp send to 192.168.1.87:40194 failed (Bad file descriptor)
```

**Comment by alfredh** [comment]
thanks for testing :)

this re patch seems to fix the problem:

```diff
diff --git a/src/udp/udp.c b/src/udp/udp.c
index f6312ab..b10fbe3 100644
--- a/src/udp/udp.c
+++ b/src/udp/udp.c
@@ -348,11 +348,7 @@ int udp_listen(struct udp_sock **usp, const struct sa *local,
                                on = 1;
                        }
 #endif
-                       /* Extra check for unspec addr - MAC OS X/Solaris */
-                       if (0==sa_set_sa(&sa, r->ai_addr) && sa_is_any(&sa)) {
-                               on = 1;
-                       }
-                       DEBUG_INFO("socket %d: IPV6_V6ONLY is %d\n", fd, on);
+                       DEBUG_NOTICE("socket %d: IPV6_V6ONLY is %d\n", fd, on);
                        if (on) {
                                us->fd6 = fd;
                                continue;
```

I have to understand more about why this extra check is there, it is a long time ago
since the code was written ...

would be great if you can give it a quick test

**Comment by robdyck** [comment]
The water has been muddied further. I haven't been able to reproduce exactly the previous result. The test was with baresip registering via IPV6 with ICE and DTLS. Call was to a WebRTC UA registered via IPV6. The call was placed over the LAN.  I wanted to reproduce the trouble prior to patching. The call actually succeeded although it took a couple of seconds for media to reach the browser. The resulting media was sent over IPV4. The file descriptor error had disappeared but  ::ffff:192.168.1.87 could not be found.

I have recently updated my Fedora. It could possibly account for the different result.

The patch didn't seem to make a difference. I could generate a new debug log if you want it.

**Comment by alfredh** [comment]
okay thanks, if you cannot reproduce the problem then I suggest that we close the issue.

**Comment by robdyck** [comment]
OK, I'll close it. If  I have time, I may look into the delayed call setup that I mentioned.
