### ISSUE TITLE
README.md links to outdated Homepage

### ISSUE THREAD

**Issue by jonassmedegaard** [baresip/baresip#1121]
README.md says "Project homepage: http://www.creytiv.com/baresip.html" and contains several other links to creytiv.com, but in #1088 is mentioned that creytiv.com is no more.
Seems links in README.md needs to be updated or removed.

**Comment by juha-h** [comment]
There is no "Project homepage" text in README.md.

**Comment by jonassmedegaard** [comment]
Indeed, this was fixed more than a month ago in 0c63a0f4b07 - not sure how I missed that.
