### ISSUE TITLE
Baresip on TLS does not attempt to verify server certificate

### ISSUE THREAD

**Issue by robdyck** [baresip/baresip#1122]
I use certificates from Let's Encrypt. I was working  a TLS problem that was not related to baresip when I became suspicious that the system couldn't find the root certificate for Let's Encrypt. After adding the root certificate to the system's CA bundle things ( let's encrypt related ) were working.

Then I wondered why baresip was not complaining. Baresip looks in /etc/ssl/certs/ca-bundle.crt which is actually a symlink to the bundle in /etc...  I hid the system bundle and sure enough things started failing but baresip on TLS kept working.

**Comment by alfredh** [comment]
verifying server certificate in SIP/TLS is not implemented.

I have added it to the roadmap:

https://github.com/baresip/baresip/wiki/Roadmap#security

it is not straight forward to implement this, I have tried in the past but did not get it working.


closing this issue, only bugs/defects here.
