### ISSUE TITLE
Audio stops after 2 seconds when calling via VPN

### ISSUE THREAD

**Issue by attley86** [baresip/baresip#1130]
Tested with latest baresip and did register & calling towards Asterisk PBX with one announcement number. Without VPN I can register and hear the continuous RTP stream from the PBX nicely, but when I turn on VPN (WireGuard) and restart baresip,  I can register but after 200OK message I only hear about 2 seconds of the announcement and after that no audio can be heard via the Baresip client. Audio cuts off for some reason.  Same goes with baresip+ when I tested the same scenario. Traced the RTP stream from the UAS machine and verified that Asterisk is pushing RTP packets to the VPN assigned IP which is owned by the phone that is running Baresip.

**Comment by attley86** [comment]
Using Oneplus 8 Android phone with Baresip 23.0.0

**Comment by juha-h** [comment]
attley86 writes:

> Using Oneplus 8 Android phone with Baresip 23.0.0

You should open this issue in baresip-studio project:

https://github.com/juha-h/baresip-studio
