### ISSUE TITLE
Baresip freeze at hangup

### ISSUE THREAD

**Issue by alberanid** [baresip/baresip#1135]
Hi, and thanks for the great project.

We have a problem that may be the same described in #885 

On an armv7l imx6ull single-core 528MHz system with just alsa (version 1.1.3, no pulseaudio), sometimes the **ua_hangup** call seems to freeze at `alsa: stopping playback thread `.
On this system a couple of alsa plugins are running to do echo cancellation; the CPU is loaded at about 30%.

Following your hint, we ve applied this patch to baresip 1.0.0:
```
Index: baresip-1.0.0/modules/alsa/alsa_play.c
===================================================================
--- baresip-1.0.0.orig/modules/alsa/alsa_play.c
+++ baresip-1.0.0/modules/alsa/alsa_play.c
@@ -39,6 +39,7 @@ static void auplay_destructor(void *arg)
 	if (st->run) {
 		debug("alsa: stopping playback thread (%s)\n", st->device);
 		st->run = false;
+		snd_pcm_drop(st->write);
 		(void)pthread_join(st->thread, NULL);
 	}
```

This seems to fix the problem (still testing, but a script with a quick call/hangup cycle is running fine since a day).
A thing that now happens is this:
```
alsa: write error: Input/output error
```

Do you think it's a problem? Despite this, everything seems to work fine.

Another question: do you think the same fix should be one in the `ausrc_destructor` function?

Thanks.

**Comment by alfredh** [comment]
hi,

I think that adding a call to `snd_pcm_drop ` should fix the problem, yes.

Since the stream is closed in the destructor, it should not have any other implications.
You can also ignore the input/output error.

Can you please make a PR with your fix ? I can also help to test it on my Debian box.

Alfred

**Comment by alberanid** [comment]
Done at #1145

Thanks for the feedback!

**Comment by alfredh** [comment]
thanks for the PR. works also fine on Debian 10.

**Comment by alberanid** [comment]
Thanks!

What about the idea to also add a similar line to `ausrc_destructor`?
