### ISSUE TITLE
Invalid password (0 - 63 characters followed by newline) and outbound requires valid UUID! 

### ISSUE THREAD

**Issue by samirmagnates** [baresip/baresip#1154]
When trying to register I am getting an invalid password error

 this is my Address: 

`let addr = "sip:\(username)@\(strSIPURL):18002;auth_pass=\(password);sipnat=outbound;outbound=\"sip:\(strSIPURL):18002;transport=udp\";answermode=manual;stunuser=311;audio_codecs=PCMU/8000/1,PCMA/8000/1;video_codecs=VP9,VP8,H264,H264;mwi=no;ptime=20;regint=3600;regq=0.5;pubint=0;"`

**My Log:** 
Local network address:  IPv4=:10.14.147.68  IPv6=:2405:204:898b:4f8c:43a:b442:843:8293
[31mdl: mod: ./stdio.so (dlopen(//stdio.so, 6): image not found)
[;m[31mmodule stdio.so: No such file or directory
[;maucodec: PCMU/8000/1
aucodec: PCMA/8000/1
aufilt: vumeter
auplay: coreaudio
ausrc: coreaudio
vidsrc: avcapture
[31mdl: mod: ./opengl.so (dlopen(//opengl.so, 6): image not found)
[;m[31mmodule opengl.so: No such file or directory
[;mmedianat: stun
medianat: turn
medianat: ice
[31muuid: fopen() /uuid (Operation not permitted)
[;m[31mdl: mod: ./uuid.so (dlopen(//uuid.so, 6): image not found)
[;m[31mmodule uuid.so: No such file or directory
[;maccount: creating accounts template /accounts
[31mdl: mod: ./account.so (dlopen(//account.so, 6): image not found)
[;m[31mmodule account.so: No such file or directory
[;mcontact: creating contacts template /contacts
[31mdl: mod: ./contact.so (dlopen(//contact.so, 6): image not found)
[;m[31mmodule contact.so: No such file or directory
[;mPopulated 2 audio codecs
Populated 1 audio filter
Populated 0 video codecs
Populated 0 video filters
[31maccount: video codec not found: VP9
[;m[31maccount: video codec not found: VP8
[;m[31maccount: video codec not found: H264
[;m[31maccount: video codec not found: H264

[;mPlease enter password for 318@xx.bx.xxx.int.xx.org: Invalid password (0 - 63 characters followed by newline)
`

Then I make the following changes to my address 

` let addr = "sip:\(username):\(password)@\(strSIPURL):18002;sipnat=outbound;outbound=\"sip:\(strSIPURL):18002;transport=udp\";answermode=manual;stunuser=311;audio_codecs=PCMU/8000/1,PCMA/8000/1;video_codecs=VP9,VP8,H264,H264;mwi=no;ptime=20;regint=3600;regq=0.5;pubint=0;"`

and Getting the following error:  **"outbound requires valid UUID! "**

Local network address:  IPv4=:10.14.147.68  IPv6=:2405:204:898b:4f8c:43a:b442:843:8293
[31mdl: mod: ./stdio.so (dlopen(//stdio.so, 6): image not found)
[;m[31mmodule stdio.so: No such file or directory
[;maucodec: PCMU/8000/1
aucodec: PCMA/8000/1
aufilt: vumeter
auplay: coreaudio
ausrc: coreaudio
vidsrc: avcapture
[31mdl: mod: ./opengl.so (dlopen(//opengl.so, 6): image not found)
[;m[31mmodule opengl.so: No such file or directory
[;mmedianat: stun
medianat: turn
medianat: ice
[31muuid: fopen() /uuid (Operation not permitted)
[;m[31mdl: mod: ./uuid.so (dlopen(//uuid.so, 6): image not found)
[;m[31mmodule uuid.so: No such file or directory
[;maccount: creating accounts template /accounts
[31mdl: mod: ./account.so (dlopen(//account.so, 6): image not found)
[;m[31mmodule account.so: No such file or directory
[;mcontact: creating contacts template /contacts
[31mdl: mod: ./contact.so (dlopen(//contact.so, 6): image not found)
[;m[31mmodule contact.so: No such file or directory
[;mPopulated 2 audio codecs
Populated 1 audio filter
Populated 0 video codecs
Populated 0 video filters
[31maccount: video codec not found: VP9
[;m[31maccount: video codec not found: VP8
[;m[31maccount: video codec not found: H264
[;m[31maccount: video codec not found: H264

**Error** 
[;m318@xxxrm.pbx.xxxxx.int.xxxx.org: Using sipnat: `outbound'
[31mua: outbound requires valid UUID!

OS I am using : MacOS 10.15.2
Xcode Version : 10.3
baresip Version : baresip v0.6.5

**Comment by alfredh** [comment]
First of all, please upgrade to latest version of baresip from git ...

Are you using the command line client or your own application?

If you are trying to load modules, and they are not loaded you need to investigate
each module why it is not loaded. if you dont need that module, it should not be loaded.
your log is full of module loading errors, please address that first and provide a clean log.

The account module is loading SIP accounts from `~/.baresip/accounts`
are you using this file ?

If you need help with integrating your application, please consider to use the mailing list instead:

https://github.com/baresip/baresip/wiki/Guidelines-for-reporting-Issues

this issues tracker is mainly for defects/bugs, I am not sure this is a bug in baresip.

Alfred

**Comment by samirmagnates** [comment]
@alberanid Thanks for your feedback.. now I can register and the module loaded successfully. But right now I am using version 0.6.5. is it ok? or I need to update?

**Comment by alfredh** [comment]
please use the latest version from git

also please use the correct github username for me :)
