### ISSUE TITLE
stunuser/stunpass should not default to authuser/authpass

### ISSUE THREAD

**Issue by juha-h** [baresip/baresip#1163]

**Comment by juha-h** [comment]
A user of my Android app reported security issue related to stunuser/stunpass.  He configured stunserver without stunuser/stunpass and then restarted the app.    After restart stunuser/stunpass were filled with authuser/authpass, resulting to possible leak of those to stunserver operator.

**Comment by alfredh** [comment]
yeah, this was a novel hack from the old days :)

fixed in 02ca5ed42dcd6389539688567792548a005bec44 (thanks Juha)
