### ISSUE TITLE
Compiling errors on v1.0.0 tag and current master

### ISSUE THREAD

**Issue by daleiliu** [baresip/baresip#1166]
I'm building the latest baresip on Debian 10 x86_64, but there are errors when compile it:
> 4e0899a35ce7 Video dir rename (#1158)
```
include/baresip.h:333:7: warning: ISO C forbids forward references to ‘enum’ types [-Wpedantic]
  enum jbuf_type jbtype;  /**< Jitter buffer type             */
       ^~~~~~~~~
include/baresip.h:333:17: error: field ‘jbtype’ has incomplete type
  enum jbuf_type jbtype;  /**< Jitter buffer type             */

```
I find the "enum jbuf_type" is undefined and add such lines in baresip.h to fix it:
```
/** Jitter buffer type */
enum jbuf_type {
	JBUF_OFF = 0,
	JBUF_FIXED,
	JBUF_ADAPTIVE,
};

```
But I think the original author of this patch should have some better idea to fix it:

> c6f384224206  Adaptive jbuf (#1112)

After that, there are many errors from modules/{fakevideo,menu,vidloop,dtls_srtp,httpreq}, which seem to often refer to non-existing libre functions.

So I start trying the v1.0.0 tag but there are still errors:
```
/usr/bin/ld: build-x86_64/src/call.o: in function `update_video':
/home/david/oss/baresip/src/call.c:358: undefined reference to `sdp_media_disabled'
/usr/bin/ld: build-x86_64/src/reg.o: in function `reg_register':
/home/david/oss/baresip/src/reg.c:213: undefined reference to `sipreg_set_rwait'
/usr/bin/ld: build-x86_64/src/reg.o: in function `reg_status':
/home/david/oss/baresip/src/reg.c:307: undefined reference to `sipreg_proxy_expires'
```

**Comment by daleiliu** [comment]
Just realize baresip has its own baresip/re repo instead of creytiv/re.

**Comment by chaseadam** [comment]
ran into multiple compile errors when compiling HEAD as well until I realized I needed to clone and **build baresip/re and baresip/rem HEAD as well** (emphasis added for future people searching for this error).

```
modules/httpreq/httpreq.c:410:19: error: storage size of ‘conf’ isn’t known
  410 |  struct http_conf conf;
      |                   ^~~~
```

**Comment by afcady** [comment]
The proper fix here is to put the re and rem as git submodules of baresip, and have baresip build them and use the headers in the build directory and not /usr/include.  That way the user doesn't have to try to figure out which versions of the library are needed with which versions of baresip.

**Comment by afcady** [comment]
The exact sequence to build baresip is this:

```
apt build-dep baresip -t buster  # on my system

git clone https://github.com/baresip/baresip
cd baresip
git clone https://github.com/baresip/re
git clone https://github.com/baresip/rem
make -C re
make -C rem
make LIBREM_PATH=rem LIBRE_PATH=re LIBRE_SO=re LIBREM_SO=rem
```

It should just be a git clone and make.

**Comment by afcady** [comment]
To be clear it's not just about user convenience.  The actual dependency information isn't recorded otherwise.  It makes things like git bissect impossible.

**Comment by juha-h** [comment]
I build and install baresip on Debian with this kind of script:

rm *.deb
cd re
git pull
dpkg-buildpackage -rfakeroot -b -us -uc
cd ..
sudo dpkg -i libre_*deb libre-dev*deb
cd rem
git pull
dpkg-buildpackage -rfakeroot -b -us -uc
cd ..
sudo dpkg -i librem_*deb librem-dev*deb
cd baresip
git pull
sudo dpkg -i librem_*deb librem-dev*deb
cd ..
sudo dpkg -i baresip_*deb

Similar scripts should be easy to write for other OSes.

**Comment by afcady** [comment]
The problem with that, is if you want to keep the working baresip installed on your system, even on the system where you are developing baresip.

Also, it doesn't do anything about what I'm saying about the repositories not containing the version dependency information.  You are running "git pull" but what if you wanted to build `baresip` commit 97dcf9538541ec3bc82f30132dbc0da17b5417c9 ? then you can't just write a script to "cd rem; git pull" because it will get the latest version, not the version that goes with 97dcf9538541ec3bc82f30132dbc0da17b5417c9.
