### ISSUE TITLE
baresip release artifacts

### ISSUE THREAD

**Issue by chenrui333** [baresip/baresip#1168]
👋  It looks like for the most recent releases (0.6.6 and 1.0.0), there are no release artifacts (`baresip-#{version}.tar.gz`) like what you folks did before. 

Is there any reason for that? If that is not the case, It would be helpful to include the release artifacts (since you have the custom version of `libre`)for the downstream builds. Thanks!

**Comment by alfredh** [comment]
please use the mailing-list to discussions:

https://github.com/baresip/baresip/wiki/Guidelines-for-reporting-Issues
