### ISSUE TITLE
Can sip clients connect directly without server?

### ISSUE THREAD

**Issue by 1341290135** [baresip/baresip#1172]
Thanks a lot

**Comment by alfredh** [comment]
yes, set the registration interval to zero:

```
<sip:alice@domain.org>;regint=0;auth_pass=XXXX
```

and then use the dial command:

```
/dial bob@1.2.3.4
```

please use the mailing list to ask questions:

https://github.com/baresip/baresip/wiki/Guidelines-for-reporting-Issues
