### ISSUE TITLE
'JBUF_ADAPTIVE': undeclared identifier

### ISSUE THREAD

**Issue by fdl333** [baresip/baresip#1184]
Trying to compile with VS 2015

Any help will be greatly appreciated

**Comment by alfredh** [comment]
please note that your report contains almost no information, if you want help please
include useful information like versions of re/rem/baresip, a full build log etc.

you should probably use this version:

https://github.com/baresip/re

**Comment by cspiel1** [comment]
Right! Same in my company. Often creativ/re is mixed with baresip/baresip which leads to "undeclared identifier" warnings.
Always use the repositories:
- baresip/re
- baresip/rem
- baresip/baresip

**Comment by fdl333** [comment]
Thank you very much!
Will test immediately

Francesco Facco de Lagarda

**Comment by fdl333** [comment]
I have downloaded correct repositories, but now it complains that it cant find "timer.c"
