### ISSUE TITLE
Windows Compile .. timer.c missing

### ISSUE THREAD

**Issue by fdl333** [baresip/baresip#1186]
Trying to compile with VS 2015

I have downloaded correct repositories at last, but now it complains that it cant find "timer.c" ...

baresip/re
baresip/rem
baresip/baresip

**Comment by sreimers** [comment]
Can you provide the complete compiler error with context/trace?

**Comment by fdl333** [comment]
Thank you, yes:

Windows 10 (64 bit)
Visual Studio 2015

It is already clear from "solution explorer" that the timer.c is required but missing..
![image](https://user-images.githubusercontent.com/19802962/104478857-11c46780-55c3-11eb-841c-2abfe0de4760.png)



Severity	Code	Description	Project	File	Line	Suppression State
Warning	C4267	'=': conversion from 'size_t' to 'uint16_t', possible loss of data	re-win32	c:\users\francesco\documents\visual studio 2015\projects\bs\re\src\turn\turnc.c	488	
Warning	C4267	'function': conversion from 'size_t' to 'uint8_t', possible loss of data	re-win32	c:\users\francesco\documents\visual studio 2015\projects\bs\re\src\bfcp\attr.c	131	
Warning	C4267	'function': conversion from 'size_t' to 'u_short', possible loss of data	re-win32	c:\users\francesco\documents\visual studio 2015\projects\bs\re\src\dns\client.c	713	
Warning	C4101	'laddr6': unreferenced local variable	re-win32	c:\users\francesco\documents\visual studio 2015\projects\bs\re\src\dns\client.c	859	
Warning	C4267	'function': conversion from 'size_t' to 'u_short', possible loss of data	re-win32	c:\users\francesco\documents\visual studio 2015\projects\bs\re\src\dns\dname.c	76	
Warning	C4267	'=': conversion from 'size_t' to 'uint8_t', possible loss of data	re-win32	c:\users\francesco\documents\visual studio 2015\projects\bs\re\src\dns\dname.c	121	
Warning	C4267	'=': conversion from 'size_t' to 'uint8_t', possible loss of data	re-win32	c:\users\francesco\documents\visual studio 2015\projects\bs\re\src\dns\dname.c	129	
Warning	C4267	'function': conversion from 'size_t' to 'u_short', possible loss of data	re-win32	c:\users\francesco\documents\visual studio 2015\projects\bs\re\src\dns\rr.c	194	
Warning	C4267	'initializing': conversion from 'size_t' to 'uint8_t', possible loss of data	re-win32	c:\users\francesco\documents\visual studio 2015\projects\bs\re\src\dns\rr.c	151	
Warning	C4244	'=': conversion from 'long double' to 'int64_t', possible loss of data	re-win32	c:\users\francesco\documents\visual studio 2015\projects\bs\re\src\json\decode.c	69	
Warning	C4244	'=': conversion from 'long double' to 'int64_t', possible loss of data	re-win32	c:\users\francesco\documents\visual studio 2015\projects\bs\re\src\json\decode.c	157	
Warning	C4996	'gethostbyname': Use getaddrinfo() or GetAddrInfoW() instead or define _WINSOCK_DEPRECATED_NO_WARNINGS to disable deprecated API warnings	re-win32	c:\users\francesco\documents\visual studio 2015\projects\bs\re\src\net\net.c	44	
Warning	C4267	'function': conversion from 'size_t' to 'uint8_t', possible loss of data	re-win32	c:\users\francesco\documents\visual studio 2015\projects\bs\re\src\rtp\pkt.c	184	
Warning	C4267	'=': conversion from 'size_t' to 'uint16_t', possible loss of data	re-win32	c:\users\francesco\documents\visual studio 2015\projects\bs\re\src\rtp\pkt.c	237	
Warning	C4267	'function': conversion from 'size_t' to 'u_short', possible loss of data	re-win32	c:\users\francesco\documents\visual studio 2015\projects\bs\re\src\stun\attr.c	168	
Warning	C4267	'=': conversion from 'size_t' to 'uint16_t', possible loss of data	re-win32	c:\users\francesco\documents\visual studio 2015\projects\bs\re\src\stun\msg.c	307	
Warning	C4267	'=': conversion from 'size_t' to 'uint16_t', possible loss of data	re-win32	c:\users\francesco\documents\visual studio 2015\projects\bs\re\src\stun\msg.c	328	
Warning	C4267	'=': conversion from 'size_t' to 'uint16_t', possible loss of data	re-win32	c:\users\francesco\documents\visual studio 2015\projects\bs\re\src\turn\turnc.c	281	
Warning	C4267	'function': conversion from 'size_t' to 'u_short', possible loss of data	re-win32	c:\users\francesco\documents\visual studio 2015\projects\bs\re\src\websock\websock.c	583	
Warning	C4267	'function': conversion from 'size_t' to 'uint8_t', possible loss of data	re-win32	c:\users\francesco\documents\visual studio 2015\projects\bs\re\src\websock\websock.c	586	
Warning	LNK4006	__NULL_IMPORT_DESCRIPTOR already defined in ws2_32.lib(WS2_32.dll); second definition ignored	re-win32	C:\Users\Francesco\Documents\Visual Studio 2015\Projects\bs\re\mk\win32\Iphlpapi.lib(IPHLPAPI.DLL)	1	
Warning	LNK4221	This object file does not define any previously undefined public symbols, so it will not be used by any link operation that consumes this library	re-win32	C:\Users\Francesco\Documents\Visual Studio 2015\Projects\bs\re\mk\win32\Iphlpapi.lib(IPHLPAPI.DLL)	1	
Warning	C4267	'=': conversion from 'size_t' to 'WORD', possible loss of data	baresip-win32	c:\users\francesco\documents\visual studio 2015\projects\bs\baresip\modules\winwave\play.c	171	
Warning	C4267	'=': conversion from 'size_t' to 'WORD', possible loss of data	baresip-win32	c:\users\francesco\documents\visual studio 2015\projects\bs\baresip\modules\winwave\src.c	165	
Warning	C4267	'function': conversion from 'size_t' to 'uint16_t', possible loss of data	baresip-win32	c:\users\francesco\documents\visual studio 2015\projects\bs\baresip\src\audio.c	1636	
Warning	C4267	'function': conversion from 'size_t' to 'uint16_t', possible loss of data	baresip-win32	c:\users\francesco\documents\visual studio 2015\projects\bs\baresip\src\audio.c	1637	
Error	C1083	Cannot open source file: '..\..\src\timer.c': No such file or directory	baresip-win32	C:\Users\Francesco\Documents\Visual Studio 2015\Projects\bs\baresip\mk\win32\c1	1

**Comment by fdl333** [comment]
also forsee problems with Warning C4996 - gethostbyname...

**Comment by alfredh** [comment]
can you please try again with git HEAD ?

(commit e831d684d50fb9b7b28750a8dbc62624f21b2e66)

**Comment by fdl333** [comment]
Thank you very much for your kind suggestions...

That fixed, but now I'm getting:

Severity	Code	Description	Project	File	Line	Suppression State
Error	LNK1120	6 unresolved externals	baresip-win32	C:\Users\Francesco\Documents\Visual Studio 2015\Projects\bs\baresip\Win32\Debug\bin\baresip-win32.exe	1	
Error	LNK2019	unresolved external symbol _dynamic_menu_register referenced in function _menu_set_incall	baresip-win32	C:\Users\Francesco\Documents\Visual Studio 2015\Projects\bs\baresip\mk\win32\menu.obj	1	
Error	LNK2019	unresolved external symbol _dynamic_menu_unregister referenced in function _module_close	baresip-win32	C:\Users\Francesco\Documents\Visual Studio 2015\Projects\bs\baresip\mk\win32\menu.obj	1	
Error	LNK2019	unresolved external symbol _static_menu_register referenced in function _module_init	baresip-win32	C:\Users\Francesco\Documents\Visual Studio 2015\Projects\bs\baresip\mk\win32\menu.obj	1	
Error	LNK2019	unresolved external symbol _static_menu_unregister referenced in function _module_close	baresip-win32	C:\Users\Francesco\Documents\Visual Studio 2015\Projects\bs\baresip\mk\win32\menu.obj	1	
Error	LNK2019	unresolved external symbol _dial_menu_register referenced in function _module_init	baresip-win32	C:\Users\Francesco\Documents\Visual Studio 2015\Projects\bs\baresip\mk\win32\menu.obj	1	
Error	LNK2019	unresolved external symbol _dial_menu_unregister referenced in function _module_close	baresip-win32	C:\Users\Francesco\Documents\Visual Studio 2015\Projects\bs\baresip\mk\win32\menu.obj	1

**Comment by alfredh** [comment]
can you try to update the windows project file and add these files after menu.c:

```
modules/menu/dynamic_menu.c
modules/menu/static_menu.c
```

**Comment by fdl333** [comment]
Thanks!
That seems to have done it!
Will you be updating the project also including the FD_SETSIZE problem for windows?

**Comment by fdl333** [comment]
OK, so I did that an it finally compiled.
Ran in debug and it gave me a whole lot of errors because it cant the relevant PDB files for all the 
"C:\windows\SysWOW64 .. " 
example : 'C:\Windows\SysWOW64\ntdll.dll'. but there's many more.


Registration fails with this error:
/uanew <sip:1009@192.168.0.234:5060>;auth=1009
Creating UA for <sip:1009@192.168.0.234:5060>;auth=1009 ...
[31mua: SIP register failed: No such file or directory
[;m
--- User Agents (1) ---
> sip:1009@192.168.0.234:5060                [33mzzz[;m  Expires 0s


So I complied again, in "release" mode and now it tells me:

Severity	Code	Description	Project	File	Line	Suppression State
Error	C1083	Cannot open include file: 'getopt.h': No such file or directory	baresip-win32	C:\Users\Francesco\Documents\Visual Studio 2015\Projects\bs\baresip\src\main.c	14

**Comment by alfredh** [comment]
can you please take your local changes to the Windows project file, and make a PR for it,
so that it can be properly fixed in master?

please also post the full log so that we can see the full context.
a short log with only the error does not really help ...

for getopt you either need to find a copy of getopt.h, or define HAVE_GETOPT in your project file.

**Comment by fdl333** [comment]
Will willingly post everything as soon as its working correctly.

What I really DONT undestand is why, if I compile in debug mode all is fine, and when I compile in release mode it complains of the getopt.h missing? 

I tried specifying HAVE_GETOPT but then I get a host of other errors!

**Comment by fdl333** [comment]
Goodevening Alfred.
I've finally got it all almost working.
I notice you can't register on-the-fly, it needs the baresip configuration folder in "C:\Users\Francesco\AppData\Roaming\.baresip"   (Francesco is my username ;)

I can control it via http (enabling the module in the config file), but if I try to enable the cons.dll module, on startup it complains it cant find the cons.dll 

baresip v1.0.0 Copyright (C) 2010 - 2020 Alfred E. Heggestad et al.
Binding to interface or IP address '192.168.0.103'
Local network address:  IPv4={C1856B28-9AB7-43DA-B379-879FCB249B32}|192.168.0.103
open: ./cons.dll LoadLibraryA() failed
[31mmodule cons.dll: No such file or directory
[;mhttpd: listening on 0.0.0.0:8000

This is strange 'cause the module correctly compiles, I see it in my output from the build.

My dream (and a very useful feature for anyone that wants to use it in windows) would be to make it run in the background (invisible or as a task-bar item), and control it from a webpage via websockets.

the httpd module is not very useful because it cant give realtime events and would need to be continuously reloaded.

I am very willing to contribute my work .. could you please explain what you mean by "... and make a PR for it,". 

Thank you once again for your fantastic work!

**Comment by alfredh** [comment]
if you made changes to the Windows project file, it would be nice to merge it into master.

Please create a Pull Request (PR):

https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request?ref=hackernoon.com

The baresip pull requests are here:

https://github.com/baresip/baresip/pulls

**Comment by alfredh** [comment]
I will close this now, waiting for your PR ...
