### ISSUE TITLE
Segfault when deleting all accounts

### ISSUE THREAD

**Issue by ursfassler** [baresip/baresip#1189]
We had a segfault when:
* configured accounts in the file
* delete each account with `uadel`
* adding a new account with `uanew`
* start a SIP call

I expect the problem to be here:
https://github.com/baresip/baresip/blob/c3831870efa33c032d02f191e3c14665825bfa30/modules/menu/static_menu.c#L632

When there is only 1 account left, `cmd_ua_next` selects the next account, which is the one we are going to delete. This account is then later on in this function deleted. The current account points then to a freed struct instead of NULL.

**Comment by alfredh** [comment]
sorry about that

could you please try to add this code and see if it helps:

```c
	bool valid = list_contains(uag_list(), menu->le_cur);
	if (!valid)
		menu->le_cur = list_head(uag_list());
```

**Comment by ursfassler** [comment]
No problem, happy to contribute.

I am not sure where you meant to add the code and if it really solves the issue. But I had another look and found a way to fix it: https://github.com/baresip/baresip/pull/1192

**Comment by alfredh** [comment]
hi, do you still have this issue, or was it fixed ?

**Comment by ursfassler** [comment]
Fixed with https://github.com/baresip/baresip/pull/1192
