### ISSUE TITLE
Call from "Contacts" app

### ISSUE THREAD

**Issue by drzraf** [baresip/baresip#1190]
I just installed baresip and registered an account.
I previously used CSIPSimple and when browsing native "contacts" I could press "Call" and choose which app to use ("Native" or "CSipSimple"), but I can't find this for baresip.

Is it possible to call using baresip straight from the contact list?

**Comment by cspiel1** [comment]
Since you wrote something about CSIPSimple I guess this belongs to https://github.com/juha-h/baresip-studio

**Comment by juha-h** [comment]
Raphaël Droz writes:

> I previously used CSIPSimple and when browsing native "contacts" I
> could press "Call" and choose which app to use ("Native" or
> "CSipSimple"), but I can't find this for baresip.

> Is it possible to call using baresip straight from the contact list?

If your issue regards Android baresip app from baresip-studio project,
please open the issue there.  But I can answer here too to save your
effort:

For security reasons baresip app does not have interaction with Android
contacts.  I don't want baresip user's contacts or call information to
leak to Google or other apps.  Baresip Android app has its own contacts
and you can place calls from there (or choose to use some other Android
app).

**Comment by drzraf** [comment]
I'm sorry I created that issue at the wrong place.

Regarding the "contact" integration, I think one-way integration (from [any] "Contact" app with baresip) is a must-have.
Since I can't provide a PR I won't insist and just hope you'd reconsider and/or find a privacy-friendly way to do it.

But please note that I don't even use the standard "Contact" app so privacy wouldn't have been a problem for me, and it's not about _leaking_ baresip contacts into "Contact" but _leaking_ (= integrating) "Contacts" with baresip and the lack of such a feature is my only [blocking] usability problem.

But thank you very much for that great library (and the quick answer !)

**Comment by juha-h** [comment]
Raphaël Droz writes:

> Regarding the "contact" integration, I think one-way integration (from
> [any] "Contact" app with baresip) is a must-have.

> Since I can't provide a PR I won't insist and just hope you'd
> reconsider and/or find a privacy-friendly way to do it.

Open a feature request issue on page

https://github.com/juha-h/baresip-studio/issues

and we can discuss about this.
