### ISSUE TITLE
cons.dll LoadLibraryA() failed

### ISSUE THREAD

**Issue by fdl333** [baresip/baresip#1197]
I have finally managed to compile in windows under vs 2015..

unfortunately, despiate apparently compiling correctly, the cons module seems unavailable:

I have checked all compile logs and see no errors, infact cons.c compiled fine. Maybe something wrong with the final linking?

baresip v1.0.0 Copyright (C) 2010 - 2020 Alfred E. Heggestad et al.
Binding to interface or IP address '192.168.0.103'
Local network address: IPv4={C1856B28-9AB7-43DA-B379-879FCB249B32}|192.168.0.103
open: ./cons.dll LoadLibraryA() failed
�[31mmodule cons.dll: No such file or directory
�[;mhttpd: listening on 0.0.0.0:8000

This is strange 'cause the module correctly compiles, I see it in my output from the build.

**Comment by alfredh** [comment]
please check this file:

mk/win32/static.c:

```c
const struct mod_export *mod_table[] = {
	&exports_account,
	&exports_auloop,
	&exports_contact,
	&exports_debug_cmd,
	&exports_dshow,
	&exports_g711,
	&exports_httpd,
	&exports_ice,
	&exports_menu,
	&exports_stun,
	&exports_turn,
	&exports_uuid,
	&exports_vidloop,
	&exports_vumeter,
	&exports_wincons,
	&exports_winwave,
	NULL
};
```

you can try to add cons to this table.

When building with make and static modules, this lookup table is generated.
but for Windows the table is manually updated.

**Comment by fdl333** [comment]
Thank you, that worked …
I’m slowly getting there ..

 

I just wish I could:
- run in background (in windows)
- control via websockets.

**Comment by alfredh** [comment]
regarding JSON over Websockets module, there are also other people interested in this.
please suggest the idea on the mailing-list and/or add it to the Roadmap:

https://github.com/baresip/baresip/wiki/Roadmap
