### ISSUE TITLE
audiounit module uses super old iOS API

### ISSUE THREAD

**Issue by Koshub** [baresip/baresip#1210]
The `audiounit` module (which gives the iOS OS support for using Baresip) is utilising deprecated iOS API
For example [this call](https://github.com/baresip/baresip/blob/b7926240cb8f2f7cc329feded120a52a8a091f91/modules/audiounit/audiounit.c#L163):
```c
	ret = AudioSessionInitialize(NULL, NULL, interruptionListener, 0);
```
uses the function `AudioSessionInitialize`, which was [deprecated](https://developer.apple.com/documentation/audiotoolbox/1618360-audiosessioninitialize) a long time ago (`Deprecated in iOS 7.0.`).
I think one should use `AVAudioSession` API as described [here](https://developer.apple.com/documentation/audiotoolbox/audio_session_support)

**Comment by alfredh** [comment]
I have added this item to the roadmap:

https://github.com/baresip/baresip/wiki/Roadmap

Is this some work that you can help out with?
I am not using the iOS port at the moment. A Pull Request is welcome.

Please note that the issues tracker is mainly for critical defects:

https://github.com/baresip/baresip/wiki/Guidelines-for-reporting-Issues

**Comment by Koshub** [comment]
@alfredh Thanks for adding this to the roadmap. According to PR, I would like to help. If I implement this earlier I will definitely make a PR. Thanks again.
