### ISSUE TITLE
Please update to latest webrtc AEC

### ISSUE THREAD

**Issue by viric** [baresip/baresip#1211]
It'd be of great help if the webrtc_aec module were adapted to the latest AEC code.

Instead of the whole webrtc code, you could use the separated webrtc-audio-processing package, that has the audio processing separated from the big package. That's what pulseaudio takes.
https://freedesktop.org/software/pulseaudio/webrtc-audio-processing/     (version 1.0 at time of writing)

**Comment by juha-h** [comment]
What are the API changes in the latest AEC code that break current webrtc_aec module?

**Comment by viric** [comment]
OH! It's completely different in class names, parameters and structures. I think this describes the new API:
https://gitlab.freedesktop.org/pulseaudio/webrtc-audio-processing/-/blob/master/webrtc/modules/audio_processing/include/audio_processing.h#L117-196

**Comment by viric** [comment]
This commit removed the "Legacy AEC" used in baresip: https://webrtc.googlesource.com/src/+/62ea0aaea04942f79a1ac98eca736b3ec0bcc860

**Comment by alfredh** [comment]
I have added the item to the roadmap:

https://github.com/baresip/baresip/wiki/Roadmap

are you able to help with coding and testing? A pull request is welcome.

I will close the issue now, as it is not a critical bug.

**Comment by viric** [comment]
Sure I'll try to test. Notice that one thing is using the echo cancellation and the other is the full audioprocessing, which is what we should head to (noise suppression, voice enhancing, echo cancellation, etc.).

These days I'm very confused with the whole new audio thing on linux, with pipewire, bluetooth HSP and its codecs and many complications everywhere.

**Comment by juha-h** [comment]
I looked at the new API and there was nothing common with the old one. If you manage to upgrade webrtc_aec module to the new API, I would be glad give it a try in my baresip Android  app.

**Comment by viric** [comment]
Baresip had code that used the "echo cancellation" API alone instead of the whole audio-processing (noise reduction, etc.). The webrtc-audio-processing packages had not included the echo_cancellation header file. I don't know whether intentionally or not.

I'll write here if I take the endeavor. I'm not sure how worth it is; pulseaudio has the webrtc audio processing included, and I might end up using even pipewire if I learn how, and maybe at some point it will also include such solution, or maybe already does.
