### ISSUE TITLE
Use a v4l2 usb camera with mjpeg pixformat

### ISSUE THREAD

**Issue by viric** [baresip/baresip#1212]
I can't find how would one use a v4l2 vidsrc with mjpeg pixformat. Is it supported?

Many usb webcams can send not only YUYV pixfmt but also MJPG in v4l2, and that's effectively what allows 30fps at more than 640x480.

Let's say I want 1280x720x30fps... that can only be achieved with mjpeg v4l2 frames.

**Comment by viric** [comment]
This issue https://github.com/baresip/baresip/issues/639 about IP MJPEG cameras faces the same challenge as for v4l2 MJPEG cameras.

I think that the avformat code can be extended to allow mjpeg acquisition from v4l2 but we lack the pixfmt conversion. mjpeg decoding provides yuvj422p.

I'll try if I can extend avformat with swscale to perform the color conversion although I'm new in this field.

**Comment by alfredh** [comment]
MJPEG is not a pixel format, but a codec:

```
$ ffmpeg -hide_banner -decoders | grep -i mjpeg
 V....D mjpeg                MJPEG (Motion JPEG)
 V....D mjpegb               Apple MJPEG-B
 A....D adpcm_ima_smjpeg     ADPCM IMA Loki SDL MJPEG
```

to use a v4l2 camera you have two options:

1. v4l2.so
2. avformat.so

v4l2.so can also use libv4l2, it is possible that libv4l2 may be able to decode mjpeg to raw frames.
please try it and see if it works.

for avformat.so you can use this config:

```
video_source           avformat,v4l2,/dev/video0
```

it will also decode any input frames, and send a raw pixel format to the core (i.e. yuv720p)

please try it and see if it works.

if you have tried something that did not work, it would be very useful if you can
paste the exact config and matching log-file here.

**Comment by viric** [comment]
Check how I address this in the PR https://github.com/baresip/baresip/pull/1216

**Comment by alfredh** [comment]
tracked in PR
