### ISSUE TITLE
Preserve aspect ratio in video display

### ISSUE THREAD

**Issue by viric** [baresip/baresip#1213]
I have tried the sdl/sdl2 video plugins and, when setting fullscreen, they expand to the full screen regardless of the image aspect 
ratio.

It'd be great that aspect ratio were preserved, for example with black bands where required, vertical or horitzontal.

In the raspberry pi, btw, with sdl2 backend I could only get fullscreen, regardless of the fullscreen setting. I couldn't get the omx module to work (default baresip build in raspbian) as the OMX libs complain about "No resource to be handled"

**Comment by alfredh** [comment]
do you have a screen shot to share ?

thanks for the input, also added to the roadmap:

https://github.com/baresip/baresip/wiki/Roadmap

**Comment by viric** [comment]
Thank you.

No, I don't have a screenshot, but I was using a 4:3 webcam in one end, and a 16:9 screen in the other. The 4:3 image was expanded horizontally to fit 16:9 with omx output.

In the sdl video output I thought also of adding a resize-to-aspect-ratio key, like 'a'. Otherwise the free resize will leave the window with wrong aspect ratio.

**Comment by alfredh** [comment]
closing this for now, it is tracked on the roadmap.

if you report similar issues, please provide config+log and screenshot, it helps to understand the problem.
