### ISSUE TITLE
Module g729 is not part of baresip and the warning can be ignored.  I also checked and there has not been changes in baresip source that would have caused the warnings.  Looks like Android  build environment has become more strict.

### ISSUE THREAD

**Issue by Othello1111** [baresip/baresip#1229]
Module g729 is not part of baresip and the warning can be ignored.  I also checked and there has not been changes in baresip source that would have caused the warnings.  Looks like Android  build environment has become more strict.

Is it OK to suppress the warnings with `-Wno-shorten-64-to-32`?

_Originally posted by @juha-h in https://github.com/baresip/baresip/issues/1226#issuecomment-781593479_

**Comment by sreimers** [comment]
Whats the purpose of duplicating the linked issue here?

**Comment by juha-h** [comment]
I don't know.  Perhaps closing helps.
