### ISSUE TITLE
misleading ua event message

### ISSUE THREAD

**Issue by juha-h** [baresip/baresip#1240]
When registering fails due to server certificate verification error, baresip application gets `REGISTER_FAIL` ua event with `Network is unreachable` prm value:
```
02-28 09:43:17.988  8272  8405 D Baresip Lib: tls: verify_handler: err          = 20
02-28 09:43:17.988  8272  8405 D Baresip Lib: tls: verify_handler: error_string = unable to get local issuer certificate
02-28 09:43:17.988  8272  8405 D Baresip Lib: tls: verify_handler: depth        = 0
02-28 09:43:17.989  8272  8405 D Baresip Lib: tls: connect: error (r=-1, ssl_err=1)
02-28 09:43:17.993  8272  8404 D Baresip Lib: ua event (REGISTER_FAIL) Network is unreachable
```
This is misleading to the user, since there is nothing wrong with network reachability and baresip user gets confused.

The tls log messages come from re/src/tls/openssl/tls.c `verify_handler()`, but the handler does not do anything else than print the log messages.

Any suggestions on how to make the verification error available to baresip?

**Comment by cspiel1** [comment]
The information you want is in the X509_STORE_CTX  or in the err code in the verify_handler().

This are the layers involved.
baresip reg -> re sipreg -> re request -> re ctransp -> re transp -> re tls

So seems to be difficult to pass the current error up to baresip.

Maybe it is enough to do it like it is done in cmd_tls_issuer() in static_menu.c. The uag_tls() returns the one and only tls object.

**Comment by juha-h** [comment]
Christian Spielberger writes:

> The information you want is in the X509_STORE_CTX  or in the err code
> in the verify_handler(). 
> 
> This are the layers involved.
> baresip reg -> re sipreg -> re request -> re ctransp -> re transp -> re tls
> 
> So seems to be difficult to pass the current error up to baresip.

That was my conclusion also, when I looked at the re code.  The error
information is buried very deep in the API hierarchy.

> Maybe it is enough to do it like it is done in cmd_tls_issuer() in
> static_menu.c. The uag_tls() returns the one and only tls object.

I'll take a look.

**Comment by juha-h** [comment]
It might be possible if cmd_tls_issuer() works on remote and not local certificate and if would be possible to check in register_handler that tls transport is being used.

**Comment by juha-h** [comment]
How should `/tlsissuer` command be used?  I registered UA over TLS and config has `sip_verify_server yes`.  Then I gave the command and got error:
```
test@test.tutpro.com: (prio 0) {1/TLS/v4} 200 OK (OpenSIPg SIP Proxy (5.5.0-0b26 (x86_64/linux))) [1 binding]
All 1 useragent registered successfully! (174 ms)
/tlsissuer
unable to get certificate issuer (Invalid argument)
```

**Comment by cspiel1** [comment]
I'm not 100% sure, but as I understood: For this feature you don't need this setting. Instead you need a client certificate (setting sip_certificate). @cHuberCoffee Please could you correct me if I am wrong?!

But anyway, also with this setting I can reproduce the error.

During initialization this is called at tls.c:211:
```
r = SSL_CTX_use_certificate_chain_file(tls->ctx, keyfile);
```
During query this at tls.c:1237:
```
SSL_CTX_get0_chain_certs(tls->ctx, &certstack)
```
Which gives no result. Will dig into openssl. cHuberCoffee will be back on Monday.

**Comment by cspiel1** [comment]
We will solve the /tlsissuer question on Monday.

But you may proceed with the error message from openssl anyway. I think that the "last error" can be retrieved from the openssl ctx like it is done in the verify_handler().

**Comment by alfredh** [comment]
in other parts of the code, we have used `EAUTH` to indicate Authentication Error.

example:

```c
int tls_peer_verify(const struct tls_conn *tc)
{
        if (!tc)
                return EINVAL;

        if (SSL_get_verify_result(tc->ssl) != X509_V_OK)
                return EAUTH;

        return 0;
}
```

**Comment by cspiel1** [comment]
EAUTH is ok for me. Libre should do some abstraction of openssl. @juha: Would it be enough if libre passes EAUTH to the register_handler(int err, ...) in this case?

**Comment by juha-h** [comment]
Yes, if it is possible to differentiate certificate authentication failure from SIP request authentication failure.

**Comment by juha-h** [comment]
I checked and when SIP request authorization fails, event prm is `401 Unauthorized`:
```
03-05 08:54:22.141 32710   367 D Baresip Lib: ua event (REGISTER_FAIL) 401 Unauthorized
```
So

**Comment by cspiel1** [comment]
In the
```
register_handler(int err, const struct sip_msg *msg, void *arg)
```
can you use in addition to err the sip_msg to retrieve some useful information. Maybe sip_msg->scode?

**Comment by cspiel1** [comment]
What about errno
 525: SSL handshake failed

Found by search in web but don't know where it is defined. Can we use another error code than EAUTH or should we add a new one?

**Comment by juha-h** [comment]
Christian Spielberger writes:

> What about errno
>  525: SSL handshake failed

It is unofficial Cloudfare code:

  https://en.wikipedia.org/wiki/List_of_HTTP_status_codes#Cloudflare

In this case, better match would be:

  526 Invalid SSL Certificate
     Cloudflare could not validate the SSL certificate on the origin web server.

> Found by search in web but don't know where it is defined. Can we use
> another error code than EAUTH or should we add a new one?

EAUTH would be OK for me if prm text would be, for example, "Invalid SSL
Certificate"

**Comment by cspiel1** [comment]
I see. Here again the layers:
baresip reg -> re sipreg -> re request -> re ctransp -> re transp -> re tls

openssl abstaction is done by tls, transport hides tls, request hides transport.

In sipreg you have only the err because I think in this situation msg==NULL.

So if we let EAUTH we could add a check in baresips register_handler(), if there was a TLS error right now.
```C
	if (err == EAUTH && tls_error(uag_tls())) {
		...
	} else if (err) {
		...
```
- Not very good SW design, right?
- Also not sure if the TLS error always belongs to the current error at this location. But I think so.

**Comment by alfredh** [comment]
check here the code involved:

```c
static int tls_connect(struct tls_conn *tc)
{
	int err = 0, r;

	ERR_clear_error();

	r = SSL_connect(tc->ssl);
	if (r <= 0) {
		const int ssl_err = SSL_get_error(tc->ssl, r);

		ERR_clear_error();

		switch (ssl_err) {

		case SSL_ERROR_WANT_READ:
			break;

		default:
			DEBUG_WARNING("connect: error (r=%d, ssl_err=%d)\n",
				      r, ssl_err);
			err = EPROTO;
			break;
		}
	}

	return err;
}
```

you can try to check for that error code, and then translate it to EAUTH

**Comment by juha-h** [comment]
I checked `unable to get local issuer certificate` case with `ERR_error_string(ssl_err, NULL);` and it didn't tell much:
```
error:00000001:lib(0):func(0):reason(1)
```

**Comment by juha-h** [comment]
I added new code and got the error info:
```
	r = SSL_connect(tc->ssl);
	if (r <= 0) {

		SSL_load_error_strings();
		ERR_print_errors_fp(file1);
		fclose(file1);
```
Then `unable to get local issuer certificate` case produces this to file1:
```
139680966902528:error:1416F086:SSL routines:tls_process_server_certificate:certi
ficate verify failed:../ssl/statem/statem_clnt.c:1915:
```

**Comment by alfredh** [comment]
the error code is SSL_ERROR_SSL which is 1, this means that you can fetch the lowlevel errorcode:

```
# define         X509_V_ERR_UNABLE_TO_GET_ISSUER_CERT_LOCALLY    20
```

**Comment by juha-h** [comment]
The code below produces the correct error string:
```
tls: connect: error (r=-1, ssl_err=1, get_err=337047686) certificate verify failed
```
I have no tbeen able to find name for error code 337047686.

How to proceed with this?

```
static int tls_connect(struct tls_conn *tc)
{
	int err = 0, get_err, r;

	ERR_clear_error();

	r = SSL_connect(tc->ssl);
	if (r <= 0) {
		const int ssl_err = SSL_get_error(tc->ssl, r);

		switch (ssl_err) {

		case SSL_ERROR_WANT_READ:
			break;

		default:
			get_err = ERR_get_error();
			SSL_load_error_strings();
			DEBUG_WARNING("connect: error "
				      "(r=%d, ssl_err=%d, get_err=%d) %s\n",
				      r, ssl_err, get_err,
				      ERR_reason_error_string(get_err));
			err = EPROTO;
			break;
		}

		ERR_clear_error();
	}

	return err;
}
```

**Comment by juha-h** [comment]
I made `tls_connect` return `EAUTH` if error reason is `certificate verify failed`, but it didn't have any effect.  baresip still prints ` Register: Network is unreachable`.  Also, I noticed that `%m` format does not recognize EAUTH (= 217) error code.

**Comment by juha-h** [comment]
> the error code is SSL_ERROR_SSL which is 1, this means that you can fetch the lowlevel errorcode:
> 
> ```
> # define         X509_V_ERR_UNABLE_TO_GET_ISSUER_CERT_LOCALLY    20
> ```

Sorry, but I didn't understand the above.  ssl_err is 1, but get_err is 337047686.  How can the low level error code be fetched?

Also, returning EAUTH does not seem to have any effect as show in my previous comment, which sort of nullifies this error code effort.

**Comment by alfredh** [comment]
you have to read the
openssl api docs.

it is possible to extract that code

**Comment by juha-h** [comment]
I have read the api docs on SSL_connect and ERR_get_error:

[https://www.ibm.com/support/knowledgecenter/en/SSB23S_1.1.0.14/gtpc2/cpp_ssl_connect.html#cpp_ssl_connect](url)
[https://www.ibm.com/support/knowledgecenter/en/SSB23S_1.1.0.14/gtpc2/cpp_ssl_get_error.html](url)

as well as read the client application example:

[https://www.ibm.com/support/knowledgecenter/en/SSB23S_1.1.0.14/gtps7/s5sple2.html](url)

but have not found anything about the low level error codes.

I'll close this issue, because I'm not able to do anything about it.  And even if I could find the code, returning `EAUTH` would not help. Also, since `tls_connect()` clears the errors, the error code can not be retrieved later in some other part of the code either.
