### ISSUE TITLE
Should ua.c really resume a call when any call terminates?

### ISSUE THREAD

**Issue by cspiel1** [baresip/baresip#1243]
Was thinking about this again, because we (@cHuberCoffee) shortly replaced the
```
resume_call(ua);
```
by the new
```
uag_hold_resume(NULL);
```
This ensures that not two calls are established at the same time.

But found this additional problems:
1. It is not correct in some situation to do so. Suppose:
- There are three calls. One is established (E), one is on-hold (H), the third is an outgoing call (O).
- Then (O) is rejected by the peer. So it terminates.
- As result (E) and (H) will be exchanged, which makes no sense.
2. But now assume (E) terminates. I think that it is not always wanted that (H) is resumed. The application should decide this. E.g. module menu, gtk, ...

So I suggest to
- add a check if the call that terminates was the established call,
- let menu decide if uag_hold_resume() should be invoked, maybe in the ua_event_handler(). Maybe also gtk to stay backward compatible for gtk users.
- Add also a config for menu if the resume is wanted if a call terminates.

I need your opinion.

**Comment by juha-h** [comment]
Is it really necessary to have such complex scenarios, where during an established call another call is placed?

**Comment by cspiel1** [comment]
Yes, you can have multiple incoming calls while having an established call. Think about a control desk application!
Also, placing an outgoing call while there is an established call is a normal scenario. And it is possible in baresip right now.

Anyway, the simple use cases where you have only one call should not be affected by the mentioned problem. Here I suggest to simplify the behavior to remove the resume in ua_hangup() and the call_event_handler(). This would solve problem 1. and 2. mentioned above.

**Comment by cspiel1** [comment]
Ok, this is a different subject. Should be discussed also. But maybe in a different issue.

Tomorrow I will make a PR for the mentioned problems. Any other suggestions how to handle this?

**Comment by juha-h** [comment]
So what happens when there is established call and ongoing call and the ongoing call is answered?

**Comment by cspiel1** [comment]
Currently then you have two established calls. This is another issue for which I plan to make another PR. @cHuberCoffee and me think that bareship should ensure that there is only one established call. There are two possible solutions:
- ua.c ensures that there is only one call, or
- the application module (e.g. menu) ensures this. I think this is the right solution to be more flexible if anyone does'nt use menu.

**Comment by cspiel1** [comment]
### To sum up
- Resume a call if the established call terminates is business logic and should be done in module menu. Currently it is done in ua.c and it is done in-correct in some situations.
- Ensuring that there is only one established call should be done in menu, like it is partly done now in cmd_answer(). Other calls should be put on hold.

**Comment by juha-h** [comment]
Christian Spielberger writes:

> Currently then you have two established calls. This is another issue
> for which I plan to make another PR. @cHuberCoffee and me think that
> bareship should ensure that there is only one established call.

That is my thinking too unless the call is a conference call in which
case baresip would act as a conference bridge.  I can imagine that a
call is started as a p2p call with two participants and then during the
call more parties are added and the call becomes a conference call.

> There are two possible solutions: 
>
> - ua.c ensures that there is only one call, or
> - the application module (e.g. menu) ensures this. I think this is the
>   right solution to be more flexible if anyone does'nt use menu.

What are the use cases for more than one, independent established calls?
Does baresip support several simultaneous microphones, speakers and
video cameras?

**Comment by sreimers** [comment]
> * ua.c ensures that there is only one call, or
> * the application module (e.g. menu) ensures this. I think this is the right solution to be more flexible if anyone does'nt use menu.

In my application i use a custom audio driver with n-1, for group calls. so please only implement this in menu.c. ua.c should
not prevent multiple calls with one account. another use case is the echo test module with audiobridge.

**Comment by cspiel1** [comment]
Resume when call terminates now
- is invoked by menu instead ua and
- only if the terminated call was established.
```
commit b0d11a5fda11e451e479cbc14bcbe1e91c6086e3
Author: Christian Spielberger <c.spielberger@commend.com>
Date:   Fri Mar 5 14:26:49 2021 +0100

    Call resume on hangup (#1246)
    
    * menu: only select call if it was resumed by us
    
    * ua: fix UA search for uag_hold_resume()
    
    * ua, menu: on hangup menu decides to resume a call
    
    * ua: uag_hold_resume() should not print a warning
    
    * ua: uag_hold_resume() better readable
```
