### ISSUE TITLE
gcc v4.8.5 build error. enum jbuf_type jbtype;  /**< Jitter buffer type 

### ISSUE THREAD

**Issue by netyuchangfa** [baresip/baresip#1263]
CC [M]  build-x86_64/modules/account/account.o
In file included from modules/account/account.c:7:0:
include/baresip.h:344:7: 警告：ISO C 不允许‘enum’类型的前向引用 [-Wpedantic]
  enum jbuf_type jbtype;  /**< Jitter buffer type             */
       ^
include/baresip.h:344:17: 错误：字段‘jbtype’的类型不完全
  enum jbuf_type jbtype;  /**< Jitter buffer type             */
                 ^
make: *** [build-x86_64/modules/account/account.o] 错误 1

GCC version 4.8.5

**Comment by cspiel1** [comment]
Please use only libs from https://github.com/baresip, not creytiv!

@alfredh @sreimers What could we do that this mistake stops to happen?

**Comment by sreimers** [comment]
Maybe we should consider rename our forks like `libbaresip-re` and `libbaresip-rem`
And add a Makefile min. version requirement dependency info to baresip itself.

**Comment by netyuchangfa** [comment]
yes, build and install re and rem.then make baresip

**Comment by alfredh** [comment]
we should also
make a new release :)

**Comment by netyuchangfa** [comment]
enum jbuf_type jbtype; /< Jitter buffer type */
^

CentOS Linux release 7.6.1810 (Core)
GCC 4.8.5

-std=c98? or c99?

**Comment by netyuchangfa** [comment]
used  https://github.com/baresip re and rem 
re-1.1.0  
rem-0.6.0

**Comment by netyuchangfa** [comment]
@cspiel1  @sreimers  @alfredh  Thansk !!!
i download new code ,rebuild  re and rem,then make baresip is ok!

**Comment by cspiel1** [comment]
> Maybe we should consider rename our forks like `libbaresip-re` and `libbaresip-rem`
> And add a Makefile min. version requirement dependency info to baresip itself.

But then the clone URLs are changing. Or not?
Makefile min version for re and rem would be great.

**Comment by juha-h** [comment]
Christian Spielberger writes:

> > Maybe we should consider rename our forks like `libbaresip-re` and `libbaresip-rem`
> > And add a Makefile min. version requirement dependency info to baresip itself.
> 
> But then the clone URLs are changing. Or not?
> Makefile min version for re and rem would be great.

Yes, better not to rename, but have version dependency like in
debian/control. If possible, use development, pre-release version
numbers.
