### ISSUE TITLE
Default disabled video,how to enable video h264 or vp8?

### ISSUE THREAD

**Issue by netyuchangfa** [baresip/baresip#1265]
Refer to the methods in the documentation:make and make install
but it not support video.
how to config it enable video h264 or vp8?

**Comment by juha-h** [comment]
www.123667.com writes:

> Refer to the methods in the documentation:make and make install
> but it not support video.
> how to config it enable video h264 or vp8?

You need to have proper dev libraries installed.  See USE_AVCODEC and
USE_VPX in mk/modules.mk.

**Comment by netyuchangfa** [comment]
Thanks very much!!
