### ISSUE TITLE
run it error:baresip: symbol lookup error: baresip: undefined symbol: tls_disable_verify_server

### ISSUE THREAD

**Issue by netyuchangfa** [baresip/baresip#1270]
baresip: symbol lookup error: baresip: undefined symbol: tls_disable_verify_server
installed (openssl/libressl) https://github.com/baresip/ci,Prebuilt assets (openssl/libressl) and helpers for Travis CI

**Comment by juha-h** [comment]
www.123667.com writes:

> baresip: symbol lookup error: baresip: undefined symbol:
> tls_disable_verify_server installed (openssl/libressl)
> https://github.com/baresip/ci,Prebuilt assets (openssl/libressl) and
> helpers for Travis CI

Use latest baresip project re.

**Comment by netyuchangfa** [comment]
@juha-h ，yes,, git clone codes, use latest baresip and re ,rem

**Comment by netyuchangfa** [comment]
x86_64 no problem,but raspberry pi

**Comment by juha-h** [comment]
www.123667.com writes:

> @juha-h ，yes,, git clone codes, use latest baresip and re ,rem

I didn't understand, but for sure, the function is in libre:
```
re$ grep -r tls_disable_verify_server
src/tls/openssl/tls.c:void tls_disable_verify_server(struct tls *tls)
include/re_tls.h:void tls_disable_verify_server(struct tls *tls);
```
If you roll your own, you need to include re_tls.h.

**Comment by netyuchangfa** [comment]
now,replace orangepi,then error:baresip: symbol lookup error: baresip: undefined symbol: sip_transp_decode
use latest codes:
wget https://github.com/baresip/baresip/archive/master.zip
wget https://github.com/baresip/re/archive/master.zip
wget https://github.com/baresip/rem/archive/master.zip

root@orangepipc:~/re-master#  grep -r tls_disable_verify_server
Binary file libre.so matches
Binary file libre.a matches
include/re_tls.h:void tls_disable_verify_server(struct tls *tls);
src/tls/openssl/tls.c:void tls_disable_verify_server(struct tls *tls)
Binary file build-arm/tls/openssl/tls.o matches
root@orangepipc:~/re-master# baresip 
baresip: symbol lookup error: baresip: undefined symbol: sip_transp_decode
root@orangepipc:~/re-master# grep -r sip_transp_decode
Binary file libre.so matches
Binary file libre.a matches
include/re_sip.h:enum sip_transp sip_transp_decode(const struct pl *pl);
src/sip/request.c:              req->tp = sip_transp_decode(&pl);
src/sip/transp.c:enum sip_transp sip_transp_decode(const struct pl *pl)
Binary file build-arm/sip/transp.o matches
Binary file build-arm/sip/request.o matches

**Comment by netyuchangfa** [comment]
baresip v1.0.0 Copyright (C) 2010 - 2020 Alfred E. Heggestad et al.
config: creating config template /home/pi/.baresip/config
/usr/local/lib/baresip/modules: detected 54 modules
Local network address:  IPv4=eth0|192.168.1.25
ua: adding SIP CA: /etc/ssl/certs/ca-certificates.crt
baresip: symbol lookup error: baresip: undefined symbol: sip_transp_add_websock
pi@raspberrypi:~ $ grep -r sip_transp_add_websock
Binary file baresip/baresip-master/build-arm6/src/ua.o matches
baresip/baresip-master/src/ua.c:        err = sip_transp_add_websock(uag.sip, SIP_TRANSP_WS, &local,
baresip/baresip-master/src/ua.c:        err = sip_transp_add_websock(uag.sip, SIP_TRANSP_WSS, &local,
Binary file baresip/baresip-master/baresip matches
baresip/re-master/include/re_sip.h:int  sip_transp_add_websock(struct sip *sip, enum sip_transp tp,
Binary file baresip/re-master/build-arm6/sip/transp.o matches
Binary file baresip/re-master/libre.a matches
baresip/re-master/src/sip/transp.c:int sip_transp_add_websock(struct sip *sip, enum sip_transp tp,
Binary file baresip/re-master/libre.so matches

pi@raspberrypi:~ $ vi .baresip/config
sip_cafile             /etc/ssl/certs/ca-certificates.crt  
#sip_trans_def  udp
sip_verify_server      yes

edit it disable  sip_cafile and sip_verify_server  :
#sip_cafile             /etc/ssl/certs/ca-certificates.crt
#sip_trans_def  udp
#sip_verify_server      yes

then run again:
pi@raspberrypi:~ $ baresip
baresip v1.0.0 Copyright (C) 2010 - 2020 Alfred E. Heggestad et al.
Local network address:  IPv4=eth0|192.168.1.25
baresip: symbol lookup error: baresip: undefined symbol: tls_disable_verify_server

**Comment by sreimers** [comment]
`/re-master` -> would be not detected by baresip (maybe you have installed another libre version), needs a rename to `/re`

The complete directory structure has to look like this:
```
/path/re
/path/rem
/path/baresip
```

A  `make info` in baresip should show the detected paths/libs.

**Comment by alfredh** [comment]
please consider to use the mailing list for questions like this:

https://groups.google.com/g/baresip

to fix the problem, please do:

1. uninstall all baresip, librem, libre packages
2. git checkout of latest versions
3. make, sudo make install
