### ISSUE TITLE
audio_stop does not update audio started flag

### ISSUE THREAD

**Issue by Koshub** [baresip/baresip#1276]
`audio_stop` does not update `audio->started` so after the stop `audio_started` returns wrong value

https://github.com/baresip/baresip/blob/42aee871bfd04fd3b66c99a70716507a861ae6a4/src/audio.c#L1878

**Comment by sreimers** [comment]
I`m not 100% sure if this is necessary. audio is destructed with call_destructor. Is there any case the audio object is reused without destructing?

**Comment by Koshub** [comment]
Thanks for answer. If I need to stop and restart call audio processing, calling `audio_stop` the call just stops its player/recorder and is not being destructed.

**Comment by Koshub** [comment]
@sreimers @alfredh Thank you

**Comment by Koshub** [comment]
Hi again. Sorry for disturbing you,  I have two related questions:
-  So is it ok that baresip starts to call audio (reallocates player/recorder) after a remote SDP event even if I stopped the call audio? 
- If I fail the player and recorder allocation to fix that will baresip try to allocate the player and recorder constantly (no matter what) while the call is in progress if some previous attempts to allocate the player and recorder fail?
