### ISSUE TITLE
rport re REGISTER Contact head  error ,Cause unable to wake up baresip

### ISSUE THREAD

**Issue by yuexiajiayan** [baresip/baresip#1307]
**i have a reg msg like this:**

local ip:192.168.1.102
sip server:192.168.70.88

recv 536 bytes from udp/[192.168.70.6]:59169 at 13:42:15.272891:
------------------------------------------------------------------------
REGISTER sip:192.168.70.88:1890;transport=udp SIP/2.0
Via: SIP/2.0/UDP 192.168.1.102:59169;branch=z9hG4bK5af141bb26e901eb;rport
Contact: <sip:1002-0x8157a0@192.168.1.102:59169>;expires=60;+sip.instance="<urn:uuid:69a4004b-6915-6615-3b25-417d79231b39>"
Max-Forwards: 70
To: <sip:1002@192.168.70.88:1890>
From: <sip:1002@192.168.70.88:1890>;tag=18be67844ae13d6c
Call-ID: 69525f9016496df1
CSeq: 11478 REGISTER
User-Agent: baresip v1.0
Allow: INVITE,ACK,BYE,CANCEL,OPTIONS,NOTIFY,SUBSCRIBE,INFO,MESSAGE,REFER
Content-Length: 0

send 630 bytes to udp/[192.168.70.6]:59169 at 13:42:15.312092:
------------------------------------------------------------------------
SIP/2.0 401 Unauthorized
Via: SIP/2.0/UDP 192.168.1.102:59169;branch=z9hG4bK5af141bb26e901eb;rport=59169;received=192.168.70.6
From: <sip:1002@192.168.70.88:1890>;tag=18be67844ae13d6c
To: <sip:1002@192.168.70.88:1890>;tag=0r3c0vg104HXe
Call-ID: 69525f9016496df1
CSeq: 11478 REGISTER
User-Agent: FreeSWITCH-mod_sofia/1.10.3-release~64bit
Allow: INVITE, ACK, BYE, CANCEL, OPTIONS, MESSAGE, INFO, UPDATE, REGISTER, REFER, NOTIFY, PUBLISH, SUBSCRIBE
Supported: timer, path, replaces
WWW-Authenticate: Digest realm="192.168.70.88", nonce="85e8033a-8b9a-11eb-815a-5d1b097a59f0", algorithm=MD5, qop="auth"
Content-Length: 0

recv 783 bytes from udp/[192.168.70.6]:59169 at 13:42:15.313993:

------------------------------------------------------------------------

**when re REGISTER  Contact head Not used 401 return msg (rport=59169;received=192.168.70.6) 
ip , it use local IP （192.168.1.102）re reg Cause unable to wake up baresip**
(
Contact: <sip:1002-0x8157a0@_192.168.1.102_:59169>;expires=60;+sip.instance="<urn:uuid:69a4004b-6915-6615-3b25-417d79231b39>"  like this ,port it's ok
)
------------------------------------------------------------------------
REGISTER sip:192.168.70.88:1890;transport=udp SIP/2.0
Via: SIP/2.0/UDP 192.168.1.102:59169;branch=z9hG4bK473016c968331340;rport
Contact: <sip:1002-0x8157a0@_192.168.1.102_:59169>;expires=60;+sip.instance="<urn:uuid:69a4004b-6915-6615-3b25-417d79231b39>"
Max-Forwards: 70
Authorization: Digest username="1002", realm="192.168.70.88", nonce="85e8033a-8b9a-11eb-815a-5d1b097a59f0", uri="sip:192.168.70.88:1890;transport=udp", response="ce48e1cbefdc1d0dce0b6e9854f9adf5", cnonce="7bf362296bd96ec7", qop=auth, nc=00000001
To: <sip:1002@192.168.70.88:1890>
From: <sip:1002@192.168.70.88:1890>;tag=18be67844ae13d6c
Call-ID: 69525f9016496df1
CSeq: 11479 REGISTER
User-Agent: baresip v1.0
Allow: INVITE,ACK,BYE,CANCEL,OPTIONS,NOTIFY,SUBSCRIBE,INFO,MESSAGE,REFER
Content-Length: 0

send 597 bytes to udp/[192.168.70.6]:59169 at 13:42:15.439669:

**hao to change local ip to report return ip**

**Comment by sreimers** [comment]
> User-Agent: baresip v0.1

Your baresip version seems to be very outdated. Can you test with the latest 1.0.0 release and/or upstream?

**Comment by yuexiajiayan** [comment]
yes i'm test baresip 1.0
