### ISSUE TITLE
make contrib error

### ISSUE THREAD

**Issue by smdDkeys** [baresip/baresip#1325]
This is the error that occurs when "make contrib". Has anyone come across this?
``` 
src/audio.c:422:10: error: implicit declaration of function 'aulevel_calc_dbov' 
is invalid in C99 [-Werror,-Wimplicit-function-declaration]
level = aulevel_calc_dbov(fmt, sampv, sampc); 
        ^

**Comment by kannanmaran** [comment]
@smdDkeys How did you fixed this error?

**Comment by cspiel1** [comment]
Such gcc errors have often the same reason. The libs re or rem are not update to date.
This function was added shortly to rem by Alfred.
```
commit 5307c3415c9ef19381784c67fa610e42d143b9d3 (HEAD -> master, origin/master)
Author: Alfred E. Heggestad <alfred.heggestad@gmail.com>
Date:   Sat Mar 27 10:52:58 2021 +0100
```

**Comment by lilkid3** [comment]
> Such gcc errors have often the same reason. The libs re or rem are not up to date.
> This function was added shortly to rem by Alfred.
> 
> ```
> commit 5307c3415c9ef19381784c67fa610e42d143b9d3 (HEAD -> master, origin/master)
> Author: Alfred E. Heggestad <alfred.heggestad@gmail.com>
> Date:   Sat Mar 27 10:52:58 2021 +0100
> 
>     add aulevel module
> ```
> 
> I assume that it was solved by:
> 
> ```
> cd rem
> git pull
> make
> sudo make install
> ```

@cspiel1 this did not work, the make still throws the same error. Thank you.

**Comment by sreimers** [comment]
> this did not work, the make still throws the same error. Thank you.

Did you use https://github.com/baresip/rem as repo for rem?

**Comment by lilkid3** [comment]
> > this did not work, the make still throws the same error. Thank you.
> 
> Did you use https://github.com/baresip/rem as repo for rem?

YES I DID

**Comment by lilkid3** [comment]
> > this did not work, the make still throws the same error. Thank you.
> 
> Did you use https://github.com/baresip/rem as repo for rem?

Yes i used th elates commit

**Comment by lilkid3** [comment]
> > this did not work, the make still throws the same error. Thank you.
> 
> Did you use https://github.com/baresip/rem as repo for rem?

Yes i did, i used the latest commit

**Comment by sreimers** [comment]
Maybe you need to cleanup old rem installation(s) first.

**Comment by lilkid3** [comment]
> Maybe you need to cleanup old rem installation(s) first.

Sorry for the mistake, i used https://github.com/creytiv/rem  I would try this https://github.com/baresip/rem. Thanks
