### ISSUE TITLE
disconnecting many times

### ISSUE THREAD

**Issue by AingTii** [baresip/baresip#1327]
I have the Problem, on raspberry Pi 3b, that the baresip disconnecting 
many times, also I cannot reach by Node-Red TCP connection.

`doorpi01@fritz.box: {0/UDP/v4} 200 OK () [1 binding]
All 1 useragent registered successfully! (140 ms)
call: connecting to 'sip:**610@fritz.box'..
call: SIP Progress: 100 Trying (/)
call: SIP Progress: 183 Session Progress (application/sdp)
audio: Set audio encoder: PCMU 8000Hz 1ch
audio: source started with sample format S16LE
audio: Set audio decoder: PCMU 8000Hz 1ch
audio: player started with sample format S16LE
audio tx pipeline:        alsa ---> vumeter ---> PCMU
audio rx pipeline:        alsa <--- vumeter <--- PCMU
doorpi01@fritz.box: Call in-progress: sip:**610@fritz.box
stream: incoming rtp for 'audio' established, receiving from 192.168.5.1:7080
call: connecting to 'sip:**610@fritz.box'..
call: SIP Progress: 100 Trying (/)                          [=========       ]  [=               ]
call: SIP Progress: 183 Session Progress (application/sdp)
audio: Set audio encoder: PCMU 8000Hz 1ch
audio: source started with sample format S16LE
audio: Set audio decoder: PCMU 8000Hz 1ch
audio: player started with sample format S16LE
audio tx pipeline:        alsa ---> vumeter ---> PCMU
audio rx pipeline:        alsa <--- vumeter <--- PCMU
doorpi01@fritz.box: Call in-progress: sip:**610@fritz.box
sip:**610@fritz.box: session closed: 486 Busy Here
doorpi01@fritz.box: Call established: sip:**610@fritz.box   [=========       ]  [==============  ]
sip:**610@fritz.box: session closed: Connection reset by peer=========       ]  [====            ]
sip:doorpi01@fritz.box: Call with sip:**610@fritz.box terminated (duration: 2 secs)
reg: sip:doorpi01@fritz.box: 401 Unauthorized ()
doorpi01@fritz.box: {0/UDP/v4} 200 OK () [1 binding]
reg: sip:doorpi01@fritz.box: 401 Unauthorized ()
doorpi01@fritz.box: {0/UDP/v4} 200 OK () [1 binding]
reg: sip:doorpi01@fritz.box: 401 Unauthorized ()
doorpi01@fritz.box: {0/UDP/v4} 200 OK () [1 binding]
reg: sip:doorpi01@fritz.box: 401 Unauthorized ()
doorpi01@fritz.box: {0/UDP/v4} 200 OK () [1 binding]
`

![image](https://user-images.githubusercontent.com/43577834/113515211-5e409300-9573-11eb-8caf-5c8fec14d060.png)

Any Idea, whats the problem?

thank you

**Comment by alfredh** [comment]
can you please reformat the log, so that the text is readable ?

https://github.com/baresip/baresip/wiki/Guidelines-for-reporting-Issues

please include the full log and your config.

**Comment by AingTii** [comment]
Oh I don't understand why it is in that format, sorry.
I will try to format....

accounts:
`#
# SIP accounts - one account per line
#
# Displayname <sip:user@domain;uri-params>;addr-params
#
#  uri-params:
#    ;transport={udp,tcp,tls}
#
#  addr-params:
#    ;answermode={manual,early,auto}
#    ;audio_codecs=opus/48000/2,pcma,...
#    ;auth_user=username
#    ;auth_pass=password
#    ;call_transfer=no
#    ;mediaenc={srtp,srtp-mand,srtp-mandf,dtls_srtp,zrtp}
#    ;medianat={stun,turn,ice}
#    ;mwi=no
#    ;outbound="sip:primary.example.com;transport=tcp"
#    ;outbound2=sip:secondary.example.com
#    ;ptime={10,20,30,40,...}
#    ;regint=3600
#    ;pubint=0 (publishing off)
#    ;regq=0.5
#    ;sipnat={outbound}
#    ;stunuser=STUN/TURN/ICE-username
#    ;stunpass=STUN/TURN/ICE-password
#    ;stunserver=stun:[user:pass]@host[:port]
#    ;video_codecs=h264,h263,...
#
# Examples:
#
#  <sip:user@domain.com;transport=tcp>;auth_pass=secret
#  <sip:user@1.2.3.4;transport=tcp>;auth_pass=secret
#  <sip:user@[2001:df8:0:16:216:6fff:fe91:614c]:5070;transport=tcp>;auth_pass=secret
#
<sip:doorpi01@fritz.box>;auth_pass=xxxxxxx
 `

config:
`#
# baresip configuration
#

#------------------------------------------------------------------------------

# Core
poll_method             epoll           # poll, select, epoll ..

# SIP
sip_trans_bsize         128
#sip_listen             0.0.0.0:5060
#sip_certificate        cert.pem

# Call
call_local_timeout      120
call_max_calls          4

# Audio
#audio_path             /usr/share/baresip
audio_player            alsa,default
audio_source            alsa,default
audio_alert             alsa,default
#ausrc_srate            48000
#auplay_srate           48000
#ausrc_channels         0
#auplay_channels        0
#audio_txmode           poll            # poll, thread
audio_level             no
ausrc_format            s16             # s16, float, ..
auplay_format           s16             # s16, float, ..
auenc_format            s16             # s16, float, ..
audec_format            s16             # s16, float, ..

# Video
#video_source           v4l2,/dev/video0
#video_display          x11,nil
video_size              352x288
video_bitrate           500000
video_fps               25.00
video_fullscreen        yes
videnc_format           yuv420p

# AVT - Audio/Video Transport
rtp_tos                 184
#rtp_ports              10000-20000
#rtp_bandwidth          512-1024 # [kbit/s]
rtcp_mux                no
jitter_buffer_delay     5-10            # frames
rtp_stats               no
#rtp_timeout            60

# Network
#dns_server             10.0.0.1:53
#net_interface          eth0

# BFCP
#bfcp_proto             udp

#------------------------------------------------------------------------------
# Modules

module_path             /usr/lib/baresip/modules

# UI Modules
module                  stdio.so
#module                 cons.so
#module                 evdev.so
#module                 httpd.so

# Audio codec Modules (in order)
#module                 opus.so
#module                 amr.so
#module                 g7221.so
#module                 g722.so
#module                 g726.so
module                  g711.so
#module                 gsm.so
#module                 l16.so
#module                 bv32.so
#module                 mpa.so
#module                 codec2.so
#module                 ilbc.so
#module                 isac.so

# Audio filter Modules (in encoding order)
module                  vumeter.so
#module                 sndfile.so
#module                 speex_aec.so
#module                 speex_pp.so
#module                 plc.so

# Audio driver Modules
module                  alsa.so
#module                 pulse.so
#module                 jack.so
#module                 portaudio.so
#module                 aubridge.so
#module                 aufile.so

# Video codec Modules (in order)
module                  avcodec.so
#module                 vp8.so
#module                 vp9.so
#module                 h265.so

# Video filter Modules (in encoding order)
#module                 selfview.so
#module                 snapshot.so
#module                 swscale.so
#module                 vidinfo.so

# Video source modules
#module                 v4l.so
#module                 v4l2.so
#module                 v4l2_codec.so
#module                 avformat.so
#module                 x11grab.so
#module                 cairo.so
#module                 vidbridge.so

# Video display modules
#module                 directfb.so
#module                 x11.so
#module                 sdl2.so
#module                 fakevideo.so

# Audio/Video source modules
#module                 rst.so
#module                 gst1.so
#module                 gst_video1.so

# Media NAT modules
module                  stun.so
module                  turn.so
module                  ice.so
#module                 natpmp.so
#module                 pcp.so

# Media encryption modules
#module                 srtp.so
#module                 dtls_srtp.so
#module                 zrtp.so

#------------------------------------------------------------------------------
# Temporary Modules (loaded then unloaded)

module_tmp              uuid.so
module_tmp              account.so


#------------------------------------------------------------------------------
# Application Modules

module_app              auloop.so
#module_app             b2bua.so
module_app              contact.so
module_app              debug_cmd.so
#module_app             dtmfio.so
#module_app             echo.so
#module_app             gtk.so
module_app              menu.so
#module_app             mwi.so
#module_app             natbd.so
#module_app             presence.so
#module_app             syslog.so
#module_app             mqtt.so
module_app              ctrl_tcp.so
module_app              vidloop.so


#------------------------------------------------------------------------------
# Module parameters


cons_listen             0.0.0.0:5555

http_listen             0.0.0.0:8000

ctrl_tcp_listen         0.0.0.0:4444

evdev_device            /dev/input/event0

# Opus codec parameters
opus_bitrate            28000 # 6000-510000
#opus_stereo            yes
#opus_sprop_stereo      yes
#opus_cbr               no
#opus_inband_fec        no
#opus_dtx               no
#opus_mirror            no
#opus_complexity                10
#opus_application               audio   # {voip,audio}

vumeter_stderr          yes

# Selfview
video_selfview          window # {window,pip}
#selfview_size          64x64

# ICE
ice_turn                no
ice_debug               no
ice_nomination          regular # {regular,aggressive}
ice_mode                full    # {full,lite}

# ZRTP
#zrtp_hash              no  # Disable SDP zrtp-hash (not recommended)

# Menu
#menu_bell              yes
#redial_attempts        3 # Num or <inf>
#redial_delay           5 # Delay in seconds
#ringback_disabled      yes
#statmode_default       off

`

**Comment by AingTii** [comment]
Log:

`
pi@raspberrypi:~ $ baresip –v

baresip v0.6.1 Copyright (C) 2010 - 2019 Alfred E. Heggestad et al.

Local network address:  IPv4=eth0:192.168.5.79

aucodec: PCMU/8000/1

aucodec: PCMA/8000/1

aufilt: vumeter

ausrc: alsa

auplay: alsa

dl: mod: /usr/lib/baresip/modules/avcodec.so (/usr/lib/baresip/modules/avcodec.so: cannot open shared object file: No such file 
or directory)

module avcodec.so: No such file or directory

medianat: stun

medianat: turn

medianat: ice

Populated 1 account

Populated 3 contacts

Populated 2 audio codecs

Populated 1 audio filter

Populated 0 video codecs

Populated 0 video filters

baresip is ready.

doorpi01@fritz.box: {0/UDP/v4} 200 OK () [1 binding]

All 1 useragent registered successfully! (60 ms)

**reg: sip:doorpi01@fritz.box: 401 Unauthorized ()**

call: connecting to 'sip:**610@fritz.box'..

call: SIP Progress: 100 Trying (/)

call: SIP Progress: 183 Session Progress (application/sdp)

audio: Set audio encoder: PCMU 8000Hz 1ch

audio: source started with sample format S16LE

audio: Set audio decoder: PCMU 8000Hz 1ch

audio: player started with sample format S16LE

audio tx pipeline:        alsa ---> vumeter ---> PCMU

audio rx pipeline:        alsa <--- vumeter <--- PCMU

doorpi01@fritz.box: Call in-progress: sip:**610@fritz.box

stream: incoming rtp for 'audio' established, receiving from 192.168.5.1:7080

doorpi01@fritz.box: Call established: sip:**610@fritz.box   [========        ]  [==============  ]

sip:**610@fritz.box: session closed: Connection reset by peer=======         ]  [==============  ]

sip:doorpi01@fritz.box: Call with sip:**610@fritz.box terminated (duration: 1 sec)

doorpi01@fritz.box: {0/UDP/v4} 200 OK () [1 binding]

call: connecting to 'sip:**610@fritz.box'..

call: SIP Progress: 100 Trying (/)

call: SIP Progress: 183 Session Progress (application/sdp)

audio: Set audio encoder: PCMU 8000Hz 1ch

audio: source started with sample format S16LE

audio: Set audio decoder: PCMU 8000Hz 1ch

audio: player started with sample format S16LE

audio tx pipeline:        alsa ---> vumeter ---> PCMU

audio rx pipeline:        alsa <--- vumeter <--- PCMU

doorpi01@fritz.box: Call in-progress: sip:**610@fritz.box

stream: incoming rtp for 'audio' established, receiving from 192.168.5.1:7078

call: connecting to 'sip:**610@fritz.box'..                 [========        ]  [=               ]

call: SIP Progress: 100 Trying (/)

call: SIP Progress: 183 Session Progress (application/sdp)

audio: Set audio encoder: PCMU 8000Hz 1ch

audio: source started with sample format S16LE

audio: Set audio decoder: PCMU 8000Hz 1ch

audio: player started with sample format S16LE

audio tx pipeline:        alsa ---> vumeter ---> PCMU

audio rx pipeline:        alsa <--- vumeter <--- PCMU

doorpi01@fritz.box: Call in-progress: sip:**610@fritz.box

sip:**610@fritz.box: session closed: 486 Busy Here

doorpi01@fritz.box: Call established: sip:**610@fritz.box   [=========       ]  [=               ]

sip:**610@fritz.box: session closed: Connection reset by peer=======         ]  [=========       ]

**reg: sip:doorpi01@fritz.box: 401 Unauthorized ()**

doorpi01@fritz.box: {0/UDP/v4} 200 OK () [1 binding]
`

**Comment by alfredh** [comment]
you are using a very old version. Please upgrade to latest baresip from git HEAD.

**Comment by AingTii** [comment]
okay, sorry, but I have no Idea how to make that,
it was really hard to find a way to install baresip, because nothing work.
Normaly I thougth it will get the latetest release by itself, but seems not.

So my question, How I upgrade baresip to latest version?

do I need to deinstall the old?

Thank you

**Comment by alfredh** [comment]
hi,

you need to build libre and librem, and then build baresip:

https://github.com/baresip/baresip#building

it is a good idea to uninstall the old version first.

**Comment by alfredh** [comment]
it is probably better for you to use the mailing list to ask questions

please try to build latest version, and if the problem persist, then open a new Issue.
