### ISSUE TITLE
Fail sending DTMF through UDP interface (module cons.so)

### ISSUE THREAD

**Issue by dannymarosi** [baresip/baresip#1329]
Observation:
When using (module stdio.so) sending DTMF works fine.
When using (module cons.so) key release KEYCODE_REL is not inserted between DTMF keys.

Solution:
Add second call to ui_input_key() with KEYCODE_REL in cons.c udp_recv().
  ![UDP DTMF solution](https://user-images.githubusercontent.com/62627034/113786274-aaafde00-96ed-11eb-9ec6-a8b3f8860f3c.png)

**Comment by alfredh** [comment]
many thanks for reporting

your fix will most likely work, but there should be a short delay before sending release.

see stdio module for similar solution:

https://github.com/baresip/baresip/blob/master/modules/stdio/stdio.c#L70

**Comment by alfredh** [comment]
hi @dannymarosi 

a couple of observations:

1. should we consider to rename the cons module to `netcons.so` (Network Console) ?

2. would you like to help with maintaining this module:
https://github.com/baresip/baresip/wiki/Modules


Alfred

**Comment by alfredh** [comment]
here is a patch adding the async timer:

```diff
diff --git a/modules/cons/cons.c b/modules/cons/cons.c
index 138619b..106f9b2 100644
--- a/modules/cons/cons.c
+++ b/modules/cons/cons.c
@@ -33,11 +33,16 @@
 
 enum {CONS_PORT = 5555};
 
+enum {
+	RELEASE_VAL = 250  /**< Key release value in [ms] */
+};
+
 struct ui_st {
 	struct udp_sock *us;
 	struct tcp_sock *ts;
 	struct tcp_conn *tc;
 	struct sa udp_peer;
+	struct tmr tmr;
 };
 
 
@@ -50,6 +55,16 @@ static int print_handler(const char *p, size_t size, void *arg)
 }
 
 
+static void timeout(void *arg)
+{
+	struct ui_st *st = arg;
+	(void)st;
+
+	/* Emulate key-release */
+	ui_input_key(baresip_uis(), KEYCODE_REL, NULL);
+}
+
+
 static void udp_recv(const struct sa *src, struct mbuf *mb, void *arg)
 {
 	struct ui_st *st = arg;
@@ -75,6 +90,8 @@ static void udp_recv(const struct sa *src, struct mbuf *mb, void *arg)
 		(void)udp_send(st->us, src, mbr);
 	}
 
+	tmr_start(&st->tmr, RELEASE_VAL, timeout, st);
+
 	mem_deref(mbr);
 }
 
@@ -83,6 +100,8 @@ static void cons_destructor(void *arg)
 {
 	struct ui_st *st = arg;
 
+	tmr_cancel(&st->tmr);
+
 	mem_deref(st->us);
 	mem_deref(st->tc);
 	mem_deref(st->ts);
@@ -118,6 +137,8 @@ static void tcp_recv_handler(struct mbuf *mb, void *arg)
 
 		ui_input_key(baresip_uis(), ch, &pf);
 	}
+
+	tmr_start(&st->tmr, RELEASE_VAL, timeout, st);
 }
 
 
```

**Comment by alfredh** [comment]
I added the fix to master.

could you please test it ?

**Comment by dannymarosi** [comment]
@alfredh 
I will test it tomorrow.
Currently master fail compilation:

`pi@raspberrypi:~/baresip $ make
  CC [M]  build-arm6/modules/vumeter/vumeter.o
modules/vumeter/vumeter.c: In function ‘audio_print_vu’:
modules/vumeter/vumeter.c:74:17: error: ‘AULEVEL_MIN’ undeclared (first use in this function); did you mean ‘LEVEL_WARN’?
  x = (*level + -AULEVEL_MIN) / -AULEVEL_MIN;
                 ^~~~~~~~~~~
                 LEVEL_WARN
modules/vumeter/vumeter.c:74:17: note: each undeclared identifier is reported only once for each function it appears in
modules/vumeter/vumeter.c: In function ‘encode’:
modules/vumeter/vumeter.c:188:16: warning: implicit declaration of function ‘aulevel_calc_dbov’ [-Wimplicit-function-declaration]
  vu->avg_rec = aulevel_calc_dbov(af->fmt, af->sampv, af->sampc);
                ^~~~~~~~~~~~~~~~~
modules/vumeter/vumeter.c:188:16: warning: nested extern declaration of ‘aulevel_calc_dbov’ [-Wnested-externs]
make: *** [mk/mod.mk:49: build-arm6/modules/vumeter/vumeter.o] Error 1
pi@raspberrypi:~/baresip $`

**Comment by sreimers** [comment]
You need https://github.com/baresip/rem v1.0.0 or HEAD

**Comment by dannymarosi** [comment]
@alfredh 
Your modification in cons.c works for sending individual DTMF digits one at a time.
When you send a string of DTMF digit you will get only one DTMF end.
audio: send DTMF digit: '1'
audio: send DTMF digit: '2'
audio: send DTMF digit: '3'
audio: send DTMF digit: '4'
audio: send DTMF digit: '5'
audio: send DTMF digit: '6'
audio: send DTMF digit: '7'
audio: send DTMF digit: '8'
audio: send DTMF digit: '9'
audio: send DTMF digit: '0'
audio: send DTMF digit end: '0'

For sending DTMF string: one must insert an end after each digit in the loop.
audio: send DTMF digit: '1'
audio: send DTMF digit end: '1'
audio: send DTMF digit: '2'
audio: send DTMF digit end: '2'
audio: send DTMF digit: '3'
audio: send DTMF digit end: '3'
audio: send DTMF digit: '4'
audio: send DTMF digit end: '4'
audio: send DTMF digit: '5'
audio: send DTMF digit end: '5'
audio: send DTMF digit: '6'
audio: send DTMF digit end: '6'
audio: send DTMF digit: '7'
audio: send DTMF digit end: '7'
audio: send DTMF digit: '8'
audio: send DTMF digit end: '8'
audio: send DTMF digit: '9'
audio: send DTMF digit end: '9'
audio: send DTMF digit: '0'
audio: send DTMF digit end: '0'

We have a working solution for now
Thanks for the Help.
