### ISSUE TITLE
New Release Version

### ISSUE THREAD

**Issue by mbattista** [baresip/baresip#1333]
There were ~350 commits since the release of 1.0.0.

Are there any plans to release 1.0.1 / 1.1.0 any time soon?
The Milestone given in the project shows no that all the flagged issues with the milestone are completed.

**Comment by alfredh** [comment]
we should make a new release, yes (version 1.1.0)

we need to test all modules on all supported platforms. can you help with testing ?

is there anyone who can volunteer to co-ordinate the release ?

**Comment by sreimers** [comment]
> is there anyone who can volunteer to co-ordinate the release ?

I just prepared [rem](https://github.com/baresip/rem) release v1.0.0 and will release [re](https://github.com/baresip/re) v2.0.0 (breaking api changes) with some release notes later today. After this i can prepare release notes for baresip.

**Comment by robert-scheck** [comment]
> I just prepared [rem](https://github.com/baresip/rem) release v1.0.0 and will release [re](https://github.com/baresip/re) v2.0.0 (breaking api changes) with some release notes later today. After this i can prepare release notes for baresip.

Given re proper soname versioning (thanks again!), is there a chance for the same in rem?

**Comment by sreimers** [comment]
> is there a chance for the same in rem?
Done, would be part of rem v1.0.1 or v1.1.0

> And for some reason, I can't file issues

Fixed

**Comment by 004930** [comment]
Platform: Ubuntu flavor version: 20.04 LTS (debian bullseye/sid based)

Just did:

make clean ; git pull https://github.com/baresip/re.git master ; make && sudo make install
make clean ; git pull https://github.com/baresip/rem.git master ; make && sudo make install
make clean ; git pull https://github.com/baresip/baresip.git master ; make && sudo make install

Compiled without errors. But when starting baresip:

baresip: error while loading shared libraries: libre.so.0: cannot open shared object file: No such file or directory

Also tried without succes:
make clean; git pull https://github.com/creytiv/rem.git master ; make && sudo make install

Still same error when starting baresip.

**Comment by sreimers** [comment]
Can you try to run a `ldconfig`

**Comment by robert-scheck** [comment]
> baresip: error while loading shared libraries: libre.so.0: cannot open shared object file: No such file or directory

I am sorry, but this must be a very local build mistake, e.g. by building for `/usr/local` rather `/usr`, a forgotten `ldconfig` call or so. Try to use `ldd /usr/bin/baresip` and `find / -name "libre.so*"` as starting point. I would assume `libre.so.0` is not on `$LD_LIBRARY_PATH` and hence the error.

Personal testing result: HEAD of re, rem and baresip build on RHEL/CentOS 7 and 8 and seem to work for basic G711 and G722 usage together with the GTK module.

**Comment by mbattista** [comment]
```
DISTRIB_ID=ManjaroLinux
DISTRIB_RELEASE=21.0.1
DISTRIB_CODENAME=Ornara
DISTRIB_DESCRIPTION="Manjaro Linux"
```

Building `re`, `rem`, and `baresip` from HEAD without errors.
Running baresip results in error 
```
baresip: error while loading shared libraries: libre.so.0: cannot open shared object file: No such file or directory
```

but running 
```
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib && baresip
```

runs without errors. GTK, G722 modules working without problems!

**Comment by 004930** [comment]
> Can you try to run `ldconfig`

Now baresip starts normal (although the command from @mbattista (export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib && baresip) worked as well.

**Comment by mbattista** [comment]
> Edit: After some tests, dialing with GTK seems broken. I will look into it.

with #1339 GTK would work again.

It is now compatible to the api changes introduced in commit https://github.com/baresip/baresip/commit/3c312583a89ecaa5fdc361f8264a635c565344c8

**Comment by alfredh** [comment]
is there anyone who wants to make the release ?

it basically means creating a new issue using this template:

https://github.com/baresip/baresip/issues/1074

before the release, we have to test:

1. All supported platforms
2. Available SIP endpoints and gateways
3. All modules

**Comment by alfredh** [comment]
I have done some testing now

1. compile:
[ok] - tlsissuer command
[ok] - test make RELEASE=yes
[ok] - test make HAVE_PTHREAD=
[ok] - valgrind
[ok] - make dox
[  ] - test make clang
[  ] - test coverity: 5 bugs left



2. platforms:
[ok] - Debian 9
[ok] - Debian 10
[ok] - OSX 10.14
[ok] - Ubuntu 20.04


what is missing now is to do some interop testing with SIP endpoints ..

**Comment by alfredh** [comment]
we are getting closer to the release ...

I have done some more testing on these platforms:

```
Platform:      OpenSSL:		Compiler:	FFmpeg:
--------       -------		--------	------

Debian 9      openssl 1.1.0l	gcc 6.3.0	ffmpeg 3.2.15
Debian 10     openssl 1.1.1d	gcc 8.3.0	ffmpeg 4.1.6
FreeBSD 13    openssl 1.1.1k	gcc 10.2.0	ffmpeg 4.3.2
OSX 10.14     openssl 1.1.1k	clang 10	ffmpeg 4.4.0
```

any other platforms that we should test ?

**Comment by alfredh** [comment]
I have set a tentative release date of 24. April 2021

here are some more results from endpoint testing:

```
Endpoints:

[ok] Chrome Version 90.0.4430.72 (Official Build) (x86_64) opus,h264,ice,dtls_srtp
[ok] Firefox 87.0 (64-bit) opus,h264,ice,dtls_srtp
[ok] Linphone desktop 4.2.5 (opus,g722,g711)
[ok] Linphone ios 4.4.0 (opus,h265)
[ok] Safari 14.03
[ok] Safari ios (opus,h264)
[ok] Sems 'sip:music@iptel.org'
[ok] SylkServer-5.7.0 -- sip:3333@sip2sip.info
[ok] TANDBERG/529 (ce9.12.3.140cd8212ba) Cisco-SX10 (opus,h264)
```

I did not find any critical bugs, so I believe it should be good to go now.

**Comment by alfredh** [comment]
https://github.com/baresip/baresip/releases/tag/v1.1.0

thanks for helping out making a good release!
