### ISSUE TITLE
about raspberry omx encoding. 

### ISSUE THREAD

**Issue by jobo-zt** [baresip/baresip#1334]
Hi alfredh
    Can you reopen this question. In the latest code exists
     -> https://github.com/baresip/baresip/issues/1077

    The same questions as https://github.com/baresip/baresip/issues/965

    I can do tests

**Comment by alfredh** [comment]
please create a new issue for the problem, please include all relevant info
like config and logs etc.

**Comment by jobo-zt** [comment]
create a new issue for the problem
