### ISSUE TITLE
Module status of av1, rtcpsummary and snapshot?

### ISSUE THREAD

**Issue by robert-scheck** [baresip/baresip#1341]
As of writing, the following modules exist in the code of HEAD, but are not enabled by any defaults or mechanisms:

  * `av1`: Not mentioned in `mk/modules.mk` at all
  * `rtcpsummary`: Mentioned in `mk/modules.mk`, but not enabled by default
  * `snapshot`: Not mentioned in `mk/modules.mk` at all

So what's the status of these modules? As a downstream packager (for Fedora, RHEL/CentOS), should I build them? Or not?

**Comment by juha-h** [comment]
Robert Scheck writes:

> As of writing, the following modules exist in the code of HEAD, but
> are not enabled by any defaults or mechanisms: 
> 
>   * `av1`: Not mentioned in `mk/modules.mk` at all
>   * `rtcpsummary`: Mentioned in `mk/modules.mk`, but not enabled by default
>   * `snapshot`: Not mentioned in `mk/modules.mk` at all

> So what's the status of these modules? As a downstream packager (for Fedora, RHEL/CentOS), should I build them? Or not?

My Android app is using av1 and snapshot modules and they both seem to
work fine.  Both depend on some ffmpeg libs.

**Comment by alfredh** [comment]
the av1 module is highly experimental and should not be used in production.
for example it is using a bogus packetization protocol, this should be upgraded to:

https://aomediacodec.github.io/av1-rtp-spec/

we should also consider moving av1.so into avcodec.so, to use the libavcodec api
and better choice of AV1 encoders/decoders.

for rtcpsummary and snapshot, they should probably be enabled by default

**Comment by robert-scheck** [comment]
Thank you very much for the clarification, I've updated the PR accordingly.
