### ISSUE TITLE
swisscom.ch and t-mobile.de: "488 SDP Parameter Error In SIP Request" answer on INVITE..

### ISSUE THREAD

**Issue by exse2** [baresip/baresip#1351]
.. is fixed by removing setting of "a=tool:baresip 0.6.4" in src/call.c like this:

        --- src/call.c.original	2021-04-14 16:04:57.336202183 +0200
        +++ src/call.c	2021-04-14 16:26:54.391953940 +0200
        @@ -667,11 +667,6 @@
         	if (err)
         		goto out;
     
    -	err = sdp_session_set_lattr(call->sdp, true,
    -				    "tool", "baresip " BARESIP_VERSION);
    -	if (err)
    -		goto out;
    -
     	/* Check for incoming SDP Offer */
     	if (msg && mbuf_get_left(msg->mb))
     		got_offer = true;

As I am still unsure how to make changes here (sorry), can a maintainer please migrate this?

**Comment by juha-h** [comment]
I too have noticed than some telcos use SIP/PSTN gateways that don't accept SDP that has tool attribute.  I therefore commented it out like in above in my libbaresip-android.

The attribute is fully conformant to standards, so there is nothing wrong in baresip when it adds it.  Perhaps the attribute could be made configurable to satisfy broken SIP devices.

**Comment by exse2** [comment]
"User-Agent: baresip v0.6.4 (x86_64/linux)" is in the INVITE anyways and it still works, so I'm opting for removing "a=tool:baresip" in the default installation. The real world is not perfect, the customer doesn't wrestle with telephony providers, he just throws baresip away then. Engineers won't win the the wrestle either (Proof: <https://lists.kamailio.org/pipermail/sr-users/2020-June/109390.html>). If you want to have an option it should be one to toggle between  "Standards Conform" and "Reality Conform".

**Comment by cspiel1** [comment]
We have also a commit that removes this. This solves an issue we have with German telecom. These days we are about to initiate another test with this SIP gateway that includes this SDP attribute again.

But now, since others have also this problem. Maybe we should make it configurable anyway?

**Comment by juha-h** [comment]
Christian Spielberger writes:

> But now, since others have also this problem. Maybe we should make it
> configurable anyway?

I would support that in order to avoid need for private patches.

**Comment by alfredh** [comment]
I think it is better to just remove the a=tool attribute. Can you please provide a PR for that ?

adding a new config option would just make the configuration more complex
(more combinations to test).

@exse2 can you also provide more details about your SIP gateway provider/server
so we can include it in the release documentation?

**Comment by cspiel1** [comment]
Ok, I'll make the PR.

**Comment by alfredh** [comment]
fixed in cead0e7608c39b7f47185a143c71b3449f723c30

thanks @cspiel1 !

**Comment by exse2** [comment]
> @exse2 can you also provide more details about your SIP gateway provider/server
> so we can include it in the release documentation?

Registrar swisscom.ch, used with Outbound Proxy fs1.ims.swisscom.ch.

**Comment by alfredh** [comment]
many thanks!

can you also share which audio codecs are working ?

**Comment by exse2** [comment]
> can you also share which audio codecs are working ?

INVITE from baresip was

        ...
        m=audio 16070 RTP/AVP 0 8 101
        a=rtpmap:0 PCMU/8000
        a=rtpmap:8 PCMA/8000
        a=rtpmap:101 telephone-event/8000
        a=fmtp:101 0-15
        ...

SIP/2.0 180 Ringing from swisscom was

        ...
        t=0 0
        m=audio 49686 RTP/AVP 8 101
        b=RR:0
        b=RS:0
        a=sendrecv
        a=rtpmap:8 PCMA/8000
        a=rtpmap:101 telephone-event/8000
        a=silenceSupp:off - - - -
        a=fmtp:101 0-15
        a=ptime:20

So it supports PCMA at least. I did hear OK quality - worse than ISDN quality this codec should provide - This is a global phenomen I observed - but those telephony providers cut costs wherever they can :(
