### ISSUE TITLE
1>D:\baresip\src\audio.c(1669,36): error C2065: “JBUF_ADAPTIVE”: undeclare identifier

### ISSUE THREAD

**Issue by bipbopbee** [baresip/baresip#1369]
VS2019 have errors
1>D:\baresip\src\audio.c(1669,36): error C2065: “JBUF_ADAPTIVE”: undeclare identifier

**Comment by cspiel1** [comment]
Use rem from github/baresip!

**Comment by alfredh** [comment]
please use latest version of libre and librem:

https://github.com/baresip/baresip#related-projects

closing as not-a-bug
