### ISSUE TITLE
Baresip tools here or in own repository?

### ISSUE THREAD

**Issue by robert-scheck** [baresip/baresip#1370]
Based on a kind request, I've written last night a simple converter in Python from the FRITZ!Box XML phone book to Baresip contacts format. As I could imagine it's helpful for others as well, I would like to contribute the script closely to the baresip project.

The question is: Would a pull request for a `tools` subdirectory inside of https://github.com/baresip/baresip be accepted or would something like this better be suited in an own repository such as e.g. https://github.com/baresip/baresip-tools? Given my converter is really just a single (script) file, I don't want to dedicate an exclusive repository for it. But I would assume that once e.g. a "tools" subdirectory or repository exists in general, other tiny script contributions appear sooner or later, too. If the decision is a separate repository, I'm indeed willing to take care of it.

**Comment by alfredh** [comment]
both options are fine with me

you can probably start in the baresip repo. If we get many tools there, we can always
move them to a separate project later.
