### ISSUE TITLE
could not find UA

### ISSUE THREAD

**Issue by juha-h** [baresip/baresip#1375]
I have one account in accounts file with regint=0.  When I start baresip and try to make call, I get `could not find UA` message.  Below is the whole output.
```
baresip -f ~/.baresip.092345671/
baresip v1.1.0 Copyright (C) 2010 - 2021 Alfred E. Heggestad et al.
Local network address:  IPv4=wlp2s0|192.168.43.160  IPv6=wlp2s0|2001:14bb:cb:277d:f3e2:45af:d522:99f5
aucodec: opus/48000/2
aucodec: PCMU/8000/1
aucodec: PCMA/8000/1
ausrc: alsa
auplay: alsa
medianat: stun
medianat: ice
mediaenc: srtp
mediaenc: srtp-mand
mediaenc: srtp-mandf
mediaenc: dtls_srtp
+35892345671@buster.tutpro.com: Using sipnat: 'outbound'
Populated 1 account
Populated 0 contacts
Subscribing to 0 contacts
Populated 3 audio codecs
Populated 0 audio filters
Populated 0 video codecs
Populated 0 video filters
baresip is ready.
>                     +35892345672
could not find UA for +35892345672
```

**Comment by cspiel1** [comment]
Don't you need a SIP registrar for dialing such a number?

**Comment by cspiel1** [comment]
I don't know if it makes sense, but if you try:
```
/dial q@+35892345672
```
The UA is selected. Anyway, the call fails after that like we would expect.
```
sip:q@+35892345672: session closed: Destination address required
```

**Comment by juha-h** [comment]
I don't need registrar because account's `;regint=0`.  There is outbound proxy defined and nothing else is needed.  If there is only one account, dialing with just userpart of URI should assume the domain of the only account.   Otherwise baresip is too difficult to use.

**Comment by alfredh** [comment]
I have a proposal;

if the number of user-agents is exactly 1 (one), there can be no ambiguity and that one should be used.

this can be done by checking that list_count(uag.ual) == 1 or this code:

```c
	if (!uag.ual.head)
		return NULL;

	/* check for single UA */
	if (uag.ual.head == uag.ual.tail)
		return list_ledata(uag.ual.head);
```

**Comment by cspiel1** [comment]
Would be great if you post your account line here. But I guess it contains `;regint=0;outbound=...` which I did not expect to be a useful configuration.

The problem here seems to be that this check is too restrictive:
```C
			if (!uri_only_user(uri) ||
					!sa_set(&sa, &uri->host, 0)) {
				/* Remember local account.
				 * But we prefer registered UA. */
				if (!ret)
					ret = ua;
			}
```

It's best to remove this `if` to support this and any other case we don't think about now. That means that a local account will always be the fallback. The PR is coming soon.

**Comment by juha-h** [comment]
Christian Spielberger writes:

> Would be great if you post your account line here. But I guess it
> contains `;regint=0;outbound=...` which I did not expect to be a
> useful configuration.

My account line is this:
```
***@***.***>;outbound="sip:192.26.134.11:5060;transport=
tcp";ptime=20;audio_codecs=OPUS/48000/2,PCMU,PCMA;regint=0;pubint=0;regq=0.5;sip
nat=outbound;answermode=manual
```
It is useful and works fine for both making and receiving calls without
registrar.

**Comment by juha-h** [comment]
Github censored the account line.  Trying again from web page:
```
<sip:+35892345671@buster.tutpro.com>;outbound="sip:192.26.134.11:5060;transport=
tcp";ptime=20;audio_codecs=OPUS/48000/2,PCMU,PCMA;regint=0;pubint=0;regq=0.5;sip
nat=outbound;answermode=manual
```

**Comment by cspiel1** [comment]
Ah. Yes, this should work now. Please could you try the branch:
https://github.com/cspiel1/baresip/tree/uag_find_requri_local_account_fallback

**Comment by cspiel1** [comment]
I see. Opened a PR. Please could you try it?  https://github.com/baresip/baresip/pull/1384

**Comment by juha-h** [comment]
I gave PR: #1384 a try and it worked fine.
