### ISSUE TITLE
H265 issue

### ISSUE THREAD

**Issue by juha-h** [baresip/baresip#1387]
After upgrading to latest baresip, I noticed that H265 video does not _always_ show properly.  When it happens, there is lots of gray in the received video and I can only vaguely see the other party.

I first noticed this when I upgraded my Android app, but then I tested H265 calls between two Debian hosts and the result was the same.  This does not happen all the time, but sometimes during the call, received video turns to gray and a few seconds later returns to normal and then turns gray again.

I'm not even sure if this started to happen after upgrade to latest baresip.  I just have not seen it before.  All other video codecs work fine.

**Comment by juha-h** [comment]
After more testing, I noticed that gray received video seems more likely if there is no movement in the sent video.  After I wave my hand at the camera, received video often turns to normal.

**Comment by alfredh** [comment]
do you have some more details like logs or screenshots ?

I have tested h265 with linphone ios 4.4.0 and it works (both directions).

Video-loop with h265 also works (OSX 10.14):

```
$ ./baresip -e "/vidloop h265"
```

perhaps you can try the same ?

**Comment by juha-h** [comment]
I was able to reproduce the issue using vidloop.  I placed one screenshot from Android to [https://box.tutpro.com/tmp/shot.png](url). The version of ffmpeg I use in Android is 4.4 and libx265 is 3.4.  As this is too vague issue, I'll close it.
