### ISSUE TITLE
FreeBSD 13: no sip_cafile/sip_capath defined and sip_verify_server is enabled, sip tls connections maybe won't work

### ISSUE THREAD

**Issue by alfredh** [baresip/baresip#1388]
I tested baresip on FreeBSD 13 and get a warning from the default config:

```
baresip v1.1.0 Copyright (C) 2010 - 2021 Alfred E. Heggestad et al.
config: creating config template /tmp/bare2/config
/usr/local/lib/baresip/modules: detected 44 modules
[31mconfig: no sip_cafile/sip_capath defined and sip_verify_server is enabled, sip tls connections maybe won't work
[;mLocal network address:  IPv4=em0|10.0.2.15 
aucodec: PCMU/8000/1
aucodec: PCMA/8000/1
ausrc: oss
... etc ...
```

the generated config contains:

```
# SIP
#sip_listen		0.0.0.0:5060
#sip_certificate	cert.pem
#sip_cafile		/etc/ssl/certs/ca-certificates.crt
#sip_trans_def		udp
sip_verify_server	yes
```

in general the default config should be working, and it should not print any warnings

**Comment by juha-h** [comment]
I suggest that in default config sip_verify_server has value no.  Otherwise sip_cafile needs to be defined and its path may not be the same in all platforms.

**Comment by sreimers** [comment]
On FreeBSD we can maybe assume that `/etc/ssl/cert.pem` exists (like the DARWIN rule). But for Windows there is no default path as far as I know.

Maybe we should set `sip_verify_server = yes` only if we detect a working default for the `sip_cafile` value and we should check if the ca file really exists.

**Comment by alfredh** [comment]
there was also a compile error in re in tmr.c, due to missing `CLOCK_MONOTONIC_RAW`
it should be easy to fix just use `CLOCK_MONOTONIC` instead

**Comment by sreimers** [comment]
> it should be easy to fix just use `CLOCK_MONOTONIC` instead
Can you try:
https://github.com/baresip/re/pull/97/files

**Comment by alfredh** [comment]
thanks, yeah that works on FreeBSD 13. also get this warning:

```
src/tmr/tmr.c: In function 'tmr_jiffies':
src/tmr/tmr.c:181:11: warning: implicit declaration of function 'gettimeofday' [-Wimplicit-function-declaration]
  181 |  if (0 != gettimeofday(&now, NULL)) {
      |           ^~~~~~~~~~~~
src/tmr/tmr.c:181:11: warning: nested extern declaration of 'gettimeofday' [-Wnested-externs]
```

**Comment by alfredh** [comment]
on freebsd the path to the ca cert is: /etc/ssl/cert.pem

I changed this in the config:

sip_cafile  /etc/ssl/cert.pem
sip_verify_server yes

and then registering via SIP/TLS works.

**Comment by sreimers** [comment]
> ```
> src/tmr/tmr.c:181:11: warning: nested extern declaration of 'gettimeofday' [-Wnested-externs]
> ```

Fixed by https://github.com/baresip/re/pull/97/commits/ba11ee928f3450c2f3314acf2ad63484f6a1aab5

**Comment by alfredh** [comment]
if there is no local CA cert, then the client cannot verify the TLS server cert.

so I think the logic should be something like this:

1. if cafile is set, enable `sip_verify_server yes`
2. if there is no cafile, set `sip_verify_server no`

the default config should be a simple working config.
users are free to change it after install.

anyone who wants to prepare a PR for fixing this logic ?

**Comment by cHuberCoffee** [comment]
#1392 should solve the problem with the active sip_verify_server option.

**Comment by alfredh** [comment]
thanks!
