### ISSUE TITLE
account's sipnat value is not checked

### ISSUE THREAD

**Issue by juha-h** [baresip/baresip#1400]
The only supported account `sipnat` value is `outbound`, but any value is accepted.  This can be confusing, for example,
```
using stunserver: 'stun:stun.l.google.com:19302'
test@test.tutpro.com: Using sipnat: 'stun'
test@test.tutpro.com: Using medianat 'stun'
```
I don't know what baresip policy is regarding bogus values, i.e., are only valid values looked for and if none is found, then it is the same as nothing was given.

**Comment by alfredh** [comment]
if the sipnat value is set, it should be checked against "outbound".

for any other value, it should print a warning

**Comment by juha-h** [comment]
Alfred E. Heggestad writes:

> if the sipnat value is set, it should be checked against "outbound".
> 
> for any other value, it should print a warning

OK, I'll try to a create PR.

**Comment by juha-h** [comment]
While looking into this, I noticed that account.c `sip_params_decode()` does not use `account_set_*()` functions, but sets the attribute values directly, e.g.:
```
	err |= param_dstr(&acc->sipnat, &aor->params, "sipnat");
```
It means that checking validity of params would need to be checked twice.  Once in `sip_params_decode()` and another time in account_set_*() functions.

How about if I use `account_set_sipnat()` in `sip_params_decode()`?

**Comment by juha-h** [comment]
I created PR https://github.com/baresip/baresip/pull/1401, but its ccheck failed without telling why.
