### ISSUE TITLE
A call in state CALL_STATE_OUTGOING can not be canceled.

### ISSUE THREAD

**Issue by cspiel1** [baresip/baresip#1416]
A call is in CALL_STATE_OUTGOING as long as the remote did not answer with 180 Ringing, 183 Session Progress, ...

Reason: The call-id is set after CALL_STATE_OUTGOING is sent.

Is is set in call.c function `send_invite()` which may also be called later in `mnat_handler()`.

Problems:
- The command "hangup" without specified call-id does not work.
- Also the CALL_STATE_OUTGOING sent to an external application via ctrl_tcp, ctrl_dbus, ... will not contain a call-id.

A solution for the hangup could be in:
```C
	case UA_EVENT_CALL_LOCAL_SDP:
		if (call_state(call) == CALL_STATE_OUTGOING)
			menu_selcall(call);
		break;
```

This is not all. It needs also to move
```
ua_event(call->ua, UA_EVENT_CALL_LOCAL_SDP, call, "offer")
```
after the `sipsess_connect()` call in function `send_invite()`.

Will make a PR later. But this solution is not optimal. Better would be if the call gets the call-id earlier.

**Comment by juha-h** [comment]
Do these proposed changes only affect menu module or also core?  If also
core, are they fully backwards compatible so that nothing needs to be
changed in current applications?

**Comment by cspiel1** [comment]
`send_invite()` is in src/call.c. The UA_EVENT_CALL_LOCAL_SDP will be sent after SIP session and SIP dialog was allocated instead of before. I don't think that this breaks something.

**Comment by cspiel1** [comment]
Let's discuss in the PR.
