### ISSUE TITLE
Can't invoke the gtk interface

### ISSUE THREAD

**Issue by znoteer** [baresip/baresip#1428]
running "baresip -m gtk" returns the errors 

```
dl: mod: ./gtk (./gtk: cannot open shared object file: No such file or directory)
module gtk: No such file or directory
could not pre-load module 'gtk' (No such file or directory)

```
I've also tried to specify the full path to the gtk.so file.  I get the same error.

How do I get the gtk gui?

Thanks

**Comment by alfredh** [comment]
can you try `-m gtk.so` ?

**Comment by znoteer** [comment]
Hi,

On Thu, May 06, 2021 at 02:14:51AM -0700, Alfred E. Heggestad wrote:
> can you try `-m gtk.so` ?
> 

I already tried with "-m gtk.so".  It gives the same error.

-- 
Znoteer
***@***.***

**Comment by mbattista** [comment]
I could change the error with `-m ../../usr/local/lib/baresip/modules/gtk.so` to `gtk: message_init failed (Invalid argument)`
It seems gtk needs to be loaded after baresip is started, and cannot be pre-loaded via the `-m` option.

Why not uncomment the gtk module in the `~/.baresip/config` file?
Search for the Line with `#module_app              gtk.so` and remove the `#`.

**Comment by znoteer** [comment]
Hello,

On Thu, May 06, 2021 at 03:59:07PM -0700, mbattista wrote:

[snip]
> 
> Why not uncomment the gtk module in the `~/.baresip/config` file?
> Search for the Line with `#module_app              gtk.so` and remove the `#`.
> 

I didn't know that was possible being new to baresip. It worked.  Thank you!

-- 
Znoteer
***@***.***

**Comment by mbattista** [comment]
No problem.

The wiki lists also some information and tipps about baresip and its usage, e.g. https://github.com/baresip/baresip/wiki/Configuration

Perhaps a link into the wiki within the README could help new users?

**Comment by alfredh** [comment]
thanks, please make a PR with the suggested link :)

closing.
