### ISSUE TITLE
wrong account selected

### ISSUE THREAD

**Issue by juha-h** [baresip/baresip#1433]
I just noticed that my baresip Android app has got broken (using latest master).  I have four accounts and only one of them (foo@tutpro.com)  is registered.  When call comes in from test@tutpro.com to foo@tutpro.com, account foo@lab.tutpro.com gets selected:
```
05-05 21:33:17.381  7259  7373 D Baresip Lib: foo@tutpro.com: (prio 0) {1/TLS/v4} 200 OK (OpenSIPg SIP Proxy (5.4.4-13 (x86_64/linux))) [1 binding]
05-05 21:33:17.381  7259  7372 D Baresip Lib: ua event (REGISTER_OK) 200 OK
...
05-05 21:34:11.371  7259  7372 D Baresip Lib: ua event (CALL_INCOMING) sip:test@tutpro.com
05-05 21:34:11.372  7259  7373 D Baresip Lib: ua: sipsess connect via TLS 192.26.111.38:8003 --> 10.145.233.30:47057
05-05 21:34:11.372  7259  7373 D Baresip Lib: foo@lab.tutpro.com: selected
```
Why is an account that did not register the contact used in the Request-URI of the INVITE get selected? I don't remember changing anything in the app that could have caused this issue.

**Comment by juha-h** [comment]
Here is another example, where test@test.tutpro.com is calling foo@test.tutpro.com and foo@lab.tutpro.com gets selected.
```
05-05 22:03:24.111  8351  8380 D Baresip Lib: TCP 192.168.43.50:37418 -> 192.168.43.160:5060
05-05 22:03:24.112  8351  8380 D Baresip Lib: REGISTER sip:test.tutpro.com SIP/2.0
05-05 22:03:24.112  8351  8380 D Baresip Lib: Via: SIP/2.0/TCP 10.145.233.30:60376;branch=z9hG4bKc4845faa117db836;rport
05-05 22:03:24.112  8351  8380 D Baresip Lib: Contact: <sip:foo-0x77296452d0@10.145.233.30:60376;transport=tcp>;expires=3600;+sip.instance="<urn:uuid:314b31b1-d978-5ef1-4135
05-05 22:03:24.112  8351  8380 D Baresip Lib: -f3305e7fe7b3>";q=0.5;reg-id=1
05-05 22:03:24.114  8351  8380 D Baresip Lib: From: "Foo" <sip:foo@test.tutpro.com>;tag=e4dd832f458c0efd
...
05-05 22:04:02.617  8351  8380 D Baresip Lib: INVITE sip:foo-0x77296452d0@10.145.233.30:60376;transport=tcp SIP/2.0
05-05 22:04:02.617  8351  8380 D Baresip Lib: From: "Test Account <sip:+35892345671@test.tutpro.com>;tag=08069c8f2449c23a
...
5-05 22:04:02.617  8351  8380 D Baresip Lib: ua: sipsess connect via TCP 192.168.43.160:5060 --> 192.168.43.50:37418
05-05 22:04:02.626  8351  8380 D Baresip Lib: foo@lab.tutpro.com: selected
```
The selected account foo@lab.tutpro.com exists, but has not registered itself.  Request-URI of INVITE matches that of foo@test.tutpro.com.

**Comment by juha-h** [comment]
I built my baresip Android app from baresip master before this commit (ua,uag: split ua.c and uag.c.):

https://github.com/baresip/baresip/commit/92fee52809b6661d5c3a4bbf48f5f140c974e694

and incoming calls worked fine.  So something got broken by the commit.

**Comment by cspiel1** [comment]
The UA is selected by function `uag_find_msg()`. For an incoming call from a SIP proxy `cuser` should be set.
```
cuser = &msg->uri.user;
```
and it should match `ua_cuser(ua)` of the correct account.

Expected log output would be:
```
foo@tutpro.com: selected for foo-0x........
```
from `ua_printf()` in `uag.c:834`.

In your case the `uaf` is selected, which is the fallback for `regint=0` accounts.

**Comment by cspiel1** [comment]
> I built my baresip Android app from baresip master before this commit (ua,uag: split ua.c and uag.c.):
> 
> [92fee52](https://github.com/baresip/baresip/commit/92fee52809b6661d5c3a4bbf48f5f140c974e694)
> 
> and incoming calls worked fine. So something got broken by the commit.

Ok, I will check this. Maybe cuser is not set.

**Comment by cspiel1** [comment]
Please could you paste the INVITE header from wireshark?

**Comment by juha-h** [comment]
As you can see from the sip trace above, foo@test.tutpro.com registered with contact `<sip:foo-0x77296452d0@10.145.233.30:60376;transport=tcp>` and the invite had the same r-uri userpart `INVITE sip:foo-0x77296452d0@10.145.233.30:60376;transport=tcp`.  So it should match.  Do you still need the pcap, because I already provided baresip trace?

**Comment by cspiel1** [comment]
Your right. The `cuser` is put into the Contact header of the REGISTER. In the INVITE it has to match.

Could you please debug why uag.c line 833 does not find the match?

**Comment by cspiel1** [comment]
I found a difference that could be relevant:
```
<                if (0 == pl_strcasecmp(cuser, ua->cuser)) {
---
>                if (0 == pl_strcasecmp(cuser, ua_cuser(ua))) {
```

So maybe line 833 should be:
```
		if (0 == pl_strcasecmp(cuser, ua_local_cuser(ua))) {
```

Please could you try this?

**Comment by cspiel1** [comment]
When only looking to the diff I am 100% sure that the lines 788 and 833 have to use function `ua_local_cuser()`. I will make a PR now.

Thanks for reporting this issue!

**Comment by juha-h** [comment]
I added info calls to uag.c:
```
	info("looking for cuser %r\n", cuser);
	cuser = &msg->uri.user;
	for (le = uag.ual.head; le; le = le->next) {
		struct ua *ua = le->data;

		info("cuser/ua_cuser(ua) %r/%r\n", cuser, ua_cuser(ua));
		if (0 == pl_strcasecmp(cuser, ua_cuser(ua))) {
			ua_printf(ua, "selected for %r\n", cuser);
			return ua;
		}
	}
```
and only got:
```
05-06 08:50:56.136 17367 17439 D Baresip Lib: looking for cuser 
```
So if format %r was correct, cuser is empty.

**Comment by cspiel1** [comment]
The first info is one line to early.

Is your `uag.ual` empty?

**Comment by cspiel1** [comment]
Here is the PR: https://github.com/baresip/baresip/pull/1434

Please try again with this branch!
