### ISSUE TITLE
pulse: device issue for incoming calls with echo plugin enabled

### ISSUE THREAD

**Issue by spellingmistake** [baresip/baresip#1439]
I'm running baresip version v1.0.0 (1ef6826) with rem v.0.6.0 (8d572e6) and re v1.1.0 (0f17505).
audio_player, audio_source and and audio_alert all use 'pulse' as mod without a dev being set. I can call people without any problems. However when I receive calls pulse says:

`pulse: could not connect to server (No such entity`
`audio: start_player failed (.A-340514e0): No such device`

I've narrowed this down to the device. Outgoing calls have no device name set, whereas incoming ones, do. As a result the calls to _pa_simple_new_ cause the above error. I was not able to figure out the reason of this behavior. When calling _pa_simple_new_ with argument _dev_ being NULL, the issue disappears. But this leaves me unable to configure the devices in my baresip config file.

I've attached my audio debug with IP addresses and sip info being redacted.

If you need any more information on the issue, let me know. I'll be pleased to provide them.

[audio_debug.txt](https://github.com/baresip/baresip/files/6443562/audio_debug.txt)

**Comment by spellingmistake** [comment]
Something else is striking, but may be completely unrelated. If I get called and hang up, the call is not ended on the other side, whereas if I initiate the call the hangup works fine.

**Comment by spellingmistake** [comment]
After 571 times calling myself (I'm probably on the list of suspicious persons now), I figured out what the issue is. The echo plugin was enabled and kept changing the rx/tx devices such that pulse wouldn't work with them anymore. If that is default hehavior, consider this bug obsolete.

**Comment by alfredh** [comment]
it would be nice if you can upgrade to master HEAD and re-test.

can you please check the device name in the log:

https://github.com/baresip/baresip/blob/master/modules/pulse/recorder.c#L142

can you check that this is the same for both outgoing+incoming calls ?

**Comment by spellingmistake** [comment]
Alfred, thanks for the reply, I updated re, rem and baresip to their corresponding master version (b66d00e, fa585e4, ef8233a6). Same behavior as before:
outgoing: pulse: opening recorder (8000 Hz, 1 channels, device '')
all fine
incoming:
pulse: opening recorder (8000 Hz, 1 channels, device 'A-e9c42ae0')
pulse: could not connect to server (No such entity)
audio: start_source failed (.A-e9c42ae0): No such device
echo: session destroyed
call: rejecting incoming call from sip:REDACTED@fritz.box (500 Server Error)

I remember to have updated the subject of the bug to something mentioning the echo plugin. Without the echo plugin, I can call out and accept calls (almost) without any problems. With the echo plugin the device name gets mangle in  https://github.com/baresip/baresip/blob/master/modules/echo/echo.c#L79
Maybe this info got lost along the lines.

**Comment by sreimers** [comment]
What is your use case for the Echo module? It is designed for `aubridge` and virtual device names. It is not used for echo cancellation (it produces echo ;-)), but primarily for test cases.

**Comment by spellingmistake** [comment]
There's no use case. I'm scratching my head as to why this module was enabled in the first place. The code in https://github.com/baresip/baresip/blob/master/src/config.c#L976 suggests that the module was never enabled by default. However, two independent installations of mine had the same issue.
Is there a document in which I can find the purpose and the configuration options of a particular module other than the code. The docs section seems really sparse.
My apologies for the fuzz, I'm closing this non-issue  with this comment. Thanks for the support.
