### ISSUE TITLE
Empty 183 Session Progress SDP for early video configuration and audio-only call

### ISSUE THREAD

**Issue by cspiel1** [baresip/baresip#1450]
The callee accounts file contains:
```
 <sip:a@localhost>;regint=0;answermode=early-video
```

The caller initiates an audio only call with:
```
/dialdir 10.1.0.2 audio=sendrecv video=inactive
```

Like always baresip callee answers with 180 Ringing. Additionally in this case maybe unwanted also sends a 183 Session Progress with empty SDP:

```
v=0
o=- 2604700548 294414210 IN IP4 10.1.0.2
s=-
c=IN IP4 10.1.0.2
t=0 0
m=audio 0 RTP/AVP 0
```

Should we fix to avoid the 183 Session Progress or is it acceptable?

**Comment by juha-h** [comment]
I don't know what ;answermode=early-video means, but since the incoming call only has audio media, what is the point of 183 reply without audio?  What useful information does it tell to callr?

**Comment by cspiel1** [comment]
That's the point. It tells nothing. If the caller is baresip it doesn't hurt currently. The ringtone is initiated by the 180 Ringing and the 183 is ignored.

But other clients maybe will stop ringing. E.g. an older baresip version.

**Comment by juha-h** [comment]
OK, then better if sending of 183 can be avoided.

**Comment by cspiel1** [comment]
Will make a PR after https://github.com/baresip/baresip/pull/1449 was merged.
```c
int call_progress(struct call *call)
{
...
	adir = sdp_media_dir(stream_sdpmedia(audio_strm(call_audio(call))));
	vdir = sdp_media_dir(stream_sdpmedia(video_strm(call_video(call))));
	if (adir == SDP_INACTIVE && vdir == SDP_INACTIVE)
		return 0;
...
```

**Comment by alfredh** [comment]
the SIP signaling should be decoupled from the SDP.

the general rule for sending 180/183 is:

1. 180 contains no SDP body
2. 183 contains an SDP body (because of early media)

it is perfectly fine to send 183 with all medialines disabled in SDP

**Comment by cspiel1** [comment]
Ok, then we don't need a PR.
