### ISSUE TITLE
./gen.sh: No such file or directory

### ISSUE THREAD

**Issue by jungle-boogie** [baresip/baresip#1453]
Hi,

Now that `re` and `rem` are up to date, I want to build `baresip` on my OpenBSD i386 machine with clang, but there's a build failure.

```
LD [M]  dtls_srtp.so
  CC [M]  build-i586/modules/g711/g711.o
  LD [M]  g711.so
  CC [M]  build-i586/modules/gsm/gsm.o
  LD [M]  gsm.so
/bin/sh: ./gen.sh: No such file or directory
gmake: *** [modules/ctrl_dbus/module.mk:21: modules/ctrl_dbus/baresipbus.c] Error 1
```

I think that `gen.sh` is in the right place:
```
$ find . -name gen.sh
./modules/ctrl_dbus/gen.sh
```

I think this commit adds in `gen.sh` stuff:
https://github.com/baresip/baresip/commit/287b1566466d0c1baea1252663e065a962e58107#diff-39611f46dbfae746434c309f570875a7ffa973af612b386faa1f1d6743ec61c8

I do happen to have bash installed, but the path is different than in the gen.sh script:
```
$ which bash
/usr/local/bin/bash
```

**Comment by jungle-boogie** [comment]
Is `bash` a requirement or can `sh` be used in this script?

**Comment by jungle-boogie** [comment]
Changing `gen.sh` to:

`#!/usr/local/bin/bash` enabled me to build `baresip.

**Comment by cspiel1** [comment]
I tried and this works also:
```
--- a/modules/ctrl_dbus/gen.sh
+++ b/modules/ctrl_dbus/gen.sh
@@ -1,4 +1,4 @@
-#!/bin/bash
+#!/bin/sh
```

Will make a PR.

**Comment by cspiel1** [comment]
https://github.com/baresip/baresip/pull/1456
