### ISSUE TITLE
How to config mcsend in the configuration file

### ISSUE THREAD

**Issue by Vieufoux** [baresip/baresip#1454]
Hi

I can start a multicast sender using sender commands "/mcsend addr=<IPv4|IPv6>:<PORT> codec=<AUCODEC>"

But i didn't find a plcace to config it in the configuration file, where can i config it? and example?

Thanks

**Comment by cspiel1** [comment]
See docs/examples/config!

The code can be found in modules/multicast.

Use the google group for questions!
