### ISSUE TITLE
paging feature

### ISSUE THREAD

**Issue by Vieufoux** [baresip/baresip#1455]
Hi

How to implement a paging system using baresip? 
The paging use scenario is that in schools, hospitals, shopping malls, you can speak in real time through a microphone, and the sound is played from multiple speakers at the same time.

Thanks

**Comment by cspiel1** [comment]
See module multicast!

**Comment by cspiel1** [comment]
Use https://groups.google.com/g/baresip for questions.

I'll close this, since it is not an issue.
