### ISSUE TITLE
Cant compile

### ISSUE THREAD

**Issue by jbittner1002** [baresip/baresip#1464]
Downloaded /installed the latest libre and librem.
trying to compile latest baresip I get these errors.  Any idea what it could be. ?

root@x00301802bf84:/usr/src/baresip# make
  CC [M]  build-x86_64/modules/account/account.o
In file included from modules/account/account.c:7:
include/baresip.h:365:7: warning: ISO C forbids forward references to 'enum' types [-Wpedantic]
  365 |  enum jbuf_type jbtype;  /**< Jitter buffer type             */
      |       ^~~~~~~~~
include/baresip.h:365:17: error: field 'jbtype' has incomplete type
  365 |  enum jbuf_type jbtype;  /**< Jitter buffer type             */
      |                 ^~~~~~
make: *** [mk/mod.mk:49: build-x86_64/modules/account/account.o] Error 1
root@x00301802bf84:/usr/src/baresip#

**Comment by juha-h** [comment]
jbittner1002 writes:

> Downloaded /installed the latest libre and librem.

Looks you don't have latest re, since it does contain enum jbuf_type in

include/re_jbuf.h

and account.c includes re.h before baresip.h.

**Comment by jbittner1002** [comment]
I could have sworn I used the latest versions.... I just erased them... git clone both of them again and installed..

Now I get this error

 CC [M]  build-x86_64/modules/aac/decode.o
modules/aac/decode.c: In function 'aac_decode_update':
modules/aac/decode.c:136:41: error: 'AAC_PCM_MIN_OUTPUT_CHANNELS' undeclared (first use in this function); did you mean 'AAC_PCM_OUTPUT_CHANNELS'?
  136 |  error  = aacDecoder_SetParam(ads->dec, AAC_PCM_MIN_OUTPUT_CHANNELS,
      |                                         ^~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                         AAC_PCM_OUTPUT_CHANNELS
modules/aac/decode.c:136:41: note: each undeclared identifier is reported only once for each function it appears in
modules/aac/decode.c:138:41: error: 'AAC_PCM_MAX_OUTPUT_CHANNELS' undeclared (first use in this function); did you mean 'AAC_PCM_OUTPUT_CHANNELS'?
  138 |  error |= aacDecoder_SetParam(ads->dec, AAC_PCM_MAX_OUTPUT_CHANNELS,
      |                                         ^~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                         AAC_PCM_OUTPUT_CHANNELS
make: *** [mk/mod.mk:49: build-x86_64/modules/aac/decode.o] Error 1

**Comment by jbittner1002** [comment]
I found someone else had this same problem and they were missing fdk-acc.
I had the one that come with ubuntu but it was to old.
I downloaded this one... installed and then I was able to compile baresip.
https://sourceforge.net/projects/opencore-amr/files/fdk-aac/fdk-aac-2.0.2.tar.gz/download

Thanks for your help...
