### ISSUE TITLE
Can't find 100 Trying in server's response

### ISSUE THREAD

**Issue by I-mpossible** [baresip/baresip#1469]
Hi, I'm experimenting baresip client and server interaction. I observed that server sends 180 Ringing in response to client's INVITE. I'm wondering whether this is an intentional design? Or is there a way to make the server respond with 100 Trying before 180 Ringing?

command used
```./baresip -f docs/examples -n 127.0.0.1```
```./baresip -f docs/examples -e "d user@127.0.0.1"```

**Comment by alfredh** [comment]
please use the mailing list to ask questions:

https://github.com/baresip/baresip/wiki/Guidelines-for-reporting-Issues
