### ISSUE TITLE
autoanswer issues

### ISSUE THREAD

**Issue by juha-h** [baresip/baresip#1474]
If I have in account config

;answermode=manual;answerdelay=1000

the call is answered automatically.

I would consider this a bug.  ;answerdelay should only have effect when answermode is auto.

In my opinion,  account's answer configuration is getting far too complicated:

;answermode={manual,early,auto,early-audio,early-video}
;answerdelay=0
;sip_autoanswer={yes, no}
;sip_autoanswer_beep={off, on, local}

There used to be only this

;answermode={manual,early,auto}

What is sip_autoanswer?

**Comment by juha-h** [comment]
OK, I understood that sip_autoanswer relates to SIP request auto answer headers, but what still remains unclear to me is, what is the relationship between answermode and sip_autoanswer.  If sip_autoanswer is yes, does it override answermode and answerdelay values?

**Comment by juha-h** [comment]
According to wiki, answerdelay values are seconds.  Based on my tests, they are milliseconds.  Sorry about writing all this under the same issue.

**Comment by negbie** [comment]
Noticed the same. I think it's because of this:
https://github.com/baresip/baresip/blob/ae5f7ba18b3fe47a368d230fb52eff6c4f4867ca/src/ua.c#L424

**Comment by negbie** [comment]
I would say that condition should be removed from ANSWERMODE_MANUAL case.

**Comment by juha-h** [comment]
Eugen Biegler writes:

> I would say that condition should be removed from ANSWERMODE_MANUAL
> case.

I agree.

**Comment by cspiel1** [comment]
- Sorry, it should be milli seconds. This is right. --> I will correct this in the wiki.
- I also once thought about in which answer mode adelay should be applicable. You can think about it, and we could discuss on Monday. Note, that menu.c decides when the ring-tone should be started or not! If we change something in ua.c then we have also do something in function `play_incoming)()` in menu.c.
- We have also the EARLY media answer modes. The adelay should also be applicable for these.

**Comment by juha-h** [comment]
According to wiki, "user has to answer the call"  in all answermode cases except "auto".  That is how it should be independent of what answerdelay value is.  That allows user to change from auto to the other modes without need to change answerdelay value.

**Comment by cspiel1** [comment]
Ok, but there are also these scenarios which are currently allowed:

- If adelay is a positive value (let's say a few seconds) then the ringtone will start and the user has the chance to accept the call before the answer delay elapsed.
- In addition also early media should be possible. Early media + adelay + manual accept if the user is faster than the adelay elapses.

So if we want to simplify something we could simplify the ANSWERMODE_AUTO, which could be the only mode where the incoming call is automatically accepted immediately, regardless how adelay is set.

**Comment by juha-h** [comment]
Sounds good to move autoanswer  stuff to menu (= application).  That is what I'm doing in my Android app.  I always use manual and then handle autoanswer in the application, not in baresip lib.

**Comment by cspiel1** [comment]
The PR was merged. I also updated the wiki: https://github.com/baresip/baresip/wiki/Accounts
