### ISSUE TITLE
audio: thread: tx aubuf underrun

### ISSUE THREAD

**Issue by negbie** [baresip/baresip#1482]
Using latest master I see alot of following messages in the console:
...
audio: thread: tx aubuf underrun (total 334)
audio: thread: tx aubuf underrun (total 335)
audio: thread: tx aubuf underrun (total 336)
audio: thread: tx aubuf underrun (total 337)
audio: thread: tx aubuf underrun (total 338)
...

when I connect to an account from two different endpoints. For this account I use following parameter:
;answermode=auto;audio_source=aubridge,nil;audio_player=aubridge,nil

In the config file I use:
call_hold_other_calls   no

I have not set ausrc_srate or auplay_srate so no resampling. Here are the relevant console logs for both lines:

call: answering call on line 1 from sip:XXX;user=phone with 200
call: update media
stream: update 'audio'
stream: audio: starting RTCP with remote XXX
stream: audio: starting mediaenc 'srtp-mand' (wait_secure=0)
srtp: audio: SRTP is Enabled (cryptosuite=AES_CM_128_HMAC_SHA1_80)
call: mediaenc event 'Secure' (audio,AES_CM_128_HMAC_SHA1_80)
stream: audio: starting RTCP with remote XXX
audio: Set audio encoder: G722 16000Hz 1ch
audio: start
aubridge: created device 'nil'
audio: source started with sample format S16LE
audio: Set audio decoder: G722 16000Hz 1ch
audio: start
audio: create recv buffer [20 - 320 ms] [640 - 10240 bytes]
audio: player started with sample format S16LE
audio tx pipeline:    aubridge ---> G722
audio rx pipeline:    aubridge <--- G722
audio: start
aubridge: thread start: 16000 Hz, 1 channels, format=S16LE
audio: update

-----------------------------------------------------------------------------------------------------------------------------

call: answering call on line 2 from sip:XXX;user=phone with 200
call: update media
stream: update 'audio'
stream: audio: starting RTCP with remote XXX
stream: audio: starting mediaenc 'srtp-mand' (wait_secure=0)
srtp: audio: SRTP is Enabled (cryptosuite=AES_CM_128_HMAC_SHA1_80)
call: mediaenc event 'Secure' (audio,AES_CM_128_HMAC_SHA1_80)
stream: audio: starting RTCP with remote XXX
audio: Set audio encoder: G722 16000Hz 1ch
audio: start
audio: source started with sample format S16LE
audio: Set audio decoder: G722 16000Hz 1ch
audio: start
audio: create recv buffer [20 - 320 ms] [640 - 10240 bytes]
audio: player started with sample format S16LE
audio tx pipeline:    aubridge ---> G722
audio rx pipeline:    aubridge <--- G722
audio: start
audio: update

audio: thread: tx aubuf underrun (total 2)
audio: thread: tx aubuf underrun (total 3)
audio: thread: tx aubuf underrun (total 4)
audio: thread: tx aubuf underrun (total 5)
audio: thread: tx aubuf underrun (total 6)

**Comment by negbie** [comment]
Here is the relevant part of my configuration file:

#
# baresip configuration
#

#------------------------------------------------------------------------------

# Core
poll_method             epoll           # poll, select, epoll ..

# SIP
#sip_listen             0.0.0.0:5060
#sip_certificate        cert.pem
sip_cafile              /etc/ssl/certs/ca-certificates.crt
#sip_trans_def          udp
#sip_verify_server      yes
sip_tos                 160

# Call
call_local_timeout      12
call_max_calls          30
call_hold_other_calls   no

# Audio
audio_path              sounds
audio_player            aubridge,nil
audio_source            ausine,362
#ausrc_srate            48000
#auplay_srate           48000
#ausrc_channels         0
#auplay_channels        0
audio_txmode            thread          # poll, thread
audio_level             no
ausrc_format            s16             # s16, float, ..
auplay_format           s16             # s16, float, ..
auenc_format            s16             # s16, float, ..
audec_format            s16             # s16, float, ..
audio_buffer            20-320          # ms

# Video
#video_source           v4l2,/dev/video0
#video_display          x11,nil
video_size              640x480
video_bitrate           1000000
video_fps               30.00
video_fullscreen        no
videnc_format           yuv420p

# AVT - Audio/Video Transport
rtp_tos                 184
rtp_video_tos           136
rtp_ports               10000-11000
#rtp_bandwidth          512-1024 # [kbit/s]
rtcp_mux                no
jitter_buffer_type      fixed           # off, fixed, adaptive
jitter_buffer_delay     5-10            # frames
#jitter_buffer_wish     6               # frames for start
rtp_stats               no
rtp_timeout             10

# Network
#dns_server             1.1.1.1:53
#dns_server             1.0.0.1:53
#dns_fallback           8.8.8.8:53
#net_interface          eth0

# Play tones
#file_ausrc             aufile
#file_srate             16000
#file_channels          1

**Comment by negbie** [comment]
It seems that this is only the case if you either set:

audio_player            aubridge,nil
audio_source           aubridge,nil

in config file or

audio_source=aubridge,nil;audio_player=aubridge,nil

in account file.

**Comment by alfredh** [comment]
the problem is that `aubridge,nil` is only one pseudo-device (nil) and in your case it is 
shared by multiple sessions.

if you have multiple accounts you can solve it like this:

```
<sip:1@domain>;audio_source=aubridge,device1
<sip:2@domain>;audio_source=aubridge,device2
<sip:3@domain>;audio_source=aubridge,device3
```

you can also use the `echo` module which supports multiple sessions.

**Comment by negbie** [comment]
Hello @alfredh,
thank you for your advice! I saw that @sreimers commit https://github.com/baresip/baresip/commit/ee2f45d59b24a0eb65abc43e65ae9b34dceeb46a fixed the underrun messages so I think we can close this.
I thank you both very much!
