### ISSUE TITLE
baresip fail to compile

### ISSUE THREAD

**Issue by dannymarosi** [baresip/baresip#1485]
latest librem and libre were pulled and compiled 
but  baresip fail with the following message:

`pi@raspberrypi:~/baresip $ make
Makefile:61: *** bad librem version, required version is ">= 1.0.0-dev"..  Stop.
pi@raspberrypi:~/baresip $
`

**Comment by sreimers** [comment]
Which librem version do you use? Please ensure its https://github.com/baresip/rem

**Comment by juha-h** [comment]
dannymarosi writes:

> latest librem and libre were pulled and compiled 
> but  baresip fail with the following message:
> 
> ***@***.***:~/baresip $ make
> Makefile:61: *** bad librem version, required version is ">= 1.0.0-dev"..  Stop.
> ***@***.***:~/baresip $
> `
Perhaps you did not install libre/rem dev packages before making
baresip.

I just tried with this script on Debian Buster and baresip was built
without issues;

$ more build-baresip.sh
rm *.deb
cd re
git pull
buildpackage
cd ..
sudo dpkg -i libre_*deb libre-dev*deb
cd rem
git pull
buildpackage
cd ..
sudo dpkg -i librem_*deb librem-dev*deb
cd baresip
git pull
buildpackage
cd ..
sudo dpkg -i baresip_*deb

**Comment by dannymarosi** [comment]
Issue solved by deleting rem folder re cloning and compiling the project
Thanks
