### ISSUE TITLE
FIPS compatible version

### ISSUE THREAD

**Issue by dmitriybabintsev** [baresip/baresip#1488]
Hi Alfred.

I was trying to run baresip agent on FIPS linix system and got the error:
`md5_dgst.c(82): OpenSSL internal error, assertion failed: Digest MD5 forbidden in FIPS mode!`
(baresip version 0.6.3, re-0.6.0)

Do you have any FIPS-compatible version?

**Comment by alfredh** [comment]
your version is really old, please upgrade to latest from git.

SIP is using md5 for the authentication. To solve this we have to add support for
a hashing algorithm that is not md5.

**Comment by dmitriybabintsev** [comment]
> your version is really old, please upgrade to latest from git.

Thanks for your reply Alfred.
I will update baresip to the latest version.

> SIP is using md5 for the authentication. To solve this we have to add support for
> a hashing algorithm that is not md5.

Is there any chance you will implement this in future? Probably during the next 3 month

**Comment by alfredh** [comment]
I am not sure if md5 is completely disabled in fips or if there is a way to enable it.

can you please share more details about your platform, including openssl version?
please also describe your SIP server.

can you please provide a full log of the output, and also a gdb backtrace
when the assert happens ?

**Comment by alfredh** [comment]
https://security-certs.docs.ubuntu.com/en/fips-faq

**Comment by sreimers** [comment]
libre has a independent MD5 implementation. You can try to disable the openssl wrap here:

https://github.com/baresip/re/blob/master/src/md5/wrap.c#L6

By replacing all `USE_OPENSSL` by `USE_OPENSSL_DISABLED` for testing.

**Comment by dmitriybabintsev** [comment]
> I am not sure if md5 is completely disabled in fips or if there is a way to enable it.
> can you please share more details about your platform, including openssl version?

We have Centos 7.9 and openssl version is:
OpenSSL 1.0.2k-fips  26 Jan 2017

> please also describe your SIP server.

this is our custom voice processing system.

> can you please provide a full log of the output, and also a gdb backtrace
> when the assert happens ?

Below is what baresip throws to the log:

```
mand/uanew <sip:16502062060*124@sip.ringcentral.com>;auth_user=XXXX;auth_pass=XXXX;medianat=ice;stunserver=stun:stun.l.google.com:19302;mediaenc=srtp-mandf;sipnat=outbound;outbound="sip:sipXXX-XXX.ringcentral.biz:8085;transport=wss"

Creating UA for <sip:16502062060*124@sip.ringcentral.com>;auth_user=XXXX;auth_pass=XXXX;medianat=ice;stunserver=stun:stun.l.google.com:19302;mediaenc=srtp-mandf;sipnat=outbound;outbound="sip:sipXXX-XXX.ringcentral.biz:8085;transport=wss" ...
using stunserver: 'stun:stun.l.google.com:19302'
16502062060*124@sip.ringcentral.com: Using sipnat: 'outbound'
16502062060*124@sip.ringcentral.com: Using medianat 'ice'
16502062060*124@sip.ringcentral.com: Using media encryption 'srtp-mandf'
ua: outbound requires valid UUID!
Entering sipreg_register function...
Dialog RURI in sip_dialog_alloc: sip:sip.ringcentral.com
Setting dlg->route from routes
> sip:16502062060*124@sip.ringcentral.com    zzz

websock: connecting to 'wss://199.255.120.165:8085/'
http/client.c: URI value: wss://199.255.120.165:8085/
HTTP request URI: wss://199.255.120.165:8085/
<0x1dbdfd0> WSS websock established to 199.255.120.165:8085
md5_dgst.c(82): OpenSSL internal error, assertion failed: Digest MD5 forbidden in FIPS mode!
Aborted (core dumped)
[root@sjc51-c01-tnt01 baresip-0.6.3]#
```

**Comment by dmitriybabintsev** [comment]
> libre has a independent MD5 implementation. You can try to disable the openssl wrap here:
> 
> https://github.com/baresip/re/blob/master/src/md5/wrap.c#L6
> 
> By replacing all `USE_OPENSSL` with `USE_OPENSSL_DISABLED` for testing.

Thanks for your advice @sreimers, I will check it

**Comment by dmitriybabintsev** [comment]
> > libre has a independent MD5 implementation. You can try to disable the openssl wrap here:
> > https://github.com/baresip/re/blob/master/src/md5/wrap.c#L6
> > By replacing all `USE_OPENSSL` with `USE_OPENSSL_DISABLED` for testing.
> 
> Thanks for your advice @sreimers, I will check it

it does not work unfortunately:

```
Creating UA for <sip:16502062060*124@sip.ringcentral.com>;auth_user=XXX;auth_pass=XXX;medianat=ice;stunserver=stun:stun.l.google.com:19302;mediaenc=srtp-mandf;sipnat=outbound;outbound="sip:sipXXX-XXX.ringcentral.biz:8085;transport=wss" ...
using stunserver: 'stun:stun.l.google.com:19302'
16502062060*124@sip.ringcentral.com: Using sipnat: 'outbound'
16502062060*124@sip.ringcentral.com: Using medianat 'ice'
16502062060*124@sip.ringcentral.com: Using media encryption 'srtp-mandf'
ua: outbound requires valid UUID!
Entering sipreg_register function...
Dialog RURI in sip_dialog_alloc: sip:sip.ringcentral.com
Setting dlg->route from routes
> sip:16502062060*124@sip.ringcentral.com    zzz 

websock: connecting to 'wss://199.255.120.165:8085/'
http/client.c: URI value: wss://199.255.120.165:8085/
HTTP request URI: wss://199.255.120.165:8085/
<0x556d3eca14b0> WSS websock established to 199.255.120.165:8085
./baresip: symbol lookup error: /usr/local/lib/libre.so: undefined symbol: md5_init
```

**Comment by sreimers** [comment]
Sorry i missed the mod.mk, here is a complete diff:
```diff
diff --git a/src/md5/mod.mk b/src/md5/mod.mk
index 891e3b30..dcfa88d9 100644
--- a/src/md5/mod.mk
+++ b/src/md5/mod.mk
@@ -4,7 +4,7 @@
 # Copyright (C) 2010 Creytiv.com
 #
 
-ifeq ($(USE_OPENSSL),)
+ifeq ($(USE_OPENSSL_DISABLED),)
 SRCS   += md5/md5.c
 endif
 
diff --git a/src/md5/wrap.c b/src/md5/wrap.c
index 97107e08..697e9c77 100644
--- a/src/md5/wrap.c
+++ b/src/md5/wrap.c
@@ -3,7 +3,7 @@
  *
  * Copyright (C) 2010 Creytiv.com
  */
-#ifdef USE_OPENSSL
+#ifdef USE_OPENSSL_DISABLED
 #include <stddef.h>
 #include <openssl/md5.h>
 #else
@@ -25,7 +25,7 @@
  */
 void md5(const uint8_t *d, size_t n, uint8_t *md)
 {
-#ifdef USE_OPENSSL
+#ifdef USE_OPENSSL_DISABLED
        (void)MD5(d, n, md);
 #else
        md5_state_t state;
```

**Comment by dmitriybabintsev** [comment]
> Sorry i missed the mod.mk, here is a complete diff:

Thanks Sebastian. This helped. Baresip works now on FIPS system :)
But it looks like deception of the system, we're still using MD5.

**Comment by alfredh** [comment]
@dmitriybabintsev can you check if your sip server supports authentication algorithm other than MD5 ?

@oej we need your expert knowledge here. do you know if there are any SIP servers that
supports SHA-256 for authentication ?


I have been testing CentOS with openssl-fips in the past, and baresip has been working fine.
so I find it strange that you get that assert.

Is there anyone else here that is using CentOS ?

**Comment by alfredh** [comment]
please note that openssl 1.0.2
is no longer supported by baresip.

you need 1.1.0 or later

**Comment by dmitriybabintsev** [comment]
> @dmitriybabintsev can you check if your sip server supports authentication algorithm other than MD5 ?

not sure, I need to check it

> I have been testing CentOS with openssl-fips in the past, and baresip has been working fine.
> so I find it strange that you get that assert.

I believe the reason of the assert is the system itself is build with some FIPS kernel options. 
We also have none-FIPS centos VMs with the same OpenSSL 1.0.2k-fips version - and there're no any assrts here, MD5 auth works fine here.

**Comment by oej** [comment]
https://kamailio.org/docs/modules/devel/modules/auth.html#auth.p.algorithm

The real important thing is to test the full extent of the new RFC, but I don't know of any server-side implementations. Getting a challenge with multiple algos is interesting.
