### ISSUE TITLE
Options in baresip

### ISSUE THREAD

**Issue by smathieson** [baresip/baresip#1491]
Hi,

Is it possible to set all options in baresip console?

I am trying to set snd_path to /tmp like so:

/options snd_path /tmp

I have tried a number of ways but keep getting an error.

What am i doing wrong?

Thanks,
Sam.

**Comment by cspiel1** [comment]
You should look in the code.
Command "options" calls function `options_command()` --> `ua_options_send()`

This sends a SIP OPTIONS. See https://datatracker.ietf.org/doc/html/rfc3261#section-11 !
