### ISSUE TITLE
Error: bad libre version, required version is ">= 2.0.1-dev"

### ISSUE THREAD

**Issue by Koshub** [baresip/baresip#1492]
Hello. Probably it is not an issue in some build configuration but when I build baresip and its dependencies from master I get this error:

> Makefile:148: *** bad libre version, required version is ">= 2.0.1-dev". LIBRE_MK: ../re/mk/re.mk.  Stop.

Did not try specific tags. Should I? Should I provide some build parameters? Because it seems something is missed since the current master of re is really 2.0.1-dev.

**Comment by sreimers** [comment]
Can you paste the content from `../re/libre.pc`

**Comment by Koshub** [comment]
@sreimers Sorry I do not have these. I use this [makefile](https://github.com/baresip/baresip-ios/blob/master/mk/contrib.mk) to build it as a library.

**Comment by sreimers** [comment]
This deletes `libre.pc` too.
https://github.com/baresip/baresip-ios/blob/master/mk/contrib.mk#L184

**Comment by Koshub** [comment]
@sreimers thanks, will try

**Comment by kisso** [comment]
still getting:
Makefile:156: *** bad librem version, required version is ">= 1.0.0-dev"..  Stop.
make: *** [baresip] Error 2

**Comment by sreimers** [comment]
> Has to be fixed for librem too:
> 
> https://github.com/baresip/baresip-ios/blob/master/mk/contrib.mk#L234

@rm -f $(LIBREM_PATH)/librem.{dylib,a}

**Comment by Koshub** [comment]
@sreimers 
> This deletes libre.pc too.
>https://github.com/baresip/baresip-ios/blob/master/mk/contrib.mk#L184
> Something like @rm -f $(LIBRE_PATH)/libre.{dylib,a} should be enough. Has to be fixed for librem too:
>https://github.com/baresip/baresip-ios/blob/master/mk/contrib.mk#L234

Confirm that works to fix compilation. Also probably there is no need to apply [that patch](https://github.com/baresip/baresip-ios/blob/master/Makefile#L28)

**Comment by Koshub** [comment]
@kisso [here](https://github.com/baresip/baresip-ios/blob/master/Makefile#L26) the link should address `https://github.com/baresip` not `https://github.com/creytiv`

**Comment by Koshub** [comment]
@sreimers pls, check it out https://github.com/baresip/baresip-ios/pull/43
