### ISSUE TITLE
wss transport issue

### ISSUE THREAD

**Issue by juha-h** [baresip/baresip#1493]
I'm trying to use wss transport in outbound URI, but during registration connection setup fails with these error messages:
```
websock: connecting to 'wss://<ip address of outbound proxy>:8003/'
tls: verify_handler: err          = 20
tls: verify_handler: error_string = unable to get local issuer certificate
tls: verify_handler: depth        = 1
tls: connect: error (r=-1, ssl_err=1)
sip: websock connection closed (Protocol error)
```
In the config file, sip_certificate, sip_cafile, and sip_verify_server have all been commented out.  Why there is error message about local issuer certificate?

My Kamailio based registrar also writes errors to syslog:
```
Jun 15 09:31:54 box /usr/bin/sip-proxy[4713]: ERROR: tls [tls_server.c:1329]: tls_h_read_f(): protocol level error
Jun 15 09:31:54 box /usr/bin/sip-proxy[4713]: ERROR: tls [tls_util.h:42]: tls_err_ret(): TLS accept:error:14094418:SSL routines:ssl3_read_bytes:tlsv1 alert unknown ca
Jun 15 09:31:54 box /usr/bin/sip-proxy[4713]: ERROR: tls [tls_server.c:1333]: tls_h_read_f(): source IP: <source ip>
Jun 15 09:31:54 box /usr/bin/sip-proxy[4713]: ERROR: tls [tls_server.c:1336]: tls_h_read_f(): destination IP: <destination ip>
```
My jssip based client is able to register with the same server without issues.  So is baresip if I change transport to tls.

If I remember correctly, I didn't have these issues in the past, when I tested baresip with wss transport. 

Any ideas?

**Comment by juha-h** [comment]
I build re and baresip from master as it was in October 2020 and baresip registered using wss transport without any  issues:
```
websock: connecting to 'wss://<ip address of outbound proxy>:8003/'
<0x56537af29400> WSS websock established to <ip address of outbound proxy>:8003
--> send
foo@test.tutpro.com: (prio 0) {1/WSS/v4} 200 OK (OpenSIPg SIP Proxy (5.5.0-8 (x86_64/linux))) [1 binding]
All 1 useragent registered successfully! (879 ms)
```
So looks like something somewhere has been broken since then.

**Comment by juha-h** [comment]
I found this re pr https://github.com/baresip/re/pull/67 where the same error message is shown.  As I mentioned, I have not configured sip_cafile and that could explain why connection setup fails, but it doesn't, since then also connection over tls should fail, but it doesn't.  So I'm lost on this.

**Comment by sreimers** [comment]
I think a ` tls_disable_verify_server(http_cli->tls)` is needed.

Maybe after this:
https://github.com/baresip/re/blob/f821ffbd0427aa1f08c57f50a43fc3bb0f8ffdab/src/sip/transp.c#L962

**Comment by juha-h** [comment]
Tried, but API does not expose http_cli->tls:
```
src/sip/transp.c: In function ‘ws_conn_send’:
src/sip/transp.c:970:44: error: dereferencing pointer to incomplete type ‘struct http_cli’
  tls_disable_verify_server(transp->http_cli->tls);
```

**Comment by juha-h** [comment]
Since sip_verify_server defaults to "no", there should be no need to call tls_disable_verify_server().  If sip_verify_server is "yes", then  tls_enable_verify_server() should be called.

**Comment by sreimers** [comment]
I think we can simplify this, can you try this:

https://github.com/baresip/re/pull/110

**Comment by juha-h** [comment]
That worked.  I tested both when sip_verify_server is no and yes.

**Comment by juha-h** [comment]
I did some more testing and found that no error message was produced when I had in config:
```
sip_certificate		cert.pem
#sip_cafile		ca-certs.crt
sip_verify_server	yes
```
```
$ baresip
baresip v1.1.0 Copyright (C) 2010 - 2021 Alfred E. Heggestad et al.
Local network address:  IPv4=wlp2s0|192.168.43.160  IPv6=wlp2s0|2001:14bb:c1:a7f2:396f:fbf1:6212:73b0
SIP Certificate: cert.pem
...
baresip is ready.
websock: connecting to 'wss://192.168.43.160:5061/'
<0x556c8dd16f50> WSS websock established to 192.168.43.160:5061
--> send
test@test.tutpro.com: (prio 0) {1/WSS/v4} 200 OK (OpenSIPg SIP Proxy (5.5.0-4 (x86_64/linux))) [1 binding]
All 1 useragent registered successfully! (346 ms)
```
Shouldn't verify fail when no sip_cafile or sip_capath is given?

**Comment by sreimers** [comment]
Yes we need the counterpart for `tls_disable_verify_server` -> `tls_enable_verify_server`, until now it was opt-out only.

**Comment by sreimers** [comment]
I update the PR https://github.com/baresip/re/pull/110 and added a new one for baresip https://github.com/baresip/baresip/pull/1497

**Comment by juha-h** [comment]
Sebastian Reimers writes:

> I update the PR https://github.com/baresip/re/pull/110 and added a new one for baresip https://github.com/baresip/baresip/pull/1497

Haven't tried yet, but would it be better to replace the two verify
functions with one:

void tls_verify_server(struct tls *tls, bool verify);

**Comment by juha-h** [comment]
Sebastian Reimers writes:

> I update the PR https://github.com/baresip/re/pull/110 and added a new one for baresip https://github.com/baresip/baresip/pull/1497

I built and installed re from verify_server branch and then built
and installed baresip from tls_enable_verify_server branch.

Still there was no error message when config has

sip_certificate		/home/jh/.baresip/cert.pem
#sip_cafile		/home/jh/.baresip/ca_list.pem
sip_verify_server	yes

and baresip registered over wss:

$ baresip
baresip v1.1.0 Copyright (C) 2010 - 2021 Alfred E. Heggestad et al.
Local network address:  IPv4=wlp2s0|192.168.43.160  IPv6=wlp2s0|2001:14bb:c1:a7f2:396f:fbf1:6212:73b0
SIP Certificate: /home/jh/.baresip/cert.pem
...
baresip is ready.
websock: connecting to 'wss://192.168.43.160:5061/'
<0x55693d011730> WSS websock established to 192.168.43.160:5061
--> send
***@***.***: (prio 0) {1/WSS/v4} 200 OK (OpenSIPg SIP Proxy (5.5.0-4 (x86_64/linux))) [1 binding]
All 1 useragent registered successfully! (490 ms)

Perhaps I missed something in the build process?

**Comment by sreimers** [comment]
Ok I had to add TLS context for secure websocket:

https://github.com/baresip/re/pull/113
https://github.com/baresip/baresip/pull/1499

Tomorrow I can setup a real WSS SIP Server and test myself. Maybe you can give it try.

**Comment by juha-h** [comment]
I tried with wss_tls_context branch from re and baresip and now registration over wss worked as expected with `sip_verify_server yes` both when ca information was available and wasn't available.  It also worked OK with `sip_verify_server no`.

**Comment by juha-h** [comment]
Sebastian Reimers writes:

> Tomorrow I can setup a real WSS SIP Server and test myself. Maybe you
> can give it try.

If needed, I can give access to my server.

**Comment by sreimers** [comment]
Ok could test now and is merged upstream.

**Comment by juha-h** [comment]
I'll make one more test with current masters and then close the issue.

**Comment by juha-h** [comment]
All tests worked OK.  Thanks.

**Comment by alfredh** [comment]
perhaps we should also add SIP over WS in selftest ?
