### ISSUE TITLE
RTP Event DTMF not properly recognized in Version 1.1.0

### ISSUE THREAD

**Issue by exse2** [baresip/baresip#1494]
Baresip is "50" and calls "23" in below log. Versions are re/v2.0.1, rem/v1.0.0, baresip/v1.1.0. The receiver, "23", accepts the call and types "1" on its keypad, which is recognized by baresip - see "received in-band DTMF event: '1' (end=0)" below. **The problem is, "received in-band DTMF event: '1' (end=1)" is missing** and instead, it writes something about discarding old audio frames. When i switch back to Version baresip/v1.0.0 (same re/rem as above) - it works! "received event: '1' (end=0)" AND  "received event: '1' (end=1)" is coming, and no note about discarding audio frames.

	  audio: update
	  audio: Set audio decoder: PCMA 8000Hz 1ch
	  audio: start
	  audio: create recv buffer [20 - 160 ms] [320 - 2560 bytes]
	  alsa: reset: srate=8000, ch=1, num_frames=160, pcmfmt=S16_LE
	  alsa: playback started (default)
	  audio: player started with sample format S16LE
	  audio: Set audio encoder: PCMA 8000Hz 1ch
	  audio: start
	  aubridge: created device 'nil2'
	  audio: source started with sample format S16LE
	  audio tx pipeline:    aubridge ---> PCMA
	  audio rx pipeline:        alsa <--- PCMA
	  call: stream start (active=1)
	  audio: start
	  50@192.168.20.11: Call established: sip:23@192.168.20.11
	  ctrl_tcp: handle_command:  cmd='ausrc', params:'gst,file:///var/www/html/cache/dialer-standalone/alarm.mp3', token=''
	  stream: incoming rtp for 'audio' established, receiving from 192.168.20.11:15288
	  gst: title: Alarm
	  gst: title: Alarm
	  gst: title: Alarm/0 (bit/s)    
	  gst: title: Alarm/0 (bit/s)    
	  ctrl_tcp: handle_command:  cmd='ausrc', params:'aubridge,nil2', token=''
	  aubridge: created device 'nil2'
	  #################### I PRESS "1" KEY ON PAD
	  received in-band DTMF event: '1' (end=0)
	  audio: [time=27.699] discard old frame (0.000 seconds old)
	  audio: [time=27.699] discard old frame (0.000 seconds old)
	  audio: [time=27.699] discard old frame (0.000 seconds old)
	  #################### AGAIN, I PRESS "1" KEY ON PAD - "received in-band DTMF event" IS MISSING BUT SOMETHING IS, AGAIN, DISCARDED. I AM GUESSING THIS IS THE end=1 EVENT.
	  audio: [time=40.590] discard old frame (0.000 seconds old)
	  audio: [time=40.590] discard old frame (0.000 seconds old)
	  audio: [time=40.590] discard old frame (0.000 seconds old)
	  #################### I PRESS "2" KEY ON PAD
	  received in-band DTMF event: '2' (end=0)
	  50@192.168.20.11: selected for 50-0x875bd0
	  ua: incoming OPTIONS message from sip:asterisk@192.168.20.11 (192.168.20.11:5060)
	  ua: using best effort AF: af=AF_INET
	  call: alloc with params laddr=192.168.20.237, af=AF_INET, use_rtp=0
	  call: use_video=0
	  audio: destroyed (started=0)
	  audio: [time=49.200] discard old frame (0.000 seconds old)
	  audio: [time=49.200] discard old frame (0.000 seconds old)
	  audio: [time=49.200] discard old frame (0.000 seconds old)

Wireshark looks like this
![rtp-event](https://user-images.githubusercontent.com/13996968/122038772-3e7ce500-cdd6-11eb-9093-3dafcf6bcb8d.jpg)

So it has to be an issue with this diff (v1.0.0 to v1.1.0) - https://github.com/baresip/baresip/compare/1ef6826..82123b6 - but that is very.... long O_O

**Comment by cspiel1** [comment]
Currently working on this.

**Comment by cspiel1** [comment]
I can't reproduce this with master HEAD. Please could you try with master HEAD?

But we have similar error messages with an Asterisk setup. So peer-to-peer inbound DTMF work, but not from Asterisk. We get:
```
audio: [time=7.966] discard old frame (0.000 seconds old)
audio: [time=7.966] discard old frame (0.000 seconds old)
audio: [time=7.966] discard old frame (0.000 seconds old)
audio: [time=7.966] discard old frame (0.000 seconds old)
```

**Comment by exse2** [comment]
I have tried to compile HEAD (with re/v2.0.1, rem/v1.0.0 still installed). It throws many compiler errors about forward declarations. So I compiled those first in their HEAD state, also:

	  rm -rf /usr/src/re* /usr/local/include/re* /usr/local/lib/libre*;cd /usr/src;ldconfig
	  cd /usr/src
	  git clone --depth 1 https://github.com/baresip/re
	  cd re
	  ldconfig;make clean;make install;ldconfig
	  cd ..
	  git clone --depth 1 https://github.com/baresip/rem
	  cd rem
	  ldconfig;make clean;make install;ldconfig
	  cd ..
	  rm -rf /usr/src/baresip* /usr/local/bin/baresip /usr/local/lib/baresip/modules/*;cd /usr/src;ldconfig
	  git clone --depth 1 https://github.com/baresip/baresip
	  cd baresip
	  ldconfig;make clean;make install;ldconfig
	  
	  Fails with:
	  
	  ..
	    CC [M]  build-x86_64/modules/g711/g711.o
	    LD [M]  g711.so
	    CC [M]  build-x86_64/modules/gsm/gsm.o
	    LD [M]  gsm.so
	    GEN     modules/ctrl_dbus/com.github.Baresip.xml
	  Usage: gdbus-codegen [options]
	  
	  gdbus-codegen: error: no such option: --output-directory
	  modules/ctrl_dbus/module.mk:26: recipe for target 'modules/ctrl_dbus/baresipbus.h' failed
	  make: *** [modules/ctrl_dbus/baresipbus.h] Error 2

The same using --branch v2.0.1, --branch v1.0.0 and --branch v1.1.0 as git command line parameters on the re, rem and baresip respectively, works.

There should be a compatibility table which version of re/rem works with which version of baresip.

**Comment by cspiel1** [comment]
There are already version checks for re in rem and baresip build. And for rem in baresip.

Your problem is that your gdbus-codegen does not have option `--output-directory`. This util program is part of glib. Which version do you have installed? I have:
```
$ apt show libglib2.0-dev-bin
Package: libglib2.0-dev-bin
Version: 2.64.6-1~ubuntu20.04.3
```

**Comment by cspiel1** [comment]
I am able to reproduce this with asterisk setup. Baresip sends SIP INFO dtmf, and asterisk converts it to an RTP Event. The receiving baresip instance prints:
```
received in-band DTMF event: '1' (end=0)it/s) efps=0.0/0.0    
audio: [time=7.759] discard old frame (0.000 seconds old)
...
audio: [time=7.759] discard old frame (0.000 seconds old)
audio: [time=7.759] discard old frame (0.000 seconds old)
```

**Comment by alfredh** [comment]
can you check what kind of packet is discarded ?

**Comment by cspiel1** [comment]
The telephone events. I have a fix which is plausible. --> PR comes soon.

**Comment by exse2** [comment]
> There are already version checks for re in rem and baresip build. And for rem in baresip.
> 
> Your problem is that your gdbus-codegen does not have option `--output-directory`. This util program is part of glib. Which version do you have installed? I have:
> 
> ```
> $ apt show libglib2.0-dev-bin
> Package: libglib2.0-dev-bin
> Version: 2.64.6-1~ubuntu20.04.3
> ```
Thank you! I have

[root@sallegra baresip-master]# rpm -qf /usr/bin/gdbus-codegen
glib2-devel-2.50.3-1.fc25.x86_64

This would mean I can't compile baresip > 1.0.0 on Fedora 25.

On topic, This occurs without SIP INFO, RTP DTMF Events are spoken by the baresip callee (Yealink "Hardware" Phone tuned to use rfc2833), inside the RTP line from the callee to baresip.

I was under the impression a SIP Server lets the attendee use his RTP line however he wants and does not interfere.

**Comment by sreimers** [comment]
Maybe we should add a version check like:

`pkg-config --exists "glib-2.0 >= 2.56"`

Ubuntu 18.04:
```
Package: libglib2.0-dev-bin
Version: 2.56.4-0ubuntu0.18.04.8
...
/usr/bin/gdbus-codegen -h
...
--output-directory OUTDIR
...
```

**Comment by cspiel1** [comment]
Added the check. PR: https://github.com/baresip/baresip/pull/1507

**Comment by cspiel1** [comment]
@exse2 Is it possible for you to compile baresip on a newer distro? And could you please test your setup with PR https://github.com/baresip/baresip/pull/1506 ?

**Comment by exse2** [comment]
How do I get it?
git clone --depth 1 --branch cspiel1:stream_fix_telephone_event https://github.com/baresip/baresip 
?
I am at a loss.

**Comment by cspiel1** [comment]
```
git remote add cspiel https://github.com/cspiel1/baresip.git
git fetch cspiel
git checkout stream_fix_telephone_event
```

**Comment by exse2** [comment]
[root@something src]# git remote add cspiel https://github.com/cspiel1/baresip.git
fatal: Not a git repository (or any of the parent directories): .git

**Comment by cspiel1** [comment]
Cleanup:
```
git checkout master
git branch -D stream_fix_telephone_event
git remote remove cspiel
```

**Comment by cspiel1** [comment]
> [root@something src]# git remote add cspiel https://github.com/cspiel1/baresip.git
> fatal: Not a git repository (or any of the parent directories): .git

In your baresip directory!

**Comment by cspiel1** [comment]
Or you clone it somewhere else:
```
git clone https://github.com/cspiel1/baresip.git
cd baresip
git checkout stream_fix_telephone_event
```

**Comment by exse2** [comment]
Thanks! I compiled successfully with this:

git clone --depth 1 https://github.com/baresip/re #with ldconfig;make clean;make install;ldconfig
git clone --depth 1 https://github.com/baresip/rem #with ldconfig;make clean;make install;ldconfig
git clone https://github.com/cspiel1/baresip.git
cd baresip
git checkout stream_fix_telephone_event
ldconfig;make clean;make USE_DBUS=;make USE_DBUS= install;ldconfig

Now CALL_DTMF_END (I am using ctrl_tcp module) is received!
Baresip says:

received in-band DTMF event: '3' (end=0)
received in-band DTMF event: '3' (end=1)

and no note of missing audio. This is solved.



However, I am not switching to this version because there is a different error:

gst: title: PIN-erkannt
gst: title: PIN-erkannt
gst: title: PIN-erkannt (bit/s)
gst: title: PIN-erkannt (bit/s)
ctrl_tcp: handle_command:  cmd='ausrc', params:'aubridge,nil2', token=''
aubridge: created device 'nil2'
ctrl_tcp: handle_command:  cmd='hangup', params:'undefined', token=''
**ctrl_tcp: error processing command (Invalid argument)**
ctrl_tcp: handle_command:  cmd='auplay', params:'aubridge,nil1', token=''
alsa: stopping playback thread (multimon)
baresip: pcm_file.c:449: snd_pcm_file_drain: Assertion `file->wbuf_used_bytes == 0' failed.
Aborted (core dumped)

The 0.6.4 does not bail in any way:

gst: title: PIN-erkannt
gst: title: PIN-erkannt (bit/s)
gst: title: PIN-erkannt (bit/s)
ctrl_tcp: handle_command:  cmd='ausrc', params:'aubridge,nil2', token=''
aubridge: created device 'nil2'
**ctrl_tcp: handle_command:  cmd='hangup', params:'undefined', token=''**
call: terminate call '41cb44dbcf197a4c' with sip:23@192.168.20.11
alsa: stopping playback thread (multimon)
sip:50@192.168.20.11: Call with sip:23@192.168.20.11 terminated (duration: 14 secs)
audio: destroyed (started=1)
ctrl_tcp: handle_command:  cmd='auplay', params:'aubridge,nil1', token=''

But this is a story for another time...
