### ISSUE TITLE
Call on hold flushes audio decode filters

### ISSUE THREAD

**Issue by sreimers** [baresip/baresip#1496]
@cspiel1 did you remember why you had to reset the `rx->filtl`? (update: you only changed the order, sry for mentioning)

https://github.com/baresip/baresip/blob/master/src/audio.c#L2052-L2053

The problem rx->filtl is never restored (for example after on hold).

I think it should enough to call  af->decupdh (if parameters are changed). But maybe i miss something.

**Comment by sreimers** [comment]
I have prepared a PR: https://github.com/baresip/baresip/pull/1498

**Comment by cspiel1** [comment]
This line came from:
```
commit 98bf08bdcf2edd9d397f32650a8bfe62186fbecf
Author: Alfred E. Heggestad <aeh@db.org>
Date:   Sun Feb 9 11:50:07 2014 +0100

    baresip 0.4.10
```

I agree with you.
