### ISSUE TITLE
makefile complains about libre version from git main

### ISSUE THREAD

**Issue by jungle-boogie** [baresip/baresip#1529]
Hi,

Now that I have the latest build of `re`, I'd like to build `baresip` from git main on the same machine. See https://github.com/baresip/re/issues/124 for the versions.

```
$ gmake CC=clang
Makefile:148: *** bad libre version, required version is ">= 2.0.1-dev4". LIBRE_MK: ../re/mk/re.mk.  Stop.
```

I have my directories for baresip setup like this:

```
$ pwd && ls -l
/home/user/bin/baresip-dir
total 24
drwxr-xr-x  13 user user 512 Jul  8 14:03 baresip
drwxr-xr-x  11 user  user  512 Jul  8 14:20 re
drwxr-xr-x  12 user  user  512 Jul  8 13:34 rem
```
I `cd` from one to another and cannot `gmake CC=clang clean` because of this. Do I need to edit the re.mk file or something?

**Comment by sreimers** [comment]
You need to compile `re` and `rem` first, can you check if `re/libre.pc` exists?

**Comment by jungle-boogie** [comment]
Yes, of course `re` needs to be compiled - and it was with your latest commit to master.

Yes, `libre.pc` exists.

**Comment by sreimers** [comment]
Is there maybe an old libre global install? can you try this:
```bash
cd ./baresip-dir/re
PKG_CONFIG_PATH=. pkg-config --exists "libre >= 2.0.1-dev4" --modversion
```
And this:

```bash
pkg-config --exists "libre >= 2.0.1-dev4" --modversion
```

**Comment by jungle-boogie** [comment]
I did both of those, plus a remake of `re` and `baresip` isn't happy yet.

**Comment by jungle-boogie** [comment]
```
$ gmake CC=clang
Makefile:148: *** bad libre version, required version is ">= 2.0.1-dev4". LIBRE_MK: ../re/mk/re.mk.  Stop.
```

**Comment by jungle-boogie** [comment]
Contents of `libre.pc`:

```
$ cart libre.pc
ksh: cart: not found
netbook$ cat libre.pc
prefix=/usr/local
exec_prefix=${prefix}
libdir=/usr/local/lib
includedir=${prefix}/include/re

Name: libre
Description: Generic library for real-time communications with async IO support
Version: 2.0.1-dev4
URL: https://github.com/baresip/re
Libs: -L${libdir} -lre
Libs.private: -L${libdir} -lre -lssl -lcrypto -lz -lpthread
Cflags: -I${includedir}
```

**Comment by jungle-boogie** [comment]
```
$ ls -lrt /usr/local/lib/libre*
-rwxr-xr-x  1 root  wheel   165892 May 19 11:49 /usr/local/lib/librem.so.0.0.0
lrwxr-xr-x  1 root  wheel       15 May 19 11:49 /usr/local/lib/librem.so.0 -> librem.so.0.0.0
lrwxr-xr-x  1 root  wheel       15 May 19 11:49 /usr/local/lib/librem.so -> librem.so.0.0.0
-rwxr-xr-x  1 root  wheel   244460 May 19 11:49 /usr/local/lib/librem.a
-rwxr-xr-x  1 root  wheel  1669464 Jul  8 15:09 /usr/local/lib/libre.so
-rwxr-xr-x  1 root  wheel  2939702 Jul  8 15:09 /usr/local/lib/libre.a
```

**Comment by jungle-boogie** [comment]
These match:

```
$ sha256 /home/user/bin/baresip-dir/re/libre.so /usr/local/lib/libre.so
SHA256 (/home/user/bin/baresip-dir/re/libre.so) = 76973c0339bca36bd365d7062f7a97b76ee01ceee09fc894e1f2b907b030f998
SHA256 (/usr/local/lib/libre.so) = 76973c0339bca36bd365d7062f7a97b76ee01ceee09fc894e1f2b907b030f998
```

**Comment by jungle-boogie** [comment]
I trashed my clone of `baresip` and attempted to compile - same result
I trashed by clone of `re` then attempted to compile `baresip`:
```
$ gmake CC=clang
Makefile:148: *** bad libre version, required version is ">= 2.0.1-dev4". LIBRE_MK: /usr/local/share/re/re.mk.  Stop.
```

Contents of /usr/local/share/re/re.mk:
https://termbin.com/rp5t

**Comment by jungle-boogie** [comment]
These `re` commits gets further with `baresip`, but `baresip` fails to build:
6dcaafb6757b4ff114548f1f9426741afcdaf345
e8d9a108b72ed3460835df35da9eb8df05f758a3


broken:
8dd357e3a9a2ac6f02cf45889b215cc9ec30ce9c

$ gmake CC=clang clean
Makefile:148: *** bad libre version, required version is ">= 2.0.1-dev4". LIBRE_MK: ../re/mk/re.mk.  Stop.

**Comment by jungle-boogie** [comment]
left a comment:

https://github.com/baresip/re/commit/8dd357e3a9a2ac6f02cf45889b215cc9ec30ce9c#diff-7b38a11fd83b96109ed31199449cd0f810d9e70fd66d860700f171bc4abec2f6

**Comment by jungle-boogie** [comment]
Opened issue in `re`.

https://github.com/baresip/re/issues/126

**Comment by sreimers** [comment]
> Is there maybe an old libre global install? can you try this:
> 
> ```shell
> cd ./baresip-dir/re
> PKG_CONFIG_PATH=. pkg-config --exists "libre >= 2.0.1-dev4" --modversion
> ```
> 
> And this:
> 
> ```shell
> pkg-config --exists "libre >= 2.0.1-dev4" --modversion
> ```

Can you provide the output of these commands?

**Comment by sreimers** [comment]
Can you try this branch:
```bash
cd baresip
git fetch
git checkout mk_dependency
make info
```

**Comment by jungle-boogie** [comment]
There is no output with the commands you provided above.

**Comment by jungle-boogie** [comment]
Here's the results from your branch: https://termbin.com/0ysv

**Comment by jungle-boogie** [comment]
With the latest `re` and `bairesip` from master, the same message is present:

`Makefile:149: *** bad libre version, required version is ">= 2.0.1-dev4". LIBRE_MK: ../re/mk/re.mk.  Stop.`

**Comment by jungle-boogie** [comment]
This commit is good and doesn't complain about the libre version on `make clean`
05ee68200d51fa298fd9054bf0d78324de345cd8

**Comment by jungle-boogie** [comment]
Hello,

Is there anything more I can do or provide to help assist to figure out what the problem is?

Thanks!

**Comment by sreimers** [comment]
If the `mk_dependency` branch works for you everything is fine, it takes some time until the PR is merged.

**Comment by jungle-boogie** [comment]
I don't think it worked out. I'll retest.

**Comment by jungle-boogie** [comment]
Using `mk_dependency` I get this on my amd64 build of OpenBSD.

```
modules/auloop/auloop.c:207:8: error: incomplete definition of type 'struct auframe'
        if (af->fmt != al->fmt) {
            ~~^
include/baresip.h:42:8: note: forward declaration of 'struct auframe'
struct auframe;
       ^
modules/auloop/auloop.c:209:15: error: incomplete definition of type 'struct auframe'
                        al->fmt, af->fmt);
                                 ~~^
include/baresip.h:42:8: note: forward declaration of 'struct auframe'
struct auframe;
       ^
modules/auloop/auloop.c:215:23: error: incomplete definition of type 'struct auframe'
        stats->n_samp   += af->sampc;
                           ~~^
include/baresip.h:42:8: note: forward declaration of 'struct auframe'
struct auframe;
       ^
modules/auloop/auloop.c:224:33: error: incomplete definition of type 'struct auframe'
        err = aubuf_write(al->aubuf, af->sampv, auframe_size(af));
                                     ~~^
include/baresip.h:42:8: note: forward declaration of 'struct auframe'
struct auframe;
       ^
modules/auloop/auloop.c:224:42: warning: implicit declaration of function 'auframe_size' is invalid in C99 [-Wimplicit-function-declaration]
        err = aubuf_write(al->aubuf, af->sampv, auframe_size(af));
                                                ^
modules/auloop/auloop.c:234:21: warning: implicit declaration of function 'auframe_size' is invalid in C99 [-Wimplicit-function-declaration]
        size_t num_bytes = auframe_size(af);
                           ^
modules/auloop/auloop.c:237:8: error: incomplete definition of type 'struct auframe'
        if (af->fmt != al->fmt) {
            ~~^
include/baresip.h:42:8: note: forward declaration of 'struct auframe'
struct auframe;
       ^
modules/auloop/auloop.c:239:38: error: incomplete definition of type 'struct auframe'
                        aufmt_name(al->fmt), aufmt_name(af->fmt));
                                                        ~~^
include/baresip.h:42:8: note: forward declaration of 'struct auframe'
struct auframe;
       ^
modules/auloop/auloop.c:244:23: error: incomplete definition of type 'struct auframe'
        stats->n_samp   += af->sampc;
                           ~~^
include/baresip.h:42:8: note: forward declaration of 'struct auframe'
struct auframe;
       ^
modules/auloop/auloop.c:254:26: error: incomplete definition of type 'struct auframe'
        aubuf_read(al->aubuf, af->sampv, num_bytes);
                              ~~^
include/baresip.h:42:8: note: forward declaration of 'struct auframe'
struct auframe;
       ^
2 warnings and 8 errors generated.
gmake: *** [mk/mod.mk:49: build-x86_64/modules/auloop/auloop.o] Error 1

```

**Comment by sreimers** [comment]
Your librem version is not up-to-date. It is interesting that there are no pkg-config error about it. I think you have librem.pc somewhere on your system with the right version but "../rem" is outdated for example.

**Comment by alfredh** [comment]
I have compiled re,rem,baresip on FreeBSD and it works fine

**Comment by jungle-boogie** [comment]
Hi,

That’s good news.

Do you suspect it would be different for OpenBSD? Did you already have re,
rem, and baresip installed?
Sebastian thinks old, existing versions are interfering with it.

Thanks!

>

**Comment by alfredh** [comment]
try to uninstall all first

then make a clean install

**Comment by jungle-boogie** [comment]
Uninstalled all

Verified all were uninstalled by looking in /usr/local/lib and
/usr/local/include

re from master installed without any issues

rem won’t install, because of “bad libre version”.  Required version is >=
2.0.1-dev

**Comment by alfredh** [comment]
please cd to rem and do this:

```
$ git remote -v
```

**Comment by jungle-boogie** [comment]
Results:

https://termbin.com/kzzw

By the way, is there an irc room for baresip on liberachat?

**Comment by sreimers** [comment]
can you check if more than one libre.pc file exists?:

```bash
find / -name "libre.pc"
```
And what version string it contains, it should look like this:

```
prefix=/usr/local
exec_prefix=${prefix}
libdir=/usr/local/lib
includedir=${prefix}/include/re

Name: libre
Description: Generic library for real-time communications with async IO support
Version: 2.0.1-dev4
URL: https://github.com/baresip/re
Libs: -L${libdir} -lre
Libs.private: -L${libdir} -lre -ldl -lssl -lcrypto -lz -lpthread
Cflags: -I${includedir}
```

**Comment by jungle-boogie** [comment]
Please see results here:

http://termbin.com/66m4

**Comment by sreimers** [comment]
It looks like openbsd uses a own perl based pkg-config version which has problems with our dev version string. normal releases should work. I have to think about how we can solve this. Maybe we exclude openbsd from version check or specific pkg-versions.

**Comment by jungle-boogie** [comment]
Ah, that must be it

https://man.openbsd.org/pkg-config

**Comment by jungle-boogie** [comment]
OpenBSD has autoconf-2.71 in ports/packages.
Does that help on this case?

https://openports.pl/path/devel/autoconf/2.71

**Comment by jungle-boogie** [comment]
Good news!

I was able to build rem and baresip from the latest source changes.

Thank you for all the progress you’ve made!

**Comment by sreimers** [comment]
I fixed this now by disabling pkg-config on openbsd. The last commits are using --modversion and this has also a different syntax on openbsd. Thanks for reporting.
