### ISSUE TITLE
How best to drop/ignore audio for audio_player? 

### ISSUE THREAD

**Issue by quentusrex** [baresip/baresip#1530]
Working on a testing system, and trying to use ausine to generate audio packets, and have aubridge,dummy basically receive and ignore/overwrite the inbound audio.

Currently getting call setup failures due to aubridge setup issue:
call: update media
stream: update 'audio'
audio: RTP/RTCP multiplexing enabled
stream: audio: starting RTCP with remote 145.40.67.105:45634
audio: update
audio: Set audio decoder: opus 48000Hz 2ch
audio: start
audio: create recv buffer [20 - 160 ms] [3840 - 30720 bytes]
audio: start_player failed (aubridge.dummy): No such file or directory
call: update: audio_decoder_set error: No such file or directory
audio: Set audio encoder: opus 48000Hz 2ch
opus: encoder fmtp (stereo=1;sprop-stereo=1;maxaveragebitrate=48000)
audio: start
audio: start_player failed (aubridge.dummy): No such file or directory
ausine: 48000 Hz, 2 channels, frequency 800 Hz CH_MODE: 0
ausine: audio ptime=20 sampc=1920
audio: source started with sample format S16LE

Any suggestions on how to setup an audio_player that will accept the call audio, but not actually try to play it over any speakers, or file?

**Comment by negbie** [comment]
Something like shis should be enough. Make sure module aubridge is enabled.

audio_player            aubridge,nil
audio_source            ausine,362

**Comment by quentusrex** [comment]
Works great thanks. The issue I had hit previously was a typo in the config file for loading the module.
