### ISSUE TITLE
account: username:password is now disabled please use ;auth_pass=xxx instead

### ISSUE THREAD

**Issue by aleh4d** [baresip/baresip#1533]
Tried to call to Linphone using baresipy python wrapper: https://github.com/OpenJarbas/baresipy,
 got error in log:
18:31:56.752 - baresipy:run:289 - DEBUG - Creating UA for sip:adushkin1:**********@sip.linphone.org ...
18:31:56.754 - baresipy:run:289 - DEBUG - account: username:password is now disabled please use ;auth_pass=xxx instead

From Log:

CODE:
from baresipy import BareSIP
from time import sleep

to = "adushkin1@sip.linphone.org"

gateway = "sip.linphone.org"
user = "adushkin1"
pswd = "*********"

class JokeBOT(BareSIP):
def handle_incoming_call(self, number):
self.accept_call()

def handle_call_established(self):
    self.speak("Welcome to the jokes bot")
    self.speak(get_joke())
    self.speak("Goodbye")
    self.hang()
b = JokeBOT(user, pswd, gateway, None, True)

b.call(to)

while b.running:
sleep(0.5)
if b.call_established:
b.send_dtmf("123")
b.speak("this is jarbas personal assistant speaking. this was a test")
b.speak("Goodbye")
b.hang()
b.quit()

**Comment by sreimers** [comment]
This is not a baresip issue. You try this: https://github.com/OpenJarbas/baresipy/pull/1
