### ISSUE TITLE
menu error

### ISSUE THREAD

**Issue by juha-h** [baresip/baresip#1539]
I have in config
```
audio_source		gst,file:///tmp/digits.wav
```
and when call (inbound or outbound) terminates, menu gives audio error message:
```
gst: end of file26114/0 (bit/s)    
menu: audio error (0,end of file)
alsa: write: wrote 5 of 960 samples
```
Otherwise the call works fine.

**Comment by cspiel1** [comment]
@RobertMi21 or me will have a look on this.

**Comment by RobertMi21** [comment]
Hello I tried to reproduce this issue.

First I copied the ring.wav file from the share directory to /tmp. 

Then I added the following to my config:

audio_source		gst,file:///tmp/ring.wav

But everthing worked as expected (I can hear the content of the ring.wav on the calling device).

Can you please check, if this works on your machine?

**Comment by juha-h** [comment]
Robert Mittermaier writes:

> Hello I tried to reproduce this issue.
> 
> First I copied the ring.wav file from the share directory to /tmp. 
> 
> Then I added the following to my config:
> 
> audio_source		gst,file:///tmp/ring.wav
> 
> But everthing worked as expected (I can hear the content of the ring.wav on the calling device).
> 
> Can you please check, if this works on your machine?

Tried on Debian Linux with
```
audio_source		gst,file:///usr/share/baresip/ring.wav
```
and got the same error message:
```
stream: incoming rtp for 'audio' established, receiving from 192.168.43.160:50102
gst: end of file0/0 (bit/s)    
menu: audio error (0,end of file)
```

**Comment by juha-h** [comment]
Should I close this, since it is just a cosmetic issue?

**Comment by negbie** [comment]
@juha-h I think it was implemented on purpose https://github.com/baresip/baresip/issues/539. Maybe it should be a warning instead of error?

**Comment by juha-h** [comment]
Eugen Biegler writes:

> @juha-h I think it was implemented on purpose
> https://github.com/baresip/baresip/issues/539. Maybe it should be a
> warning instead of error?

Yes, looks like currently also eof is covered by the same ua event
as error, which in eof case results in misleading menu message.

**Comment by RobertMi21** [comment]
Can you check the PR (#1550), if this kind of fix is OK for you?

**Comment by juha-h** [comment]
I still get red warning line to console:
```
audio: ausrc warning (end of file)/s) efps=0.0/0.0
```
which indicates that something went wrong although everything is OK.

**Comment by juha-h** [comment]
How about changing warning to info?

**Comment by RobertMi21** [comment]
Ok, I will change it.
