### ISSUE TITLE
"protocol not supported" error

### ISSUE THREAD

**Issue by juha-h** [baresip/baresip#1540]
I upgraded my Android baresip app to latest libbaresip master and noticed that it cannot anymore register at the same time over mobile network and WiFi.  Account using WiFi gives error message:
```
07-19 17:22:37.663  9462  9499 D Baresip Lib: ua event (REGISTER_FAIL) Protocol not supported
07-19 17:22:37.664  9462  9500 D Baresip Lib: reg: sip:foo@test.tutpro.com (prio 0): Register: Protocol not supported
```
Network debug gives the same output both with earlier working version and the latest failing one:
```07-19 17:26:03.972  9981 10009 D Baresip Lib: --- Network debug ---
07-19 17:26:03.972  9981 10009 D Baresip Lib:  Local IPv4:  [E] ccmni0|10.179.165.0
07-19 17:26:03.972  9981 10009 D Baresip Lib:  Local IPv6:  [E] ???|2001:14bb:677:f6fc::3098:d301
07-19 17:26:03.972  9981 10009 D Baresip Lib: net interfaces:
07-19 17:26:03.972  9981 10009 D Baresip Lib:          lo:  127.0.0.1
07-19 17:26:03.972  9981 10009 D Baresip Lib:      ccmni0:  10.179.165.0
07-19 17:26:03.972  9981 10009 D Baresip Lib:         ap0:  192.168.43.19
```
Any ideas?

**Comment by juha-h** [comment]
I did git checkout of re at commit https://github.com/baresip/re/commit/4b91257d52fa9478d581a80a8a6511e980cfe7dc, i.e., before commit `net,sip: check if destination is reachable when selecting transport` and I was able again to register all accounts, some of them over WiFi and some over mobile network.  So looks like something got broken by the latter commit.

**Comment by juha-h** [comment]
I double checked this.  When I replace in re master file src/sip/transp.c with the one from Jul 13, 2021, all registrations work fine.  With latest master version of src/sip/transp.c, only accounts that use mobile network (local address 10.179.165.0) can register and the ones that use WiFi (local address 192.168.43.19) fail to register and produce "protocol not supported" error.

**Comment by juha-h** [comment]
Here is ngrep of working REGISTER request before the `net,sip: check if destination is reachable when selecting transport` commit:
```
T 2021/07/19 19:02:15.420333 192.168.43.19:58928 -> 192.168.43.160:5060 [AP] #8
REGISTER sip:test.tutpro.com SIP/2.0.
Via: SIP/2.0/TCP 10.179.165.0:56015;branch=z9hG4bKad51af64356814ed;rport.
Contact: <sip:foo-0x78fa095bd0@10.179.165.0:56015;transport=tcp>;expires=3600;+sip.instance="<urn:uuid:e19944e2-ed33-f15d-6d45-47834f97631e>";q=0.5;reg-id=1.
```
As you see source address is of `ap0` interface and message addresses are of `ccmni0` interface and that is fine with my registrar.

**Comment by juha-h** [comment]
Forgot to mention that foo@test.tutpro.com account config has
```
;outbound="sip:lohi.tutpro.com:5060;transport=tcp"
```
and DNS tells
```
$ host lohi.tutpro.com
lohi.tutpro.com has address 192.168.43.160
```
and termux `ping lohi.tutpro.com` works fine on this Android device.

So for sure, the registrar is reachable.

If this issue cannot be easily fixed, I would suggest that commit https://github.com/baresip/re/commit/82dd86736b55c471947c41ed0c64de787282b606 is reverted until the problem is solved.

**Comment by sreimers** [comment]
Can you add this patch, for testing:

```diff
--- a/src/sip/transp.c
+++ b/src/sip/transp.c
@@ -152,6 +152,7 @@ static const struct sip_transport *transp_find(struct sip *sip,
 {
        struct le *le;
        struct sa dsttmp;
+       int err;
 
        for (le = sip->transpl.head; le; le = le->next) {
 
@@ -174,8 +175,9 @@ static const struct sip_transport *transp_find(struct sip *sip,
                sa_cpy(&dsttmp, dst);
                sa_set_scopeid(&dsttmp, sa_scopeid(laddr));
 
-               if (net_dst_source_addr_get(&dsttmp, &src))
-                       continue;
+               err = net_dst_source_addr_get(&dsttmp, &src);
+               if (err)
+                       DEBUG_WARNING("transp_find: %m (%J)\n", err, &dsttmp);
 
                if (!sa_cmp(&src, laddr, SA_ADDR))
                        continue;
```

**Comment by cspiel1** [comment]
I will have a look on this.

**Comment by cspiel1** [comment]
@juha-h Please could you give the complete account line! On a first try I could not reproduce this.

**Comment by juha-h** [comment]
Sebastian Reimers writes:

> Can you add this patch, for testing:

Tried and didn't get the DEBUG_WARNING. Still fails:
```
07-20 10:37:07.328 24902 25011 D Baresip Lib: reg: ***@***.*** (prio 0): Register: Protocol not supported
07-20 10:37:07.328 24902 25010 D Baresip Lib: ua event (REGISTER_FAIL) Protocol not supported
```

**Comment by juha-h** [comment]
Here is the account line:
```
"Foo" <sip:foo@test.tutpro.com>;auth_pass="xxxxxx";outbound="sip:lohi.tutpro.com:5060;transport=tcp";sipnat=outbound;audio_codecs=AMR-WB/16000/1,opus/16000/1,AMR/8000/1,G722/16000/1,G726-32/8000/1,G726-24/8000/1,G726-16/8000/1,G729/8000/1,PCMU/8000/1,PCMA/8000/1;mwi=yes;vm_uri="sip:*10@test.tutpro.com";ptime=20;regint=3600;regq=0.5;pubint=0;call_transfer=yes
```
Do you have same kind of net interfaces setup?

**Comment by cspiel1** [comment]
I suppose that this is the problem currently:
```
		if (!sa_cmp(&src, laddr, SA_ADDR))
			continue;
```
We need all local addresses as transport. They have to be added by baresip. For the moment we should remove this check.
@juha-h Please could you try again without this check?

**Comment by juha-h** [comment]
Christian Spielberger writes:

> I suppose that this is the problem currently:
> ```
> 		if (!sa_cmp(&src, laddr, SA_ADDR))
> 			continue;
> ```
> We need all local addresses as transport. They have to be added by baresip. For the moment we should remove this check.
> @juha-h Please could you try again without this check?

Registration worked OK when I commented out the above test.

**Comment by cspiel1** [comment]
Thanks! Will revert this or a part of it right now.

**Comment by cspiel1** [comment]
Again was thinking about this and came to the result, that the correct solution is to add a fallback transport pointer. A transport object where the `laddr` matches the address found by `net_dst_source_addr_get()` will be preferred. But if not found the fallback transport is returned. This guaranties the old behavior if not all `laddr`s are added by baresip. Here is the PR: https://github.com/baresip/re/pull/132

**Comment by juha-h** [comment]
PR https://github.com/baresip/re/pull/132 fixed the issue.
