### ISSUE TITLE
Too many "ua: using best effort AF" messages in a pending state.

### ISSUE THREAD

**Issue by viordash** [baresip/baresip#1546]
By debugging, I determined that the server periodically sends OPTIONS request, and baresip generates this message (https://github.com/baresip/baresip/blob/327af08e56e082b8dae52a4553ece22c20a1df07/src/ua.c#L715).
It probably makes sense to generate this message in the debug level, it probably does not carry important information?
I cannot disable the "info" level itself, as it contains important information (bindings, change of IP-address, etc.)

**Comment by alfredh** [comment]
change this to debug is fine, also removing it is fine.

can you please make a PR with your suggested change ?

**Comment by viordash** [comment]
Thanks. I prepared it, #1553
