### ISSUE TITLE
New Defects reported by Coverity Scan

### ISSUE THREAD

**Issue by alfredh** [baresip/baresip#1558]
Hi,

Please find the latest report on new defect(s) introduced to alfredh/baresip found with Coverity Scan.

4 new defect(s) introduced to alfredh/baresip found with Coverity Scan.
3 defect(s), reported by Coverity Scan earlier, were marked fixed in the recent build analyzed by Coverity Scan.

New defect(s) Reported-by: Coverity Scan
Showing 4 of 4 defect(s)

** CID 333030:  Security best practices violations  (STRING_OVERFLOW)
/src/config.c: 260 in decode_sip_transports()

________________________________________________________________________________________________________
*** CID 333030:  Security best practices violations  (STRING_OVERFLOW)
/src/config.c: 260 in decode_sip_transports()
254     
255     	for (i = 0; i < SIP_TRANSPC; ++i) {
256     		bool en;
257     		char buf[9];
258     		struct pl e=PL_INIT;
259     
>>>     CID 333030:  Security best practices violations  (STRING_OVERFLOW)
>>>     You might overrun the 9-character fixed-size string "buf" by copying the return value of "sip_transp_name" without checking the length.
260     		strcpy(buf, sip_transp_name(i));
261     		strcat(buf, "[^,]+");
262     		en = 0 == re_regex(pl->p, pl->l, sip_transp_name(i)) &&
263     		     0 != re_regex(pl->p, pl->l, buf, &e);
264     		u32mask_enable(&cfg->transports, i, en);
265     	}

** CID 333029:  Null pointer dereferences  (REVERSE_INULL)
/modules/amr/amr.c: 339 in encode_nb()

________________________________________________________________________________________________________
*** CID 333029:  Null pointer dereferences  (REVERSE_INULL)
/modules/amr/amr.c: 339 in encode_nb()
333     		     size_t *len, int fmt, const void *sampv, size_t sampc)
334     {
335     	const struct amr_aucodec *amr_ac = (struct amr_aucodec *)st->ac;
336     	int r;
337     	(void)marker;
338     
>>>     CID 333029:  Null pointer dereferences  (REVERSE_INULL)
>>>     Null-checking "st" suggests that it may be null, but it has already been dereferenced on all paths leading to the check.
339     	if (!st || !buf || !len || !sampv || sampc != FRAMESIZE_NB)
340     		return EINVAL;
341     	if (*len < NB_SERIAL_MAX)
342     		return ENOMEM;
343     
344     	if (fmt != AUFMT_S16LE)

** CID 333028:  Null pointer dereferences  (REVERSE_INULL)
/modules/amr/amr.c: 372 in decode_nb()

________________________________________________________________________________________________________
*** CID 333028:  Null pointer dereferences  (REVERSE_INULL)
/modules/amr/amr.c: 372 in decode_nb()
366     		     size_t *sampc,
367     		     bool marker, const uint8_t *buf, size_t len)
368     {
369     	const struct amr_aucodec *amr_ac = (struct amr_aucodec *)st->ac;
370     	(void)marker;
371     
>>>     CID 333028:  Null pointer dereferences  (REVERSE_INULL)
>>>     Null-checking "st" suggests that it may be null, but it has already been dereferenced on all paths leading to the check.
372     	if (!st || !sampv || !sampc || !buf)
373     		return EINVAL;
374     
375     	if (len > NB_SERIAL_MAX)
376     		return EPROTO;
377     

** CID 333027:  Null pointer dereferences  (REVERSE_INULL)
/src/call.c: 1109 in call_progress()

________________________________________________________________________________________________________
*** CID 333027:  Null pointer dereferences  (REVERSE_INULL)
/src/call.c: 1109 in call_progress()
1103     	enum sdp_dir adir;
1104     	enum sdp_dir vdir;
1105     	enum sdp_dir ansadir;
1106     	enum sdp_dir ansvdir;
1107     	int err;
1108     
>>>     CID 333027:  Null pointer dereferences  (REVERSE_INULL)
>>>     Null-checking "call" suggests that it may be null, but it has already been dereferenced on all paths leading to the check.
1109     	if (!call)
1110     		return EINVAL;
1111     
1112     	tmr_cancel(&call->tmr_inv);
1113     
1114     	ansadir = stream_ldir(audio_strm(call_audio(call)));

**Comment by alfredh** [comment]
hi @cspiel1 

could you please have a look at this one:

```c
static void decode_sip_transports(struct config_sip *cfg,
				      const struct pl *pl)
{
	uint8_t i;

	for (i = 0; i < SIP_TRANSPC; ++i) {
		bool en;
		char buf[9];
		struct pl e=PL_INIT;

		strcpy(buf, sip_transp_name(i));
		strcat(buf, "[^,]+");
		en = 0 == re_regex(pl->p, pl->l, sip_transp_name(i)) &&
		     0 != re_regex(pl->p, pl->l, buf, &e);
		u32mask_enable(&cfg->transports, i, en);
	}
}
```

it is probably better to use a buf size that is power of 2 (e.g. 16,32,64 etc.)
and use re_snprintf to print into the buffer.

**Comment by alfredh** [comment]
```c
static int module_read_config_handler(const struct pl *pl, void *arg)
476{
477        struct cmd_arg cmd_arg;
478        char buf[48 + 5 + 10];
479        int err = 0;
480        int n = 0;
481        int *prio = (int *) arg;
482
483        if (pl_strchr(pl, '-'))
484                goto out;
485
486        n = re_snprintf(buf, 48 + 4, "addr=%r prio=%d", pl, *prio);
   	cond_at_most: Condition n < 0, taking true branch. Now the value of n is at most -1.
   	at_most: At condition n > 53, the value of n must be at most -1.
   	dead_error_condition: The condition n > 53 cannot be true.
487        if (n < 0 && n > 48 + 5)
   	
CID 331112 (#1 of 1): Logically dead code (DEADCODE)
dead_error_line: Execution cannot reach this statement: goto out;.
488                goto out;
489
490        cmd_arg.prm = buf;
491        err = cmd_mcreg(NULL, &cmd_arg);
492
493  out:
494        if (!err)
495                (*prio)++;
496
497        return err;
498}
499
```

**Comment by alfredh** [comment]
<img width="1022" alt="Screenshot 2021-08-04 at 10 54 19" src="https://user-images.githubusercontent.com/114750/128152922-e39fc798-6763-40d6-93ef-6e72834f7281.png">

**Comment by cspiel1** [comment]
good work! :-)
