### ISSUE TITLE
error when $make in linux

### ISSUE THREAD

**Issue by maverick077** [baresip/baresip#1567]
modules/ctrl_tcp/ctrl_tcp.c:192:14: error: dereferencing pointer to incomplete type ‘const struct odict_entry’
  192 |        oe_cmd->u.str,
      |              ^~
make: *** [mk/mod.mk:49: build-x86_64/modules/ctrl_tcp/ctrl_tcp.o] Error 1

![1](https://user-images.githubusercontent.com/67913398/128600021-5132f4b7-2d02-452d-84da-9b2469dd65a3.jpg)

**Comment by sreimers** [comment]
You have a newer libre dev version than baresip. Upgrade baresip to latest upstream should work (or downgrade libre).

**Comment by maverick077** [comment]
But all I used are the latest. I tried re V2.0.0(downgrade) and the latest baresip just now, but it has new problems. Is it also because of the version?
![1](https://user-images.githubusercontent.com/67913398/128601842-c6f91b5c-fa17-468c-993d-c75143f8decc.jpg)

**Comment by sreimers** [comment]
For stable please follow: https://github.com/baresip/baresip/wiki/Install:-Stable-Release

For dev builds: https://github.com/baresip/baresip/wiki/Install:-GIT-Version

Mixing git/dev versions with release versions is not supported.

**Comment by maverick077** [comment]
Thank you for your support. I run it successfully on linux. I have other questions.
1. Does local accounts run without proxy server? I also expect to know other ways to P2P calls between two SIP clients when using baresip.
2. More information for installing baresip on windows is needed. When I try to compile baresip.sln, there are many warnings, and error "auframe.c" is not found.
![1](https://user-images.githubusercontent.com/67913398/128626889-a754dcfe-e836-4cf3-b490-19cfd9490137.jpg)
