### ISSUE TITLE
websocket transport issue

### ISSUE THREAD

**Issue by juha-h** [baresip/baresip#1568]
If I define in account  of test@test.tutpro.com `;outbound="sip:test.tutpro.com:5061;transport=wss"`, baresip sends out this kind of INVITE to SIP Proxy:
```
INVITE sip:jh@test.tutpro.com SIP/2.0
Via: SIP/2.0/WSS 192.168.43.160:9;branch=z9hG4bKdc8ebce9a2bfcefc;rport
Contact: <sip:test@test.tutpro.com;gr=urn:uuid:9b21c1a8-dc58-a3d6-83d5-7be67cbe70ce>
Max-Forwards: 70
Route: <sip:lohi.tutpro.com:5061;transport=wss;lr>
To: <sip:jh@test.tutpro.com>
From: "Test Account" <sip:test@test.tutpro.com>;tag=fe887a11b42597e0
...
```
Via header is OK, but according to https://datatracker.ietf.org/doc/html/rfc7118#section-8.2, ;transport value of Route URI should be `ws`, not `wss`.

I vaguely remember that this issue has been discussed earlier, but don't remember, what the conclusion was.

**Comment by juha-h** [comment]
How about only supporting secure websocket transport, i.e., `;outbound="sip:test.tutpro.com:5061;transport=ws"`, would mean sebsocket over tls?

**Comment by alfredh** [comment]
hi,

you can try to change the string from wss to ws, and see if it works.

have a look at JSsip how they do it

**Comment by juha-h** [comment]
I have tried with `;outbound="sip:test.tutpro.com:5061;transport=ws"` and then baresip uses http, not https.

**Comment by alfredh** [comment]
what I meant was, try to change the wss string here in the code:

```c
const char *sip_transp_param(enum sip_transp tp)
{
	switch (tp) {

	case SIP_TRANSP_UDP: return "";
	case SIP_TRANSP_TCP: return ";transport=tcp";
	case SIP_TRANSP_TLS: return ";transport=tls";
	case SIP_TRANSP_WS:  return ";transport=ws";
	case SIP_TRANSP_WSS: return ";transport=wss";
	default:             return "";
	}
}
```

**Comment by juha-h** [comment]
Looks like baresip takes route header URI  from `;outbound` value.  Thus changing `sip_transp_param` function does not help.

**Comment by juha-h** [comment]
After these two changes:
```
$ git diff
diff --git a/src/sip/transp.c b/src/sip/transp.c
index 793713a..7c31b4f 100644
--- a/src/sip/transp.c
+++ b/src/sip/transp.c
@@ -1593,7 +1593,7 @@ const char *sip_transp_param(enum sip_transp tp)
    case SIP_TRANSP_TCP: return ";transport=tcp";
    case SIP_TRANSP_TLS: return ";transport=tls";
    case SIP_TRANSP_WS:  return ";transport=ws";
-   case SIP_TRANSP_WSS: return ";transport=wss";
+   case SIP_TRANSP_WSS: return ";transport=ws";
    default:             return "";
    }
 }
@@ -1609,7 +1609,7 @@ enum sip_transp sip_transp_decode(const struct pl *pl)
    else if (!pl_strcasecmp(pl, "tls"))
        tp = SIP_TRANSP_TLS;
    else if (!pl_strcasecmp(pl, "ws"))
-       tp = SIP_TRANSP_WS;
+       tp = SIP_TRANSP_WSS;
    else if (!pl_strcasecmp(pl, "wss"))
        tp = SIP_TRANSP_WSS;
 ```
INVITE has correct Route URI:
```
INVITE sip:jh@test.tutpro.com SIP/2.0
Via: SIP/2.0/WSS 192.168.43.160:9;branch=z9hG4bK5a534789c7591ab7;rport
Contact: <sip:test@test.tutpro.com;gr=urn:uuid:9b21c1a8-dc58-a3d6-83d5-7be67cbe70ce>
Max-Forwards: 70
Route: <sip:lohi.tutpro.com:5061;transport=ws;lr>
To: <sip:jh@test.tutpro.com>
From: "Test Account" <sip:test@test.tutpro.com>;tag=4f4703b61dd7ef20
Call-ID: 59358015c6298da3
```
Account outbound is defined like this:
```
;outbound="sip:lohi.tutpro.com:5061;transport=ws
```
and only secure websocket transport is thus supported.

**Comment by alfredh** [comment]
if you want to follow the RFC, it should be fine to say that input is =wss and route header has
transport ws.

**Comment by juha-h** [comment]
Alfred E. Heggestad writes:

> if you want to follow the RFC, it should be fine to say that input is
> =wss and route header has transport ws.

Yes, but looks like Route header URI is taken directly from ;outbound
URI and the change needs to be done somewhere else than in re transp.c.

**Comment by juha-h** [comment]
It is messy to change `;transport=wss` to `;transport=ws` on re/src/sip/dialog.c line
```
err |= mbuf_printf(dlg->mb, "Route: <%s;lr>\r\n", routev[i]);
```
My suggestion is to only support secure web socket transport and indicate that with outbound `;transport=ws`.

**Comment by alfredh** [comment]
since we support both WS and WSS it seems like a bad idea to remove support for WS
just to solve this case.

it is fine to add support for a new uri scheme (wss).

we could also add a new parameter that is only valid for HTTP/WS proxy:

```
;wss_outbound=wss://www.example.com/path
```

**Comment by juha-h** [comment]
That would be great if someone has time and know how to do it.  Otherwise we could close this and add to Roadmap.

**Comment by alfredh** [comment]
please add the feature to the Roadmap. I dont have any time to implement this at the moment,
I have many things to do at the moment.

**Comment by juha-h** [comment]
Done.  Came to mind that account config could also include a param telling if Route header with preloaded URI is included at all.
