### ISSUE TITLE
Bad access on disconnect/close ringing call

### ISSUE THREAD

**Issue by Koshub** [baresip/baresip#1572]
I use Baresip 1.0.0 as a library. When the user hangs up while a call is **ringing** I call `ua_disconnect` (not from the `re_main` thread) and "close" the baresip stack. Apparently, at that moment I receive a bad access exception. It is hard to provide faster more logs and info so for now I can just attach stack screenshots.

![baresip_issue_start_source](https://user-images.githubusercontent.com/7643346/129332920-108044bd-35f4-4f39-a6da-cf1bf8385d63.jpg)
![baresip_issue_str_isset](https://user-images.githubusercontent.com/7643346/129332928-5ae82c3b-160f-4951-996d-e63a2cd77008.jpg)

**Comment by alfredh** [comment]
is the same bug also valid when running the baresip application ?

perhaps you can add some debug printf and check that the symbols are valid ?
for example:

```c
const struct ausrc *ausrc_find(const struct list *ausrcl, const char *name)
```

**Comment by alfredh** [comment]
please note that bugs here are related to the baresip application.

if you have made a custom application on top of libbaresip, please use the mailing-list to discuss.

if you want help you have to supply additional information so that we are able
to try to debug the case for you. Otherwise we just have to guess.

https://github.com/baresip/baresip/wiki/Guidelines-for-reporting-Issues

**Comment by Koshub** [comment]
Thank you for your reply. I will try to find out more info about this issue and will reopen with additional information.

**Comment by Koshub** [comment]
FYI. The issue was because of threading problems. The was only able to fix that by sending every call, like `ua_disconnect`, etc., to the `re_main` thread using `mqueue_push`, by associating code blocks with serial commands queue. That makes it harder to use the baresip api and forces to make some async work. Not sure it is a convenient way to use baresip api

Anyway, thanks for help earlier and this library.
