### ISSUE TITLE
libre.so.1 is not found

### ISSUE THREAD

**Issue by maverick077** [baresip/baresip#1574]
Libre.so.1 is not found when I try to run baresip
![1](https://user-images.githubusercontent.com/67913398/129531743-215e8ba8-9066-43bb-bf27-04cea61faa9a.jpg)

**Comment by sreimers** [comment]
For stable please follow: https://github.com/baresip/baresip/wiki/Install:-Stable-Release

For dev builds: https://github.com/baresip/baresip/wiki/Install:-GIT-Version

**Comment by maverick077** [comment]
It doesn't work. I use git version. I'm confused and cannot solve the problem. Can you give me some reference about the right version of libre, librem for baresip for stable-release?

**Comment by sreimers** [comment]
The current versions are listed as example here (its always the latest release)
https://github.com/baresip/baresip/wiki/Install:-Stable-Release

```Libre: Example: v2.0.1.tar.gz```

**Comment by maverick077** [comment]
So is it right to use the stabel release(baresip-1.1.0, libre-2.0.1, librem-1.0.0) or not?
I successfully run it on linux(x86) but fail on linux(arm) when I use the git version.

**Comment by alfredh** [comment]
can you try this:

`sudo ldconfig`

**Comment by afcady** [comment]
If you built `re` and `rem` from source,

and you did not install them,

then you can run `baresip` like this:

```
LD_LIBRARY_PATH=$PWD/re:$PWD/rem ./baresip
```

**Comment by afcady** [comment]
Hum, it still uses `/usr/lib/baresip/modules`, though.

**Comment by alfredh** [comment]
hi @maverick077 


can you please report the complete build log using this example:


```
cd re
make
sudo make install
sudo ldconfig
cd ..

cd rem
make
sudo make install
sudo ldconfig
cd ..

cd baresip
make
sudo make install

```

**Comment by maverick077** [comment]
Thanks, I neglect the command "sudo ldconfig".
