### ISSUE TITLE
make error with openssl  1.1.1k

### ISSUE THREAD

**Issue by zmxzmxzmxzmx** [baresip/baresip#1578]
LD      baresip
/usr/local/lib/libre.so: undefined reference to `BIO_get_data'
/usr/local/lib/libre.so: undefined reference to `BIO_meth_set_write'
/usr/local/lib/libre.so: undefined reference to `BIO_meth_set_ctrl'
/usr/local/lib/libre.so: undefined reference to `BIO_meth_set_create'
/usr/local/lib/libre.so: undefined reference to `X509_getm_notAfter'
/usr/local/lib/libre.so: undefined reference to `BIO_meth_free'
/usr/local/lib/libre.so: undefined reference to `BIO_meth_new'
/usr/local/lib/libre.so: undefined reference to `SSL_set1_host'
/usr/local/lib/libre.so: undefined reference to `X509_getm_notBefore'
/usr/local/lib/libre.so: undefined reference to `HMAC_CTX_free'
/usr/local/lib/libre.so: undefined reference to `BIO_set_init'
/usr/local/lib/libre.so: undefined reference to `OPENSSL_init_ssl'
/usr/local/lib/libre.so: undefined reference to `TLS_method'
/usr/local/lib/libre.so: undefined reference to `SSL_set_hostflags'
/usr/local/lib/libre.so: undefined reference to `HMAC_CTX_new'
/usr/local/lib/libre.so: undefined reference to `BIO_meth_set_destroy'
/usr/local/lib/libre.so: undefined reference to `SSL_get_state'
/usr/local/lib/libre.so: undefined reference to `BIO_set_data'
collect2: error: ld returned 1 exit status
make: *** [baresip] Error 1

My version is OpenSSL 1.1.1k

**Comment by alfredh** [comment]
https://github.com/baresip/baresip/wiki/Guidelines-for-reporting-Issues

please include info about your platform, and a full build log.

**Comment by alfredh** [comment]
closing due to lack of feedback. please reopen if you can provide additional info.
