### ISSUE TITLE
401 Unauthorized ()

### ISSUE THREAD

**Issue by maverick077** [baresip/baresip#1582]
Now I try to register a sip account on MiniSIPserver in LAN, but it shows that 
"
reg: sip:100@192.168.2.102 (prio 0): 401 Unauthorized ()
"
![微信图片_20210825100606](https://user-images.githubusercontent.com/67913398/130714412-36b881ea-de08-46de-b402-70c28bc01d77.png)

Is this a problem for baresip or the SIP server "MiniSIPserver"?
More information is needed, thanks.

**Comment by alfredh** [comment]
username:password is deprecated, please use auth_pass=PASSWORD instead
or disable authentication on the server.

Please study the template config and documentation

**Comment by alfredh** [comment]
I suggest that you start with the mailing-list if you have similar problems.

https://github.com/baresip/baresip/blob/master/docs/examples/accounts
