### ISSUE TITLE
Video encode and decode error

### ISSUE THREAD

**Issue by amneiht** [baresip/baresip#1610]
When I use Baresip+ on my android device , the  "vidcodec" not working well  , when I setting for caller with "video frame size": 960x720 , The frame is decoded in callee device is 3264 x 2448, @Note my two devide has other architecture but with 800x600 , 1024x768 everything is working well 

and on this device
![info](https://user-images.githubusercontent.com/25580403/134326007-81eb34d2-e629-4f5f-8166-ca0ed9a5eac6.png)

setting "video frame size":960x720 or "640x360" the app crash immediately when callee acepet the call

**Comment by alfredh** [comment]
perhaps this issue belongs here:

https://github.com/juha-h/baresip-studio
