### ISSUE TITLE
Win32 Build VS2019

### ISSUE THREAD

**Issue by AndyW999** [baresip/baresip#1620]
**Fresh pull of baresip, re, rem
Compile stops as auloop.c and vidloop.c not found.**

Error	C1083	Cannot open source file: '..\..\modules\auloop\auloop.c': No such file or directory	baresip-win32	H:\BareSIP Master\baresip\mk\win32\c1	1	

Error	C1083	Cannot open source file: '..\..\modules\vidloop\vidloop.c': No such file or directory	baresip-win32	H:\BareSIP Master\baresip\mk\win32\c1	1	

**Delete empty directories and remove exports in static.c.**

Error	LNK2019	unresolved external symbol _bundle_state referenced in function _encode_rtp_send	baresip-win32	H:\BareSIP Master\baresip\mk\win32\audio.obj	1	
Error	LNK2001	unresolved external symbol _bundle_state	baresip-win32	H:\BareSIP Master\baresip\mk\win32\stream.obj	1	
Error	LNK2001	unresolved external symbol _bundle_state	baresip-win32	H:\BareSIP Master\baresip\mk\win32\video.obj	1	
Error	LNK2019	unresolved external symbol _bundle_extmap_mid referenced in function _encode_rtp_send	baresip-win32	H:\BareSIP Master\baresip\mk\win32\audio.obj	1	
Error	LNK2001	unresolved external symbol _bundle_extmap_mid	baresip-win32	H:\BareSIP Master\baresip\mk\win32\video.obj	1	
Error	LNK2019	unresolved external symbol _bundle_sdp_encode referenced in function _call_alloc	baresip-win32	H:\BareSIP Master\baresip\mk\win32\call.obj	1	
Error	LNK2019	unresolved external symbol _bundle_sdp_decode referenced in function _call_accept	baresip-win32	H:\BareSIP Master\baresip\mk\win32\call.obj	1	
Error	LNK2019	unresolved external symbol _bundle_alloc referenced in function _stream_bundle_init	baresip-win32	H:\BareSIP Master\baresip\mk\win32\stream.obj	1	
Error	LNK2019	unresolved external symbol _bundle_handle_extmap referenced in function _stream_update	baresip-win32	H:\BareSIP Master\baresip\mk\win32\stream.obj	1	
Error	LNK2019	unresolved external symbol _bundle_start_socket referenced in function _stream_enable_bundle	baresip-win32	H:\BareSIP Master\baresip\mk\win32\stream.obj	1	
Error	LNK2019	unresolved external symbol _bundle_set_extmap referenced in function _stream_bundle_init	baresip-win32	H:\BareSIP Master\baresip\mk\win32\stream.obj	1	
Error	LNK2019	unresolved external symbol _bundle_set_state referenced in function _stream_enable_bundle	baresip-win32	H:\BareSIP Master\baresip\mk\win32\stream.obj	1	
Error	LNK2019	unresolved external symbol _bundle_debug referenced in function _stream_debug	baresip-win32	H:\BareSIP Master\baresip\mk\win32\stream.obj	1	
Error	LNK2019	unresolved external symbol _bundle_state_name referenced in function _stream_enable_bundle	baresip-win32	H:\BareSIP Master\baresip\mk\win32\stream.obj	1	

Any suggestions?

Thanks

Andy.

**Comment by alfredh** [comment]
can you try to change the VC project file:

- add bundle.c
- remove auloop/vidloop

**Comment by AndyW999** [comment]
Much better!

Just wish you had left Speex in!

Thanks

Andy.

**Comment by alfredh** [comment]
would you please be so kind to send a PR with the changes ?

speex codec is now deprecated, it has been replaced by opus.

**Comment by AndyW999** [comment]
If I knew what a PR was I could try!

I know Speex has been depreciated but it still works and the quality at 8kHz is about the same as Opus.

The attraction is that on embedded platforms - STM32 for example - Speex is a lot kinder on the CPU.

**Comment by juha-h** [comment]
AndyW999 writes:

> I know Speex has been depreciated but it still works and the quality
> at 8kHz is about the same as Opus.

How about narrow band arm as an alternative?

**Comment by AndyW999** [comment]
I already have Speex working!

**Comment by sreimers** [comment]
> If I knew what a PR was I could try!

https://docs.github.com/en/github/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/about-pull-requests
