### ISSUE TITLE
IP addresses in SDP may not match source IP address of request

### ISSUE THREAD

**Issue by juha-h** [baresip/baresip#1631]
It is well known that currently if destination of SIP request is a domain name, IP addresses in SDP may not match source IP address of request and it may happen that the UAS does not have route to such SDP addresses.

This issue has been discussed in connection with other issues and pull requests, but I feel that it deserves its own issue.

What would be the best solution to this issue?

**Comment by juha-h** [comment]
I check what twinkle does:
```
Send to: tcp:192.168.146.45:5060
REGISTER sip:test.tutpro.com SIP/2.0
Via: SIP/2.0/TCP 192.168.146.45:5068;rport;branch=z9hG4bKvyziahms
...
Contact: <sip:jh@192.168.146.45:5068;transport=tcp>;expires=3600
```
```
Send to: tcp:192.26.134.12:5060
INVITE sip:sua@sua.tutpro.com:5060 SIP/2.0
Via: SIP/2.0/TCP 192.26.134.1:5068;rport;branch=z9hG4bKiimnafcr
...
v=0
o=twinkle 669884219 207779194 IN IP4 192.26.134.1
...
```
It used in SDP the source address of the request.

**Comment by juha-h** [comment]
If UAC connects to UAS over VPN interface and uses default (Internet) network IP address in SDP, then UAS cannot either send early media to UAC (if it does not have route to Internet) or early media goes over Internet, which breaks the idea of VPN.

How about it baresip places a marker (e.g. non-ascii character) in message buffer, which re then replaces with address of the source interface just before sending the request out?  Or (like Kamailio does) instead of a single message buffer, could baresip use a list of buffers, that re then combines and places the source address between each?

**Comment by juha-h** [comment]
I studied the code a bit and in `sdp/msg.c/sdp_encode()` used a token (~ char) instead of laddr in the sdp buffer.  Then in `sip/request.c/request()`, I replaced the token with laddr.  That caused correct address to be used in the sdp, but the test failed because Content-Length header had wrong length value.  In order to fix that, Content-Length header should be added in `request()` function as is currently done with Via header.

This was just an experiment.  Better solution suggestions are welcome.

**Comment by juha-h** [comment]
It might be easier to figure out the Content-Length in `request()` if `struct sip_request` had separate buffers for request headers and request body.

**Comment by alfredh** [comment]
it should be possible to check which interface will be used for sending a SIP message,
and then communicate this back to the application/code that encodes the SDP.

a common scenario is to use a SIP registrar/proxy and have all outgoing requests going
through it. In this case we can just reuse the interface used by REGISTER.
your scenario is a slightly more corner-case.

**Comment by juha-h** [comment]
Alfred E. Heggestad writes:

> it should be possible to check which interface will be used for
> sending a SIP message, and then communicate this back to the
> application/code that encodes the SDP.

Sounds good, but don't know how to do it.  Also, it is not only the SDP,
but also Contact URI. The domain name may result to several IP addresses
that are tried serially until success. So for each try, there should be
this re->sdp encoder->re loop and also re->contact URI encoder->re
loop.

> a common scenario is to use a SIP registrar/proxy and have all
> outgoing requests going through it. In this case we can just reuse the
> interface used by REGISTER.

Yes, this is the common case when outbound proxy has been defined.  But
even in this common case, there can be two outbound proxies, each with
domain name in outbound proxy URI hostpart.  When one outbound proxy
fails or when an outbound proxy DNS hostname results in more than one IP
address, the re->sdp encoder->re and re->contact URI encoder-> re loops
would still be needed.

> your scenario is a slightly more corner-case.

I agree.  The most important case that users of my Android app have
communicated to me is use of correct network when VPN one of the is the
VPN one.

**Comment by juha-h** [comment]
Could we remove the two Network entries from Roadmap:

https://github.com/baresip/baresip/wiki/Roadmap#network

I think they are now done.

**Comment by cspiel1** [comment]
Ideed. I removed it right now.
