### ISSUE TITLE
mediaenc=dtls_srtp actually is mediaenc=dtls_srtpf

### ISSUE THREAD

**Issue by juha-h** [baresip/baresip#1649]
Media encryption value `dtls_srtp` is misleading, because it actually means `dtls_srtpf`, for example:
```
m=audio 30936 UDP/TLS/RTP/SAVPF 96 97 98 9 18 0 8 101
```
UDP/TLS/RTP/SAVP does exists, but is not supported by baresip:
```
RTP/SAVP (srtp-mand)
RTP/SAVPF (srtp-mandf) 
UDP/TLS/RTP/SAVP (-)
UDP/TLS/RTP/SAVPF (dtls_srtp)
```
Should the value be changed?

**Comment by alfredh** [comment]
I think this is nit-picking, you can change the name if you want but it would not have any
practical implications.

media feedback is enabled all the time. it does not make sense to disable it.

what matters is basic interop with WebRTC endpoints.

**Comment by juha-h** [comment]
Alfred E. Heggestad writes:

> I think this is nit-picking, you can change the name if you want but
> it would not have any practical implications.

I agree.  I'll check if it is easy to allow both dtls_srtp and
dtls_srtpf.

**Comment by juha-h** [comment]
I'll give up on this, since adding a second id ("dtls_srtpf") is not possible and changing the id would not be backwards compatible.
