### ISSUE TITLE
baresip does not support G729 codec 

### ISSUE THREAD

**Issue by Anisel** [baresip/baresip#1652]
Hello,

I would like to use baresip as sip agent. but it doesn't support G729 codec.
The baresip can support G719 codec ?
is it in your road map to integrate it in the next release of baresip ?

**Comment by juha-h** [comment]
See this: https://github.com/baresip/baresip/pull/1127

**Comment by Anisel** [comment]
I can't see the branch g729 ! is not opened for public ?

**Comment by juha-h** [comment]
Anisel writes:

> I can't see the branch g729 ! is not opened for public ?

Most likely I deleted the branch after closing the PR.

Take a look at this:

https://github.com/juha-h/libbaresip-android/tree/master/baresip-g729

**Comment by alfredh** [comment]
https://github.com/baresip/baresip/wiki/G.729-codec

you are welcome to implement g.729 and contribute a new module :)
