### ISSUE TITLE
NETSTRING_ERROR_NO_LENGTH ctrl_tcp_listen

### ISSUE THREAD

**Issue by projetoarduino** [baresip/baresip#1655]
Hi guys

I try control baresip via tcp socket

For the tests,  i make the connection with  `telnet 127.0.0.1 4444`

And paste the line

` {"command":"dial","params":"sip:alice@atlanta.com","token":"qwerasdf"}`

 and enter

This is correct  way?

In other console with the baresip running i receive this message 

`tcp_netstring: receive: NETSTRING_ERROR_NO_LENGTH`

**Comment by cspiel1** [comment]
This is not an issue! Please use the mailing list https://groups.google.com/g/baresip for questions!

You are missing the length field of the netstring. See https://en.wikipedia.org/wiki/Netstring !

**Comment by projetoarduino** [comment]
Ok thanks!

Only to register, this work

```
var net = require('net');

var client = new net.Socket();
client.connect(4444, '192.168.1.161', function() {
	let mess = `{"command":"dial","params":"sip:100@voipserver.com"}`
	client.write(mess.length+":"+mess+",");
        console.log(mess.length+":"+mess+",")
});

client.on('data', function(data) {
	console.log('Received: ' + data);
	//client.destroy(); // kill client after server's response
});

client.on('close', function() {
	console.log('Connection closed');
});
```

**Comment by Bettman66** [comment]
You can use Netstring.
` client.write(Netstring.write('{"command":"' + command + '","params":"' + str + '"}'));`
[https://github.com/Bettman66/ioBroker.doorio/blob/master/lib/client.js](url)
