### ISSUE TITLE
Number Pad does not open on Locked Screen

### ISSUE THREAD

**Issue by paskalito** [baresip/baresip#1656]
Thanks a tousand times for this app!

Version 35.0.0
Android 9, Lineage OS

I just figured, that when i accept a call from the Locked phone, i am not able to open the Keybord neccecarry to give an input into a Phone/Asterix System. > So i can not interact with it.

I don´t know if that is a restriction of  Androids "show things over the lock screen" ability tough.

**Comment by sreimers** [comment]
Please put your issue here: https://github.com/juha-h/baresip-studio
