### ISSUE TITLE
Possible missing locking in the method coreaudio_recorder_alloc

### ISSUE THREAD

**Issue by ycaibb** [baresip/baresip#1665]
Hi developers, thank you for your checking.

In the coreaudio_recorder_alloc method, `st->rh  = rh; and st->arg = arg;` are not guarded.
https://github.com/baresip/baresip/blob/51f1ae02233cab40d37ffe346e42489aae276d1f/modules/coreaudio/recorder.c#L103-L108

`st->rh  = rh; and st->arg = arg;` are guarded in other near methods.
https://github.com/baresip/baresip/blob/51f1ae02233cab40d37ffe346e42489aae276d1f/modules/coreaudio/recorder.c#L35-L37

https://github.com/baresip/baresip/blob/51f1ae02233cab40d37ffe346e42489aae276d1f/modules/coreaudio/recorder.c#L68-L71

**Comment by sreimers** [comment]
The record thread will start after that, so that's fine.

**Comment by ycaibb** [comment]
OK, thanks your reply
