### ISSUE TITLE
Incoming call fails, unknown sound device

### ISSUE THREAD

**Issue by robdyck** [baresip/baresip#1670]
Play, src and alert are all set to alsa,default. The device that baresip is trying to open changes with each call. It seems to be picking up a random number and interpreting a device name with it. Another UA on the host using default sound is working well.

[unknow-sound-device.txt](https://github.com/baresip/baresip/files/7620505/unknow-sound-device.txt)

**Comment by robdyck** [comment]
I didn't find the root cause but disabling the echo module makes it work. Also, it no longer auto answers. I mistakenly assumed the echo module had something to do with echo cancellation.

**Comment by sreimers** [comment]
The "echo" module is a server-side module for providing a test account like "echo@sip.example.net". For Echo cancellation you can use "webrtc_aec".
