### ISSUE TITLE
how to enable group call with baresip?

### ISSUE THREAD

**Issue by GOBIKRISHNAN-R** [baresip/baresip#1673]
I've installed baresip-1.0.0 and I can able to call one person. It is working fine but i need to make conference call. what is the configuration or procedure to call more than one person?

**Comment by sreimers** [comment]
This feature is not released yet, you can try the GIT version: https://github.com/baresip/baresip/wiki/Install:-GIT-Version
And try this module: https://github.com/baresip/baresip/wiki/Conference-Call
