### ISSUE TITLE
With gtk module and remote UA ending call, baresip is left in half ended state

### ISSUE THREAD

**Issue by robdyck** [baresip/baresip#1675]
The problem occurs only with module gtk enabled. When the other UA hangs up, baresip does not completely release the call. It continues to send RTCP packets towards the remote and the local video image remains on the screen, although still. Clicking the hang up button on the gtk pop-up clears the call completely.

![baresip-call-ended](https://user-images.githubusercontent.com/58280584/144723399-e5c1c2fd-95ed-410e-819d-06689f468494.jpg)

**Comment by mbattista** [comment]
Thanks for the report.
Perhaps GTK needs to handle the end of video calls different.

I will look into this.
