### ISSUE TITLE
windows build issue

### ISSUE THREAD

**Issue by GOBIKRISHNAN-R** [baresip/baresip#1688]
Hi,

I just commented out the dshow module in VS project file for testing purposes. Now the VS2017(VS2015 toolset) is skipping dshow build and It is compiling all other modules except the config module. while going to compile the config file, It is printing the below error.

**`Error C1083: Cannot open include file: 'dirent.h': No such file or directory`**

The line number is

https://github.com/baresip/baresip/blob/3879cd95dea9c3ea9caf48cabaaaddeed409540e/src/config.c#L7

The dirent.h is not present in Visual studio. So, I'm planning to add dirent in Visual studio(source is dirent ). Is it fine or anything I'm missing?

Thanks & Regards,
Gobi

**Comment by GOBIKRISHNAN-R** [comment]
I'm planning to download and use [dirent ](https://github.com/tronkko/dirent) source.

**Comment by sreimers** [comment]
Using the external `dirent.h` file should be fine. We try to avoid importing external source code in baresip.
