### ISSUE TITLE
Baresip not working on auto run shows Unknown error-2

### ISSUE THREAD

**Issue by VishalChauhan0037** [baresip/baresip#1691]
I am getting this unknown error-2 while running baresip script on auto run...But without autorun it is working fine..
PROBLEM -->> Cannot make outgoing call from Raspberry Pi . Baresip crashes when I am picking up the phone on incoming call
call state is Ringing after picking up phone It shows unknown error-2.....

10:06:04.838 - baresipy:run:370 - DEBUG - audio: Set audio decoder: opus 48000Hz 2ch
10:06:04.925 - baresipy:run:370 - DEBUG - audio: player started with sample format S16LE
10:06:04.973 - baresipy:run:370 - DEBUG - audio: Set audio encoder: opus 48000Hz 2ch
10:06:05.072 - baresipy:run:370 - DEBUG - warning: Unknown speex_preprocess_ctl request: 2
10:06:05.125 - baresipy:run:370 - DEBUG - warning: Unknown speex_preprocess_ctl request: 46
10:06:05.270 - baresipy:run:370 - DEBUG - warning: The VAD has been replaced by a hack pending a complete rewrite
10:06:05.470 - baresipy:run:370 - DEBUG - speex_pp: Speex preprocessor loaded: srate = 48000Hz
10:06:05.513 - baresipy:run:370 - DEBUG - �[31malsa: could not open ausrc device 'default' (No such file or directory)
10:06:05.566 - baresipy:run:370 - DEBUG - �[;m�[31maudio: start_source failed (alsa.default): Unknown error -2
10:06:05.579 - baresipy:run:370 - DEBUG - �[;msip:302@192.168.0.84: session closed: Unknown error -2
10:06:05.637 - baresipy:handle_call_status:314 - DEBUG - Call Status: DISCONNECTED
10:06:05.649 - baresipy:handle_call_ended:328 - INFO - Call ended
10:06:05.820 - baresipy:handle_call_ended:329 - DEBUG - Reason: Unknown error -2

**Comment by juha-h** [comment]
Try with baresip master.  speex_pp module does not exist.

**Comment by VishalChauhan0037** [comment]
This is my config file and also tried with speex_pp still same error

# Audio
audio_path		/usr/share/baresip
audio_player		alsa,default
audio_source		alsa,default
audio_alert		alsa,default
#ausrc_srate		48000
#auplay_srate		48000
#ausrc_channels		0
#auplay_channels	0
#audio_txmode		poll		# poll, thread
audio_level		no
ausrc_format		s16		# s16, float, ..
auplay_format		s16		# s16, float, ..
auenc_format		s16		# s16, float, ..
audec_format		s16		# s16, float, ..

# Video
#video_source		v4l2,/dev/video0
#video_display		x11,nil
video_size		352x288
video_bitrate		500000
video_fps		25.00
video_fullscreen	yes
videnc_format		yuv420p

# AVT - Audio/Video Transport
rtp_tos			184
#rtp_ports		10000-20000
#rtp_bandwidth		512-1024 # [kbit/s]
rtcp_mux		no
jitter_buffer_delay	5-10		# frames
rtp_stats		no
#rtp_timeout		60

# Network
#dns_server		10.0.0.1:53
#net_interface		wlp0s20f3

# BFCP
#bfcp_proto		udp

#------------------------------------------------------------------------------
# Modules

module_path		/usr/lib/baresip/modules

# UI Modules
module			stdio.so
#module			cons.so
#module			evdev.so
#module			httpd.so

# Audio codec Modules (in order)
module			opus.so
#module			amr.so
#module			g7221.so
#module			g722.so
#module			g726.so
module			g711.so
#module			gsm.so
#module			l16.so
#module			bv32.so
#module			mpa.so
#module			codec2.so
#module			ilbc.so
#module			isac.so

# Audio filter Modules (in encoding order)
#module			speex_aec.so
#module			vumeter.so
#module			sndfile.so
module			speex_pp.so
#module			plc.so

# Audio driver Modules
module			alsa.so
#module			pulse.so
#module			jack.so
#module			portaudio.so
#module			aubridge.so
#module			aufile.so

**Comment by VishalChauhan0037** [comment]
> Try with baresip master. speex_pp module does not exist.
Below is my config file..
# Audio
audio_path		/usr/share/baresip
audio_player		alsa,default
audio_source		alsa,default
audio_alert		alsa,default
#ausrc_srate		48000
#auplay_srate		48000
#ausrc_channels		0
#auplay_channels	0
#audio_txmode		poll		# poll, thread
audio_level		no
ausrc_format		s16		# s16, float, ..
auplay_format		s16		# s16, float, ..
auenc_format		s16		# s16, float, ..
audec_format		s16		# s16, float, ..

# Video
#video_source		v4l2,/dev/video0
#video_display		x11,nil
video_size		352x288
video_bitrate		500000
video_fps		25.00
video_fullscreen	yes
videnc_format		yuv420p

# AVT - Audio/Video Transport
rtp_tos			184
#rtp_ports		10000-20000
#rtp_bandwidth		512-1024 # [kbit/s]
rtcp_mux		no
jitter_buffer_delay	5-10		# frames
rtp_stats		no
#rtp_timeout		60

# Network
#dns_server		10.0.0.1:53
#net_interface		wlp0s20f3

# BFCP
#bfcp_proto		udp

#------------------------------------------------------------------------------
# Modules

module_path		/usr/lib/baresip/modules

# UI Modules
module			stdio.so
#module			cons.so
#module			evdev.so
#module			httpd.so

# Audio codec Modules (in order)
module			opus.so
#module			amr.so
#module			g7221.so
#module			g722.so
#module			g726.so
module			g711.so
#module			gsm.so
#module			l16.so
#module			bv32.so
#module			mpa.so
#module			codec2.so
#module			ilbc.so
#module			isac.so

# Audio filter Modules (in encoding order)
#module			speex_aec.so
#module			vumeter.so
#module			sndfile.so
module			speex_pp.so
#module			plc.so

# Audio driver Modules
module			alsa.so
#module			pulse.so
#module			jack.so
#module			portaudio.so
#module			aubridge.so
#module			aufile.so

**Comment by alfredh** [comment]
please read this first:

https://github.com/baresip/baresip/wiki/Guidelines-for-reporting-Issues
