### ISSUE TITLE
Baresip on Windows

### ISSUE THREAD

**Issue by TheWufgeng** [baresip/baresip#1694]
I am not able to build Baresip on Windows.
I tried ./mk/win32/baresip.sln which unfortunately does  not compile.
It seems like the Visual Studio Project files where not kept up to date during development. I've tried to update them by myself but it seems I am not experienced enough for that, because I always get some missing references or modules that don't compile. Also the project file does reference a "misc" folder, but unfortunately I do not know what should be inside of that.

I also tried to use MinGW and the included makefile but this does not compile either.
I tried to resolve the issue myself, but it seems like there are some functions used which are not supported by MinGW (libre). In the baresip-win32 repo, I found information to use MinGW and Wine, but I assume this only works when cross-compile for win32 on a non Windows machine (because no windows example was included nor did I found a working example of Wine on Windows).

Can anyone confirm that compiling baresip on windows  still works. Maybe it is just my setup.

**Comment by GOBIKRISHNAN-R** [comment]
Can you please share your error log?

**Comment by alfredh** [comment]
using baresip-win32 to build:

```
  CC      build-i686/src/vidconv.o
  CC      build-i686/src/websock.o
  CC      build-i686/src/trace.o
src/trace.c: In function 'test_trace':
src/trace.c:31:2: warning: implicit declaration of function 'RE_TRACE_PROCESS_NAME'; did you mean 'RE_TRACE_META_PROCESS_NAME'? [-Wimplicit-function-declaration]
   31 |  RE_TRACE_PROCESS_NAME("retest");
      |  ^~~~~~~~~~~~~~~~~~~~~
      |  RE_TRACE_META_PROCESS_NAME
src/trace.c:31:2: warning: nested extern declaration of 'RE_TRACE_PROCESS_NAME' [-Wnested-externs]
  CC      build-i686/src/tls.o
  CC      build-i686/src/dtls.o
```


@sreimers perhaps something is wrong in the trace code ?

**Comment by sreimers** [comment]
Should be fixed now: https://github.com/baresip/re/commit/17137284b175a4f43c7c85dadf3821500802ab42

**Comment by alfredh** [comment]
thanks @sreimers !

I tested with baresip-win32 on Debian 11, there are some more errors:


```
src/fmt/print.c: In function 're_vhprintf.constprop':
src/fmt/print.c:56:5: warning: 'pch' may be used uninitialized in this function [-Wmaybe-uninitialized]
   56 |  if (prfx && pch == '0')
      |     ^
src/fmt/print.c:166:7: note: 'pch' was declared here
  166 |  char pch, ch, num[NUM_SIZE], addr[64], msg[256];
      |       ^~~
ar: `u' modifier ignored since `D' is the default (see `U')
ar: `u' modifier ignored since `D' is the default (see `U')
Fontconfig warning: ignoring UTF-8: not a valid region tag
Fontconfig warning: ignoring UTF-8: not a valid region tag
Fontconfig warning: ignoring UTF-8: not a valid region tag
Fontconfig warning: ignoring UTF-8: not a valid region tag
Fontconfig warning: ignoring UTF-8: not a valid region tag
regular tests:       
test_sa: TEST_ERR: src/sa.c:354: (unknown error)
test_sa: test_sa_pton failed with addr fe80::3a28:d8d9:ddc3:25dd%{00000002-0000-0000-0000-000000000000}
test: test_sa_pton: test failed (unknown error)
Failed (unknown error)
make: *** [Makefile:129: retest] Error 101
```


```
ar: `u' modifier ignored since `D' is the default (see `U')
ar: `u' modifier ignored since `D' is the default (see `U')
ar: `u' modifier ignored since `D' is the default (see `U')
test/account.c: In function 'test_account_uri_complete':
test/account.c:182:14: warning: 'mb[0]' may be used uninitialized in this function [-Wmaybe-uninitialized]
  182 |  mem_deref(mb[0]);
      |            ~~^~~
test/account.c:183:14: warning: 'mb[1]' may be used uninitialized in this function [-Wmaybe-uninitialized]
  183 |  mem_deref(mb[1]);
      |            ~~^~~
test/account.c:182:14: warning: 'mb[0]' may be used uninitialized in this function [-Wmaybe-uninitialized]
  182 |  mem_deref(mb[0]);
      |            ~~^~~
test/account.c:183:14: warning: 'mb[1]' may be used uninitialized in this function [-Wmaybe-uninitialized]
  183 |  mem_deref(mb[1]);
      |            ~~^~~
test/account.c:183:14: warning: 'mb[1]' may be used uninitialized in this function [-Wmaybe-uninitialized]
/usr/bin/i686-w64-mingw32-ld: ./libbaresip.a(aufile.o): in function `destructor':
modules/aufile/aufile.c:54: undefined reference to `pthread_join'
/usr/bin/i686-w64-mingw32-ld: ./libbaresip.a(aufile.o): in function `alloc_handler':
modules/aufile/aufile.c:263: undefined reference to `pthread_create'
/usr/bin/i686-w64-mingw32-ld: ./libbaresip.a(aufile_play.o): in function `auplay_destructor':
modules/aufile/aufile_play.c:37: undefined reference to `pthread_join'
/usr/bin/i686-w64-mingw32-ld: ./libbaresip.a(aufile_play.o): in function `play_alloc':
modules/aufile/aufile_play.c:123: undefined reference to `pthread_create'
/usr/bin/i686-w64-mingw32-ld: ./libbaresip.a(device.o): in function `destructor':
modules/aubridge/device.c:186: undefined reference to `pthread_join'
/usr/bin/i686-w64-mingw32-ld: ./libbaresip.a(device.o): in function `aubridge_device_connect':
modules/aubridge/device.c:169: undefined reference to `pthread_create'
/usr/bin/i686-w64-mingw32-ld: ./libbaresip.a(device.o): in function `aubridge_device_stop':
modules/aubridge/device.c:186: undefined reference to `pthread_join'
collect2: error: ld returned 1 exit status
make[1]: *** [Makefile:338: selftest.exe] Error 1
make: *** [Makefile:137: baresip] Error 2
```

**Comment by alfredh** [comment]
@TheWufgeng can you please share details about your baresip-win32 setup, i.e. which host are you using ?

**Comment by alfredh** [comment]
@cspiel1 are you the link-local expert ?

I have some problem running a testcase on mingw32/wine:


```
test_sa: TEST_ERR: src/sa.c:357: (Unknown error <101>)
test_sa: test_sa_pton failed with addr fe80::3a28:d8d9:ddc3:25dd%{00000002-0000-0000-0000-000000000000}
test: test_sa_pton: test failed (Unknown error <101>)
Failed (Unknown error <101>)
make: *** [Makefile:134: retest] Error 101
```

is this something you could have a look at ?

**Comment by alfredh** [comment]
I tried with this patch, seems to work better on windows:

```diff
diff --git a/src/sa/printaddr.c b/src/sa/printaddr.c
index 262c336..fba2864 100644
--- a/src/sa/printaddr.c
+++ b/src/sa/printaddr.c
@@ -31,15 +31,13 @@ int sa_print_addr(struct re_printf *pf, const struct sa *sa)
 
        err = re_hprintf(pf, "%j", sa);
 
-#if defined (HAVE_GETIFADDRS) && defined (HAVE_INET6)
+#if defined (HAVE_INET6)
        if (sa_af(sa) == AF_INET6 && sa_is_linklocal(sa)) {
 
-               char ifname[IF_NAMESIZE];
+               uint32_t scope_id = sa_scopeid(sa);
 
-               if (!if_indextoname(sa->u.in6.sin6_scope_id, ifname))
-                       return errno;
 
-               err |= re_hprintf(pf, "%%%s", ifname);
+               err |= re_hprintf(pf, "%%%d", scope_id);
        }
 #endif
 
```


instead of appending the interface name, it appends the numerical interface index (e.g. 2)

**Comment by alfredh** [comment]
is there someone who can try to run baresip selftest on Windows and see if it works ?
the retest program can also be used.


I have tried to run it on wine, and there are some errors.

**Comment by sreimers** [comment]
Yes wine and Windows 10 are failing on test_call_answer but with different error messages:

```
C:\>selftest.exe
running baresip selftest version 1.1.0 with 46 tests
[ RUN      ] test_account
[       OK ]
[ RUN      ] test_account_uri_complete
[       OK ]
[ RUN      ] test_aulevel
[       OK ]
[ RUN      ] test_call_answer
tcp: sock_bind: bind: unknown error (af=2, 169.254.165.69:0)
ua: SIP Transport failed: unknown error
ua: init failed (unknown error)

TEST_ERR: test/call.c:376: (unknown error)
test_call_answer: test failed (unknown error)
test failed (unknown error)
re main loop:
  maxfds:  2048
  nfds:    5
  method:  2 (select)
```

I will investigate.

**Comment by sreimers** [comment]
> Update: Looks like we add Link local IPv4/IPv6 adresses for inactive (not connected) network interfaces on windows.

Fixed https://github.com/baresip/re/commit/fb042618318f3f078cdc767d48ad6d9209450959

test_call_answer works now on Windows 10 (next failed test is test_call_aufilt since ausine module is missing).

Looks like wine is defect because `net_dst_source_addr_get` returns only `0.0.0.0`, could be a wine bug.

**Comment by alfredh** [comment]
btw, it would be nice to see the real error code number:

```
ua: init failed (unknown error)
```

this can be fixed in `str_error` by printing the error code into the buffer:

```c
#else
	/* fallback */
	(void)errnum;
	s = "unknown error";
#endif
```

what about retest, does it works on Windows 10 ?

**Comment by TheWufgeng** [comment]
Thanks for taking care of this issue. I will setup my build environment again too check it and also to give you feedback. Maybe I will have time tomorrow 😃.

**Comment by TheWufgeng** [comment]
I tried different evironments

I used MinGW32, installed via "MinGW Installation Manager". And tried to build it with the msys toolchain (msys.bat).
I've got an error for both lib-re and lib-rem see my attached files of the output.
First I've got an error compiling dns/win32/srv.c, which I've fixed by added an include of WinError.h (diff attached)

[mingw32 make re.txt](https://github.com/baresip/baresip/files/7908082/mingw32.make.re.txt)
[mingw32 make rem.txt](https://github.com/baresip/baresip/files/7908089/mingw32.make.rem.txt)
[win32-srv_inlcude WinError.txt](https://github.com/baresip/baresip/files/7908093/win32-srv_inlcude.WinError.txt)

I tried MinGW64 using the Msys2 toolchain. I installed make and gcc via pacman. I then tried to build lib-re and lib-rem which also failed. I aalso attached these outputs.

[msys2 make re.txt](https://github.com/baresip/baresip/files/7908081/msys2.make.re.txt)
[msys2 make rem.txt](https://github.com/baresip/baresip/files/7908088/msys2.make.rem.txt)

Last I tried building the Solution using VS2019 (not tried VS2015 yet because I don't have it installed at the moment). Compiling lib-re and lib-rem seems to be fine here but building the baresip project fails because it can't find auloop.c and auvideo.c. After I deleted both file references compiling was succesfull but I got some linker errors. You can find the logs attached.

[VS2019.txt](https://github.com/baresip/baresip/files/7908087/VS2019.txt)

**Comment by alfredh** [comment]
can you try to add this file to the VS2019 project file:

src/bundle.c

**Comment by sreimers** [comment]
> what about retest, does it works on Windows 10 ?

now it works fine (had to implement some more patches today).

**Comment by alfredh** [comment]
if possible, we should try to remove usage of this function:

```
1>.\re\src\net\net.c(46,7): warning C4996: 'gethostbyname': Use getaddrinfo() or GetAddrInfoW() instead or define _WINSOCK_DEPRECATED_NO_WARNINGS to disable deprecated API warnings
```

we can remove the test, during writing the retest program I always tried to avoid
low level network functions (sometimes different behaviour on different platforms) ...

**Comment by sreimers** [comment]
I just saw we have a already a network test group, I will move the test.

**Comment by sreimers** [comment]
> ```
> 1>.\re\src\net\net.c(46,7): warning C4996: 'gethostbyname': Use getaddrinfo() or GetAddrInfoW() instead or define _WINSOCK_DEPRECATED_NO_WARNINGS to disable deprecated API warnings
> ```

Hm maybe we can drop `net_hostaddr` completely?

**Comment by alfredh** [comment]
it should be fine to drop `net_hostaddr` :)

the concept of fetching the "default" local address is by definition unstable and errorprone :)

**Comment by TheWufgeng** [comment]
I was able to build the baresip Visual Studio Project without errors. I had to resolve some more linker issues.
I needed to do the following:
- Removing HAVE_GETOPT from the the preprocessor defines.
- As described previously I removed the reference to the missing files auloop.c and vidloop.c. I also removed the mod_export for there in static.c
- Added reference to bundle.c

I also had to do some for the libre project:
- Added the missing reference to btrace.c
- Added an include to stdint.h in hash/func.c because UINT32_C() could not be found. This probably could also be solved by using the number prefix 'U.

I have not tested it for the moment. The only "error" that I get when running is "module netroam.dll: No such file or directory". The rest looks normal for now.

**Comment by alfredh** [comment]
thanks for your work!

with the latest version I get these warnings on Mingw:


```
src/net/net.c: In function ‘net_default_source_addr_get’:
src/net/net.c:119:1: warning: control reaches end of non-void function [-Wreturn-type]
  119 | }
      | ^
src/fmt/print.c: In function ‘re_vhprintf.constprop’:
src/fmt/print.c:56:5: warning: ‘pch’ may be used uninitialized in this function [-Wmaybe-uninitialized]
   56 |  if (prfx && pch == '0')
      |     ^
src/fmt/print.c:166:7: note: ‘pch’ was declared here
  166 |  char pch, ch, num[NUM_SIZE], addr[64], msg[256];
      |       ^~~
ar: `u' modifier ignored since `D' is the default (see `U')
src/h264/nal.c: In function ‘h264_find_startcode’:
src/h264/nal.c:129:30: warning: cast from pointer to integer of different size [-Wpointer-to-int-cast]
  129 |  const uint8_t *a = p + 4 - ((long)p & 3);
      |                              ^
ar: `u' modifier ignored since `D' is the default (see `U')
ar: `u' modifier ignored since `D' is the default (see `U')
```

Debian 11.2 with

x86_64-w64-mingw32-gcc (GCC) 10-win32 20210110
Copyright (C) 2020 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

@TheWufgeng are you able to make a PR for the VS project file ?

**Comment by sreimers** [comment]
`net_default_source_addr_get` and `h264_find_startcode` should be fixed now.
The `pch` uninitialized warning (should be a easy fix) does not show up on my mingw/gcc (9.3-win32 20200320 and 11.2.0) versions. Can you post the complete gcc options with "make V=1" so we can compare the compiler warning options:

```
x86_64-w64-mingw32-gcc -DRELEASE -Wall -Wextra -Wmissing-declarations -Wmissing-prototypes -Wstrict-prototypes -Wbad-function-cast -Wsign-compare -Wnested-externs -Wshadow -Waggregate-return -Wcast-align -Wold-style-definition -Wdeclaration-after-statement -Wvla  -g -O3   -Wuninitialized -Wno-strict-aliasing -DWIN32 -D_WIN32_WINNT=0x0600 -D__ssize_t_defined -DOS=\"win32\" -std=c11 -pedantic -DHAVE_ATOMIC -DARCH=\"x86_64\" -DUSE_OPENSSL -DUSE_TLS -DUSE_OPENSSL_DTLS -DUSE_DTLS -DUSE_OPENSSL_SRTP -DUSE_DTLS_SRTP -DHAVE_PTHREAD -DHAVE_GETOPT -DHAVE_INTTYPES_H -DHAVE_STDBOOL_H -DHAVE_INET6 -DHAVE_SELECT -DHAVE_IO_H -DVERSION=\"2.0.1-dev12\" -DVER_MAJOR=2 -DVER_MINOR=0 -DVER_PATCH=1 -DFD_SETSIZE=2048 -g -gstabs -isystem .../openssl/include -Iinclude -c src/fmt/print.c -o build-x86_64/fmt/print.o -MD -MF build-x86_64/fmt/print.d -MT build-x86_64/fmt/print.o
```

**Comment by alfredh** [comment]
here is the output:

```
x86_64-w64-mingw32-gcc -DRELEASE -Wall -Wextra -Wmissing-declarations -Wmissing-prototypes -Wstrict-prototypes -Wbad-function-cast -Wsign-compare -Wnested-externs -Wshadow -Waggregate-return -Wcast-align -Wold-style-definition -Wdeclaration-after-statement -Wvla  -g -O3   -Wuninitialized -Wno-strict-aliasing -DWIN32 -D_WIN32_WINNT=0x0600 -D__ssize_t_defined -DOS=\"win32\" -std=c11 -pedantic -DHAVE_ATOMIC -DARCH=\"x86_64\" -DUSE_OPENSSL -DUSE_TLS -DUSE_OPENSSL_DTLS -DUSE_DTLS -DUSE_OPENSSL_SRTP -DUSE_DTLS_SRTP -DHAVE_PTHREAD -DHAVE_GETOPT -DHAVE_INTTYPES_H -DHAVE_STDBOOL_H -DHAVE_INET6 -DHAVE_SELECT -DHAVE_IO_H -DVERSION=\"2.0.1-dev12\" -DVER_MAJOR=2 -DVER_MINOR=0 -DVER_PATCH=1 -DFD_SETSIZE=2048 -g -gstabs -isystem /home/alfredh/git/baresip-win32/openssl/include -Iinclude -c src/fmt/print.c -o build-x86_64/fmt/print.o -MD -MF build-x86_64/fmt/print.d -MT build-x86_64/fmt/print.o
src/fmt/print.c: In function ‘re_vhprintf.constprop’:
src/fmt/print.c:56:5: warning: ‘pch’ may be used uninitialized in this function [-Wmaybe-uninitialized]
   56 |  if (prfx && pch == '0')
      |     ^
src/fmt/print.c:166:7: note: ‘pch’ was declared here
  166 |  char pch, ch, num[NUM_SIZE], addr[64], msg[256];
      |       ^~~
```

**Comment by alfredh** [comment]
is there anything else missing here ?

should we also update the VS project file ?

**Comment by alfredh** [comment]
I will close this one for now.

We need some help to maintain the windows project files.
If you want to help, please refresh the VC files and submit a PR.
