### ISSUE TITLE
Mickey Mouse Voice after audio source replacement

### ISSUE THREAD

**Issue by cspiel1** [baresip/baresip#1699]
Mentioned here: https://github.com/baresip/baresip/issues/1697#issuecomment-1016155771

During a G722 call, change audio source to aufile and specify a WAV file with 8000Hz samplerate.

```
/ausrc aufile,/usr/local/share/baresip/ringback.wav
```
--> The file is streamed to the peer, but with ugly quality. It seems that the resampler is missing or working wrong.

Then change the ausrc back to pulse/alsa.

```
/ausrc pulse,xxx
```

The voice sounds distorted on the peer (Mickey Mouse voice).

The solution should go with these plans: https://github.com/baresip/re/discussions/184

@sreimers Should I start with a first PR? One of these:
- Move resample processing to a filter module.
- Remove jbuf from audio.c and stream.c and replace by adaptive aubuf.

**Comment by sreimers** [comment]
> @sreimers Should I start with a first PR? One of these:

Go for it :)

**Comment by alfredh** [comment]
please have a look at this code:

```c
/*
 * Read samples from Audio Source
 *
 * @note This function has REAL-TIME properties
 *
 * @note This function may be called from any thread
 */
static void ausrc_read_handler(struct auframe *af, void *arg)
{
	struct audio *a = arg;
	struct autx *tx = &a->tx;
	size_t num_bytes = auframe_size(af);

	if (tx->src_fmt != af->fmt) {
		warning("audio: ausrc format mismatch:"
			" expected=%d(%s), actual=%d(%s)\n",
			tx->src_fmt, aufmt_name(tx->src_fmt),
			af->fmt, aufmt_name(af->fmt));
		return;
	}

	if (tx->muted)
		auframe_mute(af);

	if (aubuf_cur_size(tx->aubuf) >= tx->aubuf_maxsz) {

		++tx->stats.aubuf_overrun;

		debug("audio: tx aubuf overrun (total %llu)\n",
		      tx->stats.aubuf_overrun);
	}

	(void)aubuf_write(tx->aubuf, af->sampv, num_bytes);
```

please check the auframe here, does it have samplerate 8000 Hz,
while the audio sender is sending 16000 Hz ?

I am not sure if the baresip audio core can handle switching of samplerate dynamically.
this should be possible to fix, just save the samplerate and check auframe
if samplerate is the same or different.

**Comment by cspiel1** [comment]
I try to move resample code from audio.c to a resample module, like you proposed here: https://github.com/baresip/baresip/pull/1443

This will support samplerate changes in the `encode()` function.

**Comment by cspiel1** [comment]
```
 .   .-------.    .------------.    .-------.    .---------.
 |   |       |    |            |    |       |    |         |
 |O->| ausrc |--->| aufilt |--->| aubuf |--->| encoder |->RTP
 |   |       |    |            |    |       |    |         |
 '   '-------'    '------------'    '-------'    '---------'

 *       .--------.   .-------.   .--------.   .--------.
 * |\    |        |   |       |   |        |   |        |
 * | |<--| auplay |<--| aubuf |<--| aufilt |<--| decode |<--- RTP
 * |/    |        |   |       |   |        |   |        |
 *       '--------'   '-------'   '--------'   '--------'
```
For the encoder path the input sample rate and channels is specified by the audio frame and the output by the `aufilt_prm` which is set to the codec parameters.

But for the decoder audio frame and `aufilt_prm` both specify the input sample rate and channels. In the `decode_update()` we could directly access the `config_audio` of the given `audio` object. Has someone a better idea than accessing the config for finding correct output sample rate and channel number?

**Comment by cspiel1** [comment]
Maybe this is the answer:
- Currently the audio filters have identical `srate`/`ch` for input and output.
- So we maybe are free to change what we pass to the `struct aufilt_prm *` parameter.
- If we pass the settings for the output of the filter, nothing will change for other filter modules. Then the `auresamp` module knows also for the decoding path what is the output sample rate and channel number.

What will be also a new situation, is that the resampler can be placed anywhere in the filter list.

**Comment by alfredh** [comment]
1. the input format is described in `struct auframe` of the incoming parameter
2. the output format can be described in aufilt param:

```c
/** Audio Filter Parameters */
struct aufilt_prm {
	uint32_t srate;       /**< Sampling rate in [Hz]        */
	uint8_t  ch;          /**< Number of channels           */
	int      fmt;         /**< Sample format (enum aufmt)   */
};
```

please note that in 1.) the format may change during a call,
for example from samplerate 8000Hz to 16000Hz.

if the codec change, you also need to reset the sampler.
for example changing codec from G.711 to G.722 will change
samplerate from 8000Hz to 16000Hz.

**Comment by alfredh** [comment]
I made a test using two wav files, one with 8000Hz and one with 16000Hz.
the audio is indeed corrupted if you switch between them.

I made a quick fix, here is the patch:

```patch
diff --git a/src/audio.c b/src/audio.c
index 3d65b154..695a79e6 100644
--- a/src/audio.c
+++ b/src/audio.c
@@ -879,6 +879,35 @@ static void auplay_write_handler2(struct auframe *af, void *arg)
 }
 
 
+static int tx_reset_resamp(struct autx *tx)
+{
+	int err;
+
+	info("audio: reset ausrc resampler:"
+	     " %uHz/%uch --> %uHz/%uch\n",
+	     tx->ausrc_prm.srate, tx->ausrc_prm.ch,
+	     tx->ac->srate, tx->ac->ch);
+
+	if (!tx->sampv_rs) {
+		tx->sampv_rs = mem_zalloc(AUDIO_SAMPSZ * sizeof(int16_t),
+					  NULL);
+		if (!tx->sampv_rs)
+			return ENOMEM;
+	}
+
+	err = auresamp_setup(&tx->resamp,
+			     tx->ausrc_prm.srate, tx->ausrc_prm.ch,
+			     tx->ac->srate, tx->ac->ch);
+	if (err) {
+		warning("audio: could not setup ausrc resampler"
+			" (%m)\n", err);
+		return err;
+	}
+
+	return 0;
+}
+
+
 /*
  * Read samples from Audio Source
  *
@@ -900,6 +929,18 @@ static void ausrc_read_handler(struct auframe *af, void *arg)
 		return;
 	}
 
+	if (tx->ausrc_prm.srate != af->srate) {
+
+		warning("audio: ausrc samplerate mismatch:"
+			" expected=%u, actual=%u\n",
+			tx->ausrc_prm.srate,
+			af->srate);
+
+		tx->ausrc_prm.srate = af->srate;
+
+		tx_reset_resamp(tx);
+	}
+
 	if (tx->muted)
 		auframe_mute(af);
 
@@ -1844,6 +1885,15 @@ static int start_source(struct autx *tx, struct audio *a, struct list *ausrcl)
 			return err;
 		}
 
+		if (prm.srate != tx->ausrc_prm.srate) {
+
+			info(".... audio source '%s' updated samplerate:"
+			     " %u Hz -> %u Hz\n",
+			     tx->module, prm.srate, tx->ausrc_prm.srate);
+
+			tx_reset_resamp(tx);
+		}
+
 		tx->as = ausrc_find(ausrcl, tx->module);
 
 		switch (a->cfg.txmode) {
@@ -2497,6 +2547,8 @@ int audio_set_source(struct audio *au, const char *mod, const char *device)
 
 	if (str_isset(mod)) {
 
+		uint32_t srate = tx->ausrc_prm.srate;
+
 		err = ausrc_alloc(&tx->ausrc, baresip_ausrcl(),
 				  mod, &tx->ausrc_prm, device,
 				  ausrc_read_handler, ausrc_error_handler, au);
@@ -2507,6 +2559,16 @@ int audio_set_source(struct audio *au, const char *mod, const char *device)
 		}
 
 		tx->as = ausrc_find(baresip_ausrcl(), mod);
+
+		if (srate != tx->ausrc_prm.srate) {
+
+			info(".... audio source '%s' updated samplerate:"
+			     " %u Hz -> %u Hz\n",
+			     mod, srate, tx->ausrc_prm.srate);
+
+			tx_reset_resamp(tx);
+		}
+
 	}
 
 	return 0;
```



this is just for testing. it is better to use the solution with the new `auresamp` module.

The big advantage of moving the resampler to a module, is that we can also support
other resamplers:

https://ccrma.stanford.edu/~jos/resample/Free_Resampling_Software.html

**Comment by alfredh** [comment]
hello @cspiel1 

do you know what is left to do on this ticket ?

**Comment by cspiel1** [comment]
Have to do some more tests. Today had some artifacts with streaming 32kHz sine with module `aufile` as ausrc.

**Comment by cspiel1** [comment]
With this setup the audio resampling `32000/1 --> 16000/1` works correctly.
```
audio_source  pulse,alsa_input.usb-Microsoft_Microsoft___LifeCam_Cinema_TM_-02.mono-fallback

module			auresamp.so
ausrc_srate		32000
```

**Comment by cspiel1** [comment]
This finally fixes this issue: https://github.com/baresip/baresip/pull/1741

**Comment by sreimers** [comment]
Can we close this issue now?
