### ISSUE TITLE
Build failure with clang: ld: error: undefined symbol: sipreg_alloc

### ISSUE THREAD

**Issue by jungle-boogie** [baresip/baresip#1711]
Hi,

OpenBSD i386 machine running current. 

1. We know `re` wont build, because of issue https://github.com/baresip/re/issues/201
2. Is that why I'm getting this build failure on the same machine, but this time with `baresip`?

```
  LD      baresip
ld: error: undefined symbol: sipreg_alloc
>>> referenced by reg.c:212 (src/reg.c:212)
>>>               build-i586/src/reg.o:(reg_register)

ld: error: undefined symbol: sipreg_set_srcport
>>> referenced by reg.c:233 (src/reg.c:233)
>>>               build-i586/src/reg.o:(reg_register)

ld: error: undefined symbol: sipreg_send
>>> referenced by reg.c:243 (src/reg.c:243)
>>>               build-i586/src/reg.o:(reg_register)

ld: error: undefined symbol: rtp_clear
>>> referenced by stream.c:1143 (src/stream.c:1143)
>>>               build-i586/src/stream.o:(stream_flush)
clang: error: linker command failed with exit code 1 (use -v to see invocation)
gmake: *** [Makefile:319: baresip] Error 1
```

```
$ cc -v
OpenBSD clang version 13.0.0
Target: i386-unknown-openbsd7.0
Thread model: posix
InstalledDir: /usr/bin
```

```
$ gmake -v
GNU Make 4.3
Built for i386-unknown-openbsd7.0
```

gmake info here: https://termbin.com/nu0kn

**Comment by alfredh** [comment]
I think we should support OpenBSD 7.0 which is a proper release.
I dont think we should support OpenBSD current which is a moving target.

this is not a bug in baresip

please consider using the forum for these kind of questions:

https://groups.google.com/g/baresip

**Comment by jungle-boogie** [comment]
Hi Alfred,

So you expect `baresip` master to work with OpenBSD 7.0 -release, but not for `baresip` master to work with OpenBSD -current?

Thanks!
