### ISSUE TITLE
no more that four video codecs on m line

### ISSUE THREAD

**Issue by juha-h** [baresip/baresip#1716]
I have in account file (Debian 11):
```
;video_codecs=VP9,VP8,H265,H264,AV1
```
When baresip starts it recognizes all of them:
```
vidcodec: AV1
vidcodec: H264
vidcodec: H264
vidcodec: H263
vidcodec: H265
avcodec: using H.264 encoder 'libx264' -- libx264 H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10
avcodec: using H.264 decoder 'h264' -- H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10
avcodec: using H.265 encoder 'libx265' -- libx265 H.265 / HEVC
avcodec: using H.265 decoder 'hevc' -- HEVC (High Efficiency Video Coding)
vidcodec: VP8
vidcodec: VP9
```
But when baresip sends out INVITE, it only contains four video codecs:
```
m=video 10724 RTP/AVP 96 97 98 99
a=rtpmap:96 VP9/90000
a=fmtp:96 max-fs=3600;profile-id=0
a=rtpmap:97 VP8/90000
a=fmtp:97 max-fs=3600
a=rtpmap:98 H265/90000
a=fmtp:98 profile-id=1
a=rtpmap:99 H264/90000
a=fmtp:99 packetization-mode=0;profile-level-id=42e01f
```
And also leaves out H264  packetization-mode=1 codec.

Is it specified in some standard that not more than four video codecs can be included in SDP offer or is this a baresip bug or intentional limitation?

**Comment by alfredh** [comment]
look here:

```c
struct account {
	...
	struct le vcv[4];            /**< List elements for vidcodecl        */
	struct list vidcodecl;       /**< List of preferred video-codecs     */
	...
};
```

it would be possible to increase this value

**Comment by juha-h** [comment]
Alfred E. Heggestad writes:

> look here:
> 
> ```c
> struct account {
> 	...
> 	struct le vcv[4];            /**< List elements for vidcodecl        */
> 	struct list vidcodecl;       /**< List of preferred video-codecs     */
> 	...
> };
> ```
> 
> it would be possible to increase this value

Very good it the value could be increased.

I just stumbled to this in my AV1 tests when I started to wonder why the
codec was not selected.

How about doubling the value to 8?  That would then cover at least these:

;video_codecs=VP9,VP8,H265,H264,H263,AV1

and leave one for spare.
