### ISSUE TITLE
rename branch master to main

### ISSUE THREAD

**Issue by alfredh** [baresip/baresip#1720]

**Comment by alfredh** [comment]
See: https://github.com/github/renaming

Here is my status of renaming default branch to "main":

```
x baresip
x baresip-android
x baresip-apps
x baresip-ios
x baresip-libs
x baresip-webrtc
x baresip-win32
x ci
x docker
  re
  rem
  retest
```

**Comment by sreimers** [comment]
- re
- rem
- retest

Are renamed too now.

**Comment by juha-h** [comment]
I tried to build latest baresip on Debian 11 using latest re and rem,
but it failed:

make[1]: Entering directory '/usr/src/orig/baresip'
Requested 'libre >= 2.0.1-dev13' but version of libre is 2.0.1-dev12
You may find new versions of libre at https://github.com/baresip/re
Makefile:151: *** bad libre version, required version is ">= 2.0.1-dev13" LIBRE_MK: "../re/mk/re.mk" LIBRE_PKG_PATH: "../re/".  Stop.

**Comment by sreimers** [comment]
Have `../re/libre.pc` and `../re/Makefile` the right `2.0.1-dev13` version?

**Comment by juha-h** [comment]
My bad, re, rem and baresip were still at master branch.  Fixed now to main branch and everything went OK.

**Comment by alfredh** [comment]
thanks. looks like all projects are renamed now.
