### ISSUE TITLE
Video bandwidth burst calculation

### ISSUE THREAD

**Issue by sreimers** [baresip/baresip#1724]
https://github.com/baresip/baresip/blob/7f5c43b73dd186dcb5770778fbe9460151dc7882/src/video.c#L283-L286
Maybe I miss something, but shouldn't this `bandwidth_kbps / 8` for bytes (like mentioned)?

**Comment by alfredh** [comment]
not sure if the formula is correct or not ... it is a long time ago since the code was written :)

**Comment by sreimers** [comment]
Ok I will test this a bit (just stumbled over this while debugging another problem). :)
