### ISSUE TITLE
audio_alert does not stop alerting when the call ends

### ISSUE THREAD

**Issue by negbie** [baresip/baresip#1733]
I have two baresip (from current main branch) users registered who are part of a group, so that both get an INVITE. When a caller calls this group and ends the call, audio_alert still plays the alerting sound and the only way to stop it is to close baresip.

**Comment by juha-h** [comment]
Eugen Biegler writes:

> I have two baresip users registered who are part of a group, so that
> both get an INVITE. When a caller calls this group and ends the call,
> audio_alert still plays the alerting sound and the only way to stop it
> is to close baresip.

Doesn't sound like baresip issue.  I often make calls where my SIP Proxy
parallel forks the call to two baresip UASs.  When one of them answers,
my proxy cancels the INVITE to the other baresip.

**Comment by negbie** [comment]
I haven't explained it well enough. I use one baresip client for two users who are in a parallel ringing group. When the call comes in both are ringing. None of them answers the call, the caller just hangs up (both users get the CANCEL) but audio_alert still plays the alerting sound.

**Comment by juha-h** [comment]
Eugen Biegler writes:

> I haven't explained it well enough. I use one baresip client for two
> users who are in a parallel ringing group. When the call comes in both
> are ringing. None of them answers the call, the caller just hangs up
> (both users get the CANCEL) but audio_alert still plays the alerting
> sound.

I just tried with two baresips registering the same account AoR.  Then I
called that AoR using a third SIP UA having different account AoR.  Both
baresips started to ring.  Then I canceled the call at the calling SIP
UA and both baresips stopped ringing.

**Comment by negbie** [comment]
I have only one baresip instance with two different account AoR registered. In the config I use
call_hold_other_calls   no

Do you think the problem is that I use only one baresip instance for that?

**Comment by juha-h** [comment]
Start baresip with -s option and check if it receive two CANCEL request matching the two INVITEs when the caller hangs up.

**Comment by negbie** [comment]
Already checked that. Both get a CANCEL and for both I can see
closed: Connection reset by peer
audio: destroyed (started=0)

**Comment by negbie** [comment]
From SIP side everything looks ok and if both users get a call sequentially it works like expected too. Only when both users get an INVITE at the same time ring.wav keeps playing.

**Comment by negbie** [comment]
This is the verbose output without SIP

ua: sipsess connect via TLS 1.1.1.1:5061 --> 2.2.2.2:33916
xxx@xxx.pbx.de: selected for 1-0x5602a29af450
ua: using origin address 1.1.1.1 of SDP offer
call: alloc with params laddr=2.2.2.2, af=AF_INET, use_rtp=1
call: use_video=0
stream: audio: starting mediaenc 'srtp-mand' (wait_secure=0)
sip:xxx@xxx.pbx.de: Incoming call from: [parallel group] +49xxx sip:+49xxx.pbx.de - audio-video: sendrecv-inactive - (press 'a' to accept)
alsa: reset: srate=8000, ch=2, num_frames=320, pcmfmt=S16_LE
alsa: playback started (default)
ua: sipsess connect via TLS 1.1.1.1:5061 --> 2.2.2.2:33916
xxx@xxx.pbx.de: selected for 11-0x5602a2b225f0
ua: using origin address 1.1.1.1 of SDP offer
call: alloc with params laddr=2.2.2.2, af=AF_INET, use_rtp=1
call: use_video=0
stream: audio: starting mediaenc 'srtp-mand' (wait_secure=0)
alsa: stopping playback thread (default)
sip:xxx@xxx.pbx.de: Incoming call from: [parallel group] +49xxx sip:+49xxx.pbx.de - audio-video: sendrecv-inactive - (press 'a' to accept)
alsa: reset: srate=8000, ch=2, num_frames=320, pcmfmt=S16_LE
alsa: playback started (default)



sip:+49xxx.pbx.de: session closed: Connection reset by peer
audio: destroyed (started=0)
sip:+49xxx.pbx.de: session closed: Connection reset by peer
audio: destroyed (started=0)

**Comment by juha-h** [comment]
I made similar test and can confirm that ringing does not stop:
```
test@test.tutpro.com: (prio 0) {1/TCP/v4} 200 OK (OpenSIPg SIP Proxy (5.6.0-0b22 (x86_64/linux))) [2 bindings]
+35892345671@test.tutpro.com: (prio 0) {1/TCP/v4} 200 OK (OpenSIPg SIP Proxy (5.6.0-0b22 (x86_64/linux))) [1 binding]
All 2 useragents registered successfully! (21 ms)
test@test.tutpro.com: selected for test-0x55c2ec3e48c0
ua: using origin address 192.168.59.124 of SDP offer
sip:test@test.tutpro.com: Incoming call from: Bar sip:bar@test.tutpro.com - audio-video: sendrecv-inactive - (press 'a' to accept)
+35892345671@test.tutpro.com: selected for +35892345671-0x55c2ec3726d0
ua: using origin address 192.168.59.124 of SDP offer
sip:+35892345671@test.tutpro.com: Incoming call from: Bar sip:bar@test.tutpro.com - audio-video: sendrecv-inactive - (press 'a' to accept)
sip:bar@test.tutpro.com: session closed: Connection reset by peer
sip:bar@test.tutpro.com: session closed: Connection reset by peer
no active call
```
After sessions are closed ringing does not stop before I quit baresip.

**Comment by alfredh** [comment]
is there any progress on this ? 

it should be possible to track down the code responsible for stopping the ringtone,
and see why it is not working ...

**Comment by negbie** [comment]
Since I'm not familiar enough with the codebase I did not pinpoint the issue exactly. Mby it's because the alsa thread is stopped for the second incoming parallel INVITE but not when the call ends?

**Comment by negbie** [comment]
Looking only at the audio specific debug output I see:

alsa: playback started (default)
stream: audio: starting mediaenc 'srtp-mand' (wait_secure=0)
alsa: stopping playback thread (default)

alsa: playback started (default)

audio: destroyed (started=0)
audio: destroyed (started=0)

**Comment by alfredh** [comment]
in order to simplify the debugging, you can try to use different audio modules for
player and alert. for example:


```
audio_player            aubridge,default
audio_source            aubridge,default
audio_alert             alsa,default
```

when you see debug output with "alsa" prefix, you can be sure that it is related to the alert.

**Comment by alfredh** [comment]
it is possible that the audio player is not stopped properly.
please have a look at this code:

https://github.com/baresip/baresip/blob/main/modules/menu/menu.c#L173

**Comment by negbie** [comment]
With this config:

audio_player            aubridge,default
audio_source            aubridge,default
audio_alert             alsa,default

I see:

-> INVITE
<- 180 Ringing
alsa: playback started (default)
<- 487 Request Terminated
audio: destroyed (started=0)

-> INVITE
<- 180 Ringing
alsa: stopping playback thread (default)
alsa: playback started (default)
<- 487 Request Terminated
audio: destroyed (started=0)


When I change the group from parallel to serial ringing I see:

-> INVITE
<- 180 Ringing
alsa: playback started (default)
<- 487 Request Terminated
alsa: stopping playback thread (default)
audio: destroyed (started=0)

-> INVITE
<- 180 Ringing
alsa: playback started (default)
<- 487 Request Terminated
alsa: stopping playback thread (default)
audio: destroyed (started=0)

**Comment by negbie** [comment]
Thanks to @cspiel1 ticket can be closed.
