### ISSUE TITLE
 baresip

### ISSUE THREAD

**Issue by Usama01TN** [baresip/baresip#1736]
baresip x64 never build on windows

**Comment by sreimers** [comment]
Can you give us some more information? Do you see any compiler errors?

**Comment by alfredh** [comment]
hi @Usama01TN please consider to use the mailing list if you have questions.

your issue does not contain any description about the problem.
we will try to help you, but we need more information for that.

please read this:

https://github.com/baresip/baresip/wiki/Guidelines-for-reporting-Issues
