### ISSUE TITLE
webrtc_aec: Error encode: ProcessStream error (-5)

### ISSUE THREAD

**Issue by assegaf** [baresip/baresip#1737]
I wrote some code to use baresip as sip client, but need ECHO cancellation because loudspeaker.
I tried to compile with dhost:/usr/include/webrtc_audio_processing is ready

but I got error like this, it seem running but then Segmentation fault (core dumped)

201@192.168.21.200: Call answered: sip:XXXXXX@192.168.21.200
stream: update 'audio':
stream: receive: setting SSRC: 159a6fcc
audio: Set audio decoder: G722 16000Hz 1ch
audio: player started with sample format S16LE
audio: Set audio encoder: G722 16000Hz 1ch
webrtc_aec: creating shared state: [16000 Hz, 1 channels, blocksize 160 samples]
audio: source started with sample format S16LE
audio tx pipeline:        alsa ---> webrtc_aec ---> G722
audio rx pipeline:        alsa <--- webrtc_aec <--- G722
201@192.168.21.200: Call established: sip:XXXXXXX@192.168.21.200
stream: incoming rtp for 'audio' established, receiving from 192.168.21.7:2474

webrtc_aec: encode: ProcessStream error (-5)
audio: aufilter encode: Protocol error
webrtc_aec: encode: ProcessStream error (-5)
audio: aufilter encode: Protocol error
webrtc_aec: encode: ProcessStream error (-5)
audio: aufilter encode: Protocol error
webrtc_aec: encode: ProcessStream error (-5)
audio: aufilter encode: Protocol error
Segmentation fault (core dumped)

my config file is almost default, except I define, both mic and output as 16kbps mono

audio_player            alsa,default
audio_source            alsa,default
audio_alert             alsa,default
ausrc_srate             16000
ausrc_channels          1
auplay_srate            16000
auplay_channels         1

**Comment by sreimers** [comment]
Are you using a stable release or a current git version?

**Comment by assegaf** [comment]
> Are you using a stable release or a current git version?

I am using latest github version of baresip, for /usr/include/webrtc_audio_processing I use libwebrtc-audio-processing-dev package with debian 10 buster

**Comment by juha-h** [comment]
baresip with webrtc_aec module works fine for me on Debian bullseyes.
on bullseye the lib is

libwebrtc-audio-processing1:amd64     0.3-1+b1

on buster +b1 is missing, but I don't know if that matters.

**Comment by assegaf** [comment]
thanks for the input, its helpful, I will find why first and update here, if stuck I will try to force update to .deb for 0.3-1+b1 ..

this is the package for debian 10 buster.

libwebrtc-audio-processing-dev is already the newest version (0.3-1).
libwebrtc-audio-processing1 is already the newest version (0.3-1).

**Comment by assegaf** [comment]
I updated to 

libwebrtc-audio-processing-dev is already the newest version (0.3-1+b1).
libwebrtc-audio-processing1 is already the newest version (0.3-1+b1).


but the problem persist, I added dump :
 warning("webrtc_aec: encode: ProcessStream source and destination is ready, i:%d src:%d dst:%d numChannel:%d sampc:%d\n", i, src, dest, aec->ch, sampc);

seem everything is fine, what could go wrong ?


-------------------------------------------------------------------------------------------------------
baresip v1.1.0 Copyright (C) 2010 - 2022 Alfred E. Heggestad et al.
Local network addresses:
      wlan0:  192.168.21.201
      wlan0:  fe80::49b7:afff:5563:50f3
ua: adding SIP CA file: /etc/ssl/certs/ca-certificates.crt
ua: adding SIP CA path: 
aucodec: G722/16000/1
aufilt: webrtc_aec
ausrc: alsa
auplay: alsa
medianat: stun
medianat: turn
medianat: ice
Populated 1 account
Populated 3 contacts
Populated 1 audio codec
Populated 1 audio filter
Populated 0 video codecs
Populated 0 video filters
baresip is ready.
201@192.168.21.200: (prio 0) {0/UDP/v4} 200 OK (OpenSIPS (1.7.2-tls (i386/linux))) [8 bindings]
All 1 useragent registered successfully! (5 ms)
/dial XXXXXX
201@192.168.21.200: selected for request
call uri: sip:XXXXX@192.168.21.200
call: connecting to 'sip:XXXXX@192.168.21.200'..
call id: b55c42d1104ddbb6
call: SIP Progress: 100 Giving a try (/)
call: SIP Progress: 180 Ringing (/)
201@192.168.21.200: Call answered: sip:XXXXXX@192.168.21.200
stream: update 'audio'
stream: receive: setting SSRC: 438c1d74
audio: Set audio decoder: G722 16000Hz 1ch
audio: player started with sample format S16LE
audio: Set audio encoder: G722 16000Hz 1ch
webrtc_aec: creating shared state: [16000 Hz, 1 channels, blocksize 160 samples]
audio: source started with sample format S16LE
audio tx pipeline:        alsa ---> webrtc_aec ---> G722
audio rx pipeline:        alsa <--- webrtc_aec <--- G722
201@192.168.21.200: Call established: sip:XXXXXX@192.168.21.200
stream: incoming rtp for 'audio' established, receiving from 192.168.21.4:16912

webrtc_aec: encode: ProcessStream source and destination is ready, i:0 src:2080379304 dst:2080379304 numChannel:1 sampc:320
webrtc_aec: encode: ProcessStream error (-5) for i:0 src 
audio: aufilter encode: Protocol error
webrtc_aec: encode: ProcessStream source and destination is ready, i:0 src:2080379304 dst:2080379304 numChannel:1 sampc:320
webrtc_aec: encode: ProcessStream error (-5) for i:0 src 
audio: aufilter encode: Protocol error
webrtc_aec: encode: ProcessStream source and destination is ready, i:0 src:2080379304 dst:2080379304 numChannel:1 sampc:320
webrtc_aec: encode: ProcessStream error (-5) for i:0 src 
audio: aufilter encode: Protocol error
webrtc_aec: encode: ProcessStream source and destination is ready, i:0 src:2080379304 dst:2080379304 numChannel:1 sampc:320
webrtc_aec: encode: ProcessStream error (-5) for i:0 src 
audio: aufilter encode: Protocol error
Segmentation fault (core dumped)

**Comment by assegaf** [comment]
I am sorry I made mistake to put webrtc source folder (Name: WebRTC URL: http://www.webrtc.org)

in root folder of baresip source, and dont know affecting the webrtc_aec eventough I use
WEBRTC_PATH     := /usr/include/webrtc_audio_processing

in modules/webrtc_aec/module.mk


I removed webrtc folder and recompile, and then its working fine,
closed
