### ISSUE TITLE
Baresip+ (rtsp) door intercom purposes

### ISSUE THREAD

**Issue by pergolafabio** [baresip/baresip#1743]
Hi,

just installed Baresip+ on my android, looks good
I want it to use for my door intercom purposes

i noticed it can do early media support? But PBX servers like asterisk, dont support early media (video before pickup) when using ring groups...

Is there a way to specifiy an RTSP stream manually for a door intercom contact? so the RSP stream shown before pickup?

thnx in advance

**Comment by juha-h** [comment]
pergolafabio writes:

> just installed Baresip+ on my android, looks good
> I want it to use for my door intercom purposes

This not baresip+ issue tracker.

> i noticed it can do early media support? But PBX servers like
> asterisk, dont support early media (video before pickup) when using
> ring groups...
> 
> Is there a way to specifiy an RTSP stream manually for a door intercom
> contact? so the RSP stream shown before pickup?

I don't know what you are after, but you can start baresip call without
video and then add video media to it after the call has been answered.

**Comment by pergolafabio** [comment]
Hi, ok my apologies

no, the idea was to have an RTSP stream (early media/video) before i answer the call , so we can see who is pressing the doorbell intercom, without picking up

**Comment by juha-h** [comment]
pergolafabio writes:

> no, the idea was to have an RTSP stream (early media/video) before i
> answer the call , so we can see who is pressing the doorbell intercom,
> without picking up.

Try with Linux baresip and if you get what you want, you can propose the
missing feature in baresip-studio.

But baresip Android app is meant to be a normal VoIP app and I don't
want to complicate it with any special features.  Its source code is
open and you can implement such features yourself.

**Comment by pergolafabio** [comment]
ok, thnx for feedback, appreciated
