### ISSUE TITLE
OMX deprecated

### ISSUE THREAD

**Issue by DottiestDuke47** [baresip/baresip#1755]
I'm trying to compile the latest git version of baresip, but run into this error:

`  CC [M]  build-arm6/modules/omx/omx.o
In file included from modules/omx/omx.c:10:
modules/omx/omx.h:9:10: fatal error: IL/OMX_Core.h: No such file or directory
    9 | #include <IL/OMX_Core.h>
      |          ^~~~~~~~~~~~~~~
compilation terminated.
make: *** [mk/mod.mk:49: build-arm6/modules/omx/omx.o] Error 1`

I think this is because OMX was deprecated in favor of the V4L2 encoder. Are there any workarounds to this issue?

**Comment by alfredh** [comment]
did you install the omx development headers ?

The OMX module is a video display module. If it does not work, you can try SDL or X11 modules.
Can you share some info about which platform you are using (hardware, OS, etc.)

please also read this document:

https://github.com/baresip/baresip/wiki/Guidelines-for-reporting-Issues

the omx module has no maintainer:

https://github.com/baresip/baresip/wiki/Modules

hopefully someone can step up and maintain it, otherwise we might to remove it.

**Comment by DottiestDuke47** [comment]
I tried compiling this on Raspberry Pi OS Bullseye (64 and 32bit) on a Pi 4 2GB. I did try to install the OMX development headers (libomxil-bellagio-dev), but this made no difference. I tried looking for any documentation on how I can configure the build process, maybe using flags? - I'm new to this, so if you could provide any information regarding this, it would be much appreciated (Disabling OMX and/or using alternative modules, X11 would be a good replaceement.)

**Comment by alfredh** [comment]
I will close this ticket for now. Please feel free to open a new ticket if you can provide the needed details.

I will also go ahead and mark the omx module as deprecated/unmaintained,
unless someone wants to take owner ship of it.

**Comment by DottiestDuke47** [comment]
So I managed to get it to compile by editing mk/modues.mk and commenting out the omx module. I installed the dependancies for the VP8 codec and so far it seems to work as intended, however, when initiating video it takes a few long seconds to load, and the following is reported on the command line:

```
rtcp_pb: unknown PSFB fmt 4
rtcp_pb: unknown PSFB fmt 4
rtcp_pb: unknown PSFB fmt 4
rtcp_pb: unknown PSFB fmt 4
rtcp_pb: unknown PSFB fmt 4
rtcp_pb: unknown PSFB fmt 4
```

This repeats until the video loads on the client, and this message stops appearing.
