### ISSUE TITLE
Dropped a frame to reduce latency

### ISSUE THREAD

**Issue by juha-h** [baresip/baresip#1768]
I just created new version of my Android app using latest baresip/re/rem libs and noticed that audio quality is very bad.  I get lots of these to log during call:
```
Dropped a frame to reduce latency
```
I don't believe that there is any latency, since both UAC and UAS run on my laptop.  Audio works fine with earlier version of my Android app from Feb 24.

When I look the log messages, in Feb 24 version I get this when call starts:
```
03-12 19:05:24.784 18904 18940 D Baresip+ Lib: audio: source started with sample format S16LE
03-12 19:05:24.784 18904 18940 D Baresip+ Lib: audio tx pipeline:    opensles ---> webrtc_aecm ---> opus
03-12 19:05:24.784 18904 18940 D Baresip+ Lib: audio rx pipeline:    opensles <--- webrtc_aecm <--- opus
```
With today's version I get:
```
03-12 19:16:35.474 19151 19549 D Baresip Lib: audio tx pipeline:    opensles ---> aubuf ---> webrtc_aecm ---> opus
03-12 19:16:35.474 19151 19549 D Baresip Lib: audio rx pipeline:    opensles <--- aubuf <--- webrtc_aecm <--- opus
```
That is `aubuf` is now on the pipeline and might explain why my app has become useless.

**Comment by juha-h** [comment]
I see lots of audio related changes from late Feb to March 8.  Something must have gone wrong.

**Comment by juha-h** [comment]
I build my baresip app again:

re  at https://github.com/baresip/re/commit/c3bbabcebdf123922f7f3c3f8de10ca7642f4183
rem at https://github.com/baresip/rem/commit/7cb3cd04f321586621b9d6bd43a08c37a9044468
baresip at https://github.com/baresip/baresip/commit/fe40431976571812ed1119642f31b65c94b88164

With those libs audio works fine.

**Comment by sreimers** [comment]
I think the problem is this a wrong assumption of `tmr_jiffies` here:

https://github.com/baresip/baresip/blob/main/src/audio.c#L743

The code relies on a timespec compatible value.

We have switched the implementation in libre and `jitter_buffer_type = adaptive` is broken now:

https://github.com/baresip/re/commit/947245db6ffbcb91c1ebd22aba6748259b441fd2

**Comment by juha-h** [comment]
Good that you have an idea what might cause the issue.  I'm ready to dry any possible fixes.

**Comment by sreimers** [comment]
Yes should be easy, I prepare a PR.

**Comment by juha-h** [comment]
https://github.com/baresip/baresip/pull/1769 fixed the issue, thanks.
