### ISSUE TITLE
Accessing the call events from custom modules

### ISSUE THREAD

**Issue by GOBIKRISHNAN-R** [baresip/baresip#1783]
I've implemented a custom module in baresip for our requirements. I referred [this](https://github.com/baresip/baresip/wiki/How-to-add-new-modules) page for adding this new module. my module needs to know the call events of baresip. Is it possible to read the call events in my module? How can i access it?

**Comment by sreimers** [comment]
You have to register a callback handler:

https://github.com/baresip/baresip/blob/3d4293f209a7bff9ec3984995be83a3ea9a69649/modules/mqtt/publish.c#L99

```c
static void ua_event_handler(struct ua *ua, enum ua_event ev,
			     struct call *call, const char *prm, void *arg)
{
...
```

**Comment by alfredh** [comment]
please note that this Issues forum is mainly for reporting defects. Please use the mailing list for questions.

Here is a good example:

https://github.com/baresip/baresip/blob/main/modules/ebuacip/ebuacip.c

Ref:
https://github.com/baresip/baresip/wiki/Guidelines-for-reporting-Issues
