### ISSUE TITLE
stream: remove mbuf_get_left check in rtp_handler

### ISSUE THREAD

**Issue by GGGO** [baresip/baresip#1787]
Hi,

Is it ok to remove `if (!mbuf_get_left(mb)) return` ?

Right now, only RTP packets with payload data will pass. But we are missing packets with header extension only.

`metric_add_packet` won't increment `n_packets` and `handle_rtp` won't decode the header extensions.

A peer is sending me audio state in a custom header extension that is not RFC5285, and I'm trying to decode/encode these packets.

I would prefer to not change the baresip core but it seems I have no choice to. 

PS. As baresip is doing RFC 5285 directly in the core, I wonder if it's good to move this logic to a module.

Thanks.

```C
static void rtp_handler(const struct sa *src, const struct rtp_header *hdr,
			struct mbuf *mb, void *arg)
{
	struct stream *s = arg;
	bool flush = false;
	bool first = false;
	int err;

	MAGIC_CHECK(s);

	if (!s->rx.enabled && s->type == MEDIA_AUDIO)
		return;

	if (rtp_pt_is_rtcp(hdr->pt)) {
		info("stream: drop incoming RTCP packet on RTP port"
		     " (pt=%u)\n", hdr->pt);
		return;
	}

	s->rx.ts_last = tmr_jiffies();

	// if (!mbuf_get_left(mb))
	// 	return;

	if (!(sdp_media_ldir(s->sdp) & SDP_RECVONLY))
		return;

	metric_add_packet(&s->rx.metric, mbuf_get_left(mb));
...
```

**Comment by alfredh** [comment]
most likely it should be okay to remove the mbuf_get_left check. I think you have to try
and see if it works.

mbuf_get_left==0 means an empty RTP packet, you are quite unlikely to receive that,
but in any  case the decoder will also handle it.

regarding RTP header extension, we should consider a new framework:

1. api to add local header ext (name and handlers)
2. api to exchange rtp ext using SDP
3. api to inject an rtp header extension for all outgoing RTP packets
4. api to receive a given rtp header extension

the api should be flexible enough, so that it can be used from a new module.

example:

1. Bundle / mediamux
2. Aulevel
3. Real time timestamps
4. etc.

**Comment by GGGO** [comment]
Yes if I remove mbuf_get_left, I receive the empty RTP packet.
I think, I should doing that in a module.

**Comment by GGGO** [comment]
Or maybe we can reuse mnat design for that! As Bundle code use the udp_register_helper too.
We could rename mnat to something more generic and adapt baresip core/rtp to use that ?

We can benefit from it, the design is already there and gives control on the RTP sockets.

This could lead to others possibilities, like rtp bridging between 2 peers without encoding/decoding audio.

**Comment by alfredh** [comment]
I think this can be split into two parts:

1. remove mbuf_get_left check
2. add a framework for rtp header extensions

I suggest you make a PR for 1.) and see how it works.
The internal selftest program will tell you if something broke.

for 2.) it needs a bit more discussions ...

**Comment by alfredh** [comment]
I think this can be split into two parts:

1. remove mbuf_get_left check
2. add a framework for rtp header extensions

I suggest you make a PR for 1.) and see how it works.
The internal selftest program will tell you if something broke.

for 2.) it needs a bit more discussions ...

**Comment by alfredh** [comment]
I will close this now.

for adding a generic rtpext framework, we can add item to roadmap.
we can also create a PR for discussion.
