### ISSUE TITLE
alsa: could not open ausrc device 'plughw:0,0' (No such file or directory)

### ISSUE THREAD

**Issue by gbernaldo82** [baresip/baresip#1790]
Hi, good afternoon

I'm sorry if this issue is not related to baresip maybe it's related to Alsa but, I'm not sure about it. Please, feel free to close if that is the case.

I have the next problem running baresip on my RaspberryPI and I don't know exactly how to proceed. First of all, please, let me show you my setup before get into the error. I have one RaspberryPi with 2 USB Sound Card devices plugged to the RPI. Both USB devices are detected like this using the aplay command:
![aplay](https://user-images.githubusercontent.com/94070947/161746851-ef450444-28e3-4646-8c57-8451e67c39bf.png)

The contents of accounts file in /home/[USER]/.baresip/accounts are

<sip:1111@10.0.2.161>;auth_user=[USER];auth_pass=[PASSWORD];audio_source=alsa,plughw:1,0;audio_player=alsa,plughw:1,0
<sip:1109@10.0.2.161>;auth_user=[USER];auth_pass=[PASSWORD];audio_source=alsa,plughw:0,0;audio_player=alsa,plughw:0,0

So, when I run baresip from command line I don't have any kind of problem. But, when I call to one of my contacts (1109 or 1111) I don't have audio nor phone.

![Wrong](https://user-images.githubusercontent.com/94070947/161748243-9833ac51-466e-4606-81a6-79847c3bc6b2.png)

But If I put the same configuration under the file /root/.baresip/accounts

I don't have any kind of problem, I have audio and phone on both USB Sound Cards. 

![OK](https://user-images.githubusercontent.com/94070947/161748737-410a98f7-19bb-41fa-ad06-339e3bcafa4a.png)

Please, can anyone help me?
If this is not the correct place to this kind of issue please, address me to the correct place.

Thank you so much in advance!

**Comment by gbernaldo82** [comment]
Sorry, I've added the user to the Audio group and I don't get any error like those shown in the second picture but I don't have audio nor phone anyway.

**Comment by alfredh** [comment]
can you please try to upgrade to latest version, and try again ?

please also try asking on the mailing list:

https://github.com/baresip/baresip/wiki/Guidelines-for-reporting-Issues

**Comment by gbernaldo82** [comment]
Hi!

Sorry for the delay!

Let me try it, I'll tell you something when I've done!

**Comment by alfredh** [comment]
please ask on the mailing list first.

I will close this now, please note that we only support git HEAD in this forum, not old versions.
