### ISSUE TITLE
Audio Conference Issue

### ISSUE THREAD

**Issue by GOBIKRISHNAN-R** [baresip/baresip#1792]
I have enabled mixminus.so module under audio filter in config file
Audio from A->B->C is fine
From C->B->A is not working
C and A are client (linux PC)
B is server (linux PC) enabled mixminus here

After getting call from C and A, able to merge call using z command. But audio is not working in one way. 

Baresip version: v1.1.0
libre version     : libre.so.1.0.1
librem version  : librem.so.0.0.0
amixer              : 1.2.2
Logs:
```
baresip v1.1.0 Copyright (C) 2010 - 2021 Alfred E. Heggestad et al.
Local network addresses:
       eno2:  192.168.xx.xxx
ua: adding SIP CA file: /etc/ssl/certs/ca-certificates.crt
ua: adding SIP CA path: 
aucodec: PCMU/8000/1
aucodec: PCMA/8000/1
aufilt: mixminus
ausrc: alsa
auplay: alsa
medianat: stun
medianat: turn
medianat: ice
account: mediaenc not found: 'dtls_srtp'
user@example.com: Using sipnat: 'outbound'
user@example.com: Using medianat 'ice'
using stunserver: 'stun:username:password@stunserver.org'
user@example.com: Using medianat 'ice'
account: audio codec not found: opus/48000/2
Populated 7 accounts
Populated 2 contacts
ctrl_dbus: name com.github.Baresip acquired on the systemPopulated 2 audio codecs
Populated 1 audio filter
Populated 0 video codecs
Populated 0 video filters
baresip is ready.
ctrl_dbus: bus aquired name=com.github.Baresip
ctrl_dbus: dbus name lost com.github.Baresip
ctrl_dbus: could not export dbus interface
reg: sip:user@iptel.org (prio 0): 401 Unauthorized (ser (3.3.0-pre1 (i386/linux)))
reg: sip:user@example.com (prio 0): Register: Connection timed out
reg: sip:user@example.com (prio 0): Register: Connection timed out
reg: sip:user@example.com (prio 0): Register: Connection timed out
reg: sip:user@example.com (prio 0): Register: Connection timed out
reg: sip:user@example.com (prio 0): Register: Connection timed out
alice@office: selected
ua: using origin address 192.168.xx.xx of SDP offer
sip:alice@office: Incoming call from:  sip:alice@office - audio-video: sendrecv-inactive - (press 'a' to accept)
call: answering call on line 1 from sip:alice@office with 200
stream: update 'audio'
stream: receive: setting SSRC: be73d502
audio: Set audio decoder: PCMU 8000Hz 1ch
audio: player started with sample format S16LE
audio: Set audio encoder: PCMU 8000Hz 1ch
audio: source started with sample format S16LE
audio tx pipeline:        alsa ---> mixminus ---> PCMU
audio rx pipeline:        alsa <--- mixminus <--- PCMU
alice@office: Call established: sip:alice@office
stream: incoming rtp for 'audio' established, receiving from 192.168.xx.xx:31822
alice@office: selected64000 (bit/s)    
ua: using origin address 192.168.xx.xxx of SDP offer
sip:alice@office: Incoming call from:  sip:alice@office - audio-video: sendrecv-inactive - (press 'a' to accept)
call: hold sip:alice@office
stream: update 'audio'
audio: player started with sample format S16LE
call: answering call on line 2 from sip:alice@office with 200
stream: update 'audio'
stream: receive: setting SSRC: d96f6995
audio: Set audio decoder: PCMU 8000Hz 1ch
audio: player started with sample format S16LE
audio: Set audio encoder: PCMU 8000Hz 1ch
audio: source started with sample format S16LE
audio tx pipeline:        alsa ---> mixminus ---> PCMU
audio rx pipeline:        alsa <--- mixminus <--- PCMU
alice@office: Call answered: sip:alice@office
stream: update 'audio'
audio: player started with sample format S16LE
alice@office: Call established: sip:alice@office
stream: incoming rtp for 'audio' established, receiving from 192.168.xx.xxx:33480
conference with sip:alice@office
call: resume sip:alice@office
stream: update 'audio'
audio: player started with sample format S16LE
alice@office: Call answered: sip:alice@office
stream: update 'audio'
[0:00:12] audio=46080/46506 (bit/s)    
User-Agent: user@iptel.org
--- Active calls (0) ---


User-Agent: alice@office
--- Active calls (2) ---
> [line 1, id 65386f9de1b756bd]  0:00:12  ESTABLISHED             sip:alice@office
  [line 2, id e53156cada932650]  0:00:02  ESTABLISHED             sip:alice@office


User-Agent: user@example.com
--- Active calls (0) ---


User-Agent: user@example.com
--- Active calls (0) ---


User-Agent: user@example.com
--- Active calls (0) ---


User-Agent: user@example.com
--- Active calls (0) ---


User-Agent: user@example.com
--- Active calls (0) ---
```

**Comment by GGGO** [comment]
I think a .pcap file will help here. Just to confirm that RTP packets are flowing well.

**Comment by GOBIKRISHNAN-R** [comment]
I have verified in wireshark to check packets from C->B->A  it's not sending, but from B->A and A->B->C is working fine able to see packets as well in wireshark.
Can you please share the configuration for conferencing?

**Comment by GOBIKRISHNAN-R** [comment]
#
# My Configuration is
#

#------------------------------------------------------------------------------

# Core
poll_method		epoll		# poll, select, epoll ..

# SIP
sip_listen		192.168.127.223:5060
#sip_certificate	cert.pem
sip_cafile		/etc/ssl/certs/ca-certificates.crt
#sip_transports		udp,tcp,tls,ws,wss
#sip_trans_def		udp
sip_verify_server	yes
sip_tos			160 # See TOS fields!

## TOS fields ##
#    7     6     5     4     3     2     1     0
# +-----+-----+-----+-----+-----+-----+-----+-----+
# |   PRECEDENCE    |          TOS          | MBZ |
# +-----+-----+-----+-----+-----+-----+-----+-----+
# TOS:
# bit 4 - low delay
# bit 3 - high throughput
# bit 2 - high reliability
# bit 1 - low cost
# MBZ:
# bit 0 - zero

# Call
call_local_timeout	120
call_max_calls		4
call_hold_other_calls	yes

# Audio
#audio_path		/usr/local/share/baresip
audio_player		alsa,default
audio_source		alsa,default
audio_alert		alsa,default
#ausrc_srate		48000
#auplay_srate		48000
#ausrc_channels		0
#auplay_channels	0
#audio_txmode		poll		# poll, thread
audio_level		no
ausrc_format		s16		# s16, float, ..
auplay_format		s16		# s16, float, ..
auenc_format		s16		# s16, float, ..
audec_format		s16		# s16, float, ..
audio_buffer		20-160		# ms
audio_telev_pt		101		# payload type for telephone-event

# Video
#video_source		v4l2,/dev/video0
#video_display		x11,nil
video_size		640x480
video_bitrate		1000000
video_fps		30.00
video_fullscreen	yes
videnc_format		yuv420p

# AVT - Audio/Video Transport
rtp_tos			184
rtp_video_tos		136
#rtp_ports		10000-20000
#rtp_bandwidth		512-1024 # [kbit/s]
rtcp_mux		no
jitter_buffer_type	fixed		# off, fixed, adaptive
jitter_buffer_delay	5-10		# frames
#jitter_buffer_wish	6		# frames for start
rtp_stats		no
#rtp_timeout		60

# Network
#dns_server		1.1.1.1:53
#dns_server		1.0.0.1:53
#dns_fallback		8.8.8.8:53
#net_interface		eth0
# Play tones
#file_ausrc		aufile
#file_srate		16000
#file_channels		1

#------------------------------------------------------------------------------
# Modules

module_path		/usr/local/lib/baresip/modules

# UI Modules
module			stdio.so
#module			cons.so
#module			evdev.so
#module			httpd.so

# Audio codec Modules (in order)
#module			opus.so
#module			amr.so
#module			g7221.so
#module			g722.so
#module			g726.so
module			g711.so
#module			gsm.so
#module			l16.so
#module			mpa.so
#module			codec2.so
#module			ilbc.so

# Audio filter Modules (in encoding order)
module			mixminus.so
#module			vumeter.so
#module			sndfile.so
#module			plc.so
#module			webrtc_aec.so

# Audio driver Modules
module			alsa.so
#module			pulse.so
#module			jack.so
#module			portaudio.so
#module			aubridge.so
#module			aufile.so
#module			ausine.so

# Video codec Modules (in order)
#module			avcodec.so
#module			vp8.so
#module			vp9.so

# Video filter Modules (in encoding order)
#module			selfview.so
#module			snapshot.so
#module			swscale.so
#module			vidinfo.so
#module			avfilter.so

# Video source modules
#module			v4l2.so
#module			x11grab.so
#module			vidbridge.so

# Video display modules
#module			directfb.so
#module			x11.so
#module			sdl.so
#module			fakevideo.so

# Audio/Video source modules
#module			avformat.so
#module			rst.so
#module			gst.so
#module			gst_video.so

# Compatibility modules
#module			ebuacip.so
module			uuid.so

# Media NAT modules
module			stun.so
module			turn.so
module			ice.so
#module			natpmp.so
#module			pcp.so

# Media encryption modules
#module			srtp.so
#module			dtls_srtp.so
#module			zrtp.so


#------------------------------------------------------------------------------
# Application Modules

module_app		account.so
#module_app		b2bua.so
module_app		contact.so
module_app		debug_cmd.so
#module_app		echo.so
#module_app		gtk.so
module_app		menu.so
#module_app		mwi.so
#module_app		presence.so
#module_app		serreg.so
#module_app		syslog.so
#module_app		mqtt.so
#module_app		ctrl_tcp.so
module_app		ctrl_dbus.so
#module_app		httpreq.so
#module_app		multicast.so
module_app		netroam.so


#------------------------------------------------------------------------------
# Module parameters

# DTLS SRTP parameters
#dtls_srtp_use_ec	prime256v1

# UI Modules parameters
cons_listen		0.0.0.0:5555 # cons - Console UI UDP/TCP sockets

http_listen		0.0.0.0:8000 # httpd - HTTP Server

ctrl_tcp_listen		0.0.0.0:4444 # ctrl_tcp - TCP interface JSON

evdev_device		/dev/input/event0

# Opus codec parameters
opus_bitrate		28000 # 6000-510000
#opus_stereo		yes
#opus_sprop_stereo	yes
#opus_cbr		no
#opus_inbandfec		no
#opus_dtx		no
#opus_mirror		no
#opus_complexity	10
#opus_application	audio	# {voip,audio}
#opus_samplerate	48000
#opus_packet_loss	10	# 0-100 percent (expected packet loss)

# Opus Multistream codec parameters
#opus_ms_channels	2	#total channels (2 or 4)
#opus_ms_streams	2	#number of streams
#opus_ms_c_streams	2	#number of coupled streams

vumeter_stderr		yes

#jack_connect_ports	yes

# Selfview
video_selfview		window # {window,pip}
#selfview_size		64x64

# ZRTP
#zrtp_hash		no  # Disable SDP zrtp-hash (not recommended)

# Menu
#redial_attempts	0 # Num or <inf>
#redial_delay		5 # Delay in seconds
#ringback_disabled	no
#statmode_default	off
#menu_clean_number	no
#sip_autoanswer_method	rfc5373 # {rfc5373,call-info,alert-info}
#ring_aufile		ring.wav
#callwaiting_aufile	callwaiting.wav
#ringback_aufile	ringback.wav
#notfound_aufile	notfound.wav
#busy_aufile		busy.wav
#error_aufile		error.wav
#sip_autoanswer_aufile	autoanswer.wav

# GTK
#gtk_clean_number	no

# avcodec
#avcodec_h264enc	libx264
#avcodec_h264dec	h264
#avcodec_h265enc	libx265
#avcodec_h265dec	hevc
#avcodec_hwaccel	vaapi
#avcodec_profile_level_id 42002a

# ctrl_dbus
#ctrl_dbus_use	system		# system, session

# mqtt
#mqtt_broker_host	sollentuna.example.com
#mqtt_broker_port	1883
#mqtt_broker_cafile	/path/to/broker-ca.crt	# set this to enforce TLS
#mqtt_broker_clientid	baresip01	# has to be unique
#mqtt_broker_user	user
#mqtt_broker_password	pass
#mqtt_basetopic		baresip/01

# sndfile
#snd_path		/tmp

# EBU ACIP
#ebuacip_jb_type	fixed	# auto,fixed

# HTTP request module
#httpreq_ca		trusted1.pem
#httpreq_ca		trusted2.pem
#httpreq_dns		1.1.1.1
#httpreq_dns		8.8.8.8
#httpreq_hostname	myserver
#httpreq_cert		cert.pem
#httpreq_key		key.pem

# multicast receivers (in priority order)- port number must be even
#multicast_call_prio	0
#multicast_ttl		1
#multicast_jbuf_type	fixed		# off, fixed, adaptive
#multicast_jbuf_delay	5-10		# frames
#multicast_jbuf_wish	6		# frames for start
#multicast_listener	224.0.2.21:50000
#multicast_listener	224.0.2.21:50002

# avformat
#avformat_pass_through	yes

**Comment by GGGO** [comment]
I don't use mixminus, but if you say C is not sending any RTP...baresip won't mix audio from C.
So, you need to check the SIP trace with C to confirm that SDP is ok.
Maybe you have a NAT issue ?

**Comment by GOBIKRISHNAN-R** [comment]
It was working with baresip 0.6.6 . After upgrading the baresip source code to 1.1.0. we're facing this issue.

**Comment by GGGO** [comment]
In this case,
1. install the latest version of baresip, re, rem. Maybe issues have been resolved.
2. report issue with a pcap file. (sip and rtp trace)

**Comment by GOBIKRISHNAN-R** [comment]
There's no issue with the source code and the source versions. The issue is with the command "z". In the wiki page, it mentioned like, we need to press "z" to make the conference. But in the actual scenario, we need to to press "z" twice for each additional users. @alfredh, can you please check the functionality of audio conference?

Right now, I'm pressing "z" for two times to make the conference. And, is there any feature to make the baresip for auto-answer and auto-conference?
