### ISSUE TITLE
command "Toggle UAs" is missing after v2.0.1

### ISSUE THREAD

**Issue by phoenixwu** [baresip/baresip#1807]
This command is missing on v2.0.1 and v2.0.2
/uanext                      Toggle UAs

Hotkey T for this command is missing, too.

**Comment by negbie** [comment]
Mby uafind can help you? https://github.com/baresip/baresip/pull/1407 uanext was removed quite some time ago.

**Comment by phoenixwu** [comment]
THANKS for your information, IT HELPS.
/uanext can switch UA, but not convenient like hotkey T before.

I must input complete URI to switch UA, such as
`/uafind sip:+88671234567@ims.test.com`
