### ISSUE TITLE
Create Messaging subsystem

### ISSUE THREAD

**Issue by LuThaiHoc** [baresip/baresip#1813]
I'm trying to handler incoming message event using the function `int message_listen(struct message *message, message_recv_h *recvh, void *arg)` in file **message.c**. I have succeeded in sending and receiving messages using `message_send();` function. Now I dont know how to catch the event that user agent have an incomming message, I think I got stuck by create a true `struct message *message` varible, which is the first parameter in message_listen() function. Can anyone help? Thank you!

**Comment by alfredh** [comment]
please use the mailing list for asking questions:

https://github.com/baresip/baresip/wiki/Guidelines-for-reporting-Issues



can you please try the default baresip application without any extra code first ?
does it work to send and receive messages ?

if that works, please share the extra code that you have written. Please share the full config
and a trace of the debug output plus the SIP traffic.
