### ISSUE TITLE
Is it possible using baresip to call web browser(webrtc)?

### ISSUE THREAD

**Issue by xsw9527** [baresip/baresip#1815]
As we know,webrtc is widely used in browser.Is it possible that baresip call browser using webrtc?
And is it possible that browser call baresip ?

**Comment by alfredh** [comment]
please see this project:

    https://github.com/baresip/baresip-webrtc


build and start the application on your machine. Then start Chrome and open the
URL that is printed from the program. Now you can call from Chrome to baresip.

NOTE: please use the mailing list for asking questions :)

**Comment by xsw9527** [comment]
Thanks
