### ISSUE TITLE
Running two instances of baresip in windows

### ISSUE THREAD

**Issue by GOBIKRISHNAN-R** [baresip/baresip#1820]
Hi Folks,

I'm trying to run two instances of baresip in windows. In Linux, I'm able to do multiple instances using the **-f** flag. but In Windows, the **-f** flag is not working. always the baresip is taking configurations from the **AppData\Roaming\.bareip**. 

Is there any way to make two configurations for running two instances of baresip?

Thanks,
Gobi

**Comment by sreimers** [comment]
Parsing args relies on HAVE_GETOPT (UNIX/Linux only). We can put a win32 getopt() fallback implementation to the roadmap.

Maybe you can try something like this and patch main.c with it:
https://github.com/iotivity/iotivity/blob/master/resource/c_common/windows/src/getopt.c
