### ISSUE TITLE
RTP over IPv6 refused by baresip

### ISSUE THREAD

**Issue by vanrein** [baresip/baresip#1825]
I am setting up an IPv6-only SIP server with Kamailio.  The reason for making it IPv6-only is mostly to get away from RTP proxying and its impact on SDP rewriting and ability to be encrypted.

I see a nicely formed SDP offer coming in [from Kamailio] to baresip, which then refuses it saying `call: incompatible address-family (local=AF_INET, remote=AF_INET6)`.  This is surprising, given that it is listening on both IPv4 and IPv6 for SIP traffic and received the SIP INVITE over IPv6.

Indeed, I found that baresip will make an IPv4 address offer even when its outbound proxy is set to an IPv6 address.  The reasoning may be that *as long as I have an IPv4 address, I may as well use it*.  But that won't works if the remote server is an IPv6 server, and so it would enforce always using IPv4 and suffering from NAT traversal.  And when the SDP in an INVITE offers IPv6, a response defaulting to IPv4 is theoretically possible, but likely to makes NAT and firewalls close during the call if RTP purely flows in one direction.

I suggest a change of logic (and I am aware that going IPv6-only is teasing this out).  You might consider an option, but I think the current behaviour should not continue to be the default because it is breaking things.

**Reasonable Assumptions:**

  * If a SIP server has [only] an IPv6 address, it will be aware that any [concealed] crossover to IPv4 means that it should be willing to facilitate media crossover.
  * If a SIP server has [only] an IPv4 address, it will be aware that any [concealed] crossover to IPv6 means that it should be willing to facilitate media crossover.  It probably has to do this anyway, to remedy NAT traversal.
  * If a SIP server has both IPv4 and IPv6 addresses, it might loosen these constraints, leaving crossover translation to flexible phones for at least IPv6, but it probably has to do media proxy'ing anyway, to remedy NAT traversal.
  * It is possible to send SDP with multiple `c=` lines, and it is reasonable to expect IPv6 phones to be aware of multiple IPvX families; this may not always be true for IPv4-only phones; phones without understanding of this multiplicity are likely to pick the first `c=` line.

**Baresip change proposal:**

  * It is safe to stick with a given IPvX.  Any flexibility should be used to compensate for stiffness on the other end, but given an IPvX from the other end, that is how baresip should respond.
  * When a SIP server is reached over IPvX, then it is also possible, and always safe to pass RTP over IPvX.  This should be the default behaviour, IMHO.
  * When a SIP server sends an INVITE over IPvX, the first assumption would be to pass RTP over IPvX.  An SDP attachment usually takes precedence, if it is present it determines IPvX for the remote, which is the best family to respond over *if available*.
  * Any sign that IPv6 could be acceptable is a hint that SDP can be sent with multiple `c=` lines.  The other side then has more to choose from.
  * Make an option to allow choice of the IPvX family, at the expense of communication with the IPvY other.  The default setting might be called `auto` and behave flexibly, like explained above.

I think these changes are needed to facilitate the transition to SIP over IPv6 (and direct communication between domains, without intermediate/3rd-party media relays/tapping-points).  The current behaviour of baresip only seems to support IPv6 media when *both* ends are on an IPv6-only network.  Which is not how the Internet is evolving :)

*I was using baresip 0.6.1 as shipped with Debian stable.*

I hope this is useful/constructive criticism!

**Comment by vanrein** [comment]
An added note: The remote phone used was a Fritz!Box that signed up with my IPv6-only SIP server, and it *does* follow this logic of sending an `c=...IN6...` line to an IPv6 SIP server.  Baresip breaking on that because it *also* has an IPv4 address is a clear bug.  The rest of the proposal is a matter of opinion, mixed with some experience with crossover between IPv4 and IPv6.

**Comment by sreimers** [comment]
We changed the IPv6 behavior completely in latest versions. 0.6.1 (released Feb 2019) is very old. if possible please try the newest stable versions https://github.com/baresip/baresip/wiki/Install:-Stable-Release

**Comment by sreimers** [comment]
Feel free to re-open if you can reproduce with latest versions

**Comment by vanrein** [comment]
An extra opinion, based on the lower resource use and less assault on privacy when IPv6 transparency can be used to avoid media proxy'ing:

  * When an SDP offer comes in with `c=...IN4...` as well as `c=...IN6...` then the IPv6 variant should be preferred, if locally possible.

**Comment by vanrein** [comment]
Thanks, I will upgrade!

**Comment by vanrein** [comment]
Tried it, and indeed, the problem was remedied.  I'm surprised how far behind Debian has fallen.  Thanks!
