### ISSUE TITLE
AMR-WB codec decode 41 bytes: Operation not supported

### ISSUE THREAD

**Issue by drama10** [baresip/baresip#1833]
Hello, I'm having an issue with the AMR module (I assume), running Baresip v2.3.0. This is when I'm trying to call an actual telephone number, from a SIP client.

I'm using baresip through jack with float, and back. 

May  5 15:42:07 Baresip[32552]: SIPCLIENT@XXX.com: Call in-progress: sip:00012345678@XXX.com
May  5 15:28:59 Baresip[32130]: stream: update 'audio'
May  5 15:28:59 Baresip[32130]: audio: Set audio decoder: AMR-WB 16000Hz 1ch
May  5 15:28:59 Baresip[32130]: jack: play 48000Hz,1ch
May  5 15:28:59 Baresip[32130]: jack: NOTE: source sample conversion needed: S16LE  -->  FLOAT
May  5 15:29:00 Baresip[32130]: jack: source unique name `baresip' assigned
May  5 15:29:00 Baresip[32130]: jack: engine sample rate: 48000 max_frames=960
May  5 15:29:00 Baresip[32130]: jack: connect physical input ports
May  5 15:29:00 Baresip[32130]: jack: sampc=960
May  5 15:29:00 Baresip[32130]: audio: player started with sample format S16LE
May  5 15:29:00 Baresip[32130]: audio: Set audio encoder: AMR-WB 16000Hz 1ch
May  5 15:29:00 Baresip[32130]: jack: destination unique name `baresip-01' assigned
May  5 15:29:00 Baresip[32130]: jack: engine sample rate: 48000 max_frames=960
May  5 15:29:00 Baresip[32130]: jack: connect to physical output ports
May  5 15:29:00 Baresip[32130]: jack: source sampc=960
May  5 15:29:00 Baresip[32130]: audio: source started with sample format FLOAT
May  5 15:29:00 Baresip[32130]: audio tx pipeline:        jack ---> aubuf ---> auconv ---> auresamp ---> vumeter ---> AMR-WB
May  5 15:29:00 Baresip[32130]: audio rx pipeline:        jack <--- aubuf <--- auconv <--- auresamp <--- vumeter <--- AMR-WB
May  5 15:29:00 Baresip[32130]: jack: source destroy
May  5 15:29:00 Baresip[32130]: jack: destroy
May  5 15:29:00 Baresip[32130]: jack: play 48000Hz,1ch
May  5 15:29:00 Baresip[32130]: jack: NOTE: source sample conversion needed: S16LE  -->  FLOAT
May  5 15:29:00 Baresip[32130]: jack: source unique name `baresip' assigned
May  5 15:29:00 Baresip[32130]: jack: engine sample rate: 48000 max_frames=960
May  5 15:29:00 Baresip[32130]: jack: connect physical input ports
May  5 15:29:00 Baresip[32130]: jack: sampc=960
May  5 15:29:00 Baresip[32130]: audio: player started with sample format S16LE
May  5 15:29:01 Baresip[32130]: jack: destination unique name `baresip-01' assigned
May  5 15:29:01 Baresip[32130]: jack: engine sample rate: 48000 max_frames=960
May  5 15:29:01 Baresip[32130]: jack: connect to physical output ports
May  5 15:29:01 Baresip[32130]: jack: source sampc=960
May  5 15:29:01 Baresip[32130]: audio: source started with sample format FLOAT
May  5 15:29:01 Baresip[32130]: audio tx pipeline:        jack ---> aubuf ---> auconv ---> auresamp ---> vumeter ---> AMR-WB
May  5 15:29:01 Baresip[32130]: audio rx pipeline:        jack <--- aubuf <--- auconv <--- auresamp <--- vumeter <--- AMR-WB
May  5 15:29:01 Baresip[32130]: SIPCLIENT@XXX.com: Call in-progress: sip:00012345678@XXX.com
May  5 15:29:01 Baresip[32130]: stream: update 'audio'
May  5 15:29:01 Baresip[32130]: stream: incoming rtp for 'audio' established, receiving from 123.45.67.89:31692
May  5 15:29:01 Baresip[32130]: #033[31maudio: AMR-WB codec decode 41 bytes: Operation not supported
May  5 15:29:01 Baresip[32130]: #033[;m#033[31maudio: AMR-WB codec decode 41 bytes: Operation not supported
May  5 15:29:01 Baresip[32130]: #033[;m#033[31maudio: AMR-WB codec decode 41 bytes: Operation not supported
....
and it keeps going

I can actually here to audio coming though to the telephone, but it's dead slient from the telephone -> back to the SIP

**Comment by sreimers** [comment]
The AMR-WB module only supports `s16` can you try:

~/.baresip/config:
```
ausrc_format		float	
auplay_format		float
auenc_format		s16
audec_format		s16
```

**Comment by drama10** [comment]
I've tried that.

Then I get:

May  5 17:47:12 ih880916 Baresip[3596]: #033[;m#033[31maudio: rx: invalid sample formats (S16LE -> FLOAT).
May  5 17:47:12 ih880916 Baresip[3596]: #033[;m#033[31maudio: rx: invalid sample formats (S16LE -> FLOAT).
May  5 17:47:12 ih880916 Baresip[3596]: #033[;m#033[31mauconv: format not supported (FLOAT)
May  5 17:47:12 ih880916 Baresip[3596]: #033[;m#033[31maudio: rx: invalid sample formats (S16LE -> FLOAT).
May  5 17:47:12 ih880916 Baresip[3596]: #033[;m#033[31mauconv: format not supported (FLOAT)

**Comment by drama10** [comment]
Hello! It's me again :D

Dont quite seem to work out for me. With S16 <-> FLOAT <-> S16 conversion.

Still only work one way. On version 1.0.0 I can actullay see this happening:

Baresip[13980]: audio: player started with sample format FLOAT
**Baresip[13980]: audio: NOTE: playback sample conversion needed: S16LE  -->  FLOAT**
Baresip[13980]: audio: Set audio encoder: opus 48000Hz 2ch
Baresip[13980]: opus: mirror parameters: "stereo=1;sprop-stereo=1;maxaveragebitrate=384000;cbr=1;useinbandfec=0;usedtx=0"
Baresip[13980]: jack: destination unique name `baresip-01' assigned
Baresip[13980]: jack: engine sample rate: 48000 max_frames=960
**Baresip[13980]: audio: NOTE: source sample conversion needed: FLOAT  -->  S16LE**

**Comment by juha-h** [comment]
I 'm not sure if this is relevant, but on my Debian 11, AMR-WB works fine with these config settings:
```
ausrc_format            s16
auenc_format            s16
auplay_format           s16
audec_format            s16
```
and this account `audio_codecs` parameter:
```
audio_codecs=AMR-WB/16000/1,...

**Comment by alfredh** [comment]
```c
static int process_frame(void *buf, enum aufmt target_fmt,
			 struct auframe *af)
{
	switch (target_fmt) {

	case AUFMT_S16LE:
		auconv_to_s16(buf, af->fmt, af->sampv, af->sampc);
		break;

	default:
		warning("auconv: format not supported (%s)\n",
			aufmt_name(target_fmt));
		return ENOTSUP;
	}

	af->sampv = buf;
	af->fmt   = target_fmt;

	return 0;
}
```

AUFMT_FLOAT is missing and needs to be implemented.

you need to make a function `auconv_to_float`, similar to auconv_to_s16.

**Comment by drama10** [comment]
There is a "auconv from s16", should we use that. Or create a auconv to float, and should it be generic? 
@alfredh @sreimers

**Comment by alfredh** [comment]
please try this patch:

```diff
diff --git a/modules/auconv/auconv.c b/modules/auconv/auconv.c
index cada62e9..aabc5a20 100644
--- a/modules/auconv/auconv.c
+++ b/modules/auconv/auconv.c
@@ -93,6 +93,36 @@ static int decode_update(struct aufilt_dec_st **stp, void **ctx,
 }
 
 
+static inline float ausamp_short2float(int16_t in)
+{
+	float out;
+
+	out = (float) (in / (1.0 * 0x8000));
+
+	return out;
+}
+
+
+static void auconv_to_float(float *dst_sampv, enum aufmt src_fmt,
+			    const void *src_sampv, size_t sampc)
+{
+	const int16_t *s16;
+
+	switch (src_fmt) {
+
+	case AUFMT_S16LE:
+		s16 = src_sampv;
+		for (size_t i=0; i<sampc; i++) {
+			dst_sampv[i] = ausamp_short2float(s16[i]);
+		}
+		break;
+
+	default:
+		break;
+	}
+}
+
+
 static int process_frame(void *buf, enum aufmt target_fmt,
 			 struct auframe *af)
 {
@@ -102,6 +132,10 @@ static int process_frame(void *buf, enum aufmt target_fmt,
 		auconv_to_s16(buf, af->fmt, af->sampv, af->sampc);
 		break;
 
+	case AUFMT_FLOAT:
+		auconv_to_float(buf, af->fmt, af->sampv, af->sampc);
+		break;
+
 	default:
 		warning("auconv: format not supported (%s)\n",
 			aufmt_name(target_fmt));
```

**Comment by alfredh** [comment]
please try this patch above. If it is working for you, then we can clean up the patch
and push it to main.

**Comment by drama10** [comment]
This patch works! Very nice.
