### ISSUE TITLE
ICE priority collision

### ISSUE THREAD

**Issue by juha-h** [baresip/baresip#1862]
I noticed that rtpengine issued warnings about INVITE send from baresip:
```
May 26 13:32:10 lab rtpengine[298127]: WARNING: [29f7cabb1a86b205]: [ice] Priority collision between candidate pairs vIyrj6q8cw2myNpO:8f3c7a26:1 and vIyrj6q8cw2myNpO:da8638dd:1 - ICE will likely fail
```
ICE lines in INVITE's SDP looked like this:
```
a=candidate:8f3c7a26 1 UDP 2113929471 2001:14bb:67b:28a7::93 13026 typ host
a=candidate:8f3c7a26 2 UDP 2113929470 2001:14bb:67b:28a7::93 13027 typ host
a=candidate:da8638dd 1 UDP 2113929471 2001:14bb:67b:28a7:767a:9ddb:8d38:271d 13026 typ host
a=candidate:da8638dd 2 UDP 2113929470 2001:14bb:67b:28a7:767a:9ddb:8d38:271d 13027 typ host
a=candidate:c0a89913 1 UDP 2113929471 192.168.153.19 13026 typ host
a=candidate:c0a89913 2 UDP 2113929470 192.168.153.19 13027 typ host
a=candidate:0ab7f5b0 1 UDP 2113929471 10.183.245.176 13026 typ host
a=candidate:0ab7f5b0 2 UDP 2113929470 10.183.245.176 13027 typ host
a=candidate:2521ad4e 2 UDP 1677721854 37.33.173.79 64842 typ srflx raddr 2001:14bb:67b:28a7::93 rport 13027
a=candidate:2521ad4e 1 UDP 1677721855 37.33.173.79 64841 typ srflx raddr 2001:14bb:67b:28a7::93 rport 13026
```
and indeed there was candidates with equal priority (and component ID).

I then did some digging and found Richard commenting the rtpengine warning like this:
```
To explain: Each ICE candidate is supposed to have a unique priority 
number associated with it. The ICE code in rtpengine depends on this 
being true in several places. If it encounters two ICE candidates with 
the same priority number then it triggers this warning to the log, and 
ultimately the ICE negotiation is then likely to fail. This can happen 
if the remote ICE client is buggy (seen this before: duplicate priority 
numbers in the SDP), or (gods forbid) there's a bug in rtpengine.
```
I also checked ICE RFC 8445 and found this:
```
5.1.2 Prioritizing Candidates
   The prioritization process results in the assignment of a priority to
   each candidate.  Each candidate for a data stream MUST have a unique
   priority that MUST be a positive integer between 1 and (2**31 - 1).
   This priority will be used by ICE to determine the order of the
   connectivity checks and the relative preference for candidates.
   Higher-priority values give more priority over lower values.
```
So unless proven otherwise, this looks like a bug in baresip.

**Comment by sreimers** [comment]
Looks like the prio for calculation is always zero:

https://github.com/baresip/baresip/blob/9584addda5bc314ec3d0298162c3dbe8f8c4072d/modules/ice/ice.c#L386-L394

**Comment by juha-h** [comment]
Indeed, lprio is not set after it is initialized to 0.  Calculation is explained here:

https://www.rfc-editor.org/rfc/rfc5245.html#section-4.1.2.1

but does not look simple to me.

**Comment by sreimers** [comment]
Since we have refactored the network code we can maybe use some of the new functions, like:

`const struct sa *net_laddr_af(const struct network *net, int af)`

for highest prio addresses (default route) and other multihomed IPs are simply added with decreased prio value.

**Comment by sreimers** [comment]
65535 -> net_laddr_af(const struct network *net, AF_INET6);
65534 -> net_laddr_af(const struct network *net, AF_INET);

Or we add a lprio field here: https://github.com/baresip/baresip/blob/main/src/net.c#L23

**Comment by juha-h** [comment]
Sebastian Reimers writes:

> Since we have refactored the network code we can maybe use some of the
> new functions, like: 
> 
> `const struct sa *net_laddr_af(const struct network *net, int af)`
> 
> for highest prio addresses (default route) and other multihomed IPs
> are simply added with decreased prio value.

Yes, make sense to use the default route network as the highest
priority.  If the same interface has both IPv4 and IPv6 address, which
one would have higher priority?

**Comment by sreimers** [comment]
> If the same interface has both IPv4 and IPv6 address, which one would have higher priority?

I would say IPv6, but maybe this could be made configurable.

**Comment by juha-h** [comment]
Sebastian Reimers writes:

> > If the same interface has both IPv4 and IPv6 address, which one
> > would have higher priority?
> 
> I would say IPv6, but maybe this could be made configurable.

IPv6 would be fine with me.

**Comment by sreimers** [comment]
I made quick fix: https://github.com/baresip/baresip/pull/1863
@juha-h can you help testing?

**Comment by juha-h** [comment]
Looks good also on Linux and rtpengine is happy:

a=candidate:0a840986 1 UDP 2130706175 10.132.9.134 37516 typ host
a=candidate:0a840986 2 UDP 2130706174 10.132.9.134 37517 typ host
a=candidate:1eb4c219 1 UDP 2130706431 2001:14bb:694:8484:e8ae:7d3b:d7f9:591a 37516 typ host
a=candidate:1eb4c219 2 UDP 2130706430 2001:14bb:694:8484:e8ae:7d3b:d7f9:591a 37517 typ host
a=candidate:89909526 1 UDP 2122313215 2001:14bb:694:8484::b6 37516 typ host
a=candidate:89909526 2 UDP 2122313214 2001:14bb:694:8484::b6 37517 typ host
a=candidate:c0a8e132 1 UDP 2122312959 192.168.225.50 37516 typ host
a=candidate:c0a8e132 2 UDP 2122312958 192.168.225.50 37517 typ host
a=candidate:2521d02d 2 UDP 1677721854 37.33.208.44 2325 typ srflx raddr 10.132.9.134 rport 37517
a=candidate:2521d02d 1 UDP 1677721855 37.33.208.44 2324 typ srflx raddr 10.132.9.134 rport 37516n

**Comment by alfredh** [comment]
thanks for reporting

it would be nice if we have a similar function in re to check a candidate list, that all
priorities are unique. This check can then be used in baresip/re for outgoing candidates
and incoming candidates.

**Comment by juha-h** [comment]
Sebastian Reimers writes:

> I made quick fix: https://github.com/baresip/baresip/pull/1863
> @juha-h can you help testing?

Worked fine on Linux behind NAT.  I'll try also on Android that has
more interfaces.
