### ISSUE TITLE
REGISTER event logging depends on presence module

### ISSUE THREAD

**Issue by juha-h** [baresip/baresip#1888]
REGISTER event are not logged with -v flag if presence module is not loaded.  If loaded, they are prefixed with `presence:`, for example:
```
baresip is ready.
test@test.tutpro.com: (prio 0) {1/TCP/v4} 200 OK (OpenSIPg SIP Proxy (5.6.0-0b31 (x86_64/linux))) [1 binding]
All 1 useragent registered successfully! (1021 ms)
presence: ua=0x55ba472edec0 got event 1 (REGISTER_OK)
```

**Comment by alfredh** [comment]
I think the presence module is logging all events, not just register events

if you want to see event logging in the console, we should add support for that.
this can be done in 2 ways:

1. add logging in core
2. add a module for logging

**Comment by juha-h** [comment]
I don't necessarily need that although it could in some cases be useful. It just felt strange to me that events that have nothing to do with presence are logged only it presence module is loaded.
