### ISSUE TITLE
/uareg does not register if baresip has been started with ;regint=0

### ISSUE THREAD

**Issue by juha-h** [baresip/baresip#1912]
I noticed that /`uareg 120 0` does not send REGISTER request if baresip is started so that account's `;regint=0`:
```
/uafind sip:test@test.tutpro.com
ua: sip:test@test.tutpro.com
/uareg 120 0
sip:test@test.tutpro.com: selected for request
registering sip:test@test.tutpro.com with interval 120 seconds
ua: ua_register sip:test@test.tutpro.com
presence: ua=0x56154407a330 got event 0 (REGISTERING)
```
Most likely this is because in ua.c `start_register`, regl is empty:
```
	if (!fallback)
		ua_event(ua, UA_EVENT_REGISTERING, NULL, NULL);

	for (le = ua->regl.head, i=0; le; le = le->next, i++) {
		struct reg *reg = le->data;

		err = reg_register(reg, reg_uri, params,
                         ...
```
What is the right way to solve the issue?  Should we test before the for loop if regl is empty and if so, call `create_register_clients(ua)`?

**Comment by juha-h** [comment]
I tested with this addition in the above and after that /uareg worked ok:
```
	if (!fallback)
		ua_event(ua, UA_EVENT_REGISTERING, NULL, NULL);

	if (!(ua->regl.head))
		create_register_clients(ua);
	
	for (le = ua->regl.head, i=0; le; le = le->next, i++) {
```
Would it be OK, if I create a PR?

**Comment by sreimers** [comment]
Looks fine to me, btw. you can use the `list_isempty` helper.

**Comment by juha-h** [comment]
In addition to the above, PR https://github.com/baresip/baresip/pull/1913 does not send UA_EVENT_REGISTERING if the regl remains empty, since no registrations are done.

**Comment by cspiel1** [comment]
I am a little bit confused. `regint=0` is the setting for a server-less account. This are accounts for which no REGISTER is sent. These can be used for peer-to-peer calls. What do you expect?

**Comment by juha-h** [comment]
Christian Spielberger writes:

> I am a little bit confused. `regint=0` is the setting for a
> server-less account. This are accounts for which no REGISTER is
> sent. These can be used for peer-to-peer calls. What do you expect?

If user gives command

/uareg 300 0

then I expect that from now on regint will be 300 no matter what it was
when baresip was started.

Command /uareg sets account's regint and then registers:

	err = account_set_regint(acc, regint);
	if (err)
		return err;

	if (regint) {
		re_hprintf(pf, "registering %s with interval %u seconds\n",
			   account_aor(acc), regint);
		err = ua_register(ua);
		if (err)
			return err;
	}
	else {
		re_hprintf(pf, "unregistering %s\n", account_aor(acc));
		ua_unregister(ua);
	}

So this should work also when regint initially was zero.

Users of my baresip Android app have been asking for this.  They have
some kind of tasker that turns on/off registration of certain accounts
based on time of day, etc.

**Comment by juha-h** [comment]
Closed by https://github.com/baresip/baresip/pull/1913.
