### ISSUE TITLE
No free-line signal since baresip v2.5.0

### ISSUE THREAD

**Issue by robert-scheck** [baresip/baresip#1957]
When calling somebody (outside of the own PBX), there is no free-line signal since baresip v2.5.0 anymore (baresip v2.5.0, re v2.5.0, rem v2.5.0). With "free-line signal", I mean "call-connected signal", so the classic POTS sound sequence that you normally hear as a caller while the phone is ringing at the callee. The last version known to work properly is baresip v2.4.0 (baresip v2.4.0, re v2.4.0, rem v2.4.0).

Any pointers?

**Comment by sreimers** [comment]
On a quick guess, maybe this PR is related: https://github.com/baresip/baresip/pull/1922

**Comment by robert-scheck** [comment]
Yes, good catch! Reverting commit 28fa0176148381f2e79ec0d310371436a57cdea1 makes it working again.

**Comment by sreimers** [comment]
@RobertMi21 Can you check this?

**Comment by RobertMi21** [comment]
Sorry for the troubles with my changes. I did not notice that early audio and the free-line signal did not work after my changes. I'll try to find a working fix for #1922 .

**Comment by robert-scheck** [comment]
With "free-line signal", I mean "call-connected signal", so the classic POTS sound sequence that you normally hear as a caller while the phone is ringing at the callee. Or in German "Freiton" aka "Freizeichen"; Wikipedia says this is also called "ring-back tone" in English. And yes, #1963 is a duplicate of this one.
