### ISSUE TITLE
audio call is automatically modified to audio-video call after 200 OK is received

### ISSUE THREAD

**Issue by juha-h** [baresip/baresip#2042]
Using latest main, I noticed the following with my baresip+ app:

- baresip+ sends audio only INVITE to Linux baresip
- after receiving audio only 200 OK, I get to log:
```
07-31 10:58:47.924 21275 21347 D Baresip+ Lib: call: got SDP answer (472 bytes)
07-31 10:58:47.945 21275 21346 D Baresip+ Lib: ua event (CALL_REMOTE_SDP) answer
07-31 10:58:47.946 21275 21346 D Baresip+ Lib: video RTP/AVP
07-31 10:58:47.946 21275 21346 D Baresip+ Lib:   local formats:
07-31 10:58:47.946 21275 21346 D Baresip+ Lib:      96 VP9/90000/1 () *
07-31 10:58:47.946 21275 21346 D Baresip+ Lib:      97 VP8/90000/1 () *
07-31 10:58:47.946 21275 21346 D Baresip+ Lib:      98 H264/90000/1 () *
07-31 10:58:47.946 21275 21346 D Baresip+ Lib:      99 H264/90000/1 () *
07-31 10:58:47.946 21275 21346 D Baresip+ Lib:      34 H263/90000/1 () *
07-31 10:58:47.946 21275 21346 D Baresip+ Lib:     100 H265/90000/1 (profile-id=1) *
07-31 10:58:47.946 21275 21346 D Baresip+ Lib:     101 AV1/90000/1 () *
07-31 10:58:47.946 21275 21346 D Baresip+ Lib:   remote formats:
07-31 10:58:47.946 21275 21346 D Baresip+ Lib:   local attributes:
07-31 10:58:47.946 21275 21346 D Baresip+ Lib:     rtcp-rsize
07-31 10:58:47.946 21275 21346 D Baresip+ Lib:     ssrc='132011099 cname:sip:bar@test.tutpro.com'
07-31 10:58:47.946 21275 21346 D Baresip+ Lib:     mid='1'
07-31 10:58:47.946 21275 21346 D Baresip+ Lib:     framerate='15.00'
07-31 10:58:47.946 21275 21346 D Baresip+ Lib:     rtcp-fb='* nack pli'
07-31 10:58:47.946 21275 21346 D Baresip+ Lib:     content='main'
07-31 10:58:47.946 21275 21346 D Baresip+ Lib:     label='2'
07-31 10:58:47.946 21275 21346 D Baresip+ Lib:   remote attributes:
07-31 10:58:47.946 21275 21346 D Baresip+ Lib:   local direction:  inactive
07-31 10:58:47.946 21275 21346 D Baresip+ Lib:   remote direction: sendrecv
07-31 10:58:47.946 21275 21346 D Baresip+ Lib: 
07-31 10:58:47.946 21275 21346 D Baresip+ Lib: local media dir 0
07-31 10:58:47.946 21275 21346 D Baresip+ Lib: remote media dir 3
```
- baresip+ sends ACK
- after that baresip+ automatically modifies the call by sending audio/video re-INVITE

In my opinion that should NOT happen.  User must have control if video is enabled for the call.  This did not happen earlier, but I don't know before which commit.  Please revert back to earlier behavior.

**Comment by juha-h** [comment]
I'll try to find after which commit the behavior changed or if there is something wrong in my app.  But I don't remember making any media related changes during the last few months at least.

**Comment by juha-h** [comment]
I have not found anything that the app is doing that would cause the re-INVITE with audio/video to be sent.

After the above shown debug log output this comes to the log:
```
07-31 10:58:47.948 21275 21347 D Baresip+ Lib: call: update media
07-31 10:58:47.948 21275 21347 D Baresip+ Lib: stream: update 'audio'
07-31 10:58:47.948 21275 21347 D Baresip+ Lib: stream: receive: setting SSRC: bb6677f4
07-31 10:58:47.948 21275 21347 D Baresip+ Lib: stream: audio: starting RTCP with remote x.x.x.x:60493
07-31 10:58:47.948 21275 21347 D Baresip+ Lib: stream: update 'video'
07-31 10:58:47.948 21275 21347 D Baresip+ Lib: audio: update
07-31 10:58:47.948 21275 21347 D Baresip+ Lib: audio: Set audio decoder: opus 16000Hz 1ch
07-31 10:58:47.948 21275 21347 D Baresip+ Lib: audio: start
07-31 10:58:47.948 21275 21347 D Baresip+ Lib: audio: create auplay buffer [40 - 200 ms] [1280 - 6400 bytes]
07-31 10:58:47.948 21275 21347 D Baresip+ Lib: opensles: opening player 16000Hz, 1channels
07-31 10:58:47.991 21275 21347 D Baresip+ Lib: audio: player started with sample format S16LE
07-31 10:58:47.991 21275 21347 D Baresip+ Lib: audio: Set audio encoder: opus 16000Hz 1ch
07-31 10:58:47.991 21275 21347 D Baresip+ Lib: opus: encoder fmtp (stereo=0;sprop-stereo=0;maxaveragebitrate=28000;cbr=0;useinbandfec=1)
07-31 10:58:47.992 21275 21347 D Baresip+ Lib: audio: start
07-31 10:58:47.992 21275 21347 D Baresip+ Lib: webrtc_aecm: creating shared state: [16000 Hz, 1 channels, subframe 160 samples, num_bands 1]
07-31 10:58:47.992 21275 21347 D Baresip+ Lib: opensles: opening recorder 16000Hz, 1channels
07-31 10:58:48.048 21275 21347 D Baresip+ Lib: audio: source started with sample format S16LE
07-31 10:58:48.048 21275 21347 D Baresip+ Lib: audio tx pipeline:    opensles ---> aubuf ---> webrtc_aecm ---> opus
07-31 10:58:48.048 21275 21347 D Baresip+ Lib: audio rx pipeline:    opensles <--- aubuf <--- webrtc_aecm <--- opus

ACK is sent

07-31 10:58:48.051 21275 21347 D Baresip+ Lib: call: stream start (active=1)
07-31 10:58:48.051 21275 21347 D Baresip+ Lib: opus: encoder fmtp (stereo=0;sprop-stereo=0;maxaveragebitrate=28000;cbr=0;useinbandfec=1)
07-31 10:58:48.051 21275 21347 D Baresip+ Lib: audio: start
07-31 10:58:48.051 21275 21347 D Baresip+ Lib: stream: audio: enable RTP from remote
07-31 10:58:48.051 21275 21347 D Baresip+ Lib: stream: video: enable RTP from remote
07-31 10:58:48.051 21275 21347 D Baresip+ Lib: call: modify

re-INVITE with audio and video is sent
```
Why is the call automatically modified to include also video?

**Comment by juha-h** [comment]
When the app makes a call, these API functions are called:
```
Api.ua_call_alloc(ua.uap, 0L, Api.VIDMODE_ON)
call.setMediaDirection(Api.SDP_SENDRECV, API.SDP_INACTIVE)
Api.call_connect(callp, uri)
```
Video should thus be inactive unless later activated by the user.

**Comment by juha-h** [comment]
I built baresip+ app using baresip/re/rem libs from July 1 (2.5.0) and the problem didn't appear.  No re-INVITE was sent after the call was established.

Why does latest main send the re-INVITE?  I don't see any need tor it.  Things get worse when the re-INVITE adds video to audio only call.

**Comment by sreimers** [comment]
Is this related?: https://github.com/baresip/baresip/pull/1929

**Comment by juha-h** [comment]
The problem didn't appear with baresip tag 2.5.1 either.  But it does appear when I use latest main of baresip, which also requires latest main of re and rem.

**Comment by juha-h** [comment]
> Is this related?: #1929

May be it is, but in my test calls there is no 183 response, just 180 ringing followed by 200 ok.  So there is no need to send the re-INVITE and it must not be sent.

**Comment by juha-h** [comment]
It is this commit https://github.com/baresip/baresip/commit/3c57d6c344f1dae38d845648f429f62b5c9d2b8a that causes the issue.

**Comment by sreimers** [comment]
Can you test if this also affects `menu` cli usage? Maybe your app needs a similar change like that:

https://github.com/baresip/baresip/pull/1929/files#diff-db57f558f11efa7377d3e7648c9eb88ae8e359aa78eac2d5cb5f623e28988b8fR374-R378

CC: @cspiel1

**Comment by juha-h** [comment]
Sebastian Reimers writes:

> Can you test if this also affects `menu` cli usage? Maybe your app needs a similar change like that:
> 
> https://github.com/baresip/baresip/pull/1929/files#diff-db57f558f11efa7377d3e7648c9eb88ae8e359aa78eac2d5cb5f623e28988b8fR374-R378
> 

Perhaps it doesn't affect the cli app, but I don't want to complicate my
app.  Call is now made very simply like this and it should keep working
like that:

Api.ua_call_alloc(ua.uap, 0L, Api.VIDMODE_ON)
call.setMediaDirection(Api.SDP_SENDRECV, API.SDP_INACTIVE)
Api.call_connect(callp, uri)

If the CLI app needs something more then new API calls should be
introduced rather than breaking existing behavior.

**Comment by juha-h** [comment]
There is new API function call_set_media_ansdir, but in my test call is
made, not answered.  So there should be no need to call that function
and baresip should behave as it has done before.

**Comment by juha-h** [comment]
Which section of RFC3261 mandates this, which cased the commit? `Due to RFC-3261 the SDP in the 183 Session Progress has to be equal to the SDP in the 200 Ok.`

In my test there is no 183 response and thus no need for any changes.

**Comment by cspiel1** [comment]
Let me see! I will check this.

**Comment by cspiel1** [comment]
> * after that baresip+ automatically modifies the call by sending audio/video re-INVITE
> 
> In my opinion that should NOT happen. User must have control if video is enabled for the call. This did not happen earlier, but I don't know before which commit. Please revert back to earlier behavior.

Right! But I suggest to find and solve the problem and not revert anything.

**Comment by cspiel1** [comment]
> Due to RFC-3261 the SDP in the 183 Session Progress has to be equal to the SDP
in the 200 Ok. The correct solution is to answer the call with same SDP and
send immediately a re-INVITE if needed. E.g. in case of early video send
re-INVITE in order to activate the audio stream.

This is the correct behavior. The question is if the re-INVITE is sent in cases we don't expect it. This maybe should be fixed. I will check if this is done in baresip core, or `menu`.

**Comment by juha-h** [comment]
Christian Spielberger writes:

> Right! But I suggest to find and solve the problem and not revert
> anything.

Yes, solving the issue is of course best.

**Comment by cspiel1** [comment]
The decision was that in order keep previous behavior for all applications of baresip  this piece of code was added into the baresip core `call.c`:
```c
	if (call_need_modify(call)) {
		call_set_media_direction(call, call->ansadir, call->ansvdir);
		call_modify(call);
	}
```
I think that for an outgoing call the `ansadir` and `ansvdir` simply is `SDP_SENDRECV` in `call_alloc()`. So the correct initialization seems to be missing.

@juha-h: You wrote that you use `call_set_media_direction()`. This function directly manipulates the SDP and I suggest to remove it from the API, so move it from `baresip.h` to `core.h`. Instead `call_set_media_ansdir()` can be used. Or even better for an audio-only call: `ua_connect_dir(ua, callp, VIDMODE_ON, SDP_SENDRECV, SDP_INACTIVE)` and nothing more. 

Reason: The baresip core should guarantee an RFC conform behavior. And the function `call_set_media_ansdir()` called from outside allows manipulation of SDP when it should not change.

@juha-h Is it possible for you to use `ua_connect_dir()`? It should do everything for the Android APP for an outgoing call.

**Comment by juha-h** [comment]
Thanks for the help.  I'm currently on the road, but will try your
suggestions later today.

**Comment by juha-h** [comment]
I studied my code and I need to allocate call object using `ua_call_alloc()` before making the call.  If I understood correctly, you are suggesting that after that I call function `call_set_media_ansdir()` followed by `call_connect()`.  Comment of `call_set_media_ansdir()` tells `Set stream sdp media line direction attribute for call answer`.  What has that to do with making of call?  Should there be `call_set_media_calldir()` instead?

**Comment by juha-h** [comment]
I tested and this call sequence works (vdir = Api.SDP_INACTIVE or Api.SDP_SENDRECV):
```
Api.ua_call_alloc(ua.uap, 0L, Api.VIDMODE_ON)
Api.call_set_media_ansdir(callp, Api.SDP_SENDRECV, vdir)
Api.call_connect(callp, uri)
```
And this answer sequence works (vdir = Api.SDP_RECVONLY_ or Api.SDP_SENDRECV):
```
Api.call_set_media_ansdir(callp, Api.SDP_SENDRECV, vdir)
Api.ua_answer(uap, callp, Api.VIDMODE_ON)
```
The only thing left is confusing name of `call_set_media_ansdir` function when used in placing of call.

**Comment by juha-h** [comment]
Well, now when I checked SIP trace, I found that initial INVITE contains video media in SDP when I made these API calls:
```
Api.ua_call_alloc(ua.uap, 0L, Api.VIDMODE_ON)
Api.call_set_media_ansdir(callp, Api.SDP_SENDRECV, Api.SDP_INACTIVE)
Api.call_connect(callp, uri)
```
There should only be audio media in SDP.

**Comment by juha-h** [comment]
With `call.setMediaDirection(Api.SDP_SENDRECV, API.SDP_INACTIVE)` initial INVITE only had audio media, but there was the issue with re-INVITE as described originally in this issue.  So looks like `call_set_media_ansdir` has (as name indicates) nothing to do with sending the initial INVITE.

**Comment by juha-h** [comment]
API function `ua_connect_dir` has this code after `ua_call_alloc`:
```
if (adir != SDP_SENDRECV || vdir != SDP_SENDRECV) {
		err  = call_set_media_ansdir(call, adir, vdir);
		err |= call_set_media_direction(call, adir, vdir);
		if (err) {
			mem_deref(call);
			goto out;
		}
	}
```
As I explained, I need to call `ua_call_alloc` in order to get callp before calling `call_connect`.  Thus I cannot use  `ua_connect_dir`  and  need access to `call_set_media_direction` or some other function that has the same effect.

**Comment by juha-h** [comment]
After using both direction calls:
```
Api.ua_call_alloc(ua.uap, 0L, Api.VIDMODE_ON)
Api.call_set_media_ansdir(callp, Api.SDP_SENDRECV, Api.SDP_INACTIVE)
Api.call_set_media_mediadirection(callp, Api.SDP_SENDRECV, Api.SDP_INACTIVE)
Api.call_connect(callp, uri)
```
initial INVITE only contains audio media and there no re-INVITE is sent after 200 OK.

So this could be the solution to the issue, but not a pretty one.  One direction call should be enough like it used to be.

**Comment by juha-h** [comment]
Needing to call `call_set_media_ansdir` when placing a call in order to avoid re-INVITE after 200 OK makes no sense to me.  There must be a bug somewhere as you mentioned about missing initialization.

**Comment by cspiel1** [comment]
Thanks for your analysis! I'll try to make it less confusing. A PR will follow.

**Comment by cspiel1** [comment]
With the PR #2046 your code needs no change:
```c
Api.ua_call_alloc(ua.uap, 0L, Api.VIDMODE_ON)
Api.call_set_media_direction(callp, Api.SDP_SENDRECV, Api.SDP_INACTIVE)
Api.call_connect(callp, uri)
```

**Comment by juha-h** [comment]
Thank you very much.  I tested both calling and answering and both worked with these API calls:
```
Call (vdir = Api.SDP_INACTIVE or Api.SDP_SENDRECV):

Api.ua_call_alloc(ua.uap, 0L, Api.VIDMODE_ON)
Api.call_set_media_direction(callp, Api.SDP_SENDRECV, vdir)
Api.call_connect(callp, uri)

Answer (vdir = Api.SDP_RECVONLY or Api.SDP_SENDRECV):

Api.call_set_media_direction(callp, Api.SDP_SENDRECV, vdir)
Api.ua_answer(uap, callp, Api.VIDMODE_ON)
```

**Comment by juha-h** [comment]
Solved by https://github.com/baresip/baresip/pull/2046.
