### ISSUE TITLE
stdio: could not setup terminal: Inappropriate ioctl for device

### ISSUE THREAD

**Issue by cricalix** [baresip/baresip#2044]
Context
--
I'm attempting to drive baresip via stdio. More specifically, from Python using the sarge module (https://github.com/vsajip/sarge).

I've noticed in the output from starting baresip the line `stdio: could not setup terminal: Inappropriate ioctl for device`

I've also noticed that the commands and immediate response of the commands are being printed to the terminal, not to the stdout capture that `sarge` is providing. Thus my Python code output has baresip output interleaved through it.

I can reproduce this with a simple `echo /quit | baresip`. The program starts, gets to a ready state, processes the /quit, and exits. As it starts up, it also prints the `Inappropriate ioctl` line.

Version: baresip v1.0.0 Copyright (C) 2010 - 2020 Alfred E. Heggestad et al.
This is the Ubuntu jammy package.

**Comment by cricalix** [comment]
Simple reproduction:
```python
from sarge import Command, Capture, Feeder

f = Feeder()
p = Command("baresip", stdout=Capture(buffer_size=1))
p.run(input=f, async_=True)
output = p.stdout.readlines()
# print(output)
if b"baresip is ready.\n" in output:
    print("baresip up")
f.feed(b"/quit\n")
f.close()
p.wait()
```
The expected output of this script is `baresip up`.
The actual output is 
```
baresip up
/quit
Quit
```

**Comment by cricalix** [comment]
An even simpler reproduction:
```
echo "/quit" | baresip >/dev/null
/quit
Quit
```

**Comment by alfredh** [comment]
Could you please try to upgrade to v2.6.0 or latest GIT HEAD ?

**Comment by alfredh** [comment]
closing due to lack of response. Please use Discussions instead.
