### ISSUE TITLE
SDP sample rate for telephone-event is incorrect when audio codec rate is not 8000

### ISSUE THREAD

**Issue by weili-jiang** [baresip/baresip#2062]
When a codec such as OPUS (sample rate 48000) is used, the sample rate sent in the SDP for telephone-event is still 8000 - this is wrong. It needs to match that of the associated audio codec: https://www.rfc-editor.org/rfc/rfc4733#section-2.1

> The default clock frequency is 8000 Hz, but the clock frequency can be redefined when assigning the dynamic payload type.
> 
> Named telephone events are carried as part of the audio stream and MUST use the same sequence number and timestamp base as the > regular audio channel to simplify the generation of audio waveforms at a gateway.

It's a bit peculiar because the actual time base being used by Baresip when sending DTMF is that of the audio codec - so the time base doesn't match that of the SDP. This causes incorrect DTMF durations and other glitches depending on how the receiver copes with the mismatch, see https://github.com/signalwire/freeswitch/issues/1724 (the User Agent in question was a modified Baresip).

I think `add_telev_codec` should probably send `a->tx->ac->crate` instead of the hardcoded `TELEV_SRATE`.

**Comment by alfredh** [comment]
thanks for the report

would you like to create a PR for this ?

**Comment by weili-jiang** [comment]
Okay, I will give `a->tx->ac->crate` - if it fixes the issue, I will submit a PR.

**Comment by weili-jiang** [comment]
This is a lot more complicated than I first thought - at the point of SDP generation, we do not have a specific audio codec to reference.

The issue is that in the initial SDP there are multiple multiple audio codecs being offered - this means multiple telephone-event codecs would also need to be offered, one for each audio codec, each with a distinct dynamic PT. Only when SDP is complete can the telev implementation be configured with the correct PT to use.

Another SIP client also had this problem and fix it in this manner: https://github.com/pjsip/pjproject/issues/2088

**Comment by alfredh** [comment]
Please have a look at this RFC:

https://www.rfc-editor.org/rfc/rfc7160.html


Another audio codec that has a difference between clock-rate, is G722.
The SDP says g722/8000 but the actual clockrate for audio samples is 16000Hz.

I think we are free to send DTMF events with the clock-rate we want.
This could be default 8000 Hz but we could also use the same as the current encoder.

The samplerate for Telev object can be set:

```c
int telev_set_srate(struct telev *tel, uint32_t srate);
```

**Comment by weili-jiang** [comment]
Looks like in the early days of WebRTC Mozilla also had this issue, and just like pjsip, this was resolved by offering multiple telephone-event `a=rtpmap` lines, one for each audio codec: https://bugzilla.mozilla.org/show_bug.cgi?id=785834. I found an earlier discussion (that you were part of) regarding this problem in the WebRTC context: https://groups.google.com/g/discuss-webrtc/c/LntxAkr2H_U, where the same thing is discussed.

I'm not too sure about g722, as it is an odd ball case due to a historical mistake, see https://www.rfc-editor.org/rfc/rfc3551#section-4.5.2:

> Even though the actual sampling rate for G.722 audio is 16,000 Hz, the RTP clock rate for the G722 payload format is 8,000 Hz because that value was erroneously assigned in [RFC 1890](https://www.rfc-editor.org/rfc/rfc1890) and must remain unchanged for backward compatibility. The octet rate or sample-pair rate is 8,000 Hz.

As for Baresip:

`telev_set_srate` is already being called to match the current encoder [here](https://github.com/baresip/baresip/blob/efcc907613fefce9c8f6befc5dcc749145a291d1/src/audio.c#L1771), once codec negotiation is complete.

So the actual telev rate is correct - it's just the SDP that's wrong.

The challenge with the SDP that we have to offer multiple telephone-event `a=rtpmap` lines, one for each audio codec offered. I see there's some attempt to use PT=101 with telephone-event for some [Cisco compatibility thing](https://github.com/baresip/baresip/blob/efcc907613fefce9c8f6befc5dcc749145a291d1/src/audio.c#L985) - this would not be possible with multiple a lines since each needs a different PT, say PT=101 for 8000, PT=102 for 16000, PT=103 for 48000.

Do you think this adding this multiplicity of telephone-events in the SDP would warrant a new configuration item? If so, should this be at the config or account level?

**Comment by juha-h** [comment]
I don't know if this is relevant, but just noticed that Linphone advertises two telephone event codes with different sample rates:
```
v=0
o=lin 2002 2387 IN IP4 192.168.238.225
s=Talk
c=IN IP4 192.168.238.225
t=0 0
a=rtcp-xr:rcvr-rtt=all:10000 stat-summary=loss,dup,jitt,TTL voip-metrics
m=audio 7078 RTP/AVP 96 8 97 101
a=rtpmap:96 opus/48000/2
a=fmtp:96 useinbandfec=1
a=rtpmap:97 telephone-event/48000
a=rtpmap:101 telephone-event/8000
a=rtcp-fb:* trr-int 1000
a=rtcp-fb:* ccm tmmbr
```

**Comment by alfredh** [comment]
here is a proposal for how to implement this:

1. Create a list of all sampling rates used for all codecs.
2. For each sampling rate in that list, add the telephone-event/XXX subtype
3. When session established, check which audio codec is used
4. Take the sampling rate of that codec
5. look up telephone-event/XXX to find the payload type

For outgoing events use the same clockrate as the encoder.
For incoming events look at the pt to find the clockrate.

For sending the SDP answer, you should only send a subset of telephone-event lines,
i.e. a union of what you receive and what you support.

**Comment by alfredh** [comment]
I have added this to the roadmap:

https://github.com/baresip/baresip/wiki/Roadmap

I regard this as a new feature, and I am not sure how long time it will
take to implement and test.

**Comment by alfredh** [comment]
I will close this one now, lets track the new feature in the Roadmap.

if you want to make an attempt to implement it, please create a PR for the work.
