### ISSUE TITLE
baresip doesnt automatically reconnect upon resume

### ISSUE THREAD

**Issue by landryb** [baresip/baresip#2065]
using 2.6.0 on OpenBSD, baresip works like a charm - only minor annoyance, if i suspend/resume the network temporarly goes down/up and then baresip fails to automatically reregister to my SIP provider, and timeouts forever at every retry.
```
302@xxx: selected for 302-0x933c3b12e90
302@xxx: selected for 302-0x933c3b12e90
302@xxx: selected for 302-0x933c3b12e90
# here is the suspend/resume
reg: sip:302@xxx (prio 0): Register: Network is down [50]
reg: sip:302@xxx (prio 0): Register: Operation timed out [60]
reg: sip:302@xxx (prio 0): Register: Operation timed out [60]
reg: sip:302@xxx (prio 0): Register: Operation timed out [60]
```
at that point, if i exit baresip and start it again it registers immediately.

what would be needed to properly debug that and make it work ?

**edit**: ofc, will run with `-sv` from now to get more debug info.

**Comment by sreimers** [comment]
How does `/netstat` look like? Is the `netroam` module loaded? Can you try a manual `/netchange` trigger after suspend/resume?

**Comment by landryb** [comment]
> How does `/netstat` look like? Is the `netroam` module loaded? Can you try a manual `/netchange` trigger after suspend/resume?

the netroam module wasn't built on OpenBSD since i wrongly assumed it relied on linux-only netlink. Will recheck/retry once i've built & enabled it.

**Comment by alfredh** [comment]
the sipreg module should be able to handle glitches and re-try registering

**Comment by landryb** [comment]
with netroam installed and enabled, i can no longer reproduce the initial failure doing a suspend, waiting 5mn (so that the SIP server drops the cnx from its side) and resuming.

in the debug output i see this:
```
Network changed:                                                                                          
        lo0:  fe80:4::1                                                                                                                                                                                              
       iwm0:  192.168.182.25                                                                              
        lo1:  10.0.5.138                                                                                  
uag: add local address fe80:4::1                                                                          
uag: add local address 192.168.182.25                                                                                                                                                                                
uag: add local address 10.0.5.138            
ua: ua_register sip:302@xxx      
```

so afaict `netroam` is doing its job, because even if the IPs didnt change baresip detects that something happened and re-registers to the sip server.

without netroam in the config, upon resume nothing happens on baresip (even with `-sv`) side. sipreg doesnt try to re-register, doesnt detect that the cnx is down... puzzling.

**Comment by landryb** [comment]
my understanding (without netroam configured) is that since the remote SIP server lost the cnx, so  it doesnt resend the casual OPTIONS msg every 60s, and baresip sits here idling, still thinking it has a connection to the server ? anyway, will keep running with netroam enabled now :)

**Comment by cspiel1** [comment]
Yes, if you want to handle network changes you have to use netroam.
serreg is only for multiple SIP server configurations:
- serial mode: register only to main SIP server and switch to fallback server if the main server is not reachable
- Cisco mode: same like serial mode, but also polls the fallback servers with "un-REGISTER" requests.

Can we close this?

**Comment by landryb** [comment]
yes, been using netroam on two different OpenBSD laptops over long resume sessions, and each time baresip properly reconnected to the SIP server. Thanks for giving us baresip !

**Comment by alfredh** [comment]
hi @landryb 

Could you please try to build on OpenBSD with CMake ?

We are migrating from GNU make to CMake.

Are you using this module on OpenBSD?
https://github.com/baresip/baresip/tree/main/modules/sndio

**Comment by landryb** [comment]
> hi @landryb
> 
> Could you please try to build on OpenBSD with CMake ?
> 
> We are migrating from GNU make to CMake.

Yes, i've seen that and i was planning to look at it soonish (probably once all modules were migrated), i know we ship the gtk module which wasn't ported to CMake yet last i looked.

> Are you using this module on OpenBSD? https://github.com/baresip/baresip/tree/main/modules/sndio

yes of course ! all the sound baresip uses/produces goes through sndio via this module.
