### ISSUE TITLE
DTMF via MiniSipServer does not work

### ISSUE THREAD

**Issue by basdl** [baresip/baresip#2075]
When I use MiniSipServer as SIP Proxy and send DTMF via SIPINFO to baresip, baresip responds with bad request. When I use direct call, the DTMF gets processed correctly. Looking at the attached sip traces, it seems like baresip cannot cope with some sort of trailing whitespaces.
[info-failed.txt](https://github.com/baresip/baresip/files/9372869/info-failed.txt)
[info-working.txt](https://github.com/baresip/baresip/files/9372870/info-working.txt)

The baresip version used is 2.6.0 and compiled for arm.

**Comment by alfredh** [comment]
can you please try to insert some debug printfs here and see why it is failing:

```c
        if (msg_ctype_cmp(&msg->ctyp, "application", "dtmf-relay")) {

                struct pl body, sig, dur;
                int err;

                pl_set_mbuf(&body, msg->mb);

                err  = re_regex(body.p, body.l,
                       "Signal=[ ]*[0-9*#a-d]+", NULL, &sig);
                err |= re_regex(body.p, body.l,
                       "Duration=[ ]*[0-9]+", NULL, &dur);

                if (err || !pl_isset(&sig) || sig.l == 0) {
                        (void)sip_reply(sip, msg, 400, "Bad Request");
                }
```

**Comment by alfredh** [comment]
closing due to lack of response... Please provide the needed info for bug reports.
