### ISSUE TITLE
dynamic_menu: Wait for hold acknowledgement before initiating transfer

### ISSUE THREAD

**Issue by maximilianfridrich** [baresip/baresip#2083]
When triggering a call transfer from the dynamic menu (`t` or `/transfer`) during a call, the call is first set on hold and immediately after the REFER is sent to the transferee. Some SIP clients (Linphone for example) can't handle those two requests back to back and respond to the REFER with 491 Request pending.

RFC 5589 ([section 6.1](https://www.rfc-editor.org/rfc/rfc5589.html#section-6.1)) describes the best practice is waiting for the hold to be confirmed and then sending the REFER. Since other SIP clients expect this, this is definitely what BareSIP should be doing.

**Comment by alfredh** [comment]
is this a bug or a new feature ?

**Comment by maximilianfridrich** [comment]
In some sense it's a bug. However, it looks like it hasn't come up in live systems, it was something I discovered while playing around with REFERs. So it's quite minor I'd say.

**Comment by alfredh** [comment]
thanks, it looks like a small improvement. I have added it to Roadmap:

https://github.com/baresip/baresip/wiki/Roadmap

you are welcome to create a PR for it
