### ISSUE TITLE
Debian libre-dev package has wrong prefix value in /usr/lib/pkgconfig/libre.pc file

### ISSUE THREAD

**Issue by juha-h** [baresip/baresip#2103]
When on Debian 11 I give in baresip source dir commands
```
rm -rf build; mkdir build; cd build; cmake ..
```
I get error message
```
CMake Error at /usr/share/cmake-3.24/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find RE (missing: RE_INCLUDE_DIR)
```
I do have libre-dev package installed and /usr/include/re does exist.  Why doesn't cmake find it from there?

**Comment by sreimers** [comment]
FindRE.cmake uses pkg-config, can you check:

`pkg-config --cflags libre`

**Comment by juha-h** [comment]
Sebastian Reimers writes:

> FindRE.cmake uses pkg-config, can you check:
> 
> `pkg-config --cflags libre`

How come I get wrong dir?

$ pkg-config --cflags libre
-I/usr/local/include/re

I just build and reinstalled latest libre-dev package and I don't have any other
libre-dev packages installed:

$ dpkg -L libre-dev
/.
/usr
/usr/include
/usr/include/re
/usr/include/re/re.h
/usr/include/re/re_aes.h
/usr/include/re/re_async.h
/usr/include/re/re_atomic.h
/usr/include/re/re_av1.h
/usr/include/re/re_base64.h
/usr/include/re/re_bfcp.h
/usr/include/re/re_bitv.h
/usr/include/re/re_btrace.h
/usr/include/re/re_conf.h
/usr/include/re/re_convert.h
/usr/include/re/re_crc32.h
/usr/include/re/re_dbg.h
/usr/include/re/re_dns.h
/usr/include/re/re_fmt.h
/usr/include/re/re_h264.h
/usr/include/re/re_h265.h
/usr/include/re/re_hash.h
/usr/include/re/re_hmac.h
/usr/include/re/re_http.h
/usr/include/re/re_httpauth.h
/usr/include/re/re_ice.h
/usr/include/re/re_jbuf.h
/usr/include/re/re_json.h
/usr/include/re/re_list.h
/usr/include/re/re_main.h
/usr/include/re/re_mbuf.h
/usr/include/re/re_md5.h
/usr/include/re/re_mem.h
/usr/include/re/re_mod.h
/usr/include/re/re_mqueue.h
/usr/include/re/re_msg.h
/usr/include/re/re_net.h
/usr/include/re/re_odict.h
/usr/include/re/re_pcp.h
/usr/include/re/re_rtmp.h
/usr/include/re/re_rtp.h
/usr/include/re/re_sa.h
/usr/include/re/re_sdp.h
/usr/include/re/re_sha.h
/usr/include/re/re_shim.h
/usr/include/re/re_sip.h
/usr/include/re/re_sipevent.h
/usr/include/re/re_sipreg.h
/usr/include/re/re_sipsess.h
/usr/include/re/re_srtp.h
/usr/include/re/re_stun.h
/usr/include/re/re_sys.h
/usr/include/re/re_tcp.h
/usr/include/re/re_telev.h
/usr/include/re/re_thread.h
/usr/include/re/re_tls.h
/usr/include/re/re_tmr.h
/usr/include/re/re_trace.h
/usr/include/re/re_trice.h
/usr/include/re/re_turn.h
/usr/include/re/re_types.h
/usr/include/re/re_udp.h
/usr/include/re/re_uri.h
/usr/include/re/re_websock.h
/usr/lib
/usr/lib/libre.a
/usr/lib/pkgconfig
/usr/lib/pkgconfig/libre.pc
/usr/share
/usr/share/doc
/usr/share/doc/libre-dev
/usr/share/doc/libre-dev/changelog.gz
/usr/share/doc/libre-dev/copyright
/usr/share/re
/usr/share/re/re.mk

File /usr/lib/pkgconfig/libre.pc has been generated with wrong content:

$ more /usr/lib/pkgconfig/libre.pc
prefix=/usr/local
exec_prefix=${prefix}
libdir=/usr/local/lib
includedir=${prefix}/include/re

Name: libre
Description: Generic library for real-time communications with async IO support
Version: 2.6.1
URL: https://github.com/baresip/re
Libs: -L${libdir} -lre
Libs.private: -L${libdir} -lre -ldl -lssl -lcrypto -lz -lpthread
Cflags: -I${includedir}

How to get that fixed?

**Comment by juha-h** [comment]
Could this be the explanation?
```
/usr/src/orig/re$ more packaging/libre.pc.in
prefix="@CMAKE_INSTALL_PREFIX@"
exec_prefix=${prefix}
libdir={$prefix}/lib
includedir=${prefix}/include/re
```
The file was added 4 days ago.

**Comment by juha-h** [comment]
No, libre.pc has `prefix=/usr/local` even when I hardcoded `prefix=/usr` in `packaging/libre.pc.in`.

**Comment by sreimers** [comment]
`packaging/libre.pc.in` is used by cmake only. the old libre.pc is created by `Makefile` and you can override with `PREFIX=/usr`.

But if you want to use cmake, you have to build libre also with cmake since `re-config.cmake` is required now. We should add a CPack DEB Generator config and remove the old debian directory.

**Comment by juha-h** [comment]
OK, but then should `PREFIX=/usr` be somehow added to `debian/rules`, since Debian build installs include files and libs with /usr prefix, not with /usr/local prefix.  Now there is conflict between libre.pc prefix and where the files are installed.  I'll edit tittle of the issue.

**Comment by juha-h** [comment]
Fixed by https://github.com/baresip/re/pull/501.
