### ISSUE TITLE
new compiler warnings on Debian 11

### ISSUE THREAD

**Issue by juha-h** [baresip/baresip#2118]
CC [M]  build-x86_64/modules/httpreq/httpreq.o
modules/httpreq/httpreq.c: In function ‘cmd_setbody’:
modules/httpreq/httpreq.c:278:39: warning: passing argument 2 of ‘http_reqconn_set_body’ from incompatible pointer type [-Wincompatible-pointer-types]
  278 |  err = http_reqconn_set_body(d->conn, mb);
      |                                       ^~
      |                                       |
      |                                       struct mbuf *
In file included from ../re/include/re.h:34,
                 from modules/httpreq/httpreq.c:9:
../re/include/re_http.h:229:71: note: expected ‘const struct pl *’ but argument is of type ‘struct mbuf *’
  229 | ttp_reqconn_set_body(struct http_reqconn *conn, const struct pl *body);
      |                                                 ~~~~~~~~~~~~~~~~~^~~~

**Comment by sreimers** [comment]
Looks like your libre is outdated.

**Comment by juha-h** [comment]
Yes that was it.  So dependencies are not upgraded during development?

**Comment by cspiel1** [comment]
We didn't increment the `ABI_MAJOR`. Maybe this would help in such a case.

**Comment by juha-h** [comment]
Christian Spielberger writes:

> We didn't increment the `ABI_MAJOR`. Maybe this would help in such a
> case.

It would ne nice if something would be incremented when there is such a
change in re or rem API that makes baresip build with older versions
fail.  Debian control file can be used to detect of dev libs are too old
for the build.
