### ISSUE TITLE
Dial to a domain without "@" is not possible through `menu`

### ISSUE THREAD

**Issue by cspiel1** [baresip/baresip#2150]
Suppose that `office` is a domain in the local network. It should be possible to initiate an outgoing call to domain `office`.

Current behavior:
Dialing e.g. `office` through module `menu` is not possible, because the host part of the selected account will be appended. The DNS resolution fails.

e.g. configured account:
```
<sip:alice@localhost>;regint=0
```

```
>                           office
A@localhost: selected for request
call uri: sip:office@localhost
```

**Comment by cspiel1** [comment]
We should remove the whole append host part code. This would simplify the behavior and code by 39 lines in account.
The APP should append the host part. It can't be decided much more flexible in the APP.

E.g. the decision could be passed to the user which account should be used for the outgoing call.

**Comment by cspiel1** [comment]
The `account_uri_complete()` then would be dropped, and the prepending of "sip:" could be done in `ua_connect_dir()` in ua.c.

**Comment by alfredh** [comment]
is "office" an endpoint or a domain ?

Can you prepend a dummy userpart to it:

```
sip:foo@office ?
```


Perhaps consider this; if "office" can be resolved via SIP DNS mechanism,
and it returns value entry, we should consider it as a "complete" uri.

**Comment by cspiel1** [comment]
` sip:office` is a complete URI. The domain can be resolved by DNS resolution. In a subnet setup with specific DNS configuration.

Pre-pending a dummy user is our work-around. And the appending of the hostname was also our "failure" in the past. It lead to so many problems and ugly code. Sorry for that! But now we want to get rid of it.

**Comment by alfredh** [comment]
How about using this instead:

```
sip:office@company.com
```

sip:office is not a globally routable AOR/URI ?

**Comment by cspiel1** [comment]
`office` is the user part in this SIP URI. `company.com` is the domain.

In my example `office` is the domain. No user is given.

From https://www.rfc-editor.org/rfc/rfc3261#section-25:
```
SIP-URI          =  "sip:" [ userinfo ] hostport
```

The user part is optional.

**Comment by juha-h** [comment]
I sent similar comment as email, but looks it never arrived:
```
Date: Fri, 30 Sep 2022 10:15:07 +0300
To: baresip/baresip <reply+ABP3HREKF356CJI5F4MTWSGBIPEDXEVBNHHFFGGDJY@reply.github.com>
Cc: baresip/baresip <baresip@noreply.github.com>,
    Subscribed <subscribed@noreply.github.com>
Subject: Re: [baresip/baresip] Dial to a domain without "@" is not possible
 through `menu` (Issue #2150)
In-Reply-To: <baresip/baresip/issues/2150/1263190569@github.com>
References: <baresip/baresip/issues/2150@github.com>
	<baresip/baresip/issues/2150/1263190569@github.com>
X-Mailer: VM 8.2.0b under 27.1 (x86_64-pc-linux-gnu)
From: Juha Heinanen <jh@tutpro.com>
--text follows this line--
Alfred E. Heggestad writes:

> How about using this instead:
> 
> ```
> sip:office@company.com
> ```
> 
> sip:office is not a globally routable AOR/URI ?

I think that sip:office would be a valid URI if office is found in
/etc/hosts.
```

**Comment by cspiel1** [comment]
Yes, I did similar tests with `/etc/hosts`. Our testers use a local DNS server.

**Comment by alfredh** [comment]
one more input:

The "append domain" logic should not be done in baresip core (ua.c),
the core should be kept as slim as straightforward as possible.

The logic should be implemented in the application,
i.e. menu module and/or user of libbaresip.

**Comment by cspiel1** [comment]
Done: https://github.com/baresip/baresip/pull/2163#issuecomment-1265074801

**Comment by juha-h** [comment]
Alfred E. Heggestad writes:

> How about using this instead:
> 
> ```
> ***@***.***
> ```
> 
> sip:office is not a globally routable AOR/URI ?

I think that sip:office would be a valid URI if office is found in
/etc/hosts.

**Comment by alfredh** [comment]
yes, I think that sounds like a good solution.

@cspiel1 would that work for you ?


in the past I was working for a Telecom company deploying SIP devices,
and it was practical to dial the number:

```
> 22001100
```

instead of

```
> 22001100@telecom-provider.no
```

**Comment by juha-h** [comment]
Yes, dial string 22001100 would be completed to R-URI.  In my Android app, there is account parameter `;tel_provider` having domain name or ip address as value.  If user dials 22001100 and ;tel_provider has been set, then its value will be used as hostpart of the resulting R-URI.

**Comment by juha-h** [comment]
> > e.g. use DNS query and check from /etc/hosts
> 
> btw. should we maybe enable https://github.com/baresip/baresip/wiki/Configuration#dns_getaddrinfo by default now? I was a bit worried about it, since it could be surprising that `/etc/hosts` is now used. On the other hand it could be surprising that its not used by default ;-)

I would like to keep the default as is, since I'm afraid that something would break in Android (which does not have /etc/hosts).

**Comment by cspiel1** [comment]
```
sip:office  -> sip prefix, no uri completion needed
jh          -> no sip prefix, use uri completion
```
Yes, this would work for us. No config setting would be needed. --> I will split up the PR.


> > e.g. use DNS query and check from /etc/hosts
> 
> btw. should we maybe enable https://github.com/baresip/baresip/wiki/Configuration#dns_getaddrinfo by default now? I was a bit worried about it, since it could be surprising that `/etc/hosts` is now used. On the other hand it could be surprising that its not used by default ;-)

I would prefer, if there is an `/etc/hosts` then it should be used. It could be tested if something breaks in Android.

**Comment by juha-h** [comment]
I checked from Android docs and use of getaddrinfo is OK and recommended.  I'm not sure if the call is blocking or asynchronous. I have set `dns_getaddrinfo yes` on two devices and have not noticed problems.

Android devices have file `/system/etc/hosts`, but it is not writable if the device is not rooted.  On my device its contents is
```
127.0.0.1       localhost
::1             ip6-localhost
```

**Comment by juha-h** [comment]
@sreimers Is it so that if `dns_getaddrinfo yes`, then `net_use_nameserver` API function does not have any effect, since DNS queries are done by the OS using whatever DNS servers have been configured in it (for example in /etc/resolv.conf)?

**Comment by sreimers** [comment]
Yes, but only for `A` and `AAAA` records, other records (like `SRV`) are resolved by `net_use_nameserver`.

**Comment by juha-h** [comment]
In that case, I don't see much point having `dns_getaddrinfo yes`.  Unless outbound proxies are used, NATRP/SRV queries need to be made anyway and using two different sets of dns servers for a single domain name resolution does not sound like a good idea.

**Comment by cspiel1** [comment]
Solved by prepending of `sip:`.
