### ISSUE TITLE
Baresip-2.7.0 Windows build issues

### ISSUE THREAD

**Issue by venkat1152000** [baresip/baresip#2155]
Hi,
I have downloaded re, rem and Baresip version 2.7.0 on Windows machine which has Microsoft Visual Studio Professional 2022 version 17.3.4 
I am able to compile re and rem libraries successfully.
Then i tried to configure the Baresip. Baresip found re and rem libraries.
This is the output of the Baresip cmake configure.

CMake generation started for default configuration: 'x64-Debug'.
1> Command line: "C:\Windows\system32\cmd.exe" /c "%SYSTEMROOT%\System32\chcp.com 65001 >NUL && "C:\PROGRAM FILES\MICROSOFT VISUAL STUDIO\2022\PROFESSIONAL\COMMON7\IDE\COMMONEXTENSIONS\Microsoft\CMake\CMake\bin\cmake.exe"  -G "Ninja"  -DCMAKE_BUILD_TYPE:STRING="Debug" -DCMAKE_INSTALL_PREFIX:PATH="D:\test\baresip\out\install\x64-Debug" -DCMAKE_C_COMPILER:FILEPATH="C:/Program Files/Microsoft Visual Studio/2022/Professional/VC/Tools/MSVC/14.33.31629/bin/Hostx64/x64/cl.exe" -DCMAKE_CXX_COMPILER:FILEPATH="C:/Program Files/Microsoft Visual Studio/2022/Professional/VC/Tools/MSVC/14.33.31629/bin/Hostx64/x64/cl.exe"  -DCMAKE_MAKE_PROGRAM="C:\PROGRAM FILES\MICROSOFT VISUAL STUDIO\2022\PROFESSIONAL\COMMON7\IDE\COMMONEXTENSIONS\Microsoft\CMake\Ninja\ninja.exe" "D:\test\baresip" 2>&1"
1> Working directory: D:\test\baresip\out\build\x64-Debug
1> [CMake] -- The C compiler identification is MSVC 19.33.31630.0
1> [CMake] -- The CXX compiler identification is MSVC 19.33.31630.0
1> [CMake] -- Detecting C compiler ABI info
1> [CMake] -- Detecting C compiler ABI info - done
1> [CMake] -- Check for working C compiler: C:/Program Files/Microsoft Visual Studio/2022/Professional/VC/Tools/MSVC/14.33.31629/bin/Hostx64/x64/cl.exe - skipped
1> [CMake] -- Detecting C compile features
1> [CMake] -- Detecting C compile features - done
1> [CMake] -- Detecting CXX compiler ABI info
1> [CMake] -- Detecting CXX compiler ABI info - done
1> [CMake] -- Check for working CXX compiler: C:/Program Files/Microsoft Visual Studio/2022/Professional/VC/Tools/MSVC/14.33.31629/bin/Hostx64/x64/cl.exe - skipped
1> [CMake] -- Detecting CXX compile features
1> [CMake] -- Detecting CXX compile features - done
1> [CMake] -- Found RE: D:/test/re/build/re-static.lib  
1> [CMake] -- Found REM: D:/test/rem/out/build/x64-Debug/rem.lib  
1> [CMake] -- Looking for backtrace
1> [CMake] -- Looking for backtrace - not found
1> [CMake] -- Could NOT find Backtrace (missing: Backtrace_LIBRARY Backtrace_INCLUDE_DIR) 
1> [CMake] -- Looking for pthread.h
1> [CMake] -- Looking for pthread.h - not found
1> [CMake] -- Found Threads: TRUE  
1> [CMake] -- Could NOT find ZLIB (missing: ZLIB_LIBRARY ZLIB_INCLUDE_DIR) 
1> [CMake] -- Found OpenSSL: D:/test/OpenSSL/lib/libcrypto.lib (found version "3.0.5")  
1> [CMake] -- Looking for arc4random
1> [CMake] -- Looking for arc4random - not found
1> [CMake] -- Looking for syslog.h
1> [CMake] -- Looking for syslog.h - not found
1> [CMake] -- Looking for getopt.h
1> [CMake] -- Looking for getopt.h - not found
1> [CMake] -- Looking for unistd.h
1> [CMake] -- Looking for unistd.h - not found
1> [CMake] -- Looking for thrd_create
1> [CMake] -- Looking for thrd_create - not found
1> [CMake] -- Checking for one of the modules 'fdk-aac'
1> [CMake] -- Could NOT find AAC (missing: AAC_LIBRARY AAC_INCLUDE_DIR) 
1> [CMake] -- Could NOT find ALSA (missing: ALSA_LIBRARY ALSA_INCLUDE_DIR) 
1> [CMake] NB_INCLUDE_DIRNB_INCLUDE_DIR-NOTFOUND
1> [CMake] WB_ENC_INCLUDE_DIRWB_ENC_INCLUDE_DIR-NOTFOUND
1> [CMake] WB_DEC_INCLUDE_DIRWB_DEC_INCLUDE_DIR-NOTFOUND
1> [CMake] NB_LIBRARYNB_LIBRARY-NOTFOUND
1> [CMake] WB_LIBRARYWB_LIBRARY-NOTFOUND
1> [CMake] WB_VO_ENC_LIBRARYWB_VO_ENC_LIBRARY-NOTFOUND
1> [CMake] -- Could NOT find AMR (missing: AMR_FOUND) 
1> [CMake] -- Could NOT find APTX (missing: APTX_LIBRARY APTX_INCLUDE_DIR) 
1> [CMake] -- Could NOT find AOM (missing: AOM_LIBRARY AOM_INCLUDE_DIR) 
1> [CMake] -- Could NOT find CODEC2 (missing: CODEC2_LIBRARY CODEC2_INCLUDE_DIR) 
1> [CMake] -- Found PkgConfig: C:/ProgramData/chocolatey/bin/pkg-config.exe (found version "0.28") 
1> [CMake] -- Could NOT find DIRECTFB (missing: DIRECTFB_LIBRARIES DIRECTFB_INCLUDE_DIR) 
1> [CMake] -- Could NOT find FFMPEG (missing: FFMPEG_AVUTIL_LIBRARIES FFMPEG_AVUTIL_INCLUDE_DIRS avutil avcodec avfilter avformat swscale swresample avdevice) 
1> [CMake] -- Checking for module 'gio-unix-2.0'
1> [CMake] --   No package 'gio-unix-2.0' found
1> [CMake] -- Could NOT find GIO (missing: GLIB_LIBRARY GIO_LIBRARY GOBJ_LIBRARY GIO_INCLUDE_DIR GLIB_INCLUDE_DIR GIO_UNIX_INCLUDE_DIR GDBUS_CODEGEN) 
1> [CMake] -- Checking for one of the modules 'g7221'
1> [CMake] -- Could NOT find G7221 (missing: G7221_LIBRARY G7221_INCLUDE_DIR) 
1> [CMake] -- Could NOT find GZRTP (missing: GZRTP_LIBRARY GZRTP_INCLUDE_DIR) 
1> [CMake] -- Could NOT find MOSQUITTO (missing: MOSQUITTO_LIBRARY MOSQUITTO_INCLUDE_DIR) 
1> [CMake] -- libmosquitto include dir: MOSQUITTO_INCLUDE_DIR-NOTFOUND
1> [CMake] -- libmosquitto: MOSQUITTO_LIBRARY-NOTFOUND
1> [CMake] -- Could NOT find OPUS (missing: OPUS_LIBRARY OPUS_INCLUDE_DIR) 
1> [CMake] -- Could NOT find PNG (missing: PNG_LIBRARY) 
1> [CMake] -- Could NOT find PULSE (missing: PULSE_LIBRARY PULSE_INCLUDE_DIR) 
1> [CMake] -- Could NOT find SNDFILE (missing: SNDFILE_INCLUDE_DIR SNDFILE_LIBRARIES) 
1> [CMake] -- Could NOT find SPANDSP (missing: SPANDSP_LIBRARY SPANDSP_INCLUDE_DIR) 
1> [CMake] -- Checking for module 'libv4l2'
1> [CMake] --   No package 'libv4l2' found
1> [CMake] -- Could NOT find V4L2 (missing: V4L2_LIBRARY V4L2_INCLUDE_DIR) 
1> [CMake] -- Could NOT find VPX (missing: VPX_LIBRARY) 
1> [CMake] -- Could NOT find WEBRTC_AECM (missing: WEBRTC_AECM_LIBRARY WEBRTC_AECM_INCLUDE_DIR) 
1> [CMake] -- Could NOT find ZRTP (missing: ZRTP_LIBRARY ZRTP_INCLUDE_DIR) 
1> [CMake] -- Configuring done
1> [CMake] -- Generating done
1> [CMake] -- Build files have been written to: D:/test/baresip/out/build/x64-Debug
1> Extracted CMake variables.
1> Extracted source files and headers.
1> Extracted code model.
1> Extracted toolchain configurations.
1> Extracted includes paths.
1> CMake generation finished.

Then if I try to compile the Baresip getting following errors:

>------ Build started: Project: CMakeLists, Configuration: Debug ------
  [1/188] Building C object CMakeFiles\baresip.dir\src\auplay.c.obj
  [2/188] Building C object CMakeFiles\baresip.dir\src\aucodec.c.obj
  [3/188] Building C object CMakeFiles\baresip.dir\src\aufilt.c.obj
  [4/188] Building C object CMakeFiles\baresip.dir\src\account.c.obj
  [5/188] Building C object CMakeFiles\baresip.dir\src\ausrc.c.obj
  [6/188] Building C object CMakeFiles\baresip.dir\src\audio.c.obj
  [7/188] Building C object CMakeFiles\baresip.dir\src\baresip.c.obj
  [8/188] Building C object CMakeFiles\baresip.dir\src\call.c.obj
  [9/188] Building C object CMakeFiles\baresip.dir\src\conf.c.obj
  [10/188] Building C object CMakeFiles\baresip.dir\src\dial_number.c.obj
  [11/188] Building C object CMakeFiles\baresip.dir\src\bundle.c.obj
  [12/188] Building C object CMakeFiles\baresip.dir\src\cmd.c.obj
  [13/188] Building C object CMakeFiles\baresip.dir\src\config.c.obj
  [14/188] Building C object CMakeFiles\baresip.dir\src\contact.c.obj
  [15/188] Building C object CMakeFiles\baresip.dir\src\descr.c.obj
  [16/188] Building C object CMakeFiles\baresip.dir\src\http.c.obj
  [17/188] Building C object CMakeFiles\baresip.dir\src\event.c.obj
  [18/188] Building C object CMakeFiles\baresip.dir\src\custom_hdrs.c.obj
  [19/188] Building C object CMakeFiles\baresip.dir\src\log.c.obj
  [20/188] Building C object CMakeFiles\baresip.dir\src\mediadev.c.obj
  [21/188] Building C object CMakeFiles\baresip.dir\src\mediatrack.c.obj
  [22/188] Building C object CMakeFiles\baresip.dir\src\menc.c.obj
  [23/188] Building C object CMakeFiles\baresip.dir\src\net.c.obj
  [24/188] Building C object CMakeFiles\baresip.dir\src\mnat.c.obj
  [25/188] Building C object CMakeFiles\baresip.dir\src\message.c.obj
  [26/188] Building C object CMakeFiles\baresip.dir\src\module.c.obj
  [27/188] Building C object CMakeFiles\baresip.dir\src\peerconn.c.obj
  [28/188] Building C object CMakeFiles\baresip.dir\src\sdp.c.obj
  [29/188] Building C object CMakeFiles\baresip.dir\src\play.c.obj
  [30/188] Building C object CMakeFiles\baresip.dir\src\metric.c.obj
  [31/188] Building C object CMakeFiles\baresip.dir\src\reg.c.obj
  [32/188] Building C object CMakeFiles\baresip.dir\src\sipreq.c.obj
  [33/188] Building C object CMakeFiles\baresip.dir\src\rtpstat.c.obj
  [34/188] Building C object CMakeFiles\baresip.dir\src\stream.c.obj
  [35/188] Building C object CMakeFiles\baresip.dir\src\timestamp.c.obj
  [36/188] Building C object CMakeFiles\baresip.dir\src\rtpext.c.obj
  [37/188] Building C object CMakeFiles\baresip.dir\src\stunuri.c.obj
  [38/188] Building C object CMakeFiles\baresip.dir\src\uag.c.obj
  [39/188] Building C object CMakeFiles\baresip.dir\src\ui.c.obj
  [40/188] Building C object CMakeFiles\baresip.dir\src\ua.c.obj
  [41/188] Building C object CMakeFiles\baresip.dir\src\vidcodec.c.obj
  [42/188] Building C object CMakeFiles\baresip.dir\src\vidsrc.c.obj
  [43/188] Building C object CMakeFiles\baresip.dir\src\video.c.obj
  [44/188] Building C object CMakeFiles\baresip.dir\src\vidfilt.c.obj
  [45/188] Building C object CMakeFiles\baresip.dir\src\vidutil.c.obj
  [46/188] Building C object CMakeFiles\baresip.dir\src\vidisp.c.obj
  [47/188] Building C object modules\aubridge\CMakeFiles\aubridge.dir\aubridge.c.obj
C:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\um\winbase.h(9531): warning C5105: macro expansion producing 'defined' has undefined behavior
  [48/188] Building C object CMakeFiles\baresip_exe.dir\src\main.c.obj
  [49/188] Building C object modules\account\CMakeFiles\account.dir\account.c.obj
C:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\um\winbase.h(9531): warning C5105: macro expansion producing 'defined' has undefined behavior
  [50/188] Building C object modules\aubridge\CMakeFiles\aubridge.dir\device.c.obj
C:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\um\winbase.h(9531): warning C5105: macro expansion producing 'defined' has undefined behavior
  [51/188] Building C object modules\aubridge\CMakeFiles\aubridge.dir\src.c.obj
C:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\um\winbase.h(9531): warning C5105: macro expansion producing 'defined' has undefined behavior
  [52/188] Linking C shared module modules\account\account.dll
  FAILED: modules/account/account.dll 
  cmd.exe /C "cd . && "C:\Program Files\Microsoft Visual Studio\2022\Professional\Common7\IDE\CommonExtensions\Microsoft\CMake\CMake\bin\cmake.exe" -E vs_link_dll --intdir=modules\account\CMakeFiles\account.dir --rc=C:\PROGRA~2\WI3CF2~1\10\bin\100190~1.0\x64\rc.exe --mt=C:\PROGRA~2\WI3CF2~1\10\bin\100190~1.0\x64\mt.exe --manifests  -- C:\PROGRA~1\MICROS~2\2022\PROFES~1\VC\Tools\MSVC\1433~1.316\bin\Hostx64\x64\link.exe /nologo modules\account\CMakeFiles\account.dir\account.c.obj  /out:modules\account\account.dll /implib:modules\account\account.lib /pdb:modules\account\account.pdb /dll /version:0.0 /machine:x64 /debug /INCREMENTAL -LIBPATH:\usr\local\lib kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib  && cd ."
  LINK Pass 1: command "C:\PROGRA~1\MICROS~2\2022\PROFES~1\VC\Tools\MSVC\1433~1.316\bin\Hostx64\x64\link.exe /nologo modules\account\CMakeFiles\account.dir\account.c.obj /out:modules\account\account.dll /implib:modules\account\account.lib /pdb:modules\account\account.pdb /dll /version:0.0 /machine:x64 /debug /INCREMENTAL -LIBPATH:\usr\local\lib kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib /MANIFEST /MANIFESTFILE:modules\account\CMakeFiles\account.dir/intermediate.manifest modules\account\CMakeFiles\account.dir/manifest.res" failed (exit code 1120) with the following output:
D:\test\baresip\out\build\x64-Debug\account.c.obj : error LNK2019: unresolved external symbol pl_strcpy referenced in function line_handler
D:\test\baresip\out\build\x64-Debug\account.c.obj : error LNK2019: unresolved external symbol re_fprintf referenced in function account_write_template
D:\test\baresip\out\build\x64-Debug\account.c.obj : error LNK2019: unresolved external symbol re_printf referenced in function line_handler
D:\test\baresip\out\build\x64-Debug\account.c.obj : error LNK2019: unresolved external symbol re_snprintf referenced in function account_read_file
D:\test\baresip\out\build\x64-Debug\account.c.obj : error LNK2019: unresolved external symbol list_count referenced in function account_read_file
D:\test\baresip\out\build\x64-Debug\account.c.obj : error LNK2019: unresolved external symbol mem_deref referenced in function line_handler
D:\test\baresip\out\build\x64-Debug\account.c.obj : error LNK2019: unresolved external symbol fs_mkdir referenced in function account_read_file
D:\test\baresip\out\build\x64-Debug\account.c.obj : error LNK2019: unresolved external symbol fs_isfile referenced in function account_read_file
D:\test\baresip\out\build\x64-Debug\account.c.obj : error LNK2019: unresolved external symbol account_set_auth_pass referenced in function line_handler
D:\test\baresip\out\build\x64-Debug\account.c.obj : error LNK2019: unresolved external symbol account_regint referenced in function line_handler
D:\test\baresip\out\build\x64-Debug\account.c.obj : error LNK2019: unresolved external symbol account_prio referenced in function line_handler
D:\test\baresip\out\build\x64-Debug\account.c.obj : error LNK2019: unresolved external symbol account_aor referenced in function line_handler
D:\test\baresip\out\build\x64-Debug\account.c.obj : error LNK2019: unresolved external symbol account_auth_user referenced in function line_handler
D:\test\baresip\out\build\x64-Debug\account.c.obj : error LNK2019: unresolved external symbol account_auth_pass referenced in function line_handler
D:\test\baresip\out\build\x64-Debug\account.c.obj : error LNK2019: unresolved external symbol conf_path_get referenced in function account_read_file
D:\test\baresip\out\build\x64-Debug\account.c.obj : error LNK2019: unresolved external symbol conf_parse referenced in function account_read_file
D:\test\baresip\out\build\x64-Debug\account.c.obj : error LNK2019: unresolved external symbol info referenced in function account_write_template
D:\test\baresip\out\build\x64-Debug\account.c.obj : error LNK2019: unresolved external symbol warning referenced in function line_handler
D:\test\baresip\out\build\x64-Debug\account.c.obj : error LNK2019: unresolved external symbol ua_alloc referenced in function line_handler
D:\test\baresip\out\build\x64-Debug\account.c.obj : error LNK2019: unresolved external symbol ua_register referenced in function line_handler
D:\test\baresip\out\build\x64-Debug\account.c.obj : error LNK2019: unresolved external symbol ua_fallback referenced in function line_handler
D:\test\baresip\out\build\x64-Debug\account.c.obj : error LNK2019: unresolved external symbol ua_account referenced in function line_handler
D:\test\baresip\out\build\x64-Debug\account.c.obj : error LNK2019: unresolved external symbol uag_list referenced in function account_read_file
D:\test\baresip\out\build\x64-Debug\account.c.obj : error LNK2019: unresolved external symbol ui_password_prompt referenced in function line_handler
D:\test\baresip\out\build\x64-Debug\modules\account\account.dll : fatal error LNK1120: 24 unresolved externals
  [53/188] Building C object modules\auconv\CMakeFiles\auconv.dir\auconv.c.obj
C:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\um\winbase.h(9531): warning C5105: macro expansion producing 'defined' has undefined behavior
  [54/188] Building C object modules\aubridge\CMakeFiles\aubridge.dir\play.c.obj
C:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\um\winbase.h(9531): warning C5105: macro expansion producing 'defined' has undefined behavior
  [55/188] Linking C shared library baresip.dll
  [56/188] Building C object modules\aufile\CMakeFiles\aufile.dir\aufile_play.c.obj
C:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\um\winbase.h(9531): warning C5105: macro expansion producing 'defined' has undefined behavior
  [57/188] Building C object modules\aufile\CMakeFiles\aufile.dir\aufile_src.c.obj
C:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\um\winbase.h(9531): warning C5105: macro expansion producing 'defined' has undefined behavior
  ninja: build stopped: subcommand failed.

Build failed.

Request your help to resolve these errors.

**Comment by sreimers** [comment]
Can you try the static build with: `-DSTATIC=ON` cmake option.

**Comment by venkat1152000** [comment]
> Can you try the static build with: `-DSTATIC=ON` cmake option.

I try It will run Successfully but I get this errror:


[ 78%] Building C object CMakeFiles/baresip_exe.dir/src/main.c.obj
main.c
[ 79%] Linking CXX executable baresip.exe
LINK Pass 1: command "C:\PROGRA~1\MICROS~2\2022\PROFES~1\VC\Tools\MSVC\1433~1.316\bin\Hostx86\x86\link.exe /nologo @CMakeFiles\baresip_exe.dir\objects1.rsp /out:baresip.exe /implib:baresip.lib /pdb:D:\test\baresip\baresip.pdb /version:0.0 /machine:X86 /debug /INCREMENTAL /subsystem:console -LIBPATH:\usr\local\lib baresip.lib D:\test\rem\out\build\x64-Debug\rem.lib D:\test\re\build\re-static.lib D:\test\OpenSSL\lib\libssl.lib D:\test\OpenSSL\lib\libcrypto.lib ws2_32.lib iphlpapi.lib winmm.lib gdi32.lib crypt32.lib strmiids.lib ole32.lib oleaut32.lib qwave.lib strmiids.lib ole32.lib oleaut32.lib stdc++.lib winmm.lib kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib /MANIFEST /MANIFESTFILE:CMakeFiles\baresip_exe.dir/intermediate.manifest CMakeFiles\baresip_exe.dir/manifest.res" failed (exit code 1104) with the following output:
LINK : fatal error LNK1104: cannot open file 'stdc++.lib'
NMAKE : fatal error U1077: '"C:\Program Files\CMake\bin\cmake.exe"' : return code '0xffffffff'
Stop.
NMAKE : fatal error U1077: '"C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.33.31629\bin\HostX86\x86\nmake.exe"' : return code '0x2'
Stop.
NMAKE : fatal error U1077: '"C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.33.31629\bin\HostX86\x86\nmake.exe"' : return code '0x2'
Stop.

**Comment by sreimers** [comment]
Can you try this patch:

```patch
diff --git a/modules/dshow/CMakeLists.txt b/modules/dshow/CMakeLists.txt
index 800e7f9a..dd6ed70d 100644
--- a/modules/dshow/CMakeLists.txt
+++ b/modules/dshow/CMakeLists.txt
@@ -9,4 +9,8 @@ else()
 endif()
 
 target_link_libraries(${PROJECT_NAME} PRIVATE
-  strmiids ole32 oleaut32 stdc++)
+  strmiids ole32 oleaut32)
+
+if(NOT MSVC)
+  target_link_libraries(${PROJECT_NAME} PRIVATE stdc++)
+endif()
```

**Comment by venkat1152000** [comment]
> 



> Can you try this patch:
> 
> ```diff
> diff --git a/modules/dshow/CMakeLists.txt b/modules/dshow/CMakeLists.txt
> index 800e7f9a..dd6ed70d 100644
> --- a/modules/dshow/CMakeLists.txt
> +++ b/modules/dshow/CMakeLists.txt
> @@ -9,4 +9,8 @@ else()
>  endif()
>  
>  target_link_libraries(${PROJECT_NAME} PRIVATE
> -  strmiids ole32 oleaut32 stdc++)
> +  strmiids ole32 oleaut32)
> +
> +if(NOT MSVC)
> +  target_link_libraries(${PROJECT_NAME} PRIVATE stdc++)
> +endif()
> ```

I try this but i got another error:

[ 78%] Built target baresip
Consolidate compiler generated dependencies of target baresip_exe
[ 79%] Linking CXX executable baresip.exe
LINK Pass 1: command "C:\PROGRA~1\MICROS~2\2022\PROFES~1\VC\Tools\MSVC\1433~1.316\bin\Hostx86\x86\link.exe /nologo @CMakeFiles\baresip_exe.dir\objects1.rsp /out:baresip.exe /implib:baresip.lib /pdb:D:\test\baresip\baresip.pdb /version:0.0 /machine:X86 /debug /INCREMENTAL /subsystem:console -LIBPATH:\usr\local\lib baresip.lib D:\test\rem\out\build\x64-Debug\rem.lib D:\test\re\build\re-static.lib D:\test\OpenSSL\lib\libssl.lib D:\test\OpenSSL\lib\libcrypto.lib ws2_32.lib iphlpapi.lib winmm.lib gdi32.lib crypt32.lib strmiids.lib ole32.lib oleaut32.lib qwave.lib strmiids.lib ole32.lib oleaut32.lib winmm.lib kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib /MANIFEST /MANIFESTFILE:CMakeFiles\baresip_exe.dir/intermediate.manifest CMakeFiles\baresip_exe.dir/manifest.res" failed (exit code 1149) with the following output:
LINK : fatal error LNK1149: output filename matches input filename 'D:\test\baresip\baresip.lib'
NMAKE : fatal error U1077: '"C:\Program Files\CMake\bin\cmake.exe"' : return code '0xffffffff'
Stop.
NMAKE : fatal error U1077: '"C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.33.31629\bin\HostX86\x86\nmake.exe"' : return code '0x2'
Stop.
NMAKE : fatal error U1077: '"C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.33.31629\bin\HostX86\x86\nmake.exe"' : return code '0x2'
Stop.

**Comment by sreimers** [comment]
Can you try:

```patch
diff --git a/CMakeLists.txt b/CMakeLists.txt
index b9d43120..b7927ead 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -220,6 +220,10 @@ else()
   target_link_libraries(baresip PRIVATE ${LINKLIBS})
 endif()
 
+if(MSVC)
+  set_target_properties(baresip PROPERTIES OUTPUT_NAME "libbaresip")
+endif()
+
 set_target_properties(baresip PROPERTIES POSITION_INDEPENDENT_CODE ON)
 
 set_target_properties(baresip PROPERTIES PUBLIC_HEADER "${HEADERS}")
```

**Comment by venkat1152000** [comment]
> Can you try:
> 
> ```diff
> diff --git a/CMakeLists.txt b/CMakeLists.txt
> index b9d43120..b7927ead 100644
> --- a/CMakeLists.txt
> +++ b/CMakeLists.txt
> @@ -220,6 +220,10 @@ else()
>    target_link_libraries(baresip PRIVATE ${LINKLIBS})
>  endif()
>  
> +if(MSVC)
> +  set_target_properties(baresip PROPERTIES OUTPUT_NAME "libbaresip")
> +endif()
> +
>  set_target_properties(baresip PROPERTIES POSITION_INDEPENDENT_CODE ON)
>  
>  set_target_properties(baresip PROPERTIES PUBLIC_HEADER "${HEADERS}")
> ```

I try this The previous error is resolved now... But I am facing another error:

[ 80%] Building C object webrtc/CMakeFiles/baresip-webrtc.dir/src/main.c.obj
main.c
D:\test\baresip\webrtc\src\main.c(9): fatal error C1083: Cannot open include file: 'getopt.h': No such file or directory
NMAKE : fatal error U1077: '"C:\Program Files\CMake\bin\cmake.exe"' : return code '0x2'
Stop.
NMAKE : fatal error U1077: '"C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.33.31629\bin\HostX86\x86\nmake.exe"' : return code '0x2'
Stop.
NMAKE : fatal error U1077: '"C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.33.31629\bin\HostX86\x86\nmake.exe"' : return code '0x2'
Stop.

**Comment by sreimers** [comment]
Please try git main (needs re and rem main too), I fixed some related bugs.

**Comment by venkat1152000** [comment]
> Please try git main (needs re and rem main too), I fixed some related bugs.

I'm using main branch only for all re, rem and baresip. Do I need to use latest code? Because now I'm using 2.7.0 version.

**Comment by alfredh** [comment]
please try again with HEAD and main from all projects

**Comment by alfredh** [comment]
NOTE: We should add Windows to CI
