### ISSUE TITLE
Please add gtk module to cmake

### ISSUE THREAD

**Issue by robert-scheck** [baresip/baresip#2166]
Please add gtk module to cmake :)

I am of course happy to perform tests on all active Fedora and CentOS/RHEL/Rocky releases.

**Comment by alfredh** [comment]
we are planning to move this module to `baresip-apps`.

There is no active maintainer for this module, and it is unclear if anyone is using it.

**Comment by robert-scheck** [comment]
> we are planning to move this module to `baresip-apps`.

Really, why?

> There is no active maintainer for this module, and it is unclear if anyone is using it.

According to https://github.com/baresip/baresip/wiki/Modules, @mbattista is the current maintainer.

Regarding the usage: The gtk module is actually the main reason why I'm maintaining baresip in Fedora and EPEL. I also know about 20 users of the gtk module personally (including myself).

**Comment by mbattista** [comment]
Yes, I will fix issues regarding gtk and try to keep an eye on changes, so it keeps running with changes made to baresip.

I also try to develop new features, so some known limitation will be gone in the future.
