### ISSUE TITLE
Turning -DDEFAULT_CAFILE and -DDEFAULT_AUDIO_DEVICE into cmake options?

### ISSUE THREAD

**Issue by robert-scheck** [baresip/baresip#2167]
When building baresip using `make`, I appended:

```
EXTRA_CFLAGS="-DDEFAULT_CAFILE='\"%{_sysconfdir}/pki/tls/certs/ca-bundle.crt\"' -DDEFAULT_AUDIO_DEVICE='\"pulse\"'"
```

Using `cmake` this approach obviously doesn't work anymore the same way. Do you have an opinion from upstream perspective here? Is turning `-DDEFAULT_CAFILE` and `-DDEFAULT_AUDIO_DEVICE` into cmake options an acceptable idea?

**Comment by sreimers** [comment]
> Is turning `-DDEFAULT_CAFILE` and `-DDEFAULT_AUDIO_DEVICE` into cmake options an acceptable idea?

A PR is welcome
