### ISSUE TITLE
Please add mpa module to cmake

### ISSUE THREAD

**Issue by robert-scheck** [baresip/baresip#2177]
Please add mpa module to cmake :)

I am happy to try this myself (with the goal of a pull request), however I would like to get your feedback before: The mpa module currently requires `-ltwolame -lmp3lame -lmpg123 -lspeexdsp`. Would a single `cmake/FindMPA.cmake` be the desired result? Or should this end up in 4 different cmake modules, one per library? And who is the best to answer this, maybe @sreimers?

**Comment by alfredh** [comment]
this is an old and deprecated module we should remove it instead

**Comment by robert-scheck** [comment]
Just because it is old or because it doesn't work properly anymore?
