### ISSUE TITLE
testing ice/turn without success

### ISSUE THREAD

**Issue by juha-h** [baresip/baresip#2235]
### Discussed in https://github.com/baresip/baresip/discussions/2232

<div type='discussions-op-text'>

<sup>Originally posted by **juha-h** October  6, 2022</sup>
I configured in my account:
```
;stunserver=turn:openrelay.metered.ca:80;stunuser=openrelayproject;stunpass=openrelayproject;medianat=ice
```
Then I tried to make a call:
```
test@sip.tutpro.com: selected for request
call uri: sip:foo@sip.tutpro.com
call: alloc with params laddr=192.168.238.215, af=AF_INET, use_rtp=1
ice: new session with TURN-server at openrelay.metered.ca (username=openrelayproject)
call: use_video=0
call: connecting to 'sip:foo@sip.tutpro.com'..
presence: ua=0x55ca102f7c10 got event 11 (CALL_OUTGOING)
call id: dc48c4d6cca68f0f
ice: resolved TURN-server to address 216.39.253.10:80
```
After that nothing happened.

I tested on page https://webrtc.github.io/samples/src/content/peerconnection/trickle-ice/ that the turn server is operational.

Any idea why nothing happens?  I started baresip with -v, but looks like there is no ice/turn related debug messages.

Could someone else try the same? Does it work for you?

My host is connected to mobile WiFi hotspot.</div>

**Comment by juha-h** [comment]
I tried with re/rem/baresip tags v1.0.0/v1.1.0/v1.0.0 and ;medianat=ice call with same config/account worked fine:
```
>                              bar
ua: using best effort AF: af=AF_INET
ice: new session with STUN-server at stun.l.google.com (username=test)
call: connecting to 'sip:bar@sip.tutpro.com'..
ice: audio: Default local candidates: 37.33.252.59:33255 / ?
ice: video: Default local candidates: 37.33.252.59:33256 / ?
call: media-nat 'ice' established/gathered
call: SIP Progress: 100 Trying (/)
...
```
So I start to suspect that medianat/stun stuff in badly broken in main.  Don't know how far back I would need to go in order to get it working.  So I'll label this as bug.

**Comment by juha-h** [comment]
This issue does not exist when I built re/rem/baresip using tags:
```
RE_VERSION=v2.2.2
REM_VERSION=v2.0.1
BS_VERSION=v2.0.2
```
So the bug has been introduced after that (April 2022).

**Comment by juha-h** [comment]
The issue does not exist with v2.7.x but does exist with v2.8.x.

**Comment by sreimers** [comment]
Only a guess, maybe this is related:

https://github.com/baresip/baresip/pull/2116

It removes a `update_media` call.

**Comment by juha-h** [comment]
Sebastian Reimers writes:

> Only a guess, maybe this is related:
> 
> https://github.com/baresip/baresip/pull/2116
> 
> It removes a `update_media` call.

Maybe.  Hard to test.  There is large number of commits 24 ago and also
working re would need to be found.

**Comment by juha-h** [comment]
I reverted only that commit and it didn't help.

**Comment by juha-h** [comment]
Using this kind of checkout:
```
git checkout `git rev-list -n 1 --before="2022-09-26 23:59" main`
```
I found that the issue does not exist, but does exist when I change the date to 2022-09-27.  There was many commits on Sept 27.

**Comment by juha-h** [comment]
There may be the relevant ones:
```
[ua,call: got_offer cleanup](https://github.com/baresip/baresip/commit/ac9236125d8a931068c90cf304047fe8b2df9393)
@[cspiel1](https://github.com/baresip/baresip/commits?author=cspiel1)
@[sreimers](https://github.com/baresip/baresip/commits?author=sreimers)
cspiel1 authored and sreimers committed 12 days ago

[ua,call: allocate streams for handle OPTIONS](https://github.com/baresip/baresip/commit/f85fc5d92cfb802be22992b70875c79d0e69f7a9)
@[cspiel1](https://github.com/baresip/baresip/commits?author=cspiel1)
@[sreimers](https://github.com/baresip/baresip/commits?author=sreimers)
cspiel1 authored and sreimers committed 12 days ago

[call: allocate streams after peer_uri was set](https://github.com/baresip/baresip/commit/6bcc376d3c83983a66df60b81c504c16a6951294)
@[cspiel1](https://github.com/baresip/baresip/commits?author=cspiel1)
@[sreimers](https://github.com/baresip/baresip/commits?author=sreimers)
cspiel1 authored and sreimers committed 12 days ago
```

**Comment by juha-h** [comment]
@cspiel1 Could you please check.

**Comment by juha-h** [comment]
I suspect that now call_streams_alloc is called too late and ice mediah is not called at all.  These PRs are too complex for me to figure out what goes wrong and how it should be fixed.

Anyway, the issue is severe, since now ice negotiation does not work at all.  I don't know if some kind of ice test could be added to github PR tests.

**Comment by cspiel1** [comment]
I will have a look on this.

**Comment by KORuL** [comment]
I wrote about it, but my mr ignore

https://github.com/juha-h/baresip-studio/issues/290 - here is the same problem

https://github.com/baresip/baresip/pull/2185 - this is mr

**Comment by juha-h** [comment]
Just tested and applying https://github.com/baresip/baresip/pull/2185 to main does not solve the issue.

**Comment by KORuL** [comment]
i also switch to wifi (double nat) and the stream doesn't go through turn server

**Comment by KORuL** [comment]
https://github.com/baresip/baresip/issues/2235#issuecomment-1272933062
And here I am about the fact that the call initialization occurs too late and this breaks my application on android - you have to roll back this commit of yours

**Comment by juha-h** [comment]
Fixed by https://github.com/baresip/baresip/pull/2242.

**Comment by KORuL** [comment]
Everything is still!
The connection to the turn server is established successfully. Neither video nor audio is streaming through the turn server. It works, checked through other services, the authentication data is correct
