### ISSUE TITLE
Selfview is not working

### ISSUE THREAD

**Issue by venkat1152000** [baresip/baresip#2238]
Hi All,
        I enable slefview in window mode (video_selfview		window) but during the call connection , baresip will hanging and selfview window display Not Responding

Thanks and regards
Venkatesh V

**Comment by juha-h** [comment]
Selfview works fine in window mode using latest main on Debian 11.

**Comment by venkat1152000** [comment]
> 

In ubuntu it is fine, but in windows is not working

**Comment by alfredh** [comment]
Please provide full config and log output as stated here:

https://github.com/baresip/baresip/wiki/Guidelines-for-reporting-Issues


selfview has two modes:

```
# Selfview
video_selfview          window # {window,pip}
#selfview_size          64x64
```


have you tried both ?

**Comment by alfredh** [comment]
tested on macOS:


```
aeh@iptel.org: Call established: sip:echo@10.0.1.2:5050
stream: incoming rtp for 'video' established, receiving from 10.0.1.2:46430
main: next timer: 4 ms
main: next timer: 1 ms
main: thread check: called from a NON-RE thread without thread_enter()!
main: 0   libre.10.9.0.dylib                  0x000000010ccea5e1 btrace + 49 
1   libre.10.9.0.dylib                  0x000000010cce8329 re_thread_check + 153 
2   libre.10.9.0.dylib                  0x000000010cd0c02e tmr_start_dbg + 62 
3   sdl.so                              0x000000011cc06fb5 alloc + 229 
4   baresip                             0x000000010cc82a32 vidisp_alloc + 114 
5   selfview.so                         0x000000011cb7782d encode_win + 125 
6   baresip                             0x000000010cc820c8 encode_rtp_send + 568 
7   baresip                             0x000000010cc80170 vidsrc_frame_handler + 192 
8   avformat.so                         0x000000011f156460 avformat_video_decode + 656 
9   avformat.so                         0x000000011f15545b read_thread + 891 
main: next timer: 4 ms
main: next timer: 4 ms
main: next timer: 4 ms
stream: incoming rtp for 'audio' established, receiving from 10.0.1.2:17656
main: next timer: 3 ms
main: next timer: 4 ms
sdl: unable to create sdl window: Window data not set
main: next timer: 4 ms
sdl: unable to create sdl window: Window data not set


```

**Comment by alfredh** [comment]
here is a patch:

https://github.com/baresip/baresip/pull/2253


Which video display module are you using ?

For me on macOS x11.so is working, but sdl.so does not work.

**Comment by alfredh** [comment]
hi,

I have pushed a fix to main HEAD. Could you please try again ?


@juha-h if you have time could you please also test HEAD again on Linux ?
if possible test x11.so and sdl.so

**Comment by alfredh** [comment]
hi @venkat1152000 

I did not hear back from you, so I will close the ticket.

If the issue persist, please open a new ticket and supply all the required info.


Alfred
