### ISSUE TITLE
avformat module and libpostproc

### ISSUE THREAD

**Issue by juha-h** [baresip/baresip#2270]
### Discussed in https://github.com/baresip/baresip/discussions/2269

<div type='discussions-op-text'>

<sup>Originally posted by **juha-h** October 17, 2022</sup>
Module `avformat` has this in module.mk:
```
$(MOD)_LFLAGS	+= \
	`pkg-config --libs libavformat libavcodec libswresample \
		libavutil libavdevice libavfilter libswscale libpostproc`
```
but `postprocess.h` is not included in any of its files.

Does module avformat really need libpostproc or is there a bug in the above flags and in `cmake/FindFFMPEG.cmake`?</div>

**Comment by juha-h** [comment]
I turned this to issue, since it looks like a bug to me.  I build my baresip Android app without libpostproc and video call with
```
video_source avformat,android_camera,1
```
worked fine.

I also checked `cmake/FindFFMPEG.cmake` and noticed that components handled in it do not match those listed in `modules.cmake`.

**Comment by alfredh** [comment]
postproc is not used directly by avformat.so

**Comment by juha-h** [comment]
Alfred E. Heggestad writes:

> postproc is not used directly by avformat.so

Is it used indirectly by some of the other libs that avformat is
using?

As I mentioned, when I built baresip without libpostprocess, linker
didn't complain about any missing symbols.

**Comment by juha-h** [comment]
If some libs depend on libpostproc, but baresip itself does not, then baresip build should not require libpostproc.  And that seems to be the case with cmake build, since `postproc` is not listed in
```
find_package(FFMPEG COMPONENTS
    avutil avcodec avfilter avformat swscale swresample avdevice)
```
and thus this FindFFMPEG.cmake test never matches:
```
  elseif(component STREQUAL "postproc")
    find_ffmpeg_library("${component}" "postprocess.h")
```
So it should be OK to remove that test and libpostproc from avformat/module.mk.

I use ffmpeg-kit to build ffmpeg libs and by default libpostproc is not included in those because it has vanilla GPL license. And as I mentioned, the app works fine without it.

Debian ffmpeg libs, on the other hand, have been built with postproc enabled and that is fine too.

So, is it OK if I create a PR that removes the above mentioned elseif from FindFFMPEG.cmake and libpostproc from avformat/module.mk?

**Comment by juha-h** [comment]
Closed by https://github.com/baresip/baresip/pull/2274.
