### ISSUE TITLE
amr codec seems to completely ignore mode-set and sends mode 7

### ISSUE THREAD

**Issue by whyteks** [baresip/baresip#2308]
I'm not sure what else to say other than the headline..

I don't see any mode-set parsing in the amr module source code.
I noticed this today trying out the android baresip app, as mode 7 is not usable on a GSM Half Rate Channel.

**Comment by alfredh** [comment]
hi,

please read the guidelines here:

https://github.com/baresip/baresip/wiki/Guidelines-for-reporting-Issues


amr mode-set is not supported.

For bug reports to Baresip Android app please use this:

https://github.com/juha-h/baresip-studio
