### ISSUE TITLE
Question: Call transfer/forward between 2 accounts without answering

### ISSUE THREAD

**Issue by pergolafabio** [baresip/baresip#2340]
Hi
I have a question, i see there is a transfer option, but i think this transfer option is only avaible when the call has been answered
What i want:
I have 2 accounts registered with baresip on a PBX
When there is an incoming call to user1 , can i immediately forward the call to user2 without user 1 thats answers the call?

thnx in advance

**Comment by cspiel1** [comment]
Please use the mailing list for questions!
