### ISSUE TITLE
Android app crashes at network changes

### ISSUE THREAD

**Issue by juha-h** [baresip/baresip#2402]
My baresip Android app has started to crash at network changes (new network added or existing one removed).   The API calls are `net_add_address_ifname`, `net_rm_address`, and `uag_reset_transp`.  The version that works OK is from Oct 22, 2022.  It is a bit hard for me to go back with `git checkout <commit>` to older versions or re/baresip due to changes in the build process. Any idea what changes in re/baresip could be causing the crash?

**Comment by juha-h** [comment]
The crash does not happen with re/rem/baresip --before="2022-12-15 23:59".

**Comment by juha-h** [comment]
But does happen with re/rem/baresip --before="2022-12-23 23:59".

**Comment by juha-h** [comment]
The crash is caused by this commit https://github.com/baresip/re/commit/739e62579eb33fb30219cc60d4bb90ed591438bd.  I have not set any UNIX_SOCK related flags.  Should I have done so?  If not, can the bug be fixed?

**Comment by juha-h** [comment]
The crash went away when I defined `USE_UNIXSOCK=OFF`.  It is `ON` by default.  Should it be `ON` by default only `if(NOT_ANDROID)`?

**Comment by cspiel1** [comment]
Maybe we should try to find the reason for the crash and not just configure it away.
Is it possible that you get a call stack of the crash?

**Comment by KORuL** [comment]
https://github.com/juha-h/baresip-studio/issues/296

**Comment by KORuL** [comment]
crash occurs with damage to the stack, so the exact point of the crash is not clear, you can only understand that by calling this function and exiting from it, the stack has deteriorated

**Comment by sreimers** [comment]
> The crash is caused by this commit [baresip/re@739e625](https://github.com/baresip/re/commit/739e62579eb33fb30219cc60d4bb90ed591438bd). I have not set any UNIX_SOCK related flags. Should I have done so? If not, can the bug be fixed?

If libre and baresip not compiled with same UNIX_SOCK flags, the size of `struct sa` is different:

https://github.com/baresip/re/blob/main/include/re_sa.h#L33-L47

That can lead to crashes right.

We use this cmake code to ensure same flags are set:

```
find_package(re CONFIG REQUIRED HINTS ../re/cmake)
```

**Comment by juha-h** [comment]
I have for `net_add_address_ifname():
```
    int res = 0;
    struct sa temp_sa;
    char buf[256];
    LOGD("adding address/ifname '%s/%s'\n", addr, name);
    if (0 == sa_set_str(&temp_sa, addr, 0)) {
        sa_ntop(&temp_sa, buf, 256);
        re_thread_enter();
        res = net_add_address_ifname(baresip_network(), &temp_sa, name);
        re_thread_leave();
    } else {
        LOGE("invalid ip address %s\n", addr);
        res = EAFNOSUPPORT;
    }
```
The crash line is the last }, so it does not tell much.

I have seen the crash also when calling `net_rm_address()`.

**Comment by juha-h** [comment]
Here is the network update code:
```
       val addresses = linkAddresses()

        Log.d(TAG, "Old/new link addresses $linkAddresses/$addresses")

        var added = 0
        for (a in addresses)
            if (!linkAddresses.containsKey(a.key)) {
                if (Api.net_add_address_ifname(a.key, a.value) != 0)
                    Log.e(TAG, "Failed to add address: $a")
                else
                    added++
            }
        var removed = 0
        for (a in linkAddresses)
            if (!addresses.containsKey(a.key)) {
                if (Api.net_rm_address(a.key) != 0)
                    Log.e(TAG, "Failed to remove address: $a")
                else
                    removed++
            }

        val active = activeNetwork()
        Log.d(TAG, "Added/Removed/Active = $added/$removed/$active")

        if (added > 0 || removed > 0 || active != activeNetwork) {
            linkAddresses = addresses
            activeNetwork = active
            Api.uag_reset_transp(register = true, reinvite = true)
        }

        Api.net_debug()

        if (activeNetwork != null) {
            val caps = cm.getNetworkCapabilities(activeNetwork)
            if (caps != null && caps.hasTransport(NetworkCapabilities.TRANSPORT_WIFI)) {
                Log.d(TAG, "Acquiring WiFi Lock")
                wifiLock.acquire()
                return
            }
        }
```
Message `Log.d(TAG, "Added/Removed/Active = $added/$removed/$active")` is never printed.  So the crash happens in `net_add_address_ifname` or `net_rm_address`.

**Comment by juha-h** [comment]
> We use this cmake code to ensure same flags are set:
> 
> ```
> find_package(re CONFIG REQUIRED HINTS ../re/cmake)
> ```
I have not changed anything in baresip/CMakeLists.txt.  So the above is still there.

**Comment by sreimers** [comment]
But you use `struct sa temp_sa;` in your App itself, so it has be configured like libre and baresip. If you set definitions manually it has to be added, or you can use the same `find_package` CONFIG helper to ensure new options are set properly.

**Comment by juha-h** [comment]
This is getting complicated. I don't know much about cmake.  How can baresip app CMakelist.txt https://github.com/juha-h/baresip-studio/blob/master/app/src/main/cpp/CMakeLists.txt, find package `re`?

I tried to add CMakeLists.txt lines :
```
set(re_DIR /usr/src/libbaresip/re/cmake)
find_package(re CONFIG REQUIRED HINTS /usr/src/libbaresip/re/cmake)
add_definitions(${RE_DEFINITIONS})
```
but build failed:
```
CMake Error at CMakeLists.txt:70 (find_package):
Could not find a package configuration file provided by "re" with any of
the following names:
reConfig.cmake
re-config.cmake
Add the installation prefix of "re" to CMAKE_PREFIX_PATH or set "re_DIR" to
a directory containing one of the above files.  If "re" provides a separate
development package or SDK, be sure it has been installed.
```

**Comment by juha-h** [comment]
Made mistake with re directory name.  With this build worked (haven't tested yet):
```
set(re_DIR /usr/src/libbaresip-android/re/cmake)
find_package(re CONFIG REQUIRED HINTS /usr/src/libbaresip-android/re/cmake)
add_definitions(${RE_DEFINITIONS})
```
Now baresip app build needs to know where re source is, which is not nice.  Different user may use different directories for it.

**Comment by juha-h** [comment]
The crash didn't happen with the above additions to baresip app's CMakeLists.txt. But it is very bad think that now baresip app needs to know where re source is.

What needs to be added to baresip app's  CMakeLists.txt that would avoid the `struct sa temp_sa related` crash?

**Comment by juha-h** [comment]
How about making net_add_address_ifname/net_rm_address to accept string as address argument?  Then struct sa temp_sa would be hidden inside re.

**Comment by cspiel1** [comment]
The baresip API is used not only by "external" applications. It is also used by a lot of modules compiled with baresip (or in baresip-apps). These should have access to `struct sa` directly. Especially module `netroam`.

Would it be a good solution to add wrapper functions? Or is it better to ensure a correct build for applications?

**Comment by juha-h** [comment]
I ended up doing this:

When libre is built in libbaresip-android project, also re cmake file is copied to baresip-studio distribution directory:
```
	rm -rf $(OUTPUT_DIR)/re/include
	mkdir -p $(OUTPUT_DIR)/re/include
	cp re/include/* $(OUTPUT_DIR)/re/include
	rm -rf $(OUTPUT_DIR)/re/cmake
	mkdir -p $(OUTPUT_DIR)/re/cmake
	cp re/cmake/re-config.cmake $(OUTPUT_DIR)/re/cmake
```
Then I added in CMakeLists.txt of baresip-studio project lines:
```
set(re_DIR ${distribution_DIR}/re/cmake)
find_package(re CONFIG REQUIRED HINTS ${distribution_DIR}/re/cmake)
add_definitions(${RE_DEFINITIONS})
```
That way, baresip-studio project does not need know the location of re source.

Is it only libre that needs those lines or should I add similar lines also to librem and libbaresip?
```
set(rem_DIR ${distribution_DIR}/rem/cmake)
find_package(rem CONFIG REQUIRED HINTS ${distribution_DIR}/rem/cmake)
add_definitions(${REM_DEFINITIONS})

set(baresip_DIR ${distribution_DIR}/baresip/cmake)
find_package(baresip CONFIG REQUIRED HINTS ${distribution_DIR}/baresip/cmake)
add_definitions(${BARESIP_DEFINITIONS})
```
