### ISSUE TITLE
Unable to Receive Calls

### ISSUE THREAD

**Issue by stef204** [baresip/baresip#2437]
let me know if this is the wrong repo to post this ticket please.

basresip+ 38 F-Droid
Android 12

When using the app, I can make outgoing calls but cannot receive ANY calls.  I've tried this on 2 numbers.
In `Settings!, I see:  `Listen Address: 0.0.0.0:5060`
Do I need to change this IP address?  I am inside a LAN behind a router.

**Comment by sreimers** [comment]
For android related issue use this repo: https://github.com/juha-h/baresip-studio
