### ISSUE TITLE
Custom header is not added to REGISTER request

### ISSUE THREAD

**Issue by juha-h** [baresip/baresip#2450]
One user of my baresip Android app asked about adding custom header to REGISTER and INVITE requests.  I checked and found API function `ua_add_custom_hdr`.  I tested it using menu command `/uaaddheader`, but it only added custom header to INVITE request, not to REGISTER request.

**Comment by cspiel1** [comment]
I think this was made for `INVITE`. But it will not hurt if it would also be added to `REGISTER`.

**Comment by alfredh** [comment]
it should be possible to also add it to REGISTER, if someone wants to make a patch ...

What about the other methods, like INFO, SUBSCRIBE, NOTIFY, REFER etc ?

**Comment by juha-h** [comment]
I don't see any reason not to include the custom header to all requests.  If that breaks some app, then there should be a method filter argument in the call.

**Comment by juha-h** [comment]
One way to fix this without new code is to rename the function to `ua_add_custom_invite_hdr`.

**Comment by cspiel1** [comment]
We should not make things complicated with a lot of different similar named API functions. Someone could make a patch to add the custom headers to REGISTER and maybe other SIP requests. This will not break anything.

Alternative:
An optional filter argument would be a good idea. We could add an argument `const struct pl *met` for the method.

```c
int ua_add_custom_hdr(struct ua *ua, const struct pl *met, const struct pl *name,
		      const struct pl *value);
```

If `met` is NULL or empty, it should be added to all requests. Then the code in the repos `baresip`, `baresip-apps` and the Anrdoid app has to be updated. I don't think that many other people are using this already. And the adaption is simple.

**Comment by Koshub** [comment]
@juha-h could you please check this one:
https://github.com/baresip/baresip/pull/2452

**Comment by Koshub** [comment]
@alfredh [FYI](https://github.com/baresip/baresip/pull/2452)

**Comment by juha-h** [comment]
I tested https://github.com/baresip/baresip/pull/2452 and customer header was now added also to REGISTER request.  So it would be a solution to the issue and I thus close it.  Filtering would, of course, be a more complete solution if someone would have time to implement it.
