### ISSUE TITLE
Notification on android could use some work

### ISSUE THREAD

**Issue by Rstment25** [baresip/baresip#2455]
Take a look at the video below ( I think you can watch without downloading it )
https://drive.google.com/file/d/1qhyg8TcD_pwQZRFojiuZdVScXzSZ-jB6/view?usp=sharing

In the video I'm playing with opening/closing baresip notification , notice how indicator only shows up when notification is closed?

When you open/expand notification it shows you nothing? But when the notification is closed/collapsed it shows status bar indicator? Isn't that odd behaviour...

Is it possible to have it show status bar indicator ALL the time? It already shows it with notification collapsed, it shouldn't be hard to have it show indicator when it's open as well?

Android by default shows baresip notification as open ( No indicator is shown , you have to minimise notification in order to see the indicator - very counterproductive because if for some reason indicator is showing disconnected you now have to open notification again in order to be able to click on it and open the app )

**Comment by juha-h** [comment]
You posted the issue on wrong project.  About text has the correct link
