### ISSUE TITLE
"does not depend on third party push notification services"

### ISSUE THREAD

**Issue by bagherfathi** [baresip/baresip#2477]
Hi everyone,
as you know android for saving battery goes to sleep, and apps like sip that need to send regular REGISTER message has high battery usage it's possible for android automatically or asks the user to put the sip app to sleep. 
to solve this problem, SIP proxies block the INVITE message for example 3 seconds and send a push notification to the android client to wake up the client and after the client sends the REGISTER message to the SIP proxy, the proxy unblocks the blocked INVITE and session initiation continues.
as I saw in your comments in the google play store and f-droid you mentioned that your tools: "does not depend on third party push notification services."
What's the meaning of the above phrase?
now:
1. Do you force your client to be awake always and battery usage is not mattered to you?
2. Do you have a built-in push notification in baresip to support internally?
3. or any other trade-offed solution

thanks

**Comment by juha-h** [comment]
This project is not about baresip Android app.  The correct project is https://github.com/juha-h/baresip-studio.
