### ISSUE TITLE
Missing explanation of baresip+ android app icons

### ISSUE THREAD

**Issue by rg-artcom** [baresip/baresip#2521]
Hi, if I launch baresip+ at android I see three different icons on top, but I know only the middle one (microphone). But what is the meaning of the other two icons? Would be nice to have some text below understand the GUI.

PS: If I try to add a screenshot (46 KB PNG) to the issue I just see "Something went really wrong, and we can't process that file. Try again."

**Comment by sreimers** [comment]
The baresip android app is maintained by @juha-h here: https://github.com/juha-h/baresip-studio/

**Comment by juha-h** [comment]
rg-artcom writes:

> Hi, if I launch baresip+ at android I see three different icons on
> top, but I know only the middle one (microphone). But what is the
> meaning of the other two icons? Would be nice to have some text below
> understand the GUI.

All baresip icons are Google Material Design icons, see

https://fonts.google.com/icons

The top ones in baresip+ are record, microphone, and speaker.
