### ISSUE TITLE
compiler warning

### ISSUE THREAD

**Issue by juha-h** [baresip/baresip#2533]
I noticed that Android ndk clang gave this compiler warning:
```
[ 98%] Building C object CMakeFiles/baresip.dir/src/vidutil.c.o
/usr/src/libbaresip-android/baresip/src/video.c:519:42: warning: overflow in expression; result is 1650065408 with type 'long' [-Winteger-overflow]
        const uint64_t max_delay = PKT_SIZE * 8 * 1000000L / bitrate + 1;
                                                ^
1 warning generated.
```
I'm not sure if it is correct because the const is of type uint64, not long.

**Comment by sreimers** [comment]
Can you try this PR: https://github.com/baresip/baresip/pull/2534

**Comment by juha-h** [comment]
Sebastian Reimers writes:

> Can you try this PR: https://github.com/baresip/baresip/pull/2534

With that PR the warning went away.

**Comment by sreimers** [comment]
Thanks for reporting and testing.
