### ISSUE TITLE
Buffer underrun spam when codec has new ptime and txmode is thread

### ISSUE THREAD

**Issue by Tinter** [baresip/baresip#2535]
I've discovered an issue where joining a call with a 48khz sampling rate, while the clients sample rate is set to 16khz, results in lots of messages about buffer underrun.
The spam is generated in the tx_thread here, as the initial packet size is 320, but tx->psize becomes 960.
https://github.com/baresip/baresip/blob/main/src/audio.c#L1245-L1254
As the module I wrote is sending 320 every ptime, every 2 out of 3 reads result in a buffer underrun.
The cause is that when joining the call, the codec has a ptime set, prompting baresip to recalculate the psize.
https://github.com/baresip/baresip/blob/main/src/audio.c#L1811
As you will see here, this is done on the basis of the codec's sampling rate, not the client's, but the client will resample before actually encoding and sending. This happens, even if a reset of the audio is not necessary, leading to the buffer and modules using the original sampling rate, but the sending with the new psize.

I'm not sure I have quite the necessary insight to know the fix, but either it is changing the sampling rate calculation (using tx->prm.srate), guarding the recalculation with only recalculating if the ptime is different or only using codec specific ptime when doing a reset.

**Comment by cspiel1** [comment]
Thank's for your analysis! I'll have a look on this soon.

What do you mean with "joining a call"? How are the steps to reproduce this?

**Comment by Tinter** [comment]
So I don't know too much about our set up and I was not involved in making it, but I've experienced this with a platform where we have a client connecting to an asterisk call through baresip library. One of the links I gave is to the audio_encoder_set function, which is called in call.c, for example here:
https://github.com/baresip/baresip/blob/788e3dd6a7a2895c3b3ab395cda5b20ec183bdb0/src/call.c#L328
I haven't traced it thoroughly, but I assume it's here where it happens, after the audio has been initialized with a 16k sampling rate, while the call itself uses 48k.

**Comment by cspiel1** [comment]
When the call starts (by SIP signalling): `call_stream_start()` --> `start_audio()` --> `audio_encoder_set()`. So in your case with a 16k srate. Maybe G.722 codec?

With e.g. re-INVITE it is possible that `update_audio()` is called --> `audio_encoder_set()` switching to opus.

Possible Usecase:
-  Asterisk is configured as "auto-answer" or so, which answers a call immediately in order to sends a calmdown music to the caller with G.722.
- If on the second SIP leg the callee answers the call, and wants opus codec the Asterisk sends a re-INVITE to the caller on the first leg.

I'll try to reproduce such a scenario. Maybe it is also possible with a baresip peer to peer call. There are commands in `menu` for sending re-INVITE. Not sure if there is also one for changing the codec.

**Comment by cspiel1** [comment]
I suppose that `tx->psize` should be the size of an audio packet coming directly from the audio source. The filters are applied **after** `tx->psize` is used to check if there are enough frames in the audio buffer.  In both TX modes.

So this seems to be wrong:
https://github.com/baresip/baresip/blob/1630ca0d0e8a8bf9fcbf35d2ed33770bcc1d2350/src/audio.c#L1807-L1812

**Comment by Tinter** [comment]
> Please could you attach baresip config? 

Sadly all my baresip work is for my job, so I cannot attach it
> Do you use module `auresamp`? 

I use resampling, but with a baresip version before the auresamp module, when resampling was built in. This should not make a difference as I believe the bugged code is used in the newest version.
> Which module did you wrote? Is it a codec module?

It is an audio module to write and read from named pipes. The parameters the module is initialised with are never updated, using just the initial parameters.
> 
> With this branch I am able to switch from G.722 to opus during a call with a re-INVITE. https://github.com/cspiel1/baresip/tree/menu_cmd_rmcodec
> 
> `opus` doesn't set it's `ptime` so when I try to reproduce this by a switch from G.722 to opus it does not get there:
> 
> https://github.com/baresip/baresip/blob/1630ca0d0e8a8bf9fcbf35d2ed33770bcc1d2350/src/audio.c#L1811

I'm not entirely sure on our module setup, the client I recreated the error on, with 16k sample rate, does not load any special codecs as far as I could see when I had a look, but other clients, which run 48k, do load an opus module.
> If I set opus `ptime` to 20, I see the underruns.
> 
> The question is if it is only a warning. The audio sound normal in my setup.

I'm not sure about audio integrity, I think during my testing that it sounded normal. When the read_handler is called from the module, it will print a buffer underrun on the first two invocations, but every third, the buffer is filled enough to send. So all data does seem to get sent, but it sent only every third invocation, instead of every single one. I'm not sure of the actual practical consequences to this. The debug spamming gives the impression that there is an error, even though the audio might sound fine, and the spam is distracting and annoying.


> I suppose that `tx->psize` should be the size of an audio frame coming directly from the audio source. The filters are applied **after** `tx->psize` is used to check if there are enough frames in the audio buffer. In both TX modes. And the filters contains the `auresamp` module for resampling.
> 
> So this seems to be wrong:
> 
> https://github.com/baresip/baresip/blob/1630ca0d0e8a8bf9fcbf35d2ed33770bcc1d2350/src/audio.c#L1807-L1812
> 
> Also this
> 
> https://github.com/baresip/baresip/blob/1630ca0d0e8a8bf9fcbf35d2ed33770bcc1d2350/src/audio.c#L2035-L2037
> 
> But this is correct:
> 
> https://github.com/baresip/baresip/blob/1630ca0d0e8a8bf9fcbf35d2ed33770bcc1d2350/src/audio.c#L1545-L1546

Yes, from what I've seen I agree with this. I'm not sure if the solution is just to always use the parameters (Would you ever want to do the calculation with the audio codec data instead?).

**Comment by cspiel1** [comment]
### About `ptime`
1. By default it is 20ms.
2. It can be set for each account.
3. Now you fell into the special case where the audio codec overwrites this `ptime`. Grep told me that it is used for `aptx` codec module.

### About audio source
1. By default the audio source is configured with the sample rate from the codec.
2. It is possible to force the sample rate with config setting `ausrc_srate` to a specific value. I guess like you did.

### Solution
Use resampling and compute `psize` correctly by means of the samplerate from the audio source.

I'll create a PR.

**Comment by cspiel1** [comment]
PR: https://github.com/baresip/baresip/pull/2553

**Comment by Tinter** [comment]
Sorry for the wait, but I've turned the commit into a patch, tested it out and now, with txmode as thread there is no spam. Works well as far as I can tell.
