### ISSUE TITLE
No sound at all in Baresip on Android

### ISSUE THREAD

**Issue by Mister-Teatime** [baresip/baresip#2585]
I've installed Baresip and have it set up as VoIP client directly with my provider, and as a softphone connected to my router (which then takes care of putting the VoIP connection through to the provider)

I've previously been able to have phone conversations, without a headset being connected.

I just tried with both a wired and a Bluetooth headset, and there is no sound on my end. I verified that both headsets work, and I can call with Signal alright (on the same device). I also tried calling my own landline, and the landline phone is ringing, but there's nothing on my own device.... 

I also went through the settings and found that the "default call volume" was set to "none", and updated it to 7, just to make sure, but it seems to make no difference...

I'm using a Pocophone F1 running LineageOS 19 (Android 12) with MicroG.

**Comment by juha-h** [comment]
Use https://github.com/juha-h/baresip-studio project to report baresip Android app related issues.  What you experience is most likely caused by bug in libre that is not fixed.
