### ISSUE TITLE
rtp_timeout causes lots of debug messages

### ISSUE THREAD

**Issue by juha-h** [baresip/baresip#2586]
When `rtp_timeout` is set, I started to get lots of these kind of debug messages:
```
05-19 21:10:01.828 10359 10463 D Baresip+ Lib: stream: last "audio" RTP packet: 0 milliseconds
05-19 21:10:02.828 10359 10463 D Baresip+ Lib: stream: last "audio" RTP packet: 4 milliseconds
05-19 21:10:03.828 10359 10463 D Baresip+ Lib: stream: last "audio" RTP packet: 4 milliseconds
05-19 21:10:04.830 10359 10463 D Baresip+ Lib: stream: last "audio" RTP packet: 6 milliseconds
```
Is this `stream.c/check_rtp_handler()` debug statement really needed or could it be removed?
```
		debug("stream: last \"%s\" RTP packet: %d milliseconds\n",
		      sdp_media_name(strm->sdp), diff_ms);
```

**Comment by sreimers** [comment]
It has been useful for me in the past, but I think we can limit the number of times it is called: https://github.com/baresip/baresip/pull/2587

**Comment by juha-h** [comment]
@sreimers I tried with https://github.com/baresip/baresip/pull/2587 and it greatly reduced the debug messages.  Go ahead and merge the PR.

**Comment by juha-h** [comment]
Solved by https://github.com/baresip/baresip/pull/2587.
