### ISSUE TITLE
session closed: Bad message [74]

### ISSUE THREAD

**Issue by alexlansovich** [baresip/baresip#2723]
After upgrade from 3.0.0 to 3.4 or latest i got error
sip:1001@vpbx2.xxx.net;transport=udp: session closed: Bad message [74]
I making call from console - d1001@vpbx2.xxx.net;transport=udp
On 3.0.0 dialing is working.
SIP Server based on Flexisip/2.2.4 (sofia-sip-nta/2.0)
------
Account config is
<sip:1003@vpbx2.xxxx.net:5060>;auth_pass=alexlans;answermode=auto;sip_autoanswer=yes

Config is

poll_method		epoll		# poll, select, epoll ..
sip_listen		0.0.0.0:5060
sip_cafile		/etc/ssl/certs/ca-certificates.crt
sip_trans_def		udp
sip_tos			160
call_local_timeout	120
call_max_calls		4
call_hold_other_calls	yes
audio_player		alsa,default
audio_source		alsa,default
audio_alert		alsa,default
audio_level		no
ausrc_format		s16		# s16, float, ..
auplay_format		s16		# s16, float, ..
auenc_format		s16		# s16, float, ..
audec_format		s16		# s16, float, ..
audio_buffer		20-160		# ms
audio_buffer_mode	fixed		# fixed, adaptive
audio_silence		-35.0		# in [dB]
audio_telev_pt		101		# payload type for telephone-event
video_source		v4l2,/dev/video0
video_size		640x480
video_bitrate		5000000
video_fps		30.00
video_fullscreen	no
videnc_format		yuv420p
rtp_tos			184
rtp_video_tos		136
rtp_ports		10000-20000
jitter_buffer_type	fixed		# off, fixed, adaptive
jitter_buffer_delay	5-10		# frames
rtp_stats		no
module_path		/usr/local/lib/baresip/modules
module			stdio.so
module			cons.so
module			g711.so
module			auconv.so
module			auresamp.so
module			alsa.so
module			avcodec.so
module			v4l2.so
module			uuid.so
module			stun.so
module			turn.so
module			ice.so
module_app		account.so
module_app		contact.so
module_app		debug_cmd.so
module_app		menu.so
module_app		netroam.so
cons_listen		0.0.0.0:5555 # cons - Console UI UDP/TCP sockets
http_listen		0.0.0.0:8000 # httpd - HTTP Server
ctrl_tcp_listen		0.0.0.0:4444 # ctrl_tcp - TCP interface JSON
evdev_device		/dev/input/event0
opus_bitrate		28000 # 6000-510000
vumeter_stderr		yes
video_selfview		window # {window,pip}

**Comment by sreimers** [comment]
Can you provide the full log (with `baresip -v -s`).

**Comment by alexlansovich** [comment]
I have load a gist https://gist.github.com/alexlansovich/cd5f71b021a8b2325b9d4cf79f1df47d

**Comment by alfredh** [comment]
Please make a clean install of latest version from Git HEAD, remove the old config files
and start from a fresh install.

If there are problems, please report all require information as stated here:

https://github.com/baresip/baresip/wiki/Guidelines-for-reporting-Issues


Br,
Alfred
