### ISSUE TITLE
mwi re-enters mwi_subscribe infinitely & w/no delay on PBX 404 response to SUBSCRIBE

### ISSUE THREAD

**Issue by jimmbelll** [baresip/baresip#2726]
With mwi enabled, baresip runs away with continuous messages:

> mwi: subscribing to messages for sip:...

The SIP SUBSCRIBE request goes out and gets a 404 "No voicemail service" response from the PBX. baresip immediately puts the next SUBSCRIBE request out, reentering mwi_subscribe from ua_event_handler() infinitely. (User input is locked out.)

baresip-3.4.0, built from git clone.  PBX: kamailio 5.7.1 built from git clone.

Glad to try fix attempts in this environment that causes the crash consistently.

**Comment by juha-h** [comment]
There may be bug in baresip, but also your PBX is badly broken.  SUBSCRIBE message should always  return 200 OK followed by NOTIFY.

**Comment by jimmbelll** [comment]
> There may be bug in baresip, but also your PBX is badly broken. SUBSCRIBE message should always return 200 OK followed by NOTIFY.

But aren't [Non-200-class responses](https://datatracker.ietf.org/doc/html/rfc6665#section-4.1.2.1) to be expected?

**Comment by juha-h** [comment]
jimmbelll writes:

> But aren't [Non-200-class responses](https://datatracker.ietf.org/doc/html/rfc6665#section-4.1.2.1) to be expected?

Yes, if SUBSCRIBE target does not exist.  From your description, I got
the impression that the target does exists, but there are no messages.

**Comment by jimmbelll** [comment]
> Glad to try fix attempts in this environment that causes the crash consistently.

I tried a couple trivial changes to see if there was an easy fix, but each one broke the mechanism completely.

It's odd that a 404 doesn't seem to make its way to `ua_event_handler()`, since the `ev` param is `UA_EVENT_REGISTER_OK`. But I don't see an appropriate failure code in `ua_event` either.  I wouldn't expect `sipevent_subscribe()` to return an error code since a failure response would usually not come back that quickly. (Or does it block by design?)

Seems it should retry periodically on failure.

**Comment by alfredh** [comment]
Please include the full information as listed here:

https://github.com/baresip/baresip/wiki/Guidelines-for-reporting-Issues

That includes config files, SIP trace, Debug log etc.


Br,
Alfred

**Comment by alfredh** [comment]
closing due to no response.

Please create a new Issue and provide all info if you want to help with this.
