### ISSUE TITLE
100rel yes/no issue

### ISSUE THREAD

**Issue by juha-h** [baresip/baresip#2727]
While testing 100rel/PRAC with parallel forked calls, I noticed that when I start baresip with `;100rel=yes` in account config and then give menu command
```
/100rel no
```
INVITE does not contain `PRAC` in Allow header, but still contains `100rel` in Supported header:
```
INVITE sip:bar@test.tutpro.com SIP/2.0
...
Allow: INVITE,ACK,BYE,CANCEL,OPTIONS,NOTIFY,SUBSCRIBE,INFO,MESSAGE,UPDATE,REFER
Supported: gruu,path,outbound,replaces,100rel,norefersub
```
If I start baresip with `;100rel=no`, there is no  `100rel` in Supported header.

It looks like a bug to me that `100rel` is still in Supported header after `/100 rel no` command.

**Comment by juha-h** [comment]
I studied the code and noticed that API function  `account_set_rel100_mode` only sets `acc->rel100_mode` to `REL100_DISABLED` but does not remove "100rel" from `ua->extensionv`.

**Comment by juha-h** [comment]
I tried to solve the issue by calling `ua_update_account()` after calling `account_set_rel100_mode(account, REL100_DISABLED)`.  That removed 100rel from Supported header, but then also `norefersub` disappeared which has nothing to do with this.

Before `account_set_rel100_mode(account, REL100_DISABLED); ua_update_account(ua)`:
```

Allow: INVITE,ACK,BYE,CANCEL,OPTIONS,NOTIFY,SUBSCRIBE,INFO,MESSAGE,UPDATE,PRACK,REFER
Supported: gruu,path,outbound,replaces,100rel,norefersub
```
After:
```
Allow: INVITE,ACK,BYE,CANCEL,OPTIONS,NOTIFY,SUBSCRIBE,INFO,MESSAGE,UPDATE,REFER
Supported: gruu,path,outbound,replaces
```

**Comment by juha-h** [comment]
@cspiel1 Why didn't PR https://github.com/baresip/baresip/pull/2115 call `add_extension(ua, "norefersub");` in `create_register_clients()` function, where all other extensions are added?  Instead it added the extension in `ua_alloc()` and missed it from `ua_update_account()`.

**Comment by cspiel1** [comment]
I will discuss this with @maximilianfridrich

**Comment by maximilianfridrich** [comment]
Should be fixed by the linked PR.

**Comment by juha-h** [comment]
Are you sure that the PR also solved the missing norefersub issue?  I haven't tested yet, but I have doubts.   I my opinion, ua_add_extension(ua, "norefersub"); should be moved from ua_alloc() to create_register_clients().  Then it would be call always when needed.

**Comment by maximilianfridrich** [comment]
@juha-h That was a misunderstanding. I only focused on the 100rel issue since you had an open PR for the norefersub part. I just opened one to fix the `norefersub`: #2734.

**Comment by juha-h** [comment]
I did the same. See https://github.com/baresip/baresip/pull/2735.

**Comment by maximilianfridrich** [comment]
I will close mine then. Let's just try to not close both of them simultaneously :smile:

**Comment by juha-h** [comment]
OK.

**Comment by juha-h** [comment]
By the way, I consider using ua_update account() a cleaner solution to the original issue that exposing and using ua_add/remove_extension() API calls in menu module  The latter are low level SIP protocol stuff that app writer should not need to be aware off. Perhaps @cspiel1 or @alfredh could give their opinion.

**Comment by juha-h** [comment]
So this:
```
                err = account_set_rel100_mode(ua_account(ua), mode);
                err |= ua_update_account(ua);
                if (err)
			goto out;
```
instead of this:
```
		err = account_set_rel100_mode(ua_account(ua), mode);
		if (err)
			goto out;

		if (mode == REL100_DISABLED)
			ua_remove_extension(ua, "100rel");
		else
			ua_add_extension(ua, "100rel");
```
