### ISSUE TITLE
Can not recieve Inbound Calls (Line is disconnected or unavailable)

### ISSUE THREAD

**Issue by Gigarange** [baresip/baresip#2744]
Hey i've been trying to get this to work for awhile now and i've run into a impasse. I'm able to do outbound calls to other numbers but can't receive any calls. I have used Linphone which allowed for both inbound and outbound calls, so i must be missing something in my baresip config.

OS: Android
Baresip+ Version: 44.2.0
Baresip Version: 57.2.0

I have the baresip apps connected to a turn server  as i thought that is what could have been missing, but didn't seem to change anything.

I'm not really sure where the logs would be on Android or how to get them.

**Comment by Gigarange** [comment]
Thank you for your support :)

**Comment by sreimers** [comment]
For android support see: https://github.com/juha-h/baresip-studio

**Comment by juha-h** [comment]
Gigarange,

This is wrong project.  Use https://github.com/juha-h/baresip-studio
and produce logs as described in
https://github.com/juha-h/baresip-studio/wiki/Debugging before posting
the issue.
