### ISSUE TITLE
Address family not supported by protocol

### ISSUE THREAD

**Issue by 400thecat** [baresip/baresip#2745]
I have installed baresip 1.0.0-4 on Debian 12.

regardlesss whether I start it as "baresip -4" or just as "baresip", I get these errors:

net: dns_init: Address family not supported by protocol
ua: network init failed: Address family not supported by protocol
main: baresip init failed (Address family not supported by protocol)
ua: stop all (forced=1)

when I run baresip from strace, I see its trying ipv6 socket, even though I have clearly specified "-4". Does the option -4 have no effect ?

socket(AF_INET6, SOCK_DGRAM, IPPROTO_UDP) = -1 EAFNOSUPPORT (Address family not supported by protocol)

**Comment by sreimers** [comment]
baresip 1.0.0 is quite old, we support only latest release here. Please try to compile the stable version:

https://github.com/baresip/baresip/wiki/Install:-Stable-Release

**Comment by 400thecat** [comment]
what kind of project is this? Do you expect all users to be on rolling release distros, or recompiling your package every week?

I am using the latest package available in Debian.

I have provided clear description of the problem (and can provide full strace if needed). Surely you would know if this bug has been fixed in later versions.

Recompiling package is not trivial for everybody, and can take considerable time. 
All that only to fond out that the bug is not fixed ?

**Comment by sreimers** [comment]
Ask the Debian people why baresip is no longer being updated. And if you file a bug report upstream, it's normal that we ask you to reproduce it with the current version. If it's a bug, you also need to compile it for testing/fixing, or ask the Debian people to backport a patch.

> Surely you would know if this bug has been fixed in later releases.

baresip 1.0.0 release is 3 years old and there are hundreds of pull requests/commits/fixes. I know we have done a lot of IPv6 and networking stuff in the meantime.

You can also try the docker image https://github.com/baresip/docker
