### ISSUE TITLE
Mac os Ventura Version 13.0.1 audio=0/0 (bit/s)

### ISSUE THREAD

**Issue by aarizhov** [baresip/baresip#2750]
I use brew for install baresip on my mac mini with M1 

- brew install baresip

installed version 3.5.1

I have issue, can't here voice in both side:

- "audio=0/0 (bit/s)" 

My log from terminal:

aors_590994@voice.<testdomain>.com: selected for request
call uri: sip:<phone>@voice.<testdomain>.com
call: connecting to 'sip:<phone>@voice..<testdomain>.com'..
call id: f35af2d763293b32
call: SIP Progress: 100 trying -- your call is important to us (/)
call: SIP Progress: 183 Session Progress (application/sdp)
aors_590994@voice.<testdomain>.com: Call in-progress: sip:<phone>@voice.<testdomain>.com
stream: update 'audio'
call: SIP Progress: 183 Session Progress (application/sdp)
aors_590994@voice.<testdomain>.com: Call in-progress: sip:<phone>@voice..<testdomain>.com
stream: update 'audio'
call: SIP Progress: 180 Ringing (application/sdp)
aors_590994@voice.<testdomain>.com: Call in-progress: sip:<phone>@voice.<testdomain>.com
stream: update 'audio'
aors_590994@voice.<testdomain>.com: Call answered: sip:<phone>@voice.<testdomain>.com
stream: update 'audio'
aors_590994@voice.<testdomain>.com: Call established: sip:<phone>@voice.<testdomain>.com
[0:00:19] audio=0/0 (bit/s)    

- My account config:

<sip:aors_590994@voice.<testdomain>.com>;auth_pass=<password>;outbound="sip:voice.<testdomain>.com;transport=wss;opus/48000/2,pcma"

this configuration is normal works from web by this web tool https://tryit.jssip.net/
but for some reason, sound not working for baresip on Mac OS version 

Thanks,

**Comment by alfredh** [comment]
Can you please include the full info as listed here:

https://github.com/baresip/baresip/wiki/Guidelines-for-reporting-Issues


Br,
Alfred

**Comment by alfredh** [comment]
Closing due to lack of response. Please create a new ticket and provide all info if you want help.
