### ISSUE TITLE
install TARGETS given no BUNDLE DESTINATION for MACOSX_BUNDLE executable

### ISSUE THREAD

**Issue by sdskowl** [baresip/baresip#2756]
macos ventura 13.3.1 build for ios simulator. What should I add to fix the error? What does "baresip_exe" mean? 

-- [DEFAULTS] Using explicit named language support! E.g., enable_language(CXX) is needed in the project files.
-- [DEFAULTS] Using the default min-version since DEPLOYMENT_TARGET not provided!
-- Configuring iphonesimulator build for platform: SIMULATOR64, architecture(s): x86_64
-- Using SDK: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator16.4.sdk
-- Using C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang
-- Using CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
-- Using libtool: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool
-- Using install name tool: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/install_name_tool
-- Autoconf target triple: x86_64-apple-ios11.0-simulator
-- Using minimum deployment version: 11.0 (SDK version: 16.4)
-- Merging integrated CMake 3.14+ iOS,tvOS,watchOS,macOS toolchain(s) with this toolchain!
-- CMake version: 3.27.6
-- Using a data_ptr size of: 8
-- Bitcode: Enabled
-- ARC: Enabled
-- Hiding symbols: Disabled
-- The C compiler identification is AppleClang 14.0.3.14030022
-- The CXX compiler identification is AppleClang 14.0.3.14030022
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found RE: /Users/alexmartyniuk/StudioProjects/baresipnew/re  
-- Looking for backtrace
-- Looking for backtrace - found
-- backtrace facility detected in default set of libraries
-- Found Backtrace: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator16.4.sdk/usr/include  
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
-- Found Threads: TRUE  
-- Found ZLIB: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator16.4.sdk/usr/lib/libz.tbd (found version "1.2.11")  
-- Found OpenSSL: /Users/alexmartyniuk/StudioProjects/baresipnew/openssl/lib/libcrypto-iOS-Sim.a (found suitable version "1.1.1v", minimum required is "1.1.1")  
-- Setting build type to 'Debug' as none was specified.
-- Looking for arc4random
-- Looking for arc4random - found
-- Looking for syslog.h
-- Looking for syslog.h - found
-- Looking for getopt.h
-- Looking for getopt.h - found
-- Looking for unistd.h
-- Looking for unistd.h - found
-- Looking for res_ninit
-- Looking for res_ninit - found
-- Looking for thrd_create
-- Looking for thrd_create - not found
-- Looking for accept4
-- Looking for accept4 - not found
-- Looking for epoll_create
-- Looking for epoll_create - not found
-- Looking for kqueue
-- Looking for kqueue - found
-- Looking for sys/prctl.h
-- Looking for sys/prctl.h - not found
-- Checking for one of the modules 'fdk-aac'
-- Could NOT find AAC (missing: AAC_LIBRARY AAC_INCLUDE_DIR) 
-- Could NOT find ALSA (missing: ALSA_LIBRARY ALSA_INCLUDE_DIR) 
-- Could NOT find AMR (missing: AMR_FOUND) 
-- Found PkgConfig: /usr/local/bin/pkg-config (found version "0.29.2") 
-- Checking for one of the modules 'aptx'
-- Could NOT find APTX (missing: APTX_LIBRARY APTX_INCLUDE_DIR) 
-- Could NOT find AOM (missing: AOM_LIBRARY AOM_INCLUDE_DIR) 
-- Checking for one of the modules 'codec2'
-- Could NOT find CODEC2 (missing: CODEC2_LIBRARY CODEC2_INCLUDE_DIR) 
-- Could NOT find DIRECTFB (missing: DIRECTFB_LIBRARIES DIRECTFB_INCLUDE_DIR) 
-- Could NOT find FFMPEG (missing: FFMPEG_AVCODEC_LIBRARIES FFMPEG_AVCODEC_INCLUDE_DIRS avcodec avfilter avformat swscale swresample avdevice avutil) 
-- Checking for one of the modules 'g7221'
-- Could NOT find G7221 (missing: G7221_LIBRARY G7221_INCLUDE_DIR) 
-- Checking for module 'gio-unix-2.0'
--   Found gio-unix-2.0, version 2.78.0
-- Found GIO: /usr/local/Cellar/glib/2.78.0/lib/libglib-2.0.dylib  
-- Could NOT find GST (missing: GST_FOUND) 
-- Checking for module 'gtk+-3.0'
--   No package 'gtk+-3.0' found
-- Could NOT find GTK3 (missing: GTK3_LIBRARIES GTK3_CFLAGS GTK3_CFLAGS_OTHER) 
-- Could NOT find GZRTP (missing: GZRTP_LIBRARY GZRTP_INCLUDE_DIR) 
-- Checking for one of the modules 'jack'
-- Could NOT find JACK (missing: JACK_LIBRARY JACK_INCLUDE_DIR) 
-- Could NOT find MOSQUITTO (missing: MOSQUITTO_LIBRARY MOSQUITTO_INCLUDE_DIR) 
-- libmosquitto include dir: MOSQUITTO_INCLUDE_DIR-NOTFOUND
-- libmosquitto: MOSQUITTO_LIBRARY-NOTFOUND
-- Checking for one of the modules 'twolame'
-- Checking for one of the modules 'mpg123'
-- Checking for one of the modules 'speexdsp'
-- Could NOT find MPA (missing: MPA_LIBRARIES MPA_INCLUDE_DIRS) 
-- Could NOT find OPENSLES (missing: OPENSLES_LIBRARY OPENSLES_INCLUDE_DIR) 
-- Checking for one of the modules 'opus'
-- Could NOT find OPUS (missing: OPUS_LIBRARY OPUS_INCLUDE_DIR) 
-- Could NOT find PNG (missing: PNG_LIBRARY) 
-- Checking for one of the modules 'portaudio'
-- Could NOT find PORTAUDIO (missing: PORTAUDIO_LIBRARY PORTAUDIO_INCLUDE_DIR) 
-- Checking for one of the modules 'pulse'
-- Could NOT find PULSE (missing: PULSE_LIBRARY PULSE_INCLUDE_DIR) 
-- Checking for one of the modules 'libpipewire-0.3'
-- Could NOT find PIPEWIRE (missing: PIPEWIRE_INCLUDE_DIRS PIPEWIRE_LIBRARIES) 
-- Checking for one of the modules 'sdl2'
-- Could NOT find SDL (missing: SDL_LIBRARY SDL_INCLUDE_DIR) 
-- Checking for module 'sndfile'
--   No package 'sndfile' found
-- Could NOT find SNDFILE (missing: SNDFILE_INCLUDE_DIR SNDFILE_LIBRARIES) 
-- Could NOT find SPANDSP (missing: SPANDSP_LIBRARY SPANDSP_INCLUDE_DIR) 
-- Checking for module 'libv4l2'
--   No package 'libv4l2' found
-- Could NOT find V4L2 (missing: V4L2_LIBRARY V4L2_INCLUDE_DIR) 
-- Could NOT find VPX (missing: VPX_LIBRARY VPX_INCLUDE_DIR) 
-- Could NOT find WEBRTC_AEC (missing: WEBRTC_AEC_LIBRARY WEBRTC_AEC_INCLUDE_DIR) 
-- Could NOT find WEBRTC_AECM (missing: WEBRTC_AECM_LIBRARY WEBRTC_AECM_INCLUDE_DIR) 
-- Could NOT find X11 (missing: X11_X11_LIB) 
CMake Error at CMakeLists.txt:347 (install):
  install TARGETS given no BUNDLE DESTINATION for MACOSX_BUNDLE executable
  target "baresip_exe".

-- Configuring incomplete, errors occurred!
make: Makefile: No such file or directory
make: *** No rule to make target `Makefile'.  Stop.

**Comment by alfredh** [comment]
Please include the full info as listed here:

https://github.com/baresip/baresip/wiki/Guidelines-for-reporting-Issues

**Comment by sdskowl** [comment]
Nevermind, I rewrote CmakeLists.txt and it works for me.
