### ISSUE TITLE
debian version in debian/changelog has not been updated 

### ISSUE THREAD

**Issue by juha-h** [baresip/baresip#2773]
Tag v3.6.0 has old version (3.5.1) in debian/changelog. Should a new tag v3.6.1 be created where the version is upgraded or something else?

**Comment by alfredh** [comment]
I made the release, but forgot to update the debian file ...

**Comment by alfredh** [comment]
is there any interest in maintaining these `debian` files ?

The changelog update was missing many times in the past:

https://github.com/baresip/baresip/blob/main/debian/changelog

FYI, The Debian project has their own set of `debian` files and does not use these...

**Comment by juha-h** [comment]
Alfred E. Heggestad writes:

> is there any interest in maintaining these `debian` files ?

I could maintain Debian changelog.  Just tell me after each release,
what is the version number of the next and I'll update it to main right
away so that it will not be forgotten.

**Comment by sreimers** [comment]
We can also migrate the debian files to a extra repo and release deb packages separately.

**Comment by juha-h** [comment]
Sebastian Reimers writes:

> I think it has to be part of the release and we have a release
> checklist to prevent such issues: 
> 
> https://github.com/baresip/re/wiki/Release-Checklist

OK, so debian/changelog cannot be updated beforehand.

How about bug fix releases (the last digit of the version number)?
Checklist does not mention them.  Now, for example, when the re-INVITE
ACK has been fixed, there should be new release v3.6.1.  Wait until Nov
22 would be far too long.

**Comment by juha-h** [comment]
Sebastian Reimers writes:

> We can also migrate the debian files to a extra repo and release deb
> packages separately.

Does not sound good if it complicates Debian package build process.

**Comment by sreimers** [comment]
> How about bug fix releases (the last digit of the version number)? Checklist does not mention them. Now, for example, when the re-INVITE ACK has been fixed, there should be new release v3.6.1. Wait until Nov 22 would be far too long.

Yes, sure we should make a extra branch from release tag (since we have already unrelated changes in main). I can take care of this extra release, if ready.

**Comment by juha-h** [comment]
Sebastian Reimers writes:

> Yes, sure we should make a extra branch from release tag (since we
> have already unrelated changes in main). I can take care of this extra
> release, if ready.

In my opinion, monthly releases should be branches rather than tags like
it is done in Kamailio and rtpengine projects.  Then bug fixes could be
backported to the branch (e.g. v3.6) and new tags created from it
(e.g. v3.6.1 and v3.6.2).  With that system we might even have baresip
LTS releases.

**Comment by sreimers** [comment]
It's easy to make a branch if necessary, regular release branches are rarely needed for baresip releases.

**Comment by alfredh** [comment]
Have you concluded on something here ?

Personally I dont need the "debian" folder so either someone has to step up and maintain it,
or it will be deleted.

**Comment by juha-h** [comment]
Alfred E. Heggestad writes:

> Have you concluded on something here ?
> 
> Personally I dont need the "debian" folder so either someone has to
> step up and maintain it, or it will be deleted.

I offered to maintain it, but the offer was needed.

**Comment by juha-h** [comment]
In my opinion we should release 3.6.1 now since two bugs have already been fixed since 3.6.0.

**Comment by sreimers** [comment]
> Personally I dont need the "debian" folder so either someone has to step up and maintain it,
> or it will be deleted.

If maintenance is to be done outside of a release, it needs to be a separate repo, like we do for Docker releases, I think.

**Comment by juha-h** [comment]
Sebastian Reimers writes:

> If maintenance is to be done outside of a release, it needs to be a
> separate repo, like we do for Docker releases, I think.

I prefer inside the release or not at all.  If outside, whoever
maintains Debian baresip package can do it wherever he/she wants.

**Comment by alfredh** [comment]
Juha: thanks for volunteering 

could you please add one
entry in debian changelog ?

**Comment by juha-h** [comment]
Alfred E. Heggestad writes:

> could you please add one
> entry in debian changelog ?

Created PR for the new entry.

**Comment by alfredh** [comment]
fixed in 198c37b7d6deeccc8c9e48f326259f9e8930faba
