### ISSUE TITLE
GTK Module Status Icon

### ISSUE THREAD

**Issue by richard-gravy** [baresip/baresip#2774]
Hello,
Just re issue #2295 , I am experiencing a similar problem on my desktop (Fedora Sway 38), which is Wayland-based, though it does have a status icon area in the top-right of the screen, supplied by waybar.  
So I ran baresip through gdb and got a backtrace from the critical message:-
```#0  g_logv (log_domain=0x7ffff4638086 "Gtk", log_level=G_LOG_LEVEL_CRITICAL, format=<optimized out>, args=args@entry=0x7fffee67c760) at ../glib/gmessages.c:1422  
#1  0x00007fffef543b33 in g_log (log_domain=<optimized out>, log_level=<optimized out>, format=<optimized out>) at ../glib/gmessages.c:1460  
#2  0x00007ffff45670af in gtk_widget_get_scale_factor (widget=<optimized out>) at ../gtk/gtkwidget.c:10972  
#3  0x00007ffff462b2f3 in gtk_status_icon_update_image.isra.0 (status_icon=<optimized out>) at ../gtk/deprecated/gtkstatusicon.c:1409  
#4  0x00007ffff49f28f7 in object_set_property (object=object@entry=0x7fffdc0d2600, pspec=0x7fffdc0f8af0, value=0x7fffee67cbd0, nqueue=nqueue@entry=0x0, 
    user_specified=user_specified@entry=1) at ../gobject/gobject.c:1812  
#5  0x00007ffff49f31c3 in g_object_new_internal (class=class@entry=0x7fffdc129650, params=params@entry=0x7fffee67cad0, n_params=n_params@entry=1) at ../gobject/gobject.c:2304  
#6  0x00007ffff49f4e43 in g_object_new_valist (object_type=<optimized out>, first_property_name=first_property_name@entry=0x7ffff46b6def "icon-name", 
    var_args=var_args@entry=0x7fffee67cda0) at ../gobject/gobject.c:2585  
#7  0x00007ffff49f558f in g_object_new (object_type=<optimized out>, first_property_name=first_property_name@entry=0x7ffff46b6def "icon-name") at ../gobject/gobject.c:2058  
#8  0x00007ffff45c7be0 in gtk_status_icon_new_from_icon_name (icon_name=icon_name@entry=0x7ffff4a46051 "call-start") at ../gtk/deprecated/gtkstatusicon.c:1301  
#9  0x00007ffff4a426b4 in gtk_thread (arg=0x7ffff4a49140 <mod_obj>) at /usr/src/debug/baresip-3.5.1-1.fc38.x86_64/modules/gtk/gtk_mod.c:980
```
Based on this, I think it might be a good idea to add a check after modules/gtk/gtk_mod.c:980 to validate `mod->status_icon` and to abort if it's NULL.  
Inform the user that "required notification area support is missing" or something like that.  
Likely to become a more pressing issue as time goes on, but at least it indicates that you are catching the problem. :slightly_smiling_face:

**Comment by mbattista** [comment]
Hi,

thanks for that bug report.
I will take a look at this and will fix it.

The status icon will be a big issue, since it will be dropped in GTK4.
I had a fork with a redesign of the status icon into a small window, but it is just not the same with the tidiness and the minimal solution a status icon offers.

**Comment by alfredh** [comment]
Are you able to add some nice screen shots ?

Adding the log would help us to better understand the problem ...
please look here:

https://github.com/baresip/baresip/wiki/Guidelines-for-reporting-Issues

**Comment by mbattista** [comment]
Sorry I did not find time to create a pull request to catch this.
I will work on this on this Weekend.

**Comment by alfredh** [comment]
hi @richard-gravy are you able to add some screenshots of your problem ?
