### ISSUE TITLE
baresip -d bork the terminal

### ISSUE THREAD

**Issue by gmaruzz** [baresip/baresip#2781]
baresip v3.5.1 compiled from releases

If you execute 
<pre>
$ baresip -d
</pre>
in a terminal, the terminal is left in an inconsistent state, you must then blindly type
<pre>
$ reset
</pre>
to be able to use that terminal again

**Comment by alfredh** [comment]
You have reported 2 issues, are they they overlapping ?

Please include more information as indicated here:

https://github.com/baresip/baresip/wiki/Guidelines-for-reporting-Issues

**Comment by gmaruzz** [comment]
Hello!

Thanks for your reply, and for baresip!

I don't think the two issues have a common cause or are overlapping.

The terminal is left inconsistent even if baresip exit correctly, eg in any case

Seems to me I reported all relevant info, please let me know what can I add.

**Comment by alfredh** [comment]
We need to see the console log and your config file, in order to debug the problem.


Have you considered to use `start-stop-daemon` program to start baresip?

https://man7.org/linux/man-pages/man8/start-stop-daemon.8.html

**Comment by gmaruzz** [comment]
As you asked

CONSOLE (last line is repeated ENTERs, the console is borked up to a "reset", and you cannot see what you type):
<pre>
gmaruzz@t590:~  $ baresip -a SIP.js -d -f /home/gmaruzz/baresipconf
baresip v3.5.1 Copyright (C) 2010 - 2023 Alfred E. Heggestad et al.
Local network addresses:
    bridge0:  192.168.1.61
        wg0:  10.20.30.2
    docker0:  172.17.0.1
    bridge0:  fe80::5c9e:f37b:d4d4:8dd
 vethuux8WP:  fe80::fc7f:81ff:fe86:59ba
 vethhEUuJd:  fe80::fc0d:9aff:feb8:4fd
ua: adding SIP CA file: /etc/ssl/certs/ca-certificates.crt
ua: adding SIP CA path: 
aucodec: PCMU/8000/1
aucodec: PCMA/8000/1
ausrc: alsa
auplay: alsa
vidcodec: H264
vidcodec: H264
vidcodec: H265
avcodec: using H.264 encoder 'libx264' -- libx264 H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10
avcodec: using H.264 decoder 'h264' -- H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10
avcodec: using H.265 encoder 'libx265' -- libx265 H.265 / HEVC
avcodec: using H.265 decoder 'hevc' -- HEVC (High Efficiency Video Coding)
vidcodec: VP8
vidsrc: v4l2
vidsrc: fakevideo
vidisp: fakevideo
medianat: stun
medianat: turn
medianat: ice
mediaenc: srtp
mediaenc: srtp-mand
mediaenc: srtp-mandf
dtls_srtp: use prime256v1 for elliptic curve cryptography
mediaenc: dtls_srtp
1053@panictest: Using medianat 'ice'
1053@panictest: Using media encryption 'dtls_srtp'
Populated 1 account
Populated 3 contacts
Populated 2 audio codecs
Populated 0 audio filters
Populated 4 video codecs
Populated 0 video filters
gmaruzz@t590:~  $ gmaruzz@t590:~  $ gmaruzz@t590:~  $ gmaruzz@t590:~  $ gmaruzz@t590:~  $ gmaruzz@t590:~  $ gmaruzz@t590:~  $ 
</pre>

CONFIG
[config.txt](https://github.com/baresip/baresip/files/13248875/config.txt)

config file in attachment as config.txt

=================

**Comment by alfredh** [comment]
Can you please try to not load `stdio.so` ?

**Comment by gmaruzz** [comment]
changed config not to load stdio

result is same:
<pre>
baresip -a SIP.js -d -f /home/gmaruzz/baresipconf
baresip v3.5.1 Copyright (C) 2010 - 2023 Alfred E. Heggestad et al.
Local network addresses:
    bridge0:  192.168.1.61
        wg0:  10.20.30.2
    docker0:  172.17.0.1
    bridge0:  fe80::5c9e:f37b:d4d4:8dd
 vethuux8WP:  fe80::fc7f:81ff:fe86:59ba
 vethhEUuJd:  fe80::fc0d:9aff:feb8:4fd
ua: adding SIP CA file: /etc/ssl/certs/ca-certificates.crt
ua: adding SIP CA path:
aucodec: PCMU/8000/1
aucodec: PCMA/8000/1
ausrc: alsa
auplay: alsa
vidcodec: H264
vidcodec: H264
vidcodec: H265
avcodec: using H.264 encoder 'libx264' -- libx264 H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10
avcodec: using H.264 decoder 'h264' -- H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10
avcodec: using H.265 encoder 'libx265' -- libx265 H.265 / HEVC
avcodec: using H.265 decoder 'hevc' -- HEVC (High Efficiency Video Coding)
vidcodec: VP8
vidsrc: v4l2
vidsrc: fakevideo
vidisp: fakevideo
medianat: stun
medianat: turn
medianat: ice
mediaenc: srtp
mediaenc: srtp-mand
mediaenc: srtp-mandf
dtls_srtp: use prime256v1 for elliptic curve cryptography
mediaenc: dtls_srtp
1053@panictest: Using medianat 'ice'
1053@panictest: Using media encryption 'dtls_srtp'
Populated 1 account
Populated 3 contacts
Populated 2 audio codecs
Populated 0 audio filters
Populated 4 video codecs
Populated 0 video filters
gmaruzz@t590:~  $ gmaruzz@t590:~  $ gmaruzz@t590:~  $ gmaruzz@t590:~  $ gmaruzz@t590:~  $ gmaruzz@t590:~  $ gmaruzz@t590:~  $ 

</pre>

**Comment by sreimers** [comment]
Can you try:

```shell
baresip -a SIP.js -d -f /home/gmaruzz/baresipconf 2>err.log 1>out.log
```

And upload both logs here.

**Comment by alfredh** [comment]
I tested on Debian 12 with daemon mode and no stdio.so module, and the terminal is not b0rked.


Please note that the `stdio.so` module disables character echo mode:

https://github.com/baresip/baresip/blob/main/modules/stdio/stdio.c#L95

**Comment by gmaruzz** [comment]
Hello Alfred,

thanks a lot for your answer.

please find attached the  two files (out.log is empty)
[err.log](https://github.com/baresip/baresip/files/13252309/err.log)
[out.log](https://github.com/baresip/baresip/files/13252310/out.log)


the bizarre thing is that I have not loaded stdio.so, but character echo mode was disabled anyway

but if I pressed ENTER, it was going next line
also, if I give commands, it gave me the result of commands (not the command)

I executed baresip, then I gave the command "ls", then the command "reset", 
in another teminal, I gave the command: "echo "/quit" | netcat -N 127.0.0.1 5555"
<pre>
gmaruzz@t590:~/alfred  $ baresip -a SIP.js -d -f /home/gmaruzz/baresipconf 2>err.log 1>out.log
gmaruzz@t590:~/alfred  $ err.log  out.log
gmaruzz@t590:~/alfred  $
</pre>

**Comment by gmaruzz** [comment]
I attach the new config as config2.txt, without stdio
[config2.txt](https://github.com/baresip/baresip/files/13252328/config2.txt)

**Comment by alfredh** [comment]
I have tested again with Debian and macOS. When the `stdio.so` module is NOT loaded, the terminal
is working just fine and it is not broken.

Can you please try again on 2-3 different platforms or terminals and see if the result is consistent ?

If anyone else wants to test this, please test and share your result here.

Please also share the exact Ubuntu version and terminal name.

**Comment by gmaruzz** [comment]
ok, then no problem

**Comment by gmaruzz** [comment]
FWIW: 
Ubuntu 20.04.6 LTS (GNU/Linux 5.15.0-88-generic x86_64)
xterm version 353
