### ISSUE TITLE
baresip -d do not exit correctly after a call

### ISSUE THREAD

**Issue by gmaruzz** [baresip/baresip#2782]
baresip v3.5.1  compiled from releases

If you run baresip -d, then you send a "\quit" to tcp socket, baresip exit cleanly

If you run baresip -d, then you make a call (eg, you send a "\dial 1234" to tcp socket, then after a while you send an "\hangup"), then you send a "\quit" to tcp socket, baresip kind of terminate but actually stay as a zombie or such, you cannot simply kill it, you must kill -9 it

**Comment by gmaruzz** [comment]
(on ubuntu)

**Comment by alfredh** [comment]
You have reported 2 issues, are they they overlapping ?

Please include more information as indicated here:

https://github.com/baresip/baresip/wiki/Guidelines-for-reporting-Issues


PS: Is the daemon mode so useful anymore ?

**Comment by gmaruzz** [comment]
Hello!

Thanks for your reply, and for baresip!

=============
I used the demon mode to control baresip
If demon mode is obsolete, what you suggest instead?
Is http the preferred, supported mode to control baresip?
=============

I don't think the two issues have a common cause or are overlapping.
The terminal is left inconsistent even if baresip exit correctly, eg in any case
Seems to me I reported all relevant info, please let me know what can I add.

**Comment by gmaruzz** [comment]
As you asked

CONSOLE (last line is repeated ENTERs, the console is borked up to a "reset", and you cannot see what you type):

<pre>
gmaruzz@t590:~  $ baresip -a SIP.js -d -f /home/gmaruzz/baresipconf
baresip v3.5.1 Copyright (C) 2010 - 2023 Alfred E. Heggestad et al.
Local network addresses:
    bridge0:  192.168.1.61
        wg0:  10.20.30.2
    docker0:  172.17.0.1
    bridge0:  fe80::5c9e:f37b:d4d4:8dd
 vethuux8WP:  fe80::fc7f:81ff:fe86:59ba
 vethhEUuJd:  fe80::fc0d:9aff:feb8:4fd
ua: adding SIP CA file: /etc/ssl/certs/ca-certificates.crt
ua: adding SIP CA path: 
aucodec: PCMU/8000/1
aucodec: PCMA/8000/1
ausrc: alsa
auplay: alsa
vidcodec: H264
vidcodec: H264
vidcodec: H265
avcodec: using H.264 encoder 'libx264' -- libx264 H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10
avcodec: using H.264 decoder 'h264' -- H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10
avcodec: using H.265 encoder 'libx265' -- libx265 H.265 / HEVC
avcodec: using H.265 decoder 'hevc' -- HEVC (High Efficiency Video Coding)
vidcodec: VP8
vidsrc: v4l2
vidsrc: fakevideo
vidisp: fakevideo
medianat: stun
medianat: turn
medianat: ice
mediaenc: srtp
mediaenc: srtp-mand
mediaenc: srtp-mandf
dtls_srtp: use prime256v1 for elliptic curve cryptography
mediaenc: dtls_srtp
1053@panictest: Using medianat 'ice'
1053@panictest: Using media encryption 'dtls_srtp'
Populated 1 account
Populated 3 contacts
Populated 2 audio codecs
Populated 0 audio filters
Populated 4 video codecs
Populated 0 video filters
gmaruzz@t590:~  $ gmaruzz@t590:~  $ gmaruzz@t590:~  $ gmaruzz@t590:~  $ gmaruzz@t590:~  $ gmaruzz@t590:~  $ gmaruzz@t590:~  $ 
</pre>

CONFIG
[config.txt](https://github.com/baresip/baresip/files/13248875/config.txt)

config file in attachment as config.txt

=================
[config.txt](https://github.com/baresip/baresip/files/13249056/config.txt)

**Comment by alfredh** [comment]
please try to enable syslog module to see logging in background mode.


Here are some questions for you:

* Please try also to test this in foreground. Does it hang ?
* Please include the full log, use syslog
* Please use gdb to attach to the zombie process and get a backtrace
* Can you try to compile the latest version from HEAD ?

Please note that the command prefix is slash `/` and not backslash.
