### ISSUE TITLE
Unstable valgrind test

### ISSUE THREAD

**Issue by sreimers** [baresip/baresip#2788]
Looks like valgrind is a little unstable currently:

https://github.com/baresip/baresip/actions/runs/6691103734/job/18177691315

@cspiel1 can reproduce this?

**Comment by sreimers** [comment]
Ok very hard to reproduce. Maybe a very slow github VM. Will close for now.

**Comment by cspiel1** [comment]
No, I can't. Ah, okay.

Maybe the first cancel rule with `n_vidframe==3` cancels unwanted the job before the SDP answer is processed. I am thinking about a change that would make it more stable.

**Comment by cspiel1** [comment]
This should be more stable: https://github.com/baresip/baresip/pull/2790

It avoids that the unwanted cancel rule cancels the main loop before the `ASSERT_TRUE(!call_has_video(ua_call(f->a.ua)))` that failed.
