### ISSUE TITLE
Compilation issue, latest code

### ISSUE THREAD

**Issue by jobo-zt** [baresip/baresip#2833]
I used the latest code to compile it in RPI. Before that, it was good,Before that, such as label v3.7
/usr/bin/ld: libbaresip.so.11.7.0: undefined reference to `__atomic_load_8'
/usr/bin/ld: libbaresip.so.11.7.0: undefined reference to `__atomic_store_8'
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/baresip_exe.dir/build.make:108: baresip] Error 1
make[1]: *** [CMakeFiles/Makefile2:1188: CMakeFiles/baresip_exe.dir/all] Error 2
make: *** [Makefile:171: all] Error 2

**Comment by jobo-zt** [comment]
This issue was introduced during a submission.

Test reproduction steps：
git reset --hard HEAD~8
HEAD is now at b9dbb897 rx thread: refactoring part 2 - separate audio receiver (#2795)

**Comment by cspiel1** [comment]
Which compiler do you use?

**Comment by jobo-zt** [comment]
gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/arm-linux-gnueabihf/10/lto-wrapper
Target: arm-linux-gnueabihf
Configured with: ../src/configure -v --with-pkgversion='Raspbian 10.2.1-6+rpi1' --with-bugurl=file:///usr/share/doc/gcc-10/README.Bugs --enable-languages=c,ada,c++,go,d,fortran,objc,obj-c++,m2 --prefix=/usr --with-gcc-major-version-only --program-suffix=-10 --program-prefix=arm-linux-gnueabihf- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --enable-bootstrap --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-libitm --disable-libquadmath --disable-libquadmath-support --enable-plugin --with-system-zlib --enable-libphobos-checking=release --with-target-system-zlib=auto --enable-objc-gc=auto --enable-multiarch --disable-sjlj-exceptions --with-arch=armv6 --with-fpu=vfp --with-float=hard --disable-werror --enable-checking=release --build=arm-linux-gnueabihf --host=arm-linux-gnueabihf --target=arm-linux-gnueabihf
Thread model: posix
Supported LTO compression algorithms: zlib zstd
gcc version 10.2.1 20210110 (Raspbian 10.2.1-6+rpi1)

**Comment by sreimers** [comment]
Looks like gcc on arm does not include `-latomic` if needed. So we need a cmake check for this. Will try to add one.

**Comment by jobo-zt** [comment]
This file exists in the local environment.
sudo find / -name "libatomic.so*"
/usr/lib/gcc/arm-linux-gnueabihf/10/libatomic.so
/usr/lib/arm-linux-gnueabihf/libatomic.so.1
/usr/lib/arm-linux-gnueabihf/libatomic.so.1.2.0
I tried this operation "cmake ../ -DCMAKE_SHARED_LINKER_FLAGS='-latomic'", but not ok

**Comment by sreimers** [comment]
You can try:

`-DCMAKE_REQUIRED_LIBRARIES="-latomic"`

**Comment by sreimers** [comment]
Can you try this PR: https://github.com/baresip/re/pull/1029

**Comment by jobo-zt** [comment]
> You can try:
> 
> `-DCMAKE_REQUIRED_LIBRARIES="-latomic"`

Tested, it's not working. I'll see what the reason is later


> Can you try this PR: [baresip/re#1029](https://github.com/baresip/re/pull/1029)
[ 22%] Building C object CMakeFiles/baresip_exe.dir/src/main.c.o
[ 23%] Linking C executable baresip
/usr/bin/ld: libbaresip.so.11.7.0: undefined reference to `__atomic_load_8'
/usr/bin/ld: libbaresip.so.11.7.0: undefined reference to `__atomic_store_8'
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/baresip_exe.dir/build.make:108: baresip] Error 1
make[1]: *** [CMakeFiles/Makefile2:1188: CMakeFiles/baresip_exe.dir/all] Error 2
make: *** [Makefile:171: all] Error 2

Tested, it's not working.
step:
1. re update branch and cmake make ( git checkout -b origin/cmake_atomic_detection)
2. baresip rebuild cmake and make

other tested
pi@raspberrypi:~/code/baresip/baresip/build $ ls
a.out           CMakeFiles           compile_commands.json  CPackSourceConfig.cmake  libbaresip.so     libbaresip.so.11.7.0  modules    test
CMakeCache.txt  cmake_install.cmake  CPackConfig.cmake      libbaresip.pc            libbaresip.so.11  Makefile              packaging  webrtc
pi@raspberrypi:~/code/baresip/baresip/build $ 
pi@raspberrypi:~/code/baresip/baresip/build $ **ld libbaresip.so.11**
ld: warning: cannot find entry symbol _start; defaulting to 00010154
ld: libbaresip.so.11: undefined reference to `__atomic_load_8'
ld: libbaresip.so.11: undefined reference to `__atomic_store_8'
pi@raspberrypi:~/code/baresip/baresip/build $ **ld libbaresip.so.11 -latomic**
ld: warning: cannot find entry symbol _start; defaulting to 00010164

**Comment by sreimers** [comment]
Ok, I think the reason is `CMAKE_REQUIRED_LIBRARIES` is for internal use only. Will update the PR.

**Comment by jobo-zt** [comment]
> You can try:
> 
> `-DCMAKE_REQUIRED_LIBRARIES="-latomic"`

I compared it and there was no significant difference
CMakeCache.txt  file has the following extra lines

//No help, variable specified on the command line.
CMAKE_REQUIRED_LIBRARIES:UNINITIALIZED=-latomic

**Comment by jobo-zt** [comment]
So I manually changed the link.txt file, and the compilation was okay
build/CMakeFiles/baresip_exe.dir/link.txt
build/CMakeFiles/baresip.dir/link.txt

Added -latomic at the end of the line

**Comment by sreimers** [comment]
I improved the PR https://github.com/baresip/re/pull/1029

You need also this: https://github.com/baresip/baresip/pull/2834

**Comment by jobo-zt** [comment]
Test failed
re and baresip git checkout -b origin/cmake_atomic_detection

// re cmake build
-- Performing Test COMPILER_SUPPORTS_WATOMIC
-- Performing Test COMPILER_SUPPORTS_WATOMIC - Failed
// baresip cmake build
nothing about atomic

If there is an update, I will verify it as soon as possible

**Comment by sreimers** [comment]
Have you cleaned up the build directory before? COMPILER_SUPPORTS_WATOMIC is not the test you are looking for. It should look like this:

```
-- Performing Test atomic_test
-- Performing Test atomic_test - Failed
-- Performing Test atomic_test_lib
-- Performing Test atomic_test_lib - Success
```

**Comment by jobo-zt** [comment]
No echo of "Performing Test atomic_test"

my testing steps error?
1. git clone https://github.com/baresip/re.git
2. git checkout -b origin/cmake_atomic_detection
3. mkdir build & cmake ../
4. make
1. git clone https://github.com/baresip/baresip.git
2. git checkout -b origin/cmake_atomic_detection
3. mkdir build & cmake ../
4. make

pi@raspberrypi:~/code/baresip/re $ git branch -a
  main
* origin/cmake_atomic_detection
  remotes/origin/HEAD -> origin/main
  main
* origin/cmake_atomic_detection
  remotes/origin/HEAD -> origin/main
  remotes/origin/alfredh_video_debug_mutex
  remotes/origin/cmake_atomic_detection

**Comment by jobo-zt** [comment]
I modified the code and the test passed. Please review

`##############################################################################
#
# Testing Atomic
#

enable_language(CXX)

set(ATOMIC_TEST_CODE "
     #include <stdatomic.h>
     #include <cstdint.h>
     std::atomic<uint8_t> n8 (0); // riscv64
     std::atomic<uint64_t> n64 (0); // armel, mipsel, powerpc
     int main() {
       ++n8;
       ++n64;
       return 0;
  }")
set(ATOMIC_TEST_CODE_LIB "
     #include <stdatomic.h>
     int main() {
     atomic_int a;
     return 0;  
  }")
check_cxx_source_compiles("${ATOMIC_TEST_CODE}" atomic_test)

if(NOT atomic_test)
  set(CMAKE_REQUIRED_LIBRARIES ${CMAKE_REQUIRED_LIBRARIES} atomic)
  check_c_source_compiles("${ATOMIC_TEST_CODE_LIB}" atomic_test_lib)
  if(NOT atomic_test_lib)
    message(FATAL_ERROR "No builtin or libatomic support")
  else()
    list(APPEND RE_LIBS atomic)
  endif()
endif()
`

**Comment by sreimers** [comment]
Looks like your patch file is not uploaded

**Comment by jobo-zt** [comment]
[patchfile.patch](https://github.com/baresip/baresip/files/13743357/patchfile.patch)
`
diff --git a/cmake/re-config.cmake b/cmake/re-config.cmake
index 0b13e2c..9be01f6 100644
--- a/cmake/re-config.cmake
+++ b/cmake/re-config.cmake
@@ -279,11 +279,18 @@ set(ATOMIC_TEST_CODE "
        return 0;
   }")
 
+set(ATOMIC_TEST_CODE_LIB "
+     #include <stdatomic.h>
+     int main() {
+     atomic_int a;
+     return 0;  
+  }")
+
 check_cxx_source_compiles("${ATOMIC_TEST_CODE}" atomic_test)
 
 if(NOT atomic_test)
   set(CMAKE_REQUIRED_LIBRARIES ${CMAKE_REQUIRED_LIBRARIES} atomic)
-  check_c_source_compiles("${ATOMIC_TEST_CODE}" atomic_test_lib)
+  check_c_source_compiles("${ATOMIC_TEST_CODE_LIB}" atomic_test_lib)
   if(NOT atomic_test_lib)
     message(FATAL_ERROR "No builtin or libatomic support")
   else()
`

**Comment by sreimers** [comment]
Can you retry now: https://github.com/baresip/re/pull/1029

**Comment by jobo-zt** [comment]
-- Performing Test atomic_test
-- Performing Test atomic_test - Failed
-- Performing Test atomic_test_lib
-- Performing Test atomic_test_lib - Failed
CMake Error at cmake/re-config.cmake:288 (message):

pi@raspberrypi:~/code/baresip/re/build $ cat /home/pi/code/baresip/re/build/CMakeFiles/CMakeError.log
![image](https://github.com/baresip/baresip/assets/38849089/7f6f5561-827f-41a6-b821-5a6ceb50b683)

**Comment by sreimers** [comment]
Are you sure the last commit is active? It tries to build with cc instead of c++

```patch
---
 cmake/re-config.cmake | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)

diff --git a/cmake/re-config.cmake b/cmake/re-config.cmake
index 0b13e2c5..68c0c80c 100644
--- a/cmake/re-config.cmake
+++ b/cmake/re-config.cmake
@@ -283,7 +283,7 @@ check_cxx_source_compiles("${ATOMIC_TEST_CODE}" atomic_test)
 
 if(NOT atomic_test)
   set(CMAKE_REQUIRED_LIBRARIES ${CMAKE_REQUIRED_LIBRARIES} atomic)
-  check_c_source_compiles("${ATOMIC_TEST_CODE}" atomic_test_lib)
+  check_cxx_source_compiles("${ATOMIC_TEST_CODE}" atomic_test_lib)
   if(NOT atomic_test_lib)
     message(FATAL_ERROR "No builtin or libatomic support")
   else()
```

**Comment by jobo-zt** [comment]
ok, It succeeded
-- Performing Test atomic_test
-- Performing Test atomic_test - Failed
-- Performing Test atomic_test_lib
-- Performing Test atomic_test_lib - Success
