### ISSUE TITLE
OSX: Library not loaded: @rpath/libre.19.dylib

### ISSUE THREAD

**Issue by bacterik** [baresip/baresip#2837]
I know there is recent commit, that is supposed to fix this? Yes? 
Having problems anyhow. I compile and then package libre and baresip sepretaly with pkg. And it installs in /usr/local/{bin,lib,include}. Tried to update the dyld shared cache, dosnt work. OSX Sonoma 14.2.

What does work is, if I export "DYLD_LIBRARY_PATH="$DYLD_LIBRARY_PATH:/usr/local/lib". Which I've never done before.

```
dyld[96639]: Library not loaded: @rpath/libre.19.dylib
  Referenced from: <0F43E540-C506-318E-B46D-D2B0C5D2BF02> /usr/local/bin/baresip
  Reason: tried: '/Users/xxx/dev/foo/baresip3/BaresipBuild/pkg/baresip/lib/libre.19.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Users/xxx/dev/foo/baresip3/BaresipBuild/pkg/baresip/lib/libre.19.dylib' (no such file), '/Users/xxx/dev/foo/baresip3/BaresipBuild/pkg/baresip/lib/libre.19.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Users/xxx/dev/foo/baresip3/BaresipBuild/pkg/baresip/lib/libre.19.dylib' (no such file)
Abort trap: 6

```

**Comment by sreimers** [comment]
Can you try this PR on main: https://github.com/baresip/baresip/pull/2839

It should add linked library paths to rpath

**Comment by bacterik** [comment]
Thanks @sreimers. Just tested the PR, works perfect.
