### ISSUE TITLE
Echo cancellation

### ISSUE THREAD

**Issue by exse2** [baresip/baresip#2889]
I am trying to use the echo cancellation (AEC) feature which is popping up at the main page. It's kinda required for a hands free speakers to avoid an acoustic feedback loop.
As far as my research was going, the baresip version from 2019 did not have AEC (I saw on website of cspiel that he tested early implementation as module "easy_aes" at that time), then apparently somebody said now it's "integrated", but still we need to enable modules "webrtc_aec.so" / "webrtc_aecm.so"?

Tickets like https://github.com/baresip/baresip/issues/1005#issuecomment-657005848 make it look like it's easy, but they work with precompiled x86 webrtc library. 

I am on Debian11/ARM. Followed <https://github.com/baresip/baresip/wiki/Install:-Stable-Release> until the point `cmake -B build -DCMAKE_BUILD_TYPE=Release` of baresip, which yields me a `Could NOT find WEBRTC_AEC (missing: WEBRTC_AEC_LIBRARY WEBRTC_AEC_INCLUDE_DIR)`.

So I put https://webrtc.googlesource.com/src into /usr/src/baresip3/webrtc and do `WEBRTC_AEC_INCLUDE_DIRS=/usr/src/baresip3 cmake -B build -DCMAKE_BUILD_TYPE=Release` 
Which still brings "Could NOT find", even though `./cmake/FindWEBRTC_AEC.cmake` contains 

	  find_path(WEBRTC_AEC_INCLUDE_DIR
	      NAMES webrtc/modules/audio_processing/include/audio_processing.h
	      HINTS
	          "${WEBRTC_AEC_INCLUDE_DIRS}"
	      PATHS /usr/include/webrtc_audio_processing
	  )
	
and `/usr/src/baresip3/webrtc/modules/audio_processing/include/audio_processing.h` is exsting. At least it should bring `Could NOT find WEBRTC_AEC (missing: WEBRTC_AEC_LIBRARY)`?

Oh and about the `WEBRTC_AEC_LIBRARY`, `./cmake/FindWEBRTC_AEC.cmake` says it needs `webrtc_audio_processing` library, so I have to go into `webrtc/modules/audio_processing` and compile.... what exactly? And how? I am at a loss. There are some forks of this i think (<https://freedesktop.org/software/pulseaudio/webrtc-audio-processing/> and <https://github.com/jhgorse/webrtc-audio-processing.git>) but they won't help me either because they have insane build dependencies.

**Comment by juha-h** [comment]
On Debian, I simple install libwebrtc-audio-processing-dev package and then WEBRTC_AEC is found.

**Comment by exse2** [comment]
Thank you thank you thank you! It compiled!

Package libwebrtc-audio-processing-dev contained /usr/include/webrtc_audio_processing/webrtc/modules/audio_processing/include/audio_processing.h

Package libwebrtc-audio-processing1 contained /usr/lib/aarch64-linux-gnu/libwebrtc_audio_processing.so.1

`cmake -B build -DCMAKE_BUILD_TYPE=Release` says `-- Found WEBRTC_AEC: /usr/lib/aarch64-linux-gnu/libwebrtc_audio_processing.so`.

But it still says `-- Could NOT find WEBRTC_AECM (missing: WEBRTC_AECM_LIBRARY WEBRTC_AECM_INCLUDE_DIR)`. Do I need the mobile mode? What is different from normal mode? How can I give cmake hints to build that too?

**Comment by exse2** [comment]
We tested now (with "webrtc_aec_extended_filter yes"), echo is completely cancelled, even though the microphone is practically glued on the speaker. And additionally the static which was audible previously even though this wouldn't even be the task of an EAC. 

Stellar work! You guys rock! Have a great week.

**Comment by exse2** [comment]
.

**Comment by juha-h** [comment]
exse2 writes:

> We tested now (with "webrtc_aec_extended_filter yes"), echo is
> completely cancelled, even though the microphone is practically glued
> on the speaker. And additionally the static which was audible
> previously even though this wouldn't even be the task of an EAC.

There is comment about "wbrtc_aec_extended_filter configuration option in
modules/webrtc_aec/aec.cpp:

 webrtc_aec_extended_filter {yes,no} # Enable extended_filter

but I cannot find handling of the option anywhere in the module
code.

Is the option valid?
