### ISSUE TITLE
-- Could NOT find GZRTP (missing: GZRTP_INCLUDE_DIR)

### ISSUE THREAD

**Issue by juha-h** [baresip/baresip#2914]
Debian build does not anymore automatically find gzrtp.  I get
```
-- Could NOT find GZRTP (missing: GZRTP_INCLUDE_DIR)
```
There has been no recent changes to cmake/FindGZRTP.cmake and it has:
```
find_path(GZRTP_INCLUDE_DIR
    NAMES common/osSpecifics.h
    HINTS
        "${GZRTP_INCLUDE_DIRS}"
        "${GZRTP_HINTS}/include"
    PATHS ../ZRTPCPP
)
```
GZRTP is found if I add exactly the same path to debian/rules:
```
diff --git a/debian/rules b/debian/rules
index 09879ce1..eac6b82e 100755
--- a/debian/rules
+++ b/debian/rules
@@ -4,4 +4,4 @@
    dh $@ --buildsystem=cmake
 
 override_dh_auto_configure:
-   dh_auto_configure -- -DCMAKE_BUILD_TYPE=Release
+   dh_auto_configure -- -DCMAKE_BUILD_TYPE=Release -DGZRTP_INCLUDE_DIR="../ZRTPCPP"
```
```
-- Found GZRTP: /usr/local/lib/libzrtpcppcore.a
```
Has something changed somewhere else in cmake files that could explain the issue?

**Comment by juha-h** [comment]
Here is more info.  Both baresip and ZRTPCPP source dirs are located in `/usr/src/orig` dir.  If I have in `debian/rules`:
```
	dh_auto_configure -- -DCMAKE_BUILD_TYPE=Release -DMODULES=$(MODULES) -DAPP_MODULES=$(APP_MODULES) -DAPP_MODULES_DIR="../baresip-app-modules" -DGZRTP_INCLUDE_DIRS="../ZRTPCPP"
```
I get
```
-- Could NOT find GZRTP (missing: GZRTP_INCLUDE_DIR)
```
If I use absolute path:
```
	dh_auto_configure -- -DCMAKE_BUILD_TYPE=Release -DMODULES=$(MODULES) -DAPP_MODULES=$(APP_MODULES) -DAPP_MODULES_DIR="../baresip-app-modules" -DGZRTP_INCLUDE_DIRS="/usr/src/orig/ZRTPCPP"
```
I get
```
-- Found GZRTP: /usr/local/lib/libzrtpcppcore.a  
```
How come that the path `../ZRTPCPP` does not work, when the corresponding APP_MODULES_DIR works?

I'm pretty sure that earlier GZRTP was found without any GZRTP_INCLUDE_DIRS in `debian/rules`.

**Comment by sreimers** [comment]
`find_package` is now executed from module path. So I think this is why the relative path does not work anymore.

https://github.com/baresip/baresip/blob/91e60f161239444bf335469994772956834ec372/modules/gzrtp/CMakeLists.txt#L3

Maybe something like this works:

```cmake
find_path(GZRTP_INCLUDE_DIR
    NAMES common/osSpecifics.h
    HINTS
        "${GZRTP_INCLUDE_DIRS}"
        "${GZRTP_HINTS}/include"
    PATHS ${CMAKE_SOURCE_DIR}/../ZRTPCPP
)
```

**Comment by juha-h** [comment]
@sreimers  Thanks, the above diff worked.  I guess the same change should be applied to this:
```
find_library(GZRTP_LIBRARY
    NAME zrtpcppcore
    HINTS
        "${GZRTP_LIBRARY_DIRS}"
        "${GZRTP_HINTS}/lib"
    PATHS ../ZRTPCPP/clients/no_client
)
```
and also to `cmake/FindWEBRTC_AECM.cmake`.

**Comment by juha-h** [comment]
Fixed  by https://github.com/baresip/baresip/pull/2924.
