### ISSUE TITLE
gst module not found in debian 11

### ISSUE THREAD

**Issue by juha-h** [baresip/baresip#2923]
Debian 11 has `glibconfig.h`  in directory `/usr/lib/x86_64-linux-gnu/glib-2.0/include`:
```
ls -ls /usr/lib/x86_64-linux-gnu/glib-2.0/include/
total 8
8 -rw-r--r-- 1 root root 5620 Apr  4  2023 glibconfig.h
```
but cmake/FindGST tries to look it from /usr/lib/x86_64-linux-gnu/glib-2.0 directory:
```cmake
find_path(GLIB_INCLUDE_DIR
  NAMES glibconfig.h
  HINTS
    "${GLIB_INCLUDE_DIRS}"
  PATHS /usr/lib/x86_64-linux-gnu/glib-2.0 /usr/lib64/glib-2.0 /usr/lib/glib-2.0
)
```
This patch fixes the issue:
```diff
diff --git a/cmake/FindGST.cmake b/cmake/FindGST.cmake
index 39e40c0f..32087d18 100644
--- a/cmake/FindGST.cmake
+++ b/cmake/FindGST.cmake
@@ -16,7 +16,7 @@ find_path(GLIB_INCLUDE_DIR
   NAMES glibconfig.h
   HINTS
     "${GLIB_INCLUDE_DIRS}"
-  PATHS /usr/lib/x86_64-linux-gnu/glib-2.0 /usr/lib64/glib-2.0 /usr/lib/glib-2.0
+  PATHS /usr/lib/x86_64-linux-gnu/glib-2.0/include /usr/lib64/glib-2.0 /usr/lib/glib-2.0
 )
 
 find_library(GST_LIBRARY
```
Would it be OK to create such a PR or could the find then fail on some other OSes?

**Comment by alfredh** [comment]
Some of these FindXXX.cmake files have been copied from other open source projects.

You should do a search on google and find some other project that has this file, and see how they have solved it.

I think the PATHS variable is a hint, so that you can add many entries to it.

**Comment by alfredh** [comment]
here is an example:

https://github.com/GStreamer/qt-gstreamer/blob/master/cmake/modules/FindGStreamer.cmake

You can also ask the maintainer of the GST module for help ...

**Comment by robert-scheck** [comment]
Interesting finding! Fedora has `/usr/lib(64)/glib-2.0/include/glibconfig.h`, which means something appends `/include` automagically. But as I just followed the existing example for Fedora, I don't have a real clue here. Given other paths mention the `/include` directory explicitly, e.g for `/usr/(local/)include`, it may make sense to do here as well.

**Comment by juha-h** [comment]
Fixed by https://github.com/baresip/baresip/commit/a4ff3ab09f4fbb519e03268af687c14c8d0402e8.
