### ISSUE TITLE
inreq_allowed is missing from Wiki and if not allowed produced incorrect negative response

### ISSUE THREAD

**Issue by juha-h** [baresip/baresip#2951]
Account parameter `;inreq_allowed`  is not found in Wiki/Accounts.  Also, it is not mentioned in CHANGELOG that now baresip does not by default accept MESSAGE requests.  It makes many users wondering why they now get back `488 Not Acceptable Here` response from baresip. 

Project policy should be that all commit that change earlier behavior must be clearly documented in CHANGELOG and that all new account parameter and config variables must be included in the Wiki.  It is too much to ask that users start reading the source code in order to find out how to use baresip.

The other issue related to this is that `488 Not Acceptable Here` is incorrect.  It means
```
488 Not Acceptable Here
    Some aspect of the session description or the Request-URI is not acceptable.
```
The MESSAGE that baresip rejects has nothing wrong in it.  The response should be 
```
403 Forbidden
    The server understood the request, but is refusing to fulfill it.
```
Please fix both of these issues.

**Comment by Tybil** [comment]
Maybe consider adding a warning if a message is rejected to avoid confusion when messages are not received. The rejection of messages is only visible when the sip trace is turned on.

**Comment by alfredh** [comment]
the common policy during the years is to keep backwards compat when adding new features.
this is to keep the endusers happy.

**Comment by Tybil** [comment]
The default value for this setting is not backwards compatible, that's why i think there should maybe be a warning or some other hint

**Comment by juha-h** [comment]
I tried for vain to resist accepting the PR https://github.com/baresip/baresip/pull/2877 because it broke backwards compatibility.  The PR also misses adding `;inreq_allowed` to `addr-params` and into Wiki, and the negative response has wrong code. Further., the PR does not address security consideration in https://www.rfc-editor.org/rfc/rfc3428#section-11.  In total, the PR should never have been accepted.  My proposal is to revert it completely and pass the choice on what to do with incoming MESSAGE requests to the application.

**Comment by maximilianfridrich** [comment]
#2953 Fixes the return code.

The wiki has been updated.

@juha-h We try to be very cooperative when proposing changes. Your mentioned issues were addressed in the PR, see [this comment in particular](https://github.com/baresip/baresip/pull/2877#discussion_r1477882479). I stated:

> Let me know if this is okay. If not, we will change the default to `yes`.

and got no response, but later a "looks okay to merge".

If the consensus is to allow incoming SIP MESSAGEs per default, then we will change the default and restore the old behavior.

@juha-h Please take into consideration the work we have done to improve BareSIP. We have contributed **a lot** and always take the community into account.

**Comment by cspiel1** [comment]
Updated: https://github.com/baresip/baresip/wiki/Accounts#inreq_allowed

Thanks for the hint!

**Comment by maximilianfridrich** [comment]
> Yes, you have contributed a lot, but that does not allow you to change our years long policy about backwards compatibility.

You are acting like we bypassed some policies. The PR went through a normal review process and [your issues were specifically addressed](https://github.com/baresip/baresip/pull/2877#discussion_r1477882479). **I literally asked**

> Let me know if this is okay. If not, we will change the default to `yes`.

and then got a "looks okay to merge".

> In my comments about the PR I never gave up on that. On my second to last comment I wrote: This change is far too destructive, when the default is no.

Everyone can see that these comments were added after the PR had already been merged, we're not stupid.

#2961 Here's the PR that restores the old behavior, simply because I don't want to deal with this anymore.

**Comment by juha-h** [comment]
Maximilian Fridrich writes:

> You are acting like we bypassed some policies. The PR went through a normal review process and [your issues were specifically addressed](https://github.com/baresip/baresip/pull/2877#discussion_r1477882479). **I literally asked**

The policy you bypassed is that you made a non-backwards compatible
change that negatively and unknowingly affected many users.  You did not
document the change in Wiki nor did you add the new parameter to the
account_write_template.

> > Let me know if this is okay. If not, we will change the default to `yes`.
> 
> and then got a "looks okay to merge".

It was not me who gave that.  I'm not always able to read the comments
every day.  When I then noticed that the PR was merged, I immediately
gave my negative comment: This change is far too destructive, when the
default is no.

> #2961 Here's the PR that restores the old behavior, simply because I
> #don't want to deal with this anymore.

Good.
