### ISSUE TITLE
connect a linphone account with baresip

### ISSUE THREAD

**Issue by nikhilkoottungal** [baresip/baresip#3004]
Hi @alfredh 
I have compiled the baresip source code for my laptop and I am trying to register it with a linphone sip account -> "sip:njolly@sip.linphone.org". 
I tried adding this in the baresip using the command - "/uanew sip:njolly:10Johxxxxxx@sip.linphone.org sip.linphone.org".
while trying this out I get the following error :
'reg: sip:njolly@sip.linphone.org (prio 0): Register: Permission denied [13]'.

I also tried adding the User Agent in the ~/.baresip/account file as following this format: '<sip:njolly@sip.linphone.org;transport=tcp>;auth_pass=secret'

The linphone account which i am trying to add is verified using the linphone app in android devices.

Can some one suggest a proper method to add the above mentioned linphone id, in the baresip.

**Comment by juha-h** [comment]
nikhilkoottungal writes:

> I also tried adding the User Agent in the ~/.baresip/account file as following this format: ***@***.***;transport=tcp>;auth_pass=secret'

This is not an issue (should be a discussion), but try if adding
`auth_user=something` helps;  Also, I'm not sure if ;transport=tcp in
the uri is a good idea.
