### ISSUE TITLE
SHA-256 support in baresip

### ISSUE THREAD

**Issue by nikhilkoottungal** [baresip/baresip#3006]
Hi Team,
I am currently facing issues with adding a linphone account with baresip. After the discussion, Its suggested that baresip may only support **md5**. Kindly find the siptrace logs:

sip:[njolly@sip.linphone.org](mailto:njolly@sip.linphone.org);auth_user=njolly;auth_pass=10Joxx;

baresip is ready.
20:54:51.044#
TLS 192.168.1.17:43584 -> 147.135.128.132:5223
REGISTER sip:sip.linphone.org SIP/2.0
Via: SIP/2.0/TLS 192.168.1.17:43584;branch=z9hG4bKb5b026de38c239eb;rport
Contact: sip:njolly-0x562a9d62b1c0@192.168.1.17:43584;transport=tls;expires=3819;+sip.instance="urn:uuid:f3fdf6fc-d23d-c567-d898-eb6f6a86c7a0"
Max-Forwards: 70
To: sip:njolly@sip.linphone.org
From: sip:njolly@sip.linphone.org;tag=4acb70747ca063f9
Call-ID: 9148678d83079717
CSeq: 7118 REGISTER
User-Agent: baresip v3.10.1 (x86_64/Linux)
Allow: INVITE,ACK,BYE,CANCEL,OPTIONS,NOTIFY,SUBSCRIBE,INFO,MESSAGE,UPDATE,REFER
Content-Length: 0

20:54:51.489#
TLS 147.135.128.132:5223 -> 192.168.1.17:43584
SIP/2.0 401 Unauthorized
Via: SIP/2.0/TLS 192.168.1.17:43584;branch=z9hG4bKb5b026de38c239eb;rport=1789;received=106.222.237.183
From: sip:njolly@sip.linphone.org;tag=4acb70747ca063f9
To: sip:njolly@sip.linphone.org;tag=D88NZ7F3Scegm
Call-ID: 9148678d83079717
CSeq: 7118 REGISTER
Server: Flexisip/2.3.3-33-g3ded5934 (sofia-sip-nta/2.0)
WWW-Authenticate: Digest realm="sip.linphone.org", nonce="QwvN6QAAAACPuTyTAADW8zsi5BEAAAAA", opaque="+GNywA==", **algorithm=SHA-256**, qop="auth"
Content-Length: 0

**reg: sip:[njolly@sip.linphone.org](mailto:njolly@sip.linphone.org) (prio 0): Register: Function not implemented [38]**

Please let me now if any more information is needed.

**Comment by juha-h** [comment]
According to https://httpwg.org/specs/rfc7616.html, use of MD5 is still supported, but not anymore recommended. It is replaced by SHA-256 and SHA-512 algorithms.

**Comment by sreimers** [comment]
We had a unfinished PR here: https://github.com/baresip/re/pull/180
I can have a look maybe next week.

**Comment by juha-h** [comment]
Good to learn that SHD-256 support has already been worked on.  Once PR is available, I can test it against my Kamailio SIP Proxy.
