### ISSUE TITLE
Httpd module doesn't return a body for some commands

### ISSUE THREAD

**Issue by lorentz23** [baresip/baresip#3026]
Hi,

I am using baresip v3.11.0. Playing a recorded audio during a phone call, when it finish the call continues muted and I would replay the same audio until the hangup.
Using baresip as shell command the output displays the event "ausrc - end of file" status so I can force the replay sending again the command /ausrc aufile,<AUDIO_FILE>, from the httpd module help I see is the /audiofileinfo <AUDIO_FILE> command to know some file info included the duration of it. I activate file_ausrc aufile config, but the response seems not be returned. I attach below the output from console when i call the command from http module

aufile: loading input file '<AUDIO_FILE>'
aufile: <AUDIO_FILE>: 8000 Hz, 1 channels, S16LE
aufile: audio ptime=0 sampc=320
aufile: read end of file
aufile: loaded 276252 bytes
debug_cmd: length = 17.280 seconds

I could use this output to made a duration calculation in my project to replay it again.

In addition I found the /callstat command, but the audio event ausrc - end of file is not displayed.

Many thanks.

**Comment by cspiel1** [comment]
Will have a look on this in the next days.

**Comment by alfredh** [comment]
please include more info:

https://github.com/baresip/baresip/wiki/Guidelines-for-reporting-Issues

**Comment by lorentz23** [comment]
Hi,

here is further details.

Baresip version v3.11.0

My configuration is here [config_accounts.zip](https://github.com/baresip/baresip/files/15336476/config_accounts.zip)

in particular

```
audio_source            aufile,<AUDIO_FILE>

file_ausrc             aufile

module                  httpd.so
```
I have configured the **audio_source** with a my own .wav file and making a call with http://127.0.0.1:8000/?/dial%20sip:<PHONE_NUMBER> the response is the following

```
call uri: sip:<PHONE_NUMBER>
call id: 13e25a4d96f7829b

```

During the call when the play is finished I would like to to trigger a new play of the same file calling the command http://127.0.0.1:8000/?/ausrc%20aufile%2C<AUDIO_FILE>.

From the help I see the command http://127.0.0.1:8000/?the /aufileinfo%20<AUDIO_FILE> I could use for my goal but unfortunately its http response is empty

![image](https://github.com/baresip/baresip/assets/9964485/ae16dadb-aa75-4934-a54b-02ee672400de)

However, the baresip console log displays all the info I need during its execution (in particular the duration of selected audio file I could use)

```
aufile: loading input file '/usr/local/share/baresip/<AUDIO_FILE>'
aufile: /usr/local/share/baresip/<AUDIO_FILE>: 8000 Hz, 1 channels, S16LE
aufile: audio ptime=0 sampc=320
aufile: read end of file
aufile: loaded 392708 bytes
debug_cmd: length = 24.559 seconds
```
I am available for any further clarification.

Many thanks.

**Comment by cspiel1** [comment]
I think that httpd has nothing to do with the issue.

**Comment by cspiel1** [comment]
Not sure what exactly this issue reports. Which module does not work corretly?
- aufile
- debug_cmd
- httpd

I tested successfully during an established call:
```
echo "/ausrc aufile,/usr/local/share/baresip/notfound.wav" | nc -N localhost 5555
```

**Comment by cspiel1** [comment]
This works also:
```
echo "/aufileinfo /usr/local/share/baresip/notfound.wav" | nc -N localhost 5555
...
debug_cmd: length = 2.080 seconds
```

**Comment by cspiel1** [comment]
### Module httpd
`http://localhost:8000/?/aufileinfo%20%2Fusr%2Flocal%2Fshare%2Fbaresip%2Fnotfound.wav`

Doesn't return any html body. Is this the issue you want to report?

**Comment by lorentz23** [comment]
Hi Christian,

Exactly. Is is correct or that endpoint should be return some info?

I am sorry for the misunderstanding.

Thanks

**Comment by alfredh** [comment]
there are different ways to return response:

1. info,debug,re_print
2. re_hprintf


the latter will print into the response context, eg http response.

https://github.com/baresip/baresip/blob/main/modules/debug_cmd/debug_cmd.c#L197

**Comment by cspiel1** [comment]
### Module debug_cmd
- uastat --> ok
- sysinfo --> ok
- aufileinfo --> nok

It doesn't use the `pf` to return. This could be solved, because "blocking mode for ausrc" is used for the aufileinfo command.

A general event can't be forwarded to the web browser. We should not change the behavior to HTTP long polling.

**Comment by cspiel1** [comment]
@lorentz23 please could you test with this branch: https://github.com/baresip/baresip/pull/3030

**Comment by lorentz23** [comment]
@cspiel1 I tested and it works!

![image](https://github.com/baresip/baresip/assets/9964485/afa2b5bb-b1bb-4666-a434-ed7f3892b721)

**Comment by asdasdddd1** [comment]
how i can send command from HTTP /vidsrc avformat,rtsp://admin:jnda@15.31.210.121:554/cam/realmonitor?channel=1&subtype=0
Always i recive error or not answer.

curl "http://localhost:8000?/vidsrc avformat,rtsp://localhost:554"
