### ISSUE TITLE
auconv not loading

### ISSUE THREAD

**Issue by bacterik** [baresip/baresip#3034]
macOS Sonoma. Just compiled and update to 3.12.0, but the module auconv dosnt seem to load. And I get distorted audio ofcourse.

```
ausrc_channels          1-2
auplay_channels         1-2
#audio_txmode           poll            # poll, thread
audio_level             no
ausrc_format            float           # s16, float, ..
auplay_format           float           # s16, float, ..
auenc_format            s16             # s16, float, ..
audec_format            s16             # s16, float, ..
```

...

```
# Audio codec Modules (in order)
module                  opus.so
module                  amr.so
#module                 g7221.so
#module                 g722.so
#module                 g726.so
module                  g711.so
module                  l16.so
#module                 mpa.so
#module                 codec2.so

# Audio filter Modules (in encoding order)
module                  auconv.so
module                  auresamp.so
module                  vumeter.so
#module                 sndfile.so
#module                 plc.so
#module                 webrtc_aec.so
```
...

```
aucodec: opus/48000/2
aucodec: AMR/8000/1
aucodec: PCMU/8000/1
aucodec: PCMA/8000/1
aucodec: L16/48000/2
aucodec: L16/44100/2
aucodec: L16/32000/2
aucodec: L16/16000/2
aucodec: L16/8000/2
aucodec: L16/48000/1
aucodec: L16/44100/1
aucodec: L16/32000/1
aucodec: L16/16000/1
aucodec: L16/8000/1
aufilt: auconv
aufilt: auresamp
aufilt: vumeter
auplay: coreaudio
ausrc: coreaudio
auplay: audiounit
ausrc: audiounit
auplay: jack
ausrc: jack
ausrc: aubridge
auplay: aubridge
ausrc: aufile
auplay: aufile
```
...

`All 1 useragent registered successfully! (48 ms)`

call: connecting to 'sip:xxx@xxx'..](url)

**audio tx pipeline:   coreaudio ---> aubuf ---> opus
audio rx pipeline:   coreaudio <--- aubuf <--- opus**

^ no auconv

calling-client@xxx: Call established: sip:calling-destination@xxx
audio: tx: invalid sample formats (FLOAT -> S16LE). Use module auconv!
audio: tx: invalid sample formats (FLOAT -> S16LE). Use module auconv!
audio: tx: invalid sample formats (FLOAT -> S16LE). Use module auconv!
audio: tx: invalid sample formats (FLOAT -> S16LE). Use module auconv!

Did I miss something?

**Comment by alfredh** [comment]
There are a couple of different `aufilt` modules:

* auconv
* auresamp
* mixausrc
* mixminus
* plc
* sndfile
* vumeter
* webrtc_aec
* webrtc_aecm

Could you please try to load some of them and check if it works ?


After starting baresip you can see which modules are loaded:

```
/modules

--- Modules (15) ---
            stdio type=ui           ref=1
             g711 type=audio codec  ref=1
           auconv type=filter       ref=1
         auresamp type=filter       ref=1
        coreaudio type=audio        ref=1
           aufile type=ausrc        ref=1
             uuid type=             ref=1
             stun type=mnat         ref=1
             turn type=mnat         ref=1
              ice type=mnat         ref=1
          account type=application  ref=1
          contact type=application  ref=1
        debug_cmd type=application  ref=1
             menu type=application  ref=1
          netroam type=application  ref=1
```


Could you also test an old version of baresip and see if it works ?
For example 3.11, 3.10, 3.9, 3.8 etc ...


Br,
Alfred

**Comment by cspiel1** [comment]
Should be fixed by: https://github.com/baresip/baresip/pull/3046

Please could you test again?

**Comment by sreimers** [comment]
Thanks for reporting and testing, I just released v3.12.1, since this is a major issue.

**Comment by cspiel1** [comment]
Since I introduced the issue, I'll check if it would be possible to write a unit test that tests filter setup.

**Comment by cspiel1** [comment]
There is an unfinished test for audio filters/auconv. PR: https://github.com/baresip/baresip/pull/3047
