### ISSUE TITLE
retagging issue with 3.13.0 release

### ISSUE THREAD

**Issue by chenrui333** [baresip/baresip#3070]
👋 looks like 3.13.0 release got re-tagged, raise this issue to confirm it was the case. Thanks!

relates to https://github.com/Homebrew/homebrew-core/pull/175074

**Comment by sreimers** [comment]
Yes, we had a release issue. https://github.com/baresip/baresip/pull/3069

**Comment by chenrui333** [comment]
thanks for confirming it!
