### ISSUE TITLE
RTCP Goodbye at end of call sent unencrypted when SRTP was mandatory

### ISSUE THREAD

**Issue by realbiz21** [baresip/baresip#3076]
I'm using [baresip 60.4.0](https://github.com/juha-h/baresip-studio) on Android 14, which integrates baresip.

An account is configured with "user@domain:5061;transport=tls". Outbound proxy is equivalent.

Media Encryption is set to SRTP-MAND.

With the above configuration, there should be no unencrypted SIP or RTP.

This holds true until the end of the call.

An RTP Goodbye (203) packet is seen over the RTCP port. The RTCP payload is "Source description" (202).

The RTCP Source description contains a CNAME SDES item. This CNAME item exposes the username@domain:port. 

Domain and port are not sensitive, but username should have been kept private with transport=tls and SRTP mandatory.

Issue #2638 mentions this, but was closed with no resolution.

**Comment by cspiel1** [comment]
Right I closed it without any solution or comment. Later @cHuberCoffee did further research and posted new questions:
https://github.com/baresip/baresip/issues/2638#issuecomment-1893910901

We'll try to discuss how to and if we are able to proceed here.

**Comment by realbiz21** [comment]
I'm in favor of the suggestion to drop the RTCP goodbye.

In the current situation, if the other end receives the unencrypted Goodbye packet, but they're expecting encryption, wouldn't(or, rather: shouldn't...) the other end see it as malformed and drop it?

**Comment by alfredh** [comment]
Please take a look at this PR: https://github.com/baresip/re/pull/1154

We should also consider to change CNAME from uri to a random string ...

**Comment by alfredh** [comment]
Please note that Baresip-Studio and Baresip are two different projects.
Baresip-studio is using the stack from Baresip (libbaresip):


https://github.com/juha-h/baresip-studio


it would be helpful if you can test the patch that I have made for you.
Either with baresip or baresip-studio.

Perhaps also @juha-h can help.

**Comment by juha-h** [comment]
@realbiz21 I created version of baresip app that includes https://github.com/baresip/re/pull/1154.  You can download it from here http://box.tutpro.com/tmp/baresip.apk.  Backup your config before installing.  Tell if it solves the issue.

**Comment by realbiz21** [comment]
Thank you @juha-h, you've saved me much time testing the patch.

@alfredh the patch works (tested with the prebuilt .apk from juha-h).

In an outgoing call, there were no RTCP packets observed at the end of the call, where previously there was. The call worked perfectly as it should, audio was sent and received on both ends. All traffic was TLS or SRTP as expected. Nothing abnormal observed visually, aurally, or in the wireshark capture.

**Comment by alfredh** [comment]
Thanks for testing. If we all agree we can go ahead and merge the re patch.

**Comment by alfredh** [comment]
Fixed in https://github.com/baresip/re/commit/542a85924ebfb347b7bf1c7baa471ee5ffe2d961
