### ISSUE TITLE
GTK module doesn't work with Wayland as the GDK backend

### ISSUE THREAD

**Issue by bricewge** [baresip/baresip#3119]
GTK module doesn't work with Wayland as the GDK backend, Wayland is the replacement for X11.

When starting `baresip` with the GTK module in Wayland without setting `GDK_BACKEND` or when setting it to `GDK_BACKEND=wayland` it hangs when starting a call. Then `baresip` won't terminate by sending it a SIGTERM, it needs a SIGKILL instead. Here is an example running on Debian 12 bookworm: 
```
GDK_BACKEND=wayland baresip 
baresip v3.14.0 Copyright (C) 2010 - 2024 Alfred E. Heggestad et al.
Local network addresses:
[...]
ua: adding SIP CA file: /etc/ssl/certs/ca-certificates.crt
ua: adding SIP CA path: /etc/ssl/certs
aucodec: PCMU/8000/1
aucodec: PCMA/8000/1
aufilt: auconv
aufilt: auresamp
pulse: initialized (Success [0])
auplay: pulse
ausrc: pulse
pipewire: headers 1.0.3 library 1.0.3 
pipewire: connected to pipewire
auplay: pipewire
ausrc: pipewire
medianat: stun
medianat: turn
medianat: ice
Populated 1 account
Populated 18 contacts
aufilt: gtk_vumeter
Subscribing to 0 contacts
httpreq: module init
httpd: listening on 0.0.0.0:8000
Populated 2 audio codecs
Populated 3 audio filters
Populated 0 video codecs
Populated 0 video filters
baresip is ready.

(baresip:76892): Gtk-CRITICAL **: 09:59:57.183: gtk_widget_get_scale_factor: assertion 'GTK_IS_WIDGET (widget)' failed
gtk_menu starting
Gtk-Message: 09:59:57.190: Failed to load module "canberra-gtk-module"
bricewge@example.com: selected for bricewge-0x223e330
bricewge@example.com: (prio 0) {0/UDP/v4} 200 OK (Asterisk [...]) [1 binding]
All 1 useragent registered successfully! (60 ms)
>                              100
bricewge@example.com: selected for request
call uri: 100
call: connecting to 'sip:100@example.com'..
call id: 6c91339b3b1c2407
call: SIP Progress: 100 Trying (/)
bricewge@example.com: Call answered: sip:100@example.com
stream: update 'audio'
audio: Set audio decoder: PCMU 8000Hz 1ch
pulse: opening player (8000 Hz, 1 channels, device , ptime 20)
pulse: playback stream VoIP Player started
audio: player started with sample format S16LE
audio: Set audio encoder: PCMU 8000Hz 1ch
pulse: opening recorder(8000 Hz, 1 channels,device '')
pulse: record stream VoIP Recorder started
audio: source started with sample format S16LE
audio tx pipeline:       pulse ---> aubuf ---> auconv ---> auresamp ---> gtk_vumeter ---> PCMU
audio rx pipeline:       pulse <--- aubuf <--- auconv <--- auresamp <--- gtk_vumeter <--- PCMU
bricewge@example.com: Call established: sip:100@example.com
```

This issue has already been described in #2295.

A workaround, is to force the GDK backend to be X11 with calling `baresip` with the environment variable `GDK_BACKEND=x11`.

**Comment by bricewge** [comment]
Thank you for the swift reply.

> Sadly this is a known limitation of the current GTK Module.

Understood, does it make sense to add support for Wayland in the roadmap then?

**Comment by alfredh** [comment]
Are you able to test this patch:

https://github.com/baresip/baresip/pull/3127


If there is no response from the author I will close the issue/PR.

**Comment by alfredh** [comment]
Hi,

I have added your feature request here:
https://github.com/baresip/baresip/wiki/Roadmap

We are only able to support the code and all modules on a best-effort basis.
If someone wants to help to maintain this module, please provide a working PR.

Alfred

**Comment by bricewge** [comment]
> If there is no response from the author I will close the issue/PR.

A couple of days ago I've responded to the PR https://github.com/baresip/baresip/pull/3127 directly as it seemed more appropriate.

> I have added your feature request here:

Thank you for that.

> We are only able to support the code and all modules on a best-effort basis.

I totally understand and I'm already very thankful to all the contributors for their great work on baresip.
