### ISSUE TITLE
SRV records do not work properly?

### ISSUE THREAD

**Issue by tuaris** [baresip/baresip#3125]
I have the following SRV records for my domain:

```
host -t SRV _sip._udp.example.net
_sip._udp.example.net has SRV record 10 0 5060 sip.example.com.
```

If I setup a new account using `user@example.net`, I get connection refused errors.  
If I setup the same account, but use `user@sip.example.com` it registers just fine.

I'm running version 60.4.1 on Android 8.0.  I don't know how to view the logs on this.

**Comment by juha-h** [comment]
Daniel Morante writes:

> I have the following SRV records for my domain:
> 
> ```
> host -t SRV _sip._udp.example.net
> _sip._udp.example.net has SRV record 10 0 5060 sip.example.com.
> ```
> 
> If I setup a new account using ***@***.***`, I get connection refused errors.  
> If I setup the same account, but use ***@***.***` it registers just fine.
> 
> I'm running version 60.4.1 on Android 8.0.  I don't know how to view
> the logs on this.

I cannot reproduce this using similar DNS config on my domain.  Have you
configured an outbound proxy?

**Comment by tuaris** [comment]
No outbound proxy.  It's all with in a local area network.  Does baresip ignore DNS servers assigned by DHCP?

**Comment by juha-h** [comment]
Since this is Android app specific issue/question, please re-open it in https://github.com/juha-h/baresip-studio project.  Also, check its Wiki about Debugging.
