### ISSUE TITLE
Issue with conf_path_set

### ISSUE THREAD

**Issue by gordongrech** [baresip/baresip#3146]
Hello and well done with this project.

I have just started testing Baresip as a library, I have created Rust bindings to Baresip and am currently building on macOS, my testing indicates that there is an underlying issue with conf_path_set, irrespective of my use case. 

When using conf_path_set, the conf_path value seems to be going out of scope when the function exists, as such when attempting to use conf_configure, the operation fails as follows: 

```shell
config: writing /config: Read-only file system [30]
```

The above seems to be the result of an attempted write to "/".  This seems to be caused by conf_path being empty, resulting in a final path of "/config" instead of "/mypath/config". I have managed to fix this by updating conf_path_set as per below: 

```C
static char *conf_path = NULL;

/**
 * Set the path to configuration files
 *
 * @param path Configuration path 
 */
void conf_path_set(const char *path)
{
    if (conf_path != NULL) {
        free((void *)conf_path);
    }

    conf_path = (char *)malloc(strlen(path) + 1);
    if (conf_path == NULL) {
        fprintf(stderr, "Memory allocation failed\n");
        exit(EXIT_FAILURE);
    }
    strcpy(conf_path, path);
}
```

This works, however this is my first experience with the project and with C in general and I am not familiar with the testing suite either. So if this is a bug, can you please provide guidance on the above code to get to a pull request? Feel free to scrap the above and take a different approach altogether :). 

If this is a not a bug I would appreciate your insights :)

Thank you all and good day.

**Comment by jobo-zt** [comment]
udp_thread_attach  needs to end in the thread where fd_sten is located, otherwise (! Fhs | |! Fhs ->fh) holds and continues to loop.

Can the above description provide some clues for testing work. thanks
