### ISSUE TITLE
Allow to hide phone number in contacts

### ISSUE THREAD

**Issue by omnicortex** [baresip/baresip#3155]
Please allow the options to show only contacts with SIP uri and hide all phone numbers.

**Comment by alfredh** [comment]
Can you please supply some additional info like version info, examples etc.

https://github.com/baresip/baresip/wiki/Guidelines-for-reporting-Issues

**Comment by omnicortex** [comment]
I am on android version `60.4.2`. I don't quite have an example.  I would like baresip to show the SIP uri that I have recorded in my android contacts.  Right now, bsresip only show phone numbers from my android contacts.  I would like the option to show SIP uri and hide phone numbers.

**Comment by sreimers** [comment]
The android app is maintained here: https://github.com/juha-h/baresip-studio

**Comment by omnicortex** [comment]
Should I re-post this request over at https://github.com/juha-h/baresip-studio
