### ISSUE TITLE
conf_get_float is not in baresip.h

### ISSUE THREAD

**Issue by juha-h** [baresip/baresip#3164]
Function `conf_get_float` is in `core.h`, not in `baresip.h`.  Can it be moved so that modules can use it?

**Comment by alfredh** [comment]
Yes, that function can be moved to the public api.

Some of the generic functions in conf.c can also be moved to libre conf module.

**Comment by alfredh** [comment]
thanks for adding it:

https://github.com/baresip/re/commit/b9d11ef065a44e856c60709aad2cf0aae2496bf2
