### ISSUE TITLE
Cut off tones when using ALSA module for playback

### ISSUE THREAD

**Issue by weili-jiang** [baresip/baresip#3185]
For context, we have been using Baresip with the ALSA module on a number of ARM platforms since 0.6.5.

Since recently upgrading to version 3.x, we have noticed that tones are getting cut off during playback. This is very pronounced with short tones which sometimes don't get played out to speaker at all. The issue does not occur with other audio drivers such as Pulse Audio on x86 or other custom platform ones e.g. Android and iOS.

We have isolated the change in behavior to the switch from `snd_pcm_drain` to `snd_pcm_drop` - our suspicion is that the last samples of the tone have been dispatched to ALSA but are then dropped due to `snd_pcm_drop`. If the call to `snd_pcm_drain` is put back, there are no more cut off tones.

Looking at the history, the change was made to fix some sporadic lock-ups, so I don't want to just add the `snd_pcm_drain` back. I have tried putting a delay in just before the `snd_pcm_drop` in the write thread, which for happy cases does allow the buffered samples to play out. If there was a problem, the sleep would finish regardless and proceed to flush, rather than causing a lock-up with drain. Unfortunately, some of the hardware platforms I've tested do not seem to return an accurate `snd_pcm_delay`, so I had to add in an extra `ptime` worth of delay as a fudge factor.

```
diff --git a/modules/alsa/alsa_play.c b/modules/alsa/alsa_play.c
index 09088e1a..b3d267f7 100644
--- a/modules/alsa/alsa_play.c
+++ b/modules/alsa/alsa_play.c
@@ -55,6 +55,7 @@ static int write_thread(void *arg)
        struct auplay_st *st = arg;
        struct auframe af;
        snd_pcm_sframes_t n;
+       snd_pcm_sframes_t delay = 0;
        int num_frames;
        int err;
        int policy;
@@ -85,6 +86,10 @@ static int write_thread(void *arg)
 
                sampv = st->sampv;
 
+               if (snd_pcm_delay(st->write, &delay) != 0) {
+                       warning("alsa: error reading delay: %s\n",
+                               snd_strerror((int) delay));
+               }
                n = snd_pcm_writei(st->write, sampv, samples);
 
                if (-EPIPE == n) {
@@ -108,6 +113,14 @@ static int write_thread(void *arg)
                }
        }
 
+       /* Give a chance for buffered samples to drain in happy cases */
+       /* Avoiding snd_pcm_drain which can cause lock-ups */
+       if (delay != 0) {
+               unsigned int sleep_ms = (delay * 1000 - 1) / st->prm.srate + 1;
+               sys_msleep(sleep_ms);
+       }
+       /* Extra fudge factor that seems to be required for some hardware */
+       sys_msleep(st->prm.ptime);
        snd_pcm_drop(st->write);
 
        return 0;
```

Using sleep (especially with a fudge factor) is a little ugly, but I don't see a better option given the limitations of the ALSA API. A Would you accept something like this as a PR?

**Comment by sreimers** [comment]
The problem is this blocks the main thread since destructor is waiting with `thrd_join`.

**Comment by weili-jiang** [comment]
> The problem is this blocks the main thread since destructor is waiting with `thrd_join`.

Indeed, this what `snd_pcm_drain` previously did. If that is unacceptable, I see two options:

1. Introduce arbitrary delay in the tone player - this would delay destruction and flush of all modules, not just ALSA.
2. Do some kind of delayed offloaded cleanup of the ALSA thread, maybe by timer.

**Comment by weili-jiang** [comment]
Maybe something like this

[alsa_play.patch](https://github.com/user-attachments/files/17630244/alsa_play.patch)

**Comment by alfredh** [comment]
have you tried other audio modules such as pulse, portaudio, pipewire ?

it might be possible to adjust the ALSA buffering time to a very low value, so that
when calling drop it would only drop a very short duration.
The buffering time could be e.g. 10ms or 20ms.

**Comment by weili-jiang** [comment]
> have you tried other audio modules such as pulse, portaudio, pipewire ?
As mentioned in the initial post, this only happens with the ALSA module, and only since the change to call drop instead of drain.

> it might be possible to adjust the ALSA buffering time to a very low value, so that when calling drop it would only drop a very short duration. The buffering time could be e.g. 10ms or 20ms.
Unfortunately this is not possible for us, without operating using RT scheduling we need at least 80 ms buffering otherwise we start experiencing sporadic buffer underruns (this on various embedded ARM platforms).

Another workaround is to artificially add padding silence to all the source .wav files. This wouldn't require any changes to Baresip, but I think the documentation somehow needs to acknowledge this issue with the ALSA module so that people know to do this.

**Comment by alfredh** [comment]
Looks like other projects have similar issues:

https://trac.pjsip.org/repos/ticket/2224


If you want to experiment with buffersize, here is the code for that:

```c
int alsa_reset(snd_pcm_t *pcm, uint32_t srate, uint32_t ch,
	       uint32_t num_frames,
	       snd_pcm_format_t pcmfmt)
{
	snd_pcm_hw_params_t *hw_params = NULL;
	snd_pcm_uframes_t period = num_frames, bufsize = num_frames * 4;
	int err;

	debug("alsa: reset: srate=%u, ch=%u, num_frames=%u, pcmfmt=%s\n",
	      srate, ch, num_frames, snd_pcm_format_name(pcmfmt));

	err = snd_pcm_hw_params_malloc(&hw_params);
	if (err < 0) {
		warning("alsa: cannot allocate hw params (%s)\n",
			snd_strerror(err));
		goto out;
	}

	err = snd_pcm_hw_params_any(pcm, hw_params);
	if (err < 0) {
		warning("alsa: cannot initialize hw params (%s)\n",
			snd_strerror(err));
		goto out;
	}
```

Is your problem related to real-time audio streaming or playing of WAV files ?

Could you post a log from when the problem happens, perhaps with some timing info
like duration of WAV file and how many samples are played ?


It would be nice to fix your problem, but also it would be nice for us to understand
why you cannot use pulse/pipewire on your ARM platform.

**Comment by weili-jiang** [comment]
> If you want to experiment with buffersize, here is the code for that:

We have played around with the buffer size code already in the past, which is why we know what buffer sizes we can get away with (can't reduce it any more). Changing this buffer also doesn't impact the drop very much - on our platform, `snd_pcm_delay` is returning numbers equivalent to 200-400 ms (with 8 kHz sampling rate and 20 ms ptime), which is a lot bigger than the Baresip buffer. The extra delay is in further downstream processing in ALSA and kernel pipelines, which `snd_pcm_delay` has estimates for. Calling `snd_pcm_drop` drops everything in the downstream pipeline, not just what's in the Baresip buffer, so for us a lot more than 80 ms (4 * ptime) is lost.

> Is your problem related to real-time audio streaming or playing of WAV files ?

I suspect the problem exists with real-time audio streaming also, but since it would only happen when the call is hung up (where people are unlikely to be talking), a loss of say 400 ms is not really going to be an issue. With the tone player, some of our tones are short non-repeated indicators that are as short as 150 ms in duration - any cut off is very apparent here.

> Could you post a log from when the problem happens, perhaps with some timing info like duration of WAV file and how many samples are played ?

I will try to create some kind of log or at least some audio capture, unfortunately in this area of timing sensitive code, logging creates its own issues.

> It would be nice to fix your problem, but also it would be nice for us to understand why you cannot use pulse/pipewire on your ARM platform.

In the meantime, we have decided to go with some kind of workaround for now, as changing the whole audio architecture of our platform is not a light undertaking. In the past we did experiment with PulseAudio, but we didn't have much success reducing the system latency to an acceptable level. We actually used JACK for a while, but dropped it due to some nasty sporadic bugs (not in Baresip, but in the JACK daemon).

**Comment by alfredh** [comment]
When playing a wav file it should be possible to have a low buffer-time, such as 5ms or 10ms, since all
the PCM samples is loaded into memory.

Can you try to change this value:

https://github.com/baresip/baresip/blob/main/src/play.c#L14

**Comment by alfredh** [comment]
hi @weili-jiang 

Did you have a chance to try out my suggestion about with the reduced ptime ?

Alfred

**Comment by weili-jiang** [comment]
> hi @weili-jiang
> 
> Did you have a chance to try out my suggestion about with the reduced ptime ?
> 
> Alfred

This ptime has negligible effect on our problem - it controls how many samples Baresip **is going to write** to ALSA and how long it waits until the next write (or stop), but our problem is with the samples **already written** to ALSA.

Just because ALSA has indicated it is ready to receive the next batch of samples, it does not mean that it has actually finished draining the previous batch of samples to speaker. Baresip thinks it is done after it waits for another ptime, but in our case this is not sufficient since the ALSA pipeline length is actually greater than the ptime. If Baresip calls `snd_pcm_drop` when it thinks it is done but before all the samples have drained from the ALSA pipeline to speaker, the entire pipeline in that is still draining from ALSA (about 200-300 ms for us) is lost.

As you point out, ALSA is a fairly niche use case, but the way Baresip currently uses the ALSA API does not seem to match what the ALSA API design recommends. From studying the ALSA API, there appears to be no way for an ALSA client to reliably know when the pipeline has fully drained except using `snd_pcm_drain` - that appears to be what the ALSA designers intend for clients to call to ensure all samples are played out. To avoid blocking the main thread, we could do a delayed call to `snd_pcm_drain` using the `re_thread_async` mechanism, but since the old usage of `snd_pcm_drain` in Baresip seems to have caused complete lockups for some people, that's probably not a workable option.

I have not been successful in adding very useful logging - the existing logging within Baresip looks fine, but that is because Baresip has no way of knowing what the state of the ALSA pipeline really is. The only interesting thing I found was logging the values returned by my added calls to `snd_pcm_delay`, which as previously mentioned is returning values higher than any ptime (200-300 ms).

As I mentioned, we can maintain our workaround as a custom patch, but I would suggest documenting the limitation in the ALSA module somehow to save some future person some debugging headache figuring out where their samples went 😉.

**Comment by cspiel1** [comment]
Look also in the git log!
- 4b8282502f619c23720fedfbab8a8438eba4504f
- 8e73f5beebef8dbfffe0f06c0fde1ff1509866b0

**Comment by alfredh** [comment]
are you able to help document this problem and workaround ?
The text could be stored in the Wiki for example.

I dont think that delayed draining is a good solution. If the ALSA device can only be opened by
one client, there is a risk that it would block the next client trying to play a tone.

For example:

1. Play "1"
2. Delay
3. Play "2"
4. Delay
5. Play "3"
6. Delay
7. etc ...

Another option, if you can live with it, is to add a config flag to the ALSA module
that controls if you want to "DROP" or "DRAIN" the samples...

**Comment by weili-jiang** [comment]
> are you able to help document this problem and workaround ? The text could be stored in the Wiki for example.

Certainly, would a section in https://github.com/baresip/baresip/wiki/Using-Baresip:-Module-alsa be a good place?

**Comment by alfredh** [comment]
thanks for the text, I updated the Wiki page with your text.

You should also be able to edit the Wiki page, please feel free to edit the page later if needed ...
