### ISSUE TITLE
logo.png and *.wav files are no longer installed after commit 085e86fa

### ISSUE THREAD

**Issue by GojiraBSD** [baresip/baresip#3191]
> Does this actually work? logo.png and *.wav files are no longer installed. Tested on FreeBSD and Arch GNU/Linux. 

 _Originally posted by @GojiraBSD in [085e86f](https://github.com/baresip/baresip/commit/085e86fa32f67f6fe54b92cb11aa8ee740032a53#r148826685)_

I had to replace the line with e.g:

`file(GLOB SHARE_FILES "${PROJECT_SOURCE_DIR}/share/*.wav" "${PROJECT_SOURCE_DIR}/share/*.png")`

**Comment by robert-scheck** [comment]
Confirming that `/usr/share/baresip/` is no longer populated as of baresip v3.17.0 when building for Fedora and EPEL.
