### ISSUE TITLE
Missing: Extra headers from the start ...

### ISSUE THREAD

**Issue by flash7777** [baresip/baresip#3199]
I missed the option to set extra SIP headers, ideally right at the start, on the command line—and even better, not just one, but several. That would be great.

usage:  
`baresip  -x <key>:<val> -x <key>:<val>`

Attached is a forward patch of an older 1.0.0 hotfix.  So i kept this uag fragment.

[baresip-3.16.0_mod.patch.txt](https://github.com/user-attachments/files/17708524/baresip-3.16.0_mod.patch.txt)

**Comment by alfredh** [comment]
Could you please create a Pull Request for this patch ?

**Comment by flash7777** [comment]
i have no branch here. how to proceed?

**Comment by sreimers** [comment]
> i have no branch here. how to proceed?

You can fork the project and submit the PR from your fork.

**Comment by alfredh** [comment]
we can track the progress in the PR
