### ISSUE TITLE
How to use call volume in baresip-studio？

### ISSUE THREAD

**Issue by ONiKiDSK** [baresip/baresip#3201]
The Android project baresip-studio has been using the media volume during calls. Although many issues have reported that the call volume should be used instead of the media volume, this requirement has not been met. I have also tried several solutions without success. Is it because the underlying library uses a specific audio stream type, so the audio stream type cannot be set in the upper application? At least please give me a direction, thank you.

**Comment by sreimers** [comment]
Please report here: https://github.com/juha-h/baresip-studio
