### ISSUE TITLE
Volume not working on Android

### ISSUE THREAD

**Issue by gordongrech** [baresip/baresip#3229]
Hello, 

On Android, using OpenSL ES, there is an issue where audio player plays as media stream and not as voice. This is problematic when using Android Telecom and Connection Service, as volume controls do not work. This also results in UX issues when users have media volume set low. 

I've managed to address this by setting stream type to SL_ANDROID_STREAM_VOICE in the OpenSL ES player. I can create a pull request with the change, but before doing so, I would like to know if this is desirable, also considering OpenSL ES may soon be deprecated in favor of the new AAudio module. 

Thanks

**Comment by juha-h** [comment]
In aaudio module streams have this:
```
AAudioStreamBuilder_setUsage(builder,
		 AAUDIO_USAGE_VOICE_COMMUNICATION);
```
Does it fix your issue?

**Comment by gordongrech** [comment]
Good day. I have not been able to test AAudio yet but most probably it will. 

The issue in OpenSL ES  is fixed by getting the player config and setting the stream type as follows: 

``` c
    SLint32 streamType = SL_ANDROID_STREAM_VOICE;
    r = (*playerConfig)->SetConfiguration(
        playerConfig,
        SL_ANDROID_KEY_STREAM_TYPE,
        &streamType,
        sizeof(SLint32)
    );
```

This seems very similar to AAUDIO_USAGE_VOICE_COMMUNICATION in AAudio.

**Comment by alfredh** [comment]
hi @juha-h which versions of Android do you support in your application ?

**Comment by alfredh** [comment]
in your application and baresip, should we support only *aaudio* and later ?

i.e. should we deprecate *opensles* ?

**Comment by juha-h** [comment]
I'm not going to need opensles anymore, since (unlike aaudio), it does not give access to streams ids.  But don't know about others.

**Comment by GGGO** [comment]
Does opensles stay in baresip modules but just marked as depreciated by Google ?
If opensles is stable and useful for old devices, I think we should keep it.

**Comment by alfredh** [comment]
We can keep both modules for now if that is wanted by users

@gordongrech could you please create a PR for your opensles patch ?

**Comment by alfredh** [comment]
I will close this issue now ... waiting for patch from @gordongrech ...

**Comment by gordongrech** [comment]
Hello. 

Sure I will create a pull request but there is one consideration I need guidance on. 

Once the patch is deployed, calls will stream over the voice channel. The volume functionality will stop working for anyone using media volume control in existing Android apps. 

Should we document this as a backward incompatible change or make the output stream configurable via config? E.g. auplay_stream=default,media? 

Thanks
