### ISSUE TITLE
How to put baresip in notification zone

### ISSUE THREAD

**Issue by Br31zh** [baresip/baresip#3237]
Hello,

Since the v3.17.0, the GTK module now have a dedicated window, that’s a good idea but it replace the notification zone icon, which was more practical for me.

I didn’t found an option to restore the previous behaviour, is it possible? If it is, what’s the configuration I need to do?

If it’s not, would it be possible to add an option to do this (so that we can choose between the notification area, the standalone window or eventually both).

Thanks.

**Comment by alfredh** [comment]
Could you please include some screenshots and more info about your platform:

https://github.com/baresip/baresip/wiki/Guidelines-for-reporting-Issues

**Comment by Br31zh** [comment]
I missed this guideline, sorry. After reading it I guess it should be a feature request instead of an issue. So I’ll post it in the right place, this issue can be closed.
