### ISSUE TITLE
Echo in the other person

### ISSUE THREAD

**Issue by l7v2uj** [baresip/baresip#3248]
The other person hears his own echo, but there is no echo of the other person on my side.
The situation is the same in Linphone, everything is fine on Zoiper.
System: [Arch Linux](https://archlinux.org/)
[Noise Suppression v1.10](https://github.com/werman/noise-suppression-for-voice)
[baresip v3.18.0](https://github.com/baresip/baresip/releases/tag/v3.18.0)
The _"webrtc_aec.so"_ module is enabled.

<details>
  <summary>My "config" (click me)</summary>
  
 #
# baresip configuration
#

#------------------------------------------------------------------------------

# SIP
#sip_listen		0.0.0.0:5060
#sip_certificate	cert.pem
sip_cafile		/etc/ssl/certs/ca-certificates.crt
sip_capath		/etc/ssl/certs
#sip_transports		udp,tcp,tls,ws,wss
#sip_trans_def		udp
#sip_verify_server	yes
#sip_verify_client	no
#sip_tls_resumption	all
sip_tos			160
#filter_registrar	udp,tcp,tls,ws,wss

# Call
call_local_timeout	120
call_max_calls		4
call_hold_other_calls	yes
call_accept		no

# Audio
#audio_path		/usr/local/share/baresip
audio_player		pipewire,analog-output-headphones
audio_source		pipewire,rnnoise_source
audio_alert		pipewire,analog-output-headphones
#ausrc_srate		48000
#auplay_srate		48000
#ausrc_channels		0
#auplay_channels	0
#audio_txmode		poll		# poll, thread
audio_level		no
ausrc_format		s16		# s16, float, ..
auplay_format		s16		# s16, float, ..
auenc_format		s16		# s16, float, ..
audec_format		s16		# s16, float, ..
audio_buffer		20-160		# ms
audio_buffer_mode	fixed		# fixed, adaptive
audio_silence		-35.0		# in [dB]
audio_telev_pt		101		# payload type for telephone-event

# Video
#video_source		v4l2,/dev/video0
#video_display		x11,nil
#video_size		640x480
#video_bitrate		1000000
#video_fps		30.00
#video_fullscreen	no
#videnc_format		yuv420p

# AVT - Audio/Video Transport
rtp_tos			184
#rtp_video_tos		136
#rtp_ports		10000-20000
#rtp_bandwidth		512-1024 # [kbit/s]
audio_jitter_buffer_type	fixed		# off, fixed, adaptive
audio_jitter_buffer_delay	5-10		# (min. frames)-(max. packets)
#video_jitter_buffer_type	fixed		# off, fixed, adaptive
#video_jitter_buffer_delay	5-50		# (min. frames)-(max. packets)
rtp_stats		no
#rtp_timeout		60
#avt_bundle		no
#rtp_rxmode		main

# Network
#dns_server		1.1.1.1:53
#dns_server		1.0.0.1:53
#dns_fallback		8.8.8.8:53
#dns_getaddrinfo		no
#net_interface		wlan0

# Play tones
#file_ausrc		aufile
#file_srate		16000
#file_channels		1

#------------------------------------------------------------------------------
# Modules

module_path		/usr/local/lib/baresip/modules

# UI Modules
module			stdio.so
#module			cons.so
#module			evdev.so
#module			httpd.so

# Audio codec Modules (in order)
#module			opus.so
#module			amr.so
#module			g7221.so
#module			g722.so
#module			g726.so
module			g711.so
#module			l16.so
#module			mpa.so
#module			codec2.so

# Audio filter Modules (in encoding order)
module			auconv.so
module			auresamp.so
#module			vumeter.so
#module			sndfile.so
#module			plc.so
module			webrtc_aec.so

# Audio driver Modules
#module			alsa.so
#module			pulse.so
module			pipewire.so
#module			jack.so
#module			portaudio.so
#module			aubridge.so
#module			aufile.so
#module			ausine.so

# Video codec Modules (in order)
#module			avcodec.so
#module			vp8.so
#module			vp9.so

# Video filter Modules (in encoding order)
#module			selfview.so
#module			snapshot.so
#module			swscale.so
#module			vidinfo.so
#module			avfilter.so

# Video source modules
#module			v4l2.so
#module			vidbridge.so

# Video display modules
#module			directfb.so
#module			x11.so
#module			sdl.so
#module			fakevideo.so

# Audio/Video source modules
#module			avformat.so
#module			gst.so

# Compatibility modules
#module			ebuacip.so
module			uuid.so

# Media NAT modules
#module			stun.so
#module			turn.so
#module			ice.so
#module			natpmp.so
#module			pcp.so

# Media encryption modules
#module			srtp.so
#module			dtls_srtp.so
#module			gzrtp.so

#------------------------------------------------------------------------------
# Application Modules

module_app		account.so
#module_app		contact.so
#module_app		debug_cmd.so
module_app		echo.so
#module_app		gtk.so
module_app		menu.so
#module_app		mwi.so
#module_app		presence.so
#module_app		serreg.so
#module_app		syslog.so
#module_app		mqtt.so
#module_app		ctrl_tcp.so
#module_app		ctrl_dbus.so
#module_app		httpreq.so
module_app		netroam.so

#------------------------------------------------------------------------------
# Module parameters

# DTLS SRTP parameters
#dtls_srtp_use_ec	prime256v1

# UI Modules parameters
cons_listen		0.0.0.0:5555 # cons - Console UI UDP/TCP sockets

http_listen		0.0.0.0:8000 # httpd - HTTP Server

ctrl_tcp_listen		0.0.0.0:4444 # ctrl_tcp - TCP interface JSON

evdev_device		/dev/input/event0

# Opus codec parameters
opus_bitrate		28000 # 6000-510000
#opus_stereo		yes
#opus_sprop_stereo	yes
#opus_cbr		no
#opus_inbandfec		no
#opus_dtx		no
#opus_mirror		no
#opus_complexity	10
#opus_application	audio	# {voip,audio}
#opus_samplerate	48000
#opus_packet_loss	10	# 0-100 percent (expected packet loss)

# Opus Multistream codec parameters
#opus_ms_channels	2	#total channels (2 or 4)
#opus_ms_streams	2	#number of streams
#opus_ms_c_streams	2	#number of coupled streams

vumeter_stderr		yes

#jack_connect_ports	yes

# Selfview
#video_selfview		window # {window,pip}
#selfview_size		64x64

# Menu
#redial_attempts	0 # Num or <inf>
#redial_delay		5 # Delay in seconds
#ringback_disabled	no
#statmode_default	off
#menu_clean_number	no
#sip_autoanswer_method	rfc5373 # {rfc5373,call-info,alert-info}
#ring_aufile		ring.wav
#callwaiting_aufile	callwaiting.wav
#ringback_aufile	ringback.wav
#notfound_aufile	notfound.wav
#busy_aufile		busy.wav
#error_aufile		error.wav
#sip_autoanswer_aufile	autoanswer.wav
#menu_max_earlyaudio	32
#menu_max_earlyvideo_rx	32
#menu_max_earlyvideo_tx	32
#menu_message_tone	yes

# GTK
#gtk_clean_number	no
#gtk_use_status_icon	yes
gtk_use_window	yes

# avcodec
#avcodec_h264enc	libx264
#avcodec_h264dec	h264
#avcodec_h265enc	libx265
#avcodec_h265dec	hevc
#avcodec_hwaccel	vaapi
#avcodec_profile_level_id 42002a
#avcodec_keyint		10

# vp8
#vp8_enc_threads 1
#vp8_enc_cpuused 16 # range -16..16, greater 0 increases speed over quality

# ctrl_dbus
#ctrl_dbus_use	system		# system, session

# mqtt
#mqtt_broker_host	sollentuna.example.com
#mqtt_broker_port	1883
#mqtt_broker_cafile	/path/to/broker-ca.crt	# set this to enforce TLS
#mqtt_broker_clientid	baresip01	# has to be unique
#mqtt_broker_user	user
#mqtt_broker_password	pass
#mqtt_basetopic		baresip/01

# sndfile
#snd_path		/tmp

# EBU ACIP
#ebuacip_jb_type	fixed	# auto,fixed

# HTTP request module
#httpreq_ca		trusted1.pem
#httpreq_ca		trusted2.pem
#httpreq_dns		1.1.1.1
#httpreq_dns		8.8.8.8
#httpreq_hostname	myserver
#httpreq_cert		cert.pem
#httpreq_key		key.pem

# avformat
#avformat_hwaccel	vaapi
#avformat_inputformat	mjpeg
#avformat_decoder	mjpeg
#avformat_pass_through	yes
#avformat_rtsp_transport	udp

# ice
#ice_policy		all	# all, relay (candidates)
  
</details>

Please help me, I really like this client, but it's hard to talk. I don't want to use Zoiper(

**Comment by juha-h** [comment]
Just for curiosity, if you have an Android device, could you try with baresip Android app available on F-Droid or here: https://github.com/juha-h/baresip-studio/releases.

**Comment by l7v2uj** [comment]
> Just for curiosity, if you have an Android device, could you try with baresip Android app available on F-Droid or here: https://github.com/juha-h/baresip-studio/releases.

Unfortunately, I can't call. I call a number, for example 1234567, and it changes it to sip:1234567@1.2.3.4;user=phone

**Comment by juha-h** [comment]
If you call telephone number without domain part, the app uses account's Telephony Provider as domain part.

**Comment by juha-h** [comment]
Yes:
```
test@test.tutpro.com: (prio 0) {0/TCP/v4} 200 OK (OpenSIPg SIP Proxy (6.0.0-0b07 (x86_64/linux))) [1 binding]
All 1 useragent registered successfully! (12 ms)
>                            12345
test@test.tutpro.com: selected for request
call uri: 12345
call: connecting to 'sip:12345@test.tutpro.com'..
```

**Comment by l7v2uj** [comment]
Yes indeed, I checked that too. So what's the mistake?

**Comment by juha-h** [comment]
Don't know.  I think we should give up, since this is not related to your issue.

**Comment by l7v2uj** [comment]
It worked, I added the transport to the contact, as it looks on the PC. I called a few people, no echo, everything is fine.

**Comment by l7v2uj** [comment]
But the problem remains on the PC, the other person hears his echo, I don't hear his echo(

**Comment by juha-h** [comment]
@l7v2uj   Good to learn that there was no echo with baresip Android app. The reason is that on most Android devices the app uses acoustic echo canceler provides by the device, not the software one provided by baresip webrtc_aec module.  Thanks for testing.

**Comment by l7v2uj** [comment]
Friends, I solved my problem!)
I did as described [here](https://gitlab.freedesktop.org/pipewire/pipewire/-/issues/2165).
[Noise Suppression v1.10](https://github.com/werman/noise-suppression-for-voice) deleted. Even disabled the "webrtc_aec.so" module. Everything works without noise or echo.
