### ISSUE TITLE
no registration after initial regint=0 is changed to positive value

### ISSUE THREAD

**Issue by juha-h** [baresip/baresip#408]
I created an new user agent with ua_alloc() API call and used aor param <sip:foo@bar>;regint=0.  After that I changed regint to value 60 using API function account_set_regint() and verified with account_regint() that the change had taken effect.  I also set all other needed account parameters.

After that I issued ua_register() API call and saw in the logs ua REGISTERING event. However, no REGISTER request was sent out.  I then saved the account config and restarted baresip, which made the ua register correctly.

I  repeated the exercise by creating the ua with aor param <sip:foo@bar>;regint=60 and then ua_register() did sent out REGISTER request. So I started to suspect that there is a bug somewhere that prevents dynamic change of regint from 0 to positive value from taking effect until baresip restart.

-- Juha

**Comment by juha-h** [comment]
I did some more digging on this.  When ua is allocated  by ua_alloc(), it is added one or more times to its regl:

	if (0 == str_casecmp(ua->acc->sipnat, "outbound")) {
                ...
		for (i=0; i<ARRAY_SIZE(ua->acc->outboundv); i++) {
			if (ua->acc->outboundv[i] && ua->acc->regint) {
				err = reg_add(&ua->regl, ua, (int)i+1);
				...
			}
		}
        else if (ua->acc->regint) {
		err = reg_add(&ua->regl, ua, 0);
	}

When ua_register() is called, REGISTERING event is sent as I reported earlier, but actual registration(s) is/are done only if ua's regl is not empty:

	ua_event(ua, UA_EVENT_REGISTERING, NULL, NULL);
	for (le = ua->regl.head, i=0; le; le = le->next, i++) {
		struct reg *reg = le->data;
		err = reg_register(reg, reg_uri, params, acc->regint, acc->outboundv[i]);
                ...
I have not found an API way to add the ua to its regl AFTER ua_alloc has been done, e.g. after reg_int has been set to positive value.

Is there something missing in the API or am I missing something? Any pointers are appreciated.

**Comment by alfredh** [comment]
the list of register clients is created in `ua_alloc` based on the content
of the SIP account. the code was written in a way that it does not expect any changes
to _account_ after that.

perhaps we can extract this code to a new function, and add a function
for refreshing the `ua->acc` based on a new or old `account`.

example:

```
int ua_refresh_account(struct ua *ua, struct acc *acc);
```

or perhaps move the creation of `regl` to ua_register?

I will look into this and see if there are any unforeseen side effects.

**Comment by juha-h** [comment]
Alfred E. Heggestad writes:

> the list of register clients is created in `ua_alloc` based on the content
> of the SIP account. the code was written in a way that it does not
> expect any changes to _account_ after that.
> 
> perhaps we can extract this code to a new function, and add a function
> for refreshing the `ua->acc` based on a new or old `account`.
>
> example:
> 
> ```
> int ua_refresh_account(struct ua *ua, struct acc *acc);
> ```
>

That is close to what ua_update() does.

> or perhaps move the creation of `regl` to ua_register?

That is a possibility, but there is also the extensions that are derived
from presence or absence of sipnat "outbound".

> I will look into this and see if there are any unforeseen side
> effects.

Thanks.  Waiting to learn which way you want to go.

**Comment by alfredh** [comment]
I have made a suggestion here:

https://github.com/alfredh/baresip/tree/ua_update_account

the function will reset all the extensions and destroy all the register clients,
and then re-build it using current account.

the application logic is something like:

1. make some changes to `struct account`
2. call ua_update_account
3. call ua_register

**Comment by juha-h** [comment]
Alfred E. Heggestad writes:

> I have made a suggestion here:
> 
> https://github.com/alfredh/baresip/tree/ua_update_account
> 
> the function will reset all the extensions and destroy all the register clients,
> and then re-build it using current account.
> 
> the application logic is something like:
> 
> 1. make some changes to `struct account`
> 2. call ua_update_account
> 3. call ua_register

The code looks good to me.  It is similar to mine, but avoids duplication
of code.

-- Juha
