### ISSUE TITLE
No keep-alives from baresip

### ISSUE THREAD

**Issue by secondstar1** [baresip/baresip#695]
Baresip located on PC behind NAT. Therefore it must send keep-alives to keep NAT stay opened.
I've set sipnat option 

<sip:1101@x.x.x.x:9998>;answermode=manual;auth_pass=yyyyyyy;video_codecs=h264;sipnat=outbound;outbound="sip:x.x.x.x:9998;transport=udp"

where x.x.x.x - IP address of asterisk server with non-standard port (9998). 
But I can't see any periodic keep-alives from client using tcpdump.

**Comment by GGGO** [comment]
Hi @secondstar1,
baresip will send keep-alives only if the server supports outbound.
Asterisk sip channels don't support outbound. I'm not sure about pjsip channels.

**Comment by alfredh** [comment]
this looks like a very old ticket, so I will close it.

if you still have the problem, please create a new Issue and include all details
like config, log, network trace.
