### ISSUE TITLE
DTLS hash not supported followed by seg fault

### ISSUE THREAD

**Issue by robdyck** [baresip/baresip#980]
When checking the fingerprint dtls-srtp only accepts sha-256 hash. This is rather contradictory since baresip itself sends sha-1 fingerprint to the peer. Then it seg faults.
See terminal text and back trace attached.
[dtls-fail-backtrace.txt](https://github.com/alfredh/baresip/files/4617463/dtls-fail-backtrace.txt)
[dtls-fail.txt](https://github.com/alfredh/baresip/files/4617464/dtls-fail.txt)

**Comment by sreimers** [comment]
Thanks for reporting. But the dtls_srtp module offers only sha-256 fingerprint:

https://github.com/alfredh/baresip/blob/master/modules/dtls_srtp/dtls_srtp.c#L175-L176

Maybe you`re confused by the profile names? 

Can you test the current master baresip code? There are some ICE related changes, so maybe the crash is already fixed.

**Comment by robdyck** [comment]
With the latest from github I get the same result.

Maybe we're not talking about the same thing. Here is the message that I find puzzling. Baresip appears to be using SHA-1.

Tue May 12 2020 12:44:39 GMT-0700 (Pacific Daylight Time) | sip.transport | received WebSocket text message:
  
SIP/2.0 200 Answering
Record-Route: <sip:192.168.1.2;transport=tcp;r2=on;lr;ftag=q9id7p7ve4>
Record-Route: <sip:192.168.1.1:8000;transport=wss;r2=on;lr;ftag=q9id7p7ve4>
Via: SIP/2.0/WSS qkne7f4tatcp.invalid;rport=28612;received=209.52.88.62;branch=z9hG4bK3873890
To: <sip:2@bogus.com>;tag=8f7b46b5ddefa702
From: "Rob" <sip:4@bogus.com>;tag=q9id7p7ve4
Call-ID: aah4pe99qq05k5nqea7r
CSeq: 4416 INVITE
**Server: baresip v0.6.5 (x86_64/linux)**
Contact: <sip:2-0x11071c0@192.168.1.3:39049;transport=tcp>
Allow: INVITE,ACK,BYE,CANCEL,OPTIONS,NOTIFY,SUBSCRIBE,INFO,MESSAGE,REFER
Content-Type: application/sdp
Content-Length: 809

v=0
o=- 2406926275 1868650615 IN IP4 192.168.1.3
s=-
c=IN IP4 192.168.1.3
t=0 0
a=tool:baresip 0.6.5
m=audio 35000 UDP/TLS/RTP/SAVPF 109 9 0 8 101
c=IN IP4 ww.yy.xx.zz
a=label:1
a=ssrc:632696271 cname:sip:2@bogus.com
a=minptime:20
a=mid:0
a=rtpmap:109 opus/48000/2
a=rtpmap:9 G722/8000
a=rtpmap:0 PCMU/8000
a=rtpmap:8 PCMA/8000
a=rtpmap:101 telephone-event/8000
a=fmtp:109 stereo=1;sprop-stereo=1;maxaveragebitrate=28000
a=sendrecv
a=rtcp:35001
a=setup:active
**a=fingerprint:sha-1 BA:33:B9:26:38:A7:2A:BD:32:6D:62:0D:B3:85:3E:16:1C:39:CB:3C**
a=ptime:20
a=ice-ufrag:pR4VB1QC
a=ice-pwd:ddT8Ie0rVFKQNUc3mMwIyBJnvj
a=candidate:3L0df9zHMV6Sw6kH 1 UDP 2130706431 192.168.1.1 35000 typ host
a=candidate:3L0df9zHMV6Sw6kH 2 UDP 2130706430 192.168.1.1 35001 typ host

**Comment by robdyck** [comment]
I found what is happening with the hash. The hash was being rewritten by the media relay. Both UAs were actually sending SHA-256 fingerprints. So as far as baresip is concerned the hash itself is not an issue but it reveals a corner case that was not well handled.

**Comment by alfredh** [comment]
Your media relay is doing a Man-In-The-Middle (MITM) Attack. It is inserting itself
between the 2 UAs both on the Signaling path and the Media path.

Very naught media relay! This defeats the purpose of End-to-End Encryption (E2EE)
where the 2 UAs can exchange keys and make sure that no middleboxes are
listening or modifying the media.

On the other side it was sad that Baresip could not detect it..

You should contact your media relay provider and tell them to stop using SHA-1
which has known collisions.

Aside from that, you have found a real bug in the ice code. Thanks for that!

here is the code, in the ice module:

```c
		if (m->connh) {
			m->connh(icem_lcand_addr(cand1),
				  icem_lcand_addr(cand2),
				  m->arg);
		}

		/* Check all conncheck flags */
		LIST_FOREACH(&sess->medial, le) {
			struct mnat_media *mx = le->data;
			if (!mx->complete)
				return;
		}
```

the `connh` Connected Handler is called, inside the connected handler
it will start DTLS-SRTP (which fails) and hence close the stream/session.
When the `connh` returns, the object pointed to by `m` is no longer valid.

a solution could be to move connh to the end of the function,
or use mem_ref/deref to inc/dec the object reference count
before and after the call.

**Comment by robdyck** [comment]
I am the man in the middle. I am familiarizing myself with rtpengine and experimenting. I should probably raise an issue with rtpengine.
Thank you for the comments.
