### ISSUE TITLE
Returning message body in register OK event

### ISSUE THREAD

**Issue by jurjen-van-dijk** [baresip/baresip#982]
I am quite new to baresip, and try to use it in iOS. And I am trying this out to see if I can make the library work with our setup.

When I register successfully, it returns a list of servers I need to use in the body of the message, and I try to pass that back in the string that is sent in the OK event. And something strange happens here. Maybe someone sees what I am missing?

In reg.c, in the register_handler I have these lines, the second one is a modified version of the original that is already there:

(void)re_printf("\r\nbaresip->\r\n\r\n<body>%s</body>\r\n\r\n<-baresip", mbuf_buf(msg->mb));
ua_event(reg->ua, UA_EVENT_REGISTER_OK, NULL, "%u %r <body>%s</body>", msg->scode, &msg->reason, mbuf_buf(msg->mb));

The 'body' is just to visualize if the char * has a value anyway.

In Swift I have this event handler:
let handler = EventHandler { ua, ev, call, prm, args in
	let event = UAEvent(rawValue: ev.rawValue)
	var strPrms = "<none>"
	if let safePrm = prm {
		strPrms = String(cString: safePrm)
	}
	print("\nCALLBACK: *** \(event!.toString), prms [\(strPrms)]")
}

And in my logs I see this:

baresip->

<body>{"turn":{"servers":["turns:europe-west1-d-0.coturn.voice.staging.server.com:443?transport=tcp ","turns:europe-west1-c-0.coturn.voice.staging.staging.server.com:443?transport=tcp ","turns:europe-west4-a-0.coturn.voice.staging.staging.server.com:443?transport=tcp "],"credentials":{"username”:"xxxxxxxxx","password”:"xxxxxxxxxxxxxxx="}},"zone":"europe-west4"}</body>

<-baresip
CALLBACK: *** Registered OK, prms [200 Ok <body>]

So, when I print the 'const char *' that  mbuf_buf(msg->mb) returns in the library it shows the correct value. But when I pass it the same way to the event it cuts off.

**Comment by alfredh** [comment]
https://github.com/baresip/baresip/wiki/Guidelines-for-reporting-Issues
