### ISSUE TITLE
CentOS 7 64-bit does not include /usr/local/lib folder in ld.so.conf [SOLVED]

### ISSUE THREAD

**Issue by idelac3** [baresip/baresip#983]
Problem while starting baresip after compiling re and rem libs:

_baresip: error while loading shared libraries: libre.so: cannot open shared object file: No such file or directory_

Solution:

Add following to **/etc/ld.so.conf.d/baresip.conf**

**/usr/local/lib** 

Eg.

```
[root@sip-1 re]# cat /etc/ld.so.conf.d/baresip.conf
/usr/local/lib
[root@sip-1 re]#
```

**Comment by robert-scheck** [comment]
The issue here is that libre was installed wrongly by @idelac3, because `/usr/local/lib64` would be part of `$LD_LIBRARY_PATH` on 64 bit systems, thus `make install LIBDIR=/usr/local/lib64` rather `make install` would have been better, because `/usr/local/lib` is suited for 32 bit libraries.

**Comment by idelac3** [comment]
Agree.
