### ISSUE TITLE
Video Calling Works Intermittently (audio always works)

### ISSUE THREAD

**Issue by Syirrus** [baresip/baresip#984]
Well, I believe I can safely conclude that this issue lies within Baresip or some strange config issue :(. If I use different SIP clients other than Baresip (Microsip and GS wave for android) video calls work over my (NAT'ed) network and the cellular network with GS Wave for android. Those clients also work both on my NAT'ed network as well.

As a part of the testing, I removed the STUN and TURN server out of the equation completely and have everything going over UDP.

When to try with Baresip on my (NAT'ed) network with GS Wave or Linphone over the same (NAT'ed) network, video calling works most of the time, but it's intermittent (irrespective of which device is calling whom). My camera on the pi indicates that it's on always, but sometimes there is just not picture on GS Wave or Linphone. I would say it works 2 out of 3 times.

When I try with Baresip on my (NAT'ed) network with GS Wave over the cellular network, video calling fails every time, however I do have audio, just not video.

Any ideas @alfredh ? I have spent tons of time on this double and triple checking my config and accounts file and it's just not that.

**Comment by alfredh** [comment]
https://github.com/baresip/baresip/wiki/Guidelines-for-reporting-Issues
