### ISSUE TITLE
jack audio driver ignores "jack_connect_ports" setting from config file

### ISSUE THREAD

**Issue by eafunk** [baresip/baresip#991]
A "jack_connect_ports\tno" setting line, regardless of where I place it in the baresip config file, does not change the jack audio driver behavior, preventing auto-connection of the baresip source and destination to the system inputs and outputs, as expected.  The driver code default to a "yes" equivalent on both the source and destination audio implementation code.  So it looks to me like the following line:

(void)conf_get_bool(conf, "jack_connect_ports",  &jack_connect_ports);

is failing to get the actual setting from the config file, to override the default, and I am not sure why.  It looks like it should work.

**Comment by eafunk** [comment]
I forgot to include the version: Baresip version 0.6.4, as pulled from Ubuntu 20.04 apt package installer.

**Comment by sreimers** [comment]
Please re-try with Baresip 0.6.6, the option was added after 0.6.4

https://github.com/baresip/baresip/pull/896
