### ISSUE TITLE
disabling .wav file playback

### ISSUE THREAD

**Issue by JarbasAl** [baresip/baresip#995]
i am using baresip in a voice assistant, this means i am handling all audio feedback my own way

i want to disable playback of

```
user@user-Predator-PH315-51:~$ ls /usr/local/share/baresip/
busy.wav  callwaiting.wav  error.wav message.wav  notfound.wav  ringback.wav  ring.wav
```
Please let me know if i am missing any other file besides these

how can i do this? i would rather not change the user filesystem (others will be installing this), so hopefully there is a command i can enter in the cli?

The only approach i can think of is replacing these files with silence on install of my project, but i dont want to do that...

see project [here](https://github.com/JarbasAl/baresipy)

**Comment by Roog** [comment]
Hi! 
I'm not sure, there might be another way.. Since this one will throw an "silent-error".

But you can just point the "audio_path" to something that doesn't exist
> audio_path              /usr/local/share/baresip/path/that/doesnt/exist

Best regards
Roger

**Comment by capncybo** [comment]
Can't you just edit the config file & set something such as
audio_source           alsa,null

**Comment by alfredh** [comment]
https://github.com/baresip/baresip/wiki/Guidelines-for-reporting-Issues

**Comment by JarbasAl** [comment]
thx guys, i will try that

@alfredh best support ever! this is a repo i ain't coming back to..
