### ISSUE TITLE
Address family not supported by protocol

### ISSUE THREAD

**Issue by robdyck** [baresip/baresip#997]
This issue occurs on a call with both agents on the LAN. Two-way audio works. ICE finds a valid pair of ipv4 rfc1918 addresses. There are also valid ipv6 candidates but these cause the error message being reported here. Otherwise ipv6 is good. Both agents register with their ipv6 addresses.
Here is the console output ( addresses altered for privacy )
 Local Candidates:  (8)
  {1} fnd=c0a80103 prio=7e0000ff enp2s0:host:192.168.1.3:7162
  {2} fnd=c0a80103 prio=7e0000fe enp2s0:host:192.168.1.3:7163
  {1} fnd=a2cb0d65 prio=7e0000ff enp2s0:host:[fd00::]:7162
  {2} fnd=a2cb0d65 prio=7e0000fe enp2s0:host:[fd00::]:7163
  {1} fnd=cb5fbac5 prio=7e0000ff enp2s0:host:[2001:]:7162
  {2} fnd=cb5fbac5 prio=7e0000fe enp2s0:host:[2001:]:7163
  {1} fnd=325cf52d prio=640000ff enp2s0:srflx:50.92.:7162 (rel-addr=192.168.1.3:7162)
  {2} fnd=325cf52d prio=640000fe enp2s0:srflx:50.92:7163 (rel-addr=192.168.1.3:7163)
 Remote Candidates:  (8)
  {1} fnd=0  prio=7e7d00ff host:192.168.1.87:47397
  {1} fnd=2  prio=7e7e00ff host:[fd00::]:36242
  {1} fnd=4  prio=7e7f00ff host:[2001:]:57317
  {2} fnd=0  prio=7e7d00fe host:192.168.1.87:52472
  {2} fnd=2  prio=7e7e00fe host:[fd00::]:34498
  {2} fnd=4  prio=7e7f00fe host:[2001:]:56692
  {1} fnd=1  prio=647d1fff srflx:50.92.:47397 (rel-addr=192.168.1.87:47397)
  {2} fnd=1  prio=647d1ffe srflx:50.92.:52472 (rel-addr=192.168.1.87:52472)
 Check list: [state=Completed] (10)
     {comp=1}     Failed {   } enp2s0:host:[2001:]:7162 <---> host:[2001:]:57317 (Address family not supported by protocol)
     {comp=1}     Failed {   } enp2s0:host:[fd00::]:7162 <---> host:[2001:]:57317 (Address family not supported by protocol)
     {comp=1}     Failed {   } enp2s0:host:[2001:]:7162 <---> host:[fd00::]:36242 (Address family not supported by protocol)
     {comp=1}     Failed {   } enp2s0:host:[fd00::]:7162 <---> host:[fd00::]:36242 (Address family not supported by protocol)
     {comp=2}     Failed {   } enp2s0:host:[2001:]:7163 <---> host:[2001:]:56692 (Address family not supported by protocol)
     {comp=2}     Failed {   } enp2s0:host:[fd00::]:7163 <---> host:[2001:]:56692 (Address family not supported by protocol)
     {comp=2}     Failed {   } enp2s0:host:[2001:]:7163 <---> host:[fd00::]:34498 (Address family not supported by protocol)
     {comp=2}     Failed {   } enp2s0:host:[fd00::]:7163 <---> host:[fd00::]:34498 (Address family not supported by protocol)
     {comp=1}     Failed {   } enp2s0:host:192.168.1.3:7162 <---> srflx:50.92.:47397 (Connection timed out)
     {comp=2}     Failed {   } enp2s0:host:192.168.1.3:7163 <---> srflx:50.92.:52472 (Connection timed out)
 Valid list:  (2)
  *  {comp=1}  Succeeded { VN} enp2s0:host:192.168.1.3:7162 <---> host:192.168.1.87:47397
  *  {comp=2}  Succeeded { V } enp2s0:host:192.168.1.3:7163 <---> host:192.168.1.87:52472

**Comment by alfredh** [comment]
what is the issue here ?

Ice should find one or more working candidate pairs.
in your case it finds a pair so it should be working.

**Comment by robdyck** [comment]
What if the context was an IPV6 only network. RTP over IPV6 would need to be implemented. Why support signalling over IPV6 and not media?

**Comment by alfredh** [comment]
I think your issue is an artificial one.

You are reporting a bug from this context, and then you say that it "might" happen in a different context ?
This is not a valid usecase for reporting bugs.

You need to report the bug from your context, and prove that it is a real issue.

Both IPv4 and IPv6 is supported. I would like to suggest that you test it again
in a V6 only network, and then report it again if it does not work.
