### ISSUE TITLE
contact management from cli

### ISSUE THREAD

**Issue by JarbasAl** [baresip/baresip#998]
I made a python wrapper for baresip, see [here](https://github.com/JarbasAl/baresipy), and i want to manage contacts from the cli, without editing system files (i dont want to edit ~/.baresip/contacts )

Maybe im just not finding it, but is there some command i can use to add/delete contacts? i only see an option to list them

If this is there, consider this a support request, if it isnt, consider this a feature request

This is meant for a [mycroft skill](https://github.com/JarbasSkills/skill--voip), i want more control than ~/.baresip/contacts provides so i use my own [.json database](https://github.com/HelloChatterbox/json_database), i guess i could sync that db with ~/.baresip/contacts but id rather not touch that at all

To illustrate my use case consider credentials, i want to support the baresip way, but i also want to allow using mycrofts own mechanisms, therefore i use /uanew for log in. im looking for something similar for contacts, where i support the baresip way for privacy, and the mycroft way for user convenience.

Ideally changes done from cli/mycroft would be ephemeral and not persisted to disk

**Comment by alfredh** [comment]
https://github.com/baresip/baresip/wiki/Guidelines-for-reporting-Issues
